"""Mission Control configuration — loaded from environment variables."""

import os
from pathlib import Path

from dotenv import load_dotenv

load_dotenv(Path(__file__).resolve().parent.parent / ".env")

# Root of the plan engine repo
REPO_ROOT = Path(__file__).resolve().parent.parent

# Key directories (still needed for local pipeline execution)
ATHLETES_DIR = REPO_ROOT / "athletes"
TEMPLATES_DIR = REPO_ROOT / "templates" / "emails"
INTAKES_DIR = REPO_ROOT / "intakes"
PLANS_DIR = REPO_ROOT / "plans"

# Pipeline entry point
PIPELINE_SCRIPT = REPO_ROOT / "run_pipeline.py"
PRE_DELIVERY_AUDIT = REPO_ROOT / "scripts" / "pre_delivery_audit.py"

# Jinja2 templates for the web UI
WEB_TEMPLATES_DIR = Path(__file__).resolve().parent / "templates"
STATIC_DIR = Path(__file__).resolve().parent / "static"

# Supabase
SUPABASE_URL = os.environ.get("SUPABASE_URL", "")
SUPABASE_SERVICE_KEY = os.environ.get("SUPABASE_SERVICE_KEY", "")

# Resend (email sending)
RESEND_API_KEY = os.environ.get("RESEND_API_KEY", "")
RESEND_FROM_EMAIL = os.environ.get("RESEND_FROM_EMAIL", "plans@gravelgodcycling.com")
RESEND_FROM_NAME = os.environ.get("RESEND_FROM_NAME", "Gravel God Training")

# Sequence email identity (marketing automation)
SEQUENCE_FROM_EMAIL = os.environ.get("SEQUENCE_FROM_EMAIL", "matti@gravelgodcycling.com")
SEQUENCE_FROM_NAME = os.environ.get("SEQUENCE_FROM_NAME", "Matti at Gravel God")
REPLY_TO_EMAIL = os.environ.get("REPLY_TO_EMAIL", "gravelgodcoaching@gmail.com")

# Per-brand sequence sender identity. Sequences carry a "brand" key
# (absent = gravelgod); the engine looks up sender/utm here. Road sends
# require the roadielabs.com domain to be verified in Resend first —
# until then road sequences should stay inactive.
BRAND_SEQUENCE_SENDERS = {
    "gravelgod": {
        "from_email": SEQUENCE_FROM_EMAIL,
        "from_name": SEQUENCE_FROM_NAME,
        "reply_to": REPLY_TO_EMAIL,
        "utm_source": "gravel_god",
    },
    "roadielabs": {
        "from_email": os.environ.get("RL_SEQUENCE_FROM_EMAIL", "matti@roadielabs.com"),
        "from_name": os.environ.get("RL_SEQUENCE_FROM_NAME", "Matti at Roadie Labs"),
        "reply_to": os.environ.get("RL_REPLY_TO_EMAIL", "gravelgodcoaching@gmail.com"),
        "utm_source": "roadie_labs",
    },
    # XC sends require xcskilabs.com verified in Resend first — until then
    # xc_* sequences stay inactive (same gate road went through).
    "xcskilabs": {
        "from_email": os.environ.get("XC_SEQUENCE_FROM_EMAIL", "matti@xcskilabs.com"),
        "from_name": os.environ.get("XC_SEQUENCE_FROM_NAME", "Matti at XC Ski Labs"),
        "reply_to": os.environ.get("XC_REPLY_TO_EMAIL", "gravelgodcoaching@gmail.com"),
        "utm_source": "xc_ski_labs",
    },
}

# Published race-date maps for the countdown trigger (see
# services/race_countdown.py + docs/specs/race-countdown-trigger.md).
# Regenerated by each brand repo's scripts/generate_race_dates.py.
RACE_DATES_URLS = {
    "gravelgod": os.environ.get(
        "GG_RACE_DATES_URL",
        "https://gravelgodcycling.com/wp-content/uploads/race-dates.json"),
    "roadielabs": os.environ.get(
        "RL_RACE_DATES_URL",
        "https://roadielabs.com/race-dates.json"),
}

# Webhook secret (for Worker → Mission Control auth)
WEBHOOK_SECRET = os.environ.get("WEBHOOK_SECRET", "")

# Resend signs event webhooks Svix-style (svix-signature header), NOT with
# an Authorization bearer. Signing secret from the Resend dashboard
# (Webhooks -> endpoint -> Signing Secret, starts with "whsec_").
RESEND_WEBHOOK_SECRET = os.environ.get("RESEND_WEBHOOK_SECRET", "")

# Admin auth secret (for Mission Control dashboard routes)
MISSION_CONTROL_SECRET = os.environ.get("MISSION_CONTROL_SECRET", "")

# Server
HOST = os.environ.get("HOST", "0.0.0.0")
PORT = int(os.environ.get("PORT", "8000"))

# Storage bucket name
STORAGE_BUCKET = os.environ.get("STORAGE_BUCKET", "plans")

# GA4 Analytics
GA4_PROPERTY_ID = os.environ.get("GA4_PROPERTY_ID", "")
GA4_CREDENTIALS_PATH = os.environ.get("GA4_CREDENTIALS_PATH", "")

# Stripe (optional)
STRIPE_WEBHOOK_SECRET = os.environ.get("STRIPE_WEBHOOK_SECRET", "")
STRIPE_API_KEY = os.environ.get("STRIPE_API_KEY", "")

# Public URL (for unsubscribe links in emails)
PUBLIC_URL = os.environ.get("PUBLIC_URL", "https://athlete-profiles-production.up.railway.app")

# HMAC secret for unsubscribe tokens (falls back to WEBHOOK_SECRET)
UNSUBSCRIBE_SECRET = os.environ.get("UNSUBSCRIBE_SECRET", "") or WEBHOOK_SECRET
