"""Tests for generate_markdown_profiles.py.

Includes v2 edge case tests for YAML escaping, _safe(0) preservation,
markdown pipe escaping, citation deduplication, and generation timestamps.
"""

import json
import sys
from pathlib import Path

import pytest

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))
sys.path.insert(0, str(Path(__file__).resolve().parent.parent / "scripts"))

from scripts.generate_markdown_profiles import (
    generate_profile,
    _yaml_escape,
    _safe,
    _md_escape,
    _frontmatter,
    _section_citations,
    _section_vitals,
    _section_course,
    _section_rating,
    _section_verdict,
    _fmt_dist,
    _fmt_elev,
)

PROJECT_ROOT = Path(__file__).resolve().parent.parent
INDEX_FILE = PROJECT_ROOT / "web" / "race-index.json"
RACE_DATA_DIR = PROJECT_ROOT / "race-data"


@pytest.fixture
def index():
    return json.loads(INDEX_FILE.read_text())


@pytest.fixture
def index_map(index):
    return {r["slug"]: r for r in index}


@pytest.fixture
def unbound_md(index_map):
    return generate_profile("unbound-200", index_map["unbound-200"], RACE_DATA_DIR)


class TestProfileGeneration:
    def test_generates_for_known_race(self, unbound_md):
        assert unbound_md is not None
        assert len(unbound_md) > 1000

    def test_returns_none_for_missing(self, index_map):
        result = generate_profile("nonexistent-xyz", {"slug": "nonexistent-xyz"}, RACE_DATA_DIR)
        assert result is None

    def test_all_races_generate(self, index):
        generated = 0
        for r in index:
            md = generate_profile(r["slug"], r, RACE_DATA_DIR)
            if md is not None:
                generated += 1
        assert generated >= 325  # Allow a few stubs


class TestFrontmatter:
    def test_starts_with_yaml(self, unbound_md):
        assert unbound_md.startswith("---\n")

    def test_has_slug(self, unbound_md):
        assert 'slug: "unbound-200"' in unbound_md

    def test_has_tier(self, unbound_md):
        assert "tier: 1" in unbound_md

    def test_has_score(self, unbound_md):
        assert "score: 93" in unbound_md

    def test_has_url(self, unbound_md):
        assert "url: " in unbound_md
        assert "gravelgodcycling.com" in unbound_md

    def test_has_distance(self, unbound_md):
        assert "distance_mi: 200" in unbound_md

    def test_has_location(self, unbound_md):
        assert "location:" in unbound_md


class TestSections:
    def test_has_title(self, unbound_md):
        assert "# Unbound 200" in unbound_md

    def test_has_tagline(self, unbound_md):
        assert "> " in unbound_md

    def test_has_vitals(self, unbound_md):
        assert "## Vitals" in unbound_md
        assert "Distance" in unbound_md

    def test_has_course(self, unbound_md):
        assert "## Course" in unbound_md

    def test_has_suffering_zones(self, unbound_md):
        assert "### Suffering Zones" in unbound_md

    def test_has_terrain(self, unbound_md):
        assert "## Terrain" in unbound_md

    def test_has_climate(self, unbound_md):
        assert "## Climate" in unbound_md

    def test_has_rating_table(self, unbound_md):
        assert "## Gravel God Rating" in unbound_md
        assert "| Dimension | Score |" in unbound_md
        assert "Logistics" in unbound_md

    def test_has_verdict(self, unbound_md):
        assert "## The Verdict" in unbound_md

    def test_has_logistics(self, unbound_md):
        assert "## Logistics" in unbound_md

    def test_has_history(self, unbound_md):
        assert "## History" in unbound_md

    def test_has_non_negotiables(self, unbound_md):
        assert "## Non-Negotiables" in unbound_md

    def test_has_tires(self, unbound_md):
        assert "## Tire Recommendations" in unbound_md

    def test_has_citations(self, unbound_md):
        assert "## Citations" in unbound_md

    def test_has_generation_timestamp(self, unbound_md):
        """v2: Each profile should end with a generation timestamp."""
        assert "Generated by Gravel God" in unbound_md


class TestEdgeCases:
    def test_race_with_string_terrain(self, index_map):
        """Some races have terrain as a plain string instead of dict."""
        # Find a race with string terrain
        for slug in index_map:
            f = RACE_DATA_DIR / f"{slug}.json"
            if f.exists():
                data = json.loads(f.read_text())
                rd = data.get("race", data)
                if isinstance(rd.get("terrain"), str):
                    md = generate_profile(slug, index_map[slug], RACE_DATA_DIR)
                    assert md is not None
                    assert "## Terrain" in md
                    return
        pytest.skip("No race with string terrain found")

    def test_race_with_rider_intel(self, index_map):
        """Races with rider_intel should have Riders Report section."""
        for slug in index_map:
            f = RACE_DATA_DIR / f"{slug}.json"
            if f.exists():
                data = json.loads(f.read_text())
                rd = data.get("race", data)
                if rd.get("youtube_data", {}).get("rider_intel"):
                    md = generate_profile(slug, index_map[slug], RACE_DATA_DIR)
                    assert md is not None
                    assert "## Riders Report" in md
                    return
        pytest.skip("No race with rider_intel found")

    def test_missing_sections_gracefully_omitted(self, index_map):
        """A race missing some fields should still generate without errors."""
        # All 328 should generate without errors
        errors = []
        for slug in list(index_map.keys())[:50]:
            try:
                md = generate_profile(slug, index_map[slug], RACE_DATA_DIR)
                assert md is not None
            except Exception as e:
                errors.append(f"{slug}: {e}")
        assert not errors, f"Errors in profile generation: {errors}"


# ---------------------------------------------------------------------------
# v2 BUG FIX: YAML frontmatter escaping
# ---------------------------------------------------------------------------

class TestYamlEscaping:
    """YAML frontmatter values must handle double quotes safely."""

    def test_yaml_escape_plain_string(self):
        assert _yaml_escape("hello") == '"hello"'

    def test_yaml_escape_string_with_double_quotes(self):
        """Double quotes inside must be escaped to prevent YAML parse errors."""
        result = _yaml_escape('He said "hello"')
        assert result == '"He said \\"hello\\""'

    def test_yaml_escape_string_with_colon(self):
        """Colons in YAML values are dangerous without quoting."""
        result = _yaml_escape("Emporia: Kansas")
        assert result == '"Emporia: Kansas"'

    def test_yaml_escape_integer(self):
        """Integers should NOT be quoted."""
        assert _yaml_escape(1) == "1"
        assert _yaml_escape(93) == "93"

    def test_yaml_escape_float(self):
        """Floats should NOT be quoted."""
        assert _yaml_escape(3.14) == "3.14"

    def test_yaml_escape_zero(self):
        """Zero should NOT be quoted."""
        assert _yaml_escape(0) == "0"

    def test_yaml_escape_backslash(self):
        """Backslashes must be escaped before quotes."""
        result = _yaml_escape("path\\to\\file")
        assert result == '"path\\\\to\\\\file"'

    def test_yaml_escape_empty_string(self):
        assert _yaml_escape("") == '""'

    def test_frontmatter_survives_quotes_in_name(self):
        """A race name containing quotes should produce valid YAML frontmatter."""
        entry = {"slug": "test", "tier": 1, "overall_score": 50}
        rd = {
            "name": 'The "Epic" Race',
            "vitals": {"location": "Here"},
            "gravel_god_rating": {"tier": 1, "overall_score": 50, "discipline": "gravel"},
        }
        fm = _frontmatter("test", entry, rd)
        assert "---" in fm
        assert '\\"Epic\\"' in fm
        # Should not have unescaped double quotes inside a YAML value
        lines = fm.splitlines()
        for line in lines:
            if line.startswith("name:"):
                # The value should be properly quoted
                val = line.split(":", 1)[1].strip()
                assert val.startswith('"') and val.endswith('"')


# ---------------------------------------------------------------------------
# v2 BUG FIX: _safe(0) preservation (Python falsiness bug)
# ---------------------------------------------------------------------------

class TestSafeFunction:
    """_safe() must use `is None` check, not `not val` (which drops 0, '', False)."""

    def test_safe_zero_preserved(self):
        """CRITICAL: _safe(0) must return 0, NOT the default."""
        assert _safe(0) == 0
        assert _safe(0, "default") == 0

    def test_safe_empty_string_preserved(self):
        """_safe('') must return '', NOT the default."""
        assert _safe("") == ""
        assert _safe("", "default") == ""

    def test_safe_false_preserved(self):
        """_safe(False) must return False, NOT the default."""
        assert _safe(False) is False
        assert _safe(False, "default") is False

    def test_safe_none_returns_default(self):
        assert _safe(None) == ""
        assert _safe(None, "fallback") == "fallback"

    def test_safe_normal_value(self):
        assert _safe("hello") == "hello"
        assert _safe(42) == 42


# ---------------------------------------------------------------------------
# v2 BUG FIX: Markdown table pipe escaping
# ---------------------------------------------------------------------------

class TestMarkdownPipeEscaping:
    """Pipe characters in table cell values must be escaped."""

    def test_md_escape_pipe(self):
        assert _md_escape("A | B") == "A \\| B"

    def test_md_escape_newline(self):
        assert _md_escape("line1\nline2") == "line1 line2"

    def test_md_escape_none(self):
        assert _md_escape(None) == ""

    def test_md_escape_normal(self):
        assert _md_escape("Emporia, Kansas") == "Emporia, Kansas"

    def test_pipe_in_real_profiles_doesnt_break_tables(self, index):
        """Scan some profiles for broken table rows."""
        errors = []
        for r in index[:20]:
            md = generate_profile(r["slug"], r, RACE_DATA_DIR)
            if md is None:
                continue
            for i, line in enumerate(md.splitlines(), 1):
                if line.startswith("|"):
                    # Replace escaped pipes before counting
                    cleaned = line.replace("\\|", "XX")
                    cols = cleaned.count("|")
                    # A valid table row should have at least 3 pipes (| a | b |)
                    if cols < 3:
                        errors.append(f"{r['slug']} line {i}: only {cols} pipes: {line[:80]}")
        assert not errors, f"Broken table rows: {errors}"


# ---------------------------------------------------------------------------
# v2 BUG FIX: Citation deduplication
# ---------------------------------------------------------------------------

class TestCitationDeduplication:
    """Citations with the same URL should be deduplicated."""

    def test_dedup_by_url(self):
        rd = {
            "citations": [
                {"url": "https://example.com/a", "label": "Source A", "category": "official"},
                {"url": "https://example.com/a", "label": "Source A dup", "category": "official"},
                {"url": "https://example.com/b", "label": "Source B", "category": "media"},
            ]
        }
        result = _section_citations(rd)
        assert result.count("example.com/a") == 1  # deduped
        assert "example.com/b" in result

    def test_no_citations_returns_empty(self):
        assert _section_citations({}) == ""
        assert _section_citations({"citations": []}) == ""

    def test_real_profile_no_duplicate_urls(self, index_map):
        """Check a real profile for citation URL uniqueness."""
        md = generate_profile("unbound-200", index_map["unbound-200"], RACE_DATA_DIR)
        assert md is not None
        # Count citation URLs in the Citations section
        in_citations = False
        urls = []
        for line in md.splitlines():
            if line.startswith("## Citations"):
                in_citations = True
                continue
            if in_citations and line.startswith("## "):
                break
            if in_citations and line.startswith("- ["):
                # Extract URL from [label](url)
                start = line.index("](") + 2
                end = line.index(")", start)
                urls.append(line[start:end])
        assert len(urls) == len(set(urls)), f"Duplicate citation URLs: {urls}"

    def test_citation_no_url_key(self):
        """Citation without a 'url' key should be silently skipped, not crash."""
        rd = {"citations": [{"label": "No URL", "category": "other"}]}
        result = _section_citations(rd)
        assert result == ""

    def test_citation_duplicate_label_different_url(self):
        """Same label but different URL should NOT be deduped."""
        rd = {
            "citations": [
                {"url": "https://a.com", "label": "Source", "category": "official"},
                {"url": "https://b.com", "label": "Source", "category": "media"},
            ]
        }
        result = _section_citations(rd)
        assert "a.com" in result
        assert "b.com" in result


# ---------------------------------------------------------------------------
# Synthetic profile generation (no dependency on real data files)
# ---------------------------------------------------------------------------

class TestSyntheticProfiles:
    """Test generate_profile with controlled synthetic data via tmp_path.
    Isolates logic testing from real data dependencies."""

    @pytest.fixture
    def synthetic_profile(self, tmp_path):
        """Create a minimal synthetic race profile."""
        profile = {
            "race": {
                "name": "Synthetic Race",
                "slug": "synthetic-race",
                "tagline": "A test tagline",
                "vitals": {
                    "distance_mi": 100,
                    "elevation_ft": 5000,
                    "location": "Testville, TS",
                    "date": "2026-06-15",
                    "terrain_types": ["gravel", "dirt"],
                },
                "gravel_god_rating": {
                    "tier": 2, "overall_score": 72, "discipline": "gravel",
                    "logistics": 3, "length": 3, "technicality": 4,
                    "elevation": 3, "climate": 3, "altitude": 2,
                    "adventure": 4, "prestige": 3, "race_quality": 4,
                    "experience": 4, "community": 3, "field_depth": 3,
                    "value": 4, "expenses": 3,
                },
                "course_description": {
                    "character": "Rolling hills with gravel roads.",
                    "suffering_zones": [
                        {"label": "The Wall", "mile": "45", "desc": "Steep climb"},
                    ],
                    "signature_challenge": "Mile 45 climb at 15% grade",
                },
                "final_verdict": {
                    "one_liner": "Worth every pedal stroke.",
                    "should_you_race": "Yes, if you like suffering.",
                },
                "logistics": {"airport": "TST", "official_site": "https://synthetic.race"},
                "history": {"founded": "2020", "origin_story": "Born from a bet."},
                "non_negotiables": [
                    {"requirement": "100mi base", "by_when": "4 weeks out", "why": "Endurance"},
                ],
                "citations": [
                    {"url": "https://example.com/a", "label": "Source A", "category": "official"},
                ],
            }
        }
        (tmp_path / "synthetic-race.json").write_text(json.dumps(profile))
        return tmp_path

    @pytest.fixture
    def synthetic_entry(self):
        return {
            "slug": "synthetic-race", "name": "Synthetic Race", "tier": 2,
            "overall_score": 72, "distance_mi": 100, "elevation_ft": 5000,
            "location": "Testville, TS", "region": "Test Region",
            "month": "June", "discipline": "gravel",
        }

    def test_generates_complete_profile(self, synthetic_profile, synthetic_entry):
        md = generate_profile("synthetic-race", synthetic_entry, synthetic_profile)
        assert md is not None
        assert "# Synthetic Race" in md
        assert "## Vitals" in md
        assert "## Course" in md
        assert "## Gravel God Rating" in md
        assert "## The Verdict" in md
        assert "## Logistics" in md
        assert "## History" in md
        assert "## Non-Negotiables" in md
        assert "## Citations" in md
        assert "Generated by Gravel God" in md

    def test_frontmatter_values_correct(self, synthetic_profile, synthetic_entry):
        md = generate_profile("synthetic-race", synthetic_entry, synthetic_profile)
        assert 'slug: "synthetic-race"' in md
        assert "tier: 2" in md
        assert "score: 72" in md
        assert "distance_mi: 100" in md

    def test_missing_profile_file(self, tmp_path):
        """No JSON file on disk → must return None, not crash."""
        entry = {"slug": "ghost-race", "name": "Ghost"}
        result = generate_profile("ghost-race", entry, tmp_path)
        assert result is None

    def test_corrupt_json_profile(self, tmp_path):
        """Corrupt JSON file → must return None, not crash."""
        (tmp_path / "corrupt-race.json").write_text("{{{bad json")
        entry = {"slug": "corrupt-race", "name": "Corrupt"}
        result = generate_profile("corrupt-race", entry, tmp_path)
        assert result is None

    def test_empty_race_dict(self, tmp_path):
        """Profile with empty 'race' dict → should still generate, just sparse.
        Name falls back to slug when race dict has no 'name' key."""
        (tmp_path / "empty-race.json").write_text('{"race": {}}')
        entry = {"slug": "empty-race", "name": "Empty", "tier": 4, "overall_score": 20}
        result = generate_profile("empty-race", entry, tmp_path)
        assert result is not None
        assert "# empty-race" in result
        assert "Generated by Gravel God" in result


# ---------------------------------------------------------------------------
# Frontmatter with zero values
# ---------------------------------------------------------------------------

class TestFrontmatterZeroValues:
    """_safe(0) must produce 0 in frontmatter, not skip the field."""

    def test_zero_elevation_preserved(self):
        entry = {"slug": "flat", "tier": 4, "overall_score": 20, "elevation_ft": 0}
        rd = {
            "name": "Flat Race",
            "vitals": {"elevation_ft": 0, "distance_mi": 50},
            "gravel_god_rating": {"tier": 4, "overall_score": 20, "discipline": "gravel"},
        }
        fm = _frontmatter("flat", entry, rd)
        assert "elevation_ft: 0" in fm

    def test_zero_distance_preserved(self):
        entry = {"slug": "zero", "tier": 4, "overall_score": 20, "distance_mi": 0}
        rd = {
            "name": "Zero Race",
            "vitals": {"distance_mi": 0},
            "gravel_god_rating": {"tier": 4, "overall_score": 20, "discipline": "gravel"},
        }
        fm = _frontmatter("zero", entry, rd)
        assert "distance_mi: 0" in fm


# ---------------------------------------------------------------------------
# Section builder edge cases
# ---------------------------------------------------------------------------

class TestSectionBuilders:
    """Test individual section builders with edge case data."""

    def test_vitals_all_none(self):
        assert _section_vitals({}) == ""
        assert _section_vitals({"vitals": {}}) == ""

    def test_vitals_partial(self):
        """Only distance present — should still produce a table."""
        rd = {"vitals": {"distance_mi": 100}}
        result = _section_vitals(rd)
        assert "## Vitals" in result
        assert "Distance" in result

    def test_course_empty(self):
        assert _section_course({}) == ""

    def test_course_character_only(self):
        rd = {"course_description": {"character": "Rolling hills."}}
        result = _section_course(rd)
        assert "## Course" in result
        assert "Rolling hills." in result

    def test_rating_empty(self):
        assert _section_rating({}) == ""

    def test_verdict_empty(self):
        assert _section_verdict({}) == ""

    def test_verdict_one_liner_only(self):
        rd = {"final_verdict": {"one_liner": "Pure suffering."}}
        result = _section_verdict(rd)
        assert "## The Verdict" in result
        assert "Pure suffering." in result

    def test_fmt_dist_zero(self):
        assert _fmt_dist(0) == ""

    def test_fmt_elev_zero(self):
        assert _fmt_elev(0) == ""
