"""Pricing single-source-of-truth tests (docs/specs/goals-2027-funnel-spec.md D18).

Three things this file guards:

1. No stray money literal ("$249", "$15/week", ...) outside data/pricing.json
   and the code that reads it. `find_stray_literals()` walks every file
   tracked by git and flags anything that looks like a hand-typed dollar
   figure matching the race plan's current numbers.
2. Equivalence: the price computed by the OLD duplicated formula (weekly
   rate * weeks, 4-week minimum, $249 cap — the formula every generator used
   to hardcode) matches the NEW pricing.json-driven function, for every
   week count from 1 to 60.
3. The Season Plan's shape in pricing.json, and that its reconciliation
   label is registered (docs/specs/goals-2027-funnel-spec.md D15).
"""
from __future__ import annotations

import json
import re
import subprocess
import sys
from pathlib import Path

import pytest

PROJECT_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(PROJECT_ROOT / "wordpress"))

import pricing as wp_pricing  # data/pricing.json (D18)

PRICING_JSON_PATH = PROJECT_ROOT / "data" / "pricing.json"


# ── 1. Stray money literal scanner ───────────────────────────────────

# Every file below is a documented exception. Nothing gets added here
# without a reason — see docs/specs/goals-2027-funnel-spec.md D18.
ALLOWLIST = {
    # Historical docs / specs — the spec explicitly allowlists these.
    ".claude/skills/conversion-and-email/SKILL.md": "handover doc, not code",
    ".claude/skills/email-sequences/SKILL.md": "handover doc, not code",
    "docs/HONEST_AUDIT.md": "historical audit doc",
    "docs/archive/friend-register/council-merged-28-set.md": "historical archive",
    "docs/friend-test-findings.json": "historical test-run record",
    "docs/friend-test-findings.md": "historical test-run record",
    "docs/friend-test-findings-road.json": "historical test-run record",
    "docs/friend-test-findings-road.md": "historical test-run record",
    "docs/handoffs/2026-09-22-season-review-and-goals-funnel.md": "historical handoff",
    "docs/race-page-overhaul-handoff.md": "historical handoff",
    "docs/specs/bikepacking-program-spec.md": "spec doc",
    "docs/specs/goals-2027-funnel-spec.md": "spec doc (this task's own spec)",
    "docs/specs/offseason-goal-setting-product-spec.md": "spec doc",
    "docs/specs/race-countdown-trigger.md": "spec doc",
    "docs/race-page-spine-v2-canonical.md": "durable copy-contract doc; not "
        "code, update by hand alongside a real price change",
    "research-dumps/lake-taupo-cycle-challenge-raw.md": "a race's entry fee, not our product price",

    # Account-state records, not a place copy is authored.
    "data/stripe-products.json": "cached Stripe account price catalog; "
        "checked against pricing.json by TestStripePricingParity in "
        "tests/test_training_plans.py, not a copy source",
    "data/enrichment-snapshots/gravel-and-granite-pre.json": "race enrichment "
        "snapshot; the $ figure is an unrelated race fact",

    # Checked-in generated outputs — the generator that writes them is
    # itself pricing.json-driven (regenerate with the listed command if
    # this ever goes stale).
    "seo/meta-descriptions.json": "generated by scripts/generate_meta_descriptions.py",
    "web/ab/experiments.json": "generated by wordpress/ab_experiments.py",

    # Hand-maintained reference copies outside the generator pipeline. Each
    # one's own docstring/CLAUDE.md entry says it is reference, not truth:
    # generate_training_plans.py is explicitly "Port of web/training-plans.html
    # ... into the generator system", and repo CLAUDE.md documents the
    # questionnaire file as drifted from the live Elementor widget.
    "web/training-plans.html": "superseded reference copy, not live output",
    "web/training-plans-questionnaire.html": "reference copy; live widget is "
        "the source of truth per repo CLAUDE.md",

    # Internal, non-customer-facing text.
    "mission_control/sequences/race_countdown.py": "docstring comment, never rendered",
    "wordpress/generate_mission_control.py": "noindex internal ops dashboard; "
        "the $ figure is a historical build-log entry, not a live price quote",
    "scripts/create_stripe_products.py": "top-of-file usage docstring; the "
        "actual price table (TRAINING_PLAN_PRICES) is pricing.json-driven",

    # The source of truth and its loaders — the numbers legitimately live here.
    "data/pricing.json": "the source of truth",
    "wordpress/pricing.py": "canonical loader; comments illustrate the value",
    "mission_control/services/pricing.py": "canonical loader; comments illustrate the value",

    # Design-lab prototypes — never generated by the pipeline, never deployed.
    "design-lab/race-page-redesign/preview-amundsen-gg.html":
        "static design mockup, not live output; found when the scanner "
        "was extended to cover the Season Plan's $499 (sol review round 2)",
}


def _stray_literal_pattern() -> re.Pattern:
    """Build the scanner regex from pricing.json's own current values, so it
    stays correct if the weekly rate, cap, or Season Plan price ever change."""
    race_plan = wp_pricing.RACE_PLAN
    weekly = re.escape(race_plan["weekly_rate_display"])  # "$15"
    cap = re.escape(race_plan["cap_display"])  # "$249"
    # sol review round 2 NIT: the scanner covered the race plan's two
    # numbers but not the Season Plan's — a hardcoded "$499" anywhere
    # outside data/pricing.json and its loaders would have passed clean.
    season_plan_price = re.escape(wp_pricing.SEASON_PLAN["price_display"])  # "$499"
    return re.compile(
        rf"{cap}\b"
        rf"|{weekly}\s*(?:/\s*(?:week|wk)\b|\s+per\s+week\b)"
        rf"|{season_plan_price}\b",
        re.IGNORECASE,
    )


def _tracked_files() -> list[str]:
    out = subprocess.run(
        ["git", "ls-files"], cwd=PROJECT_ROOT, capture_output=True, text=True, check=True,
    )
    return [line for line in out.stdout.splitlines() if line]


def find_stray_literals() -> list[str]:
    """Return "path:line: text" for every non-allowlisted money literal."""
    pattern = _stray_literal_pattern()
    hits: list[str] = []
    for rel_path in _tracked_files():
        if rel_path in ALLOWLIST:
            continue
        # Test files legitimately assert on real rendered/computed numbers —
        # that verifies the source of truth, it isn't a second copy of it.
        name = Path(rel_path).name
        if name.startswith("test_") and name.endswith(".py"):
            continue
        if not rel_path.endswith((".py", ".js", ".html", ".json", ".md")):
            continue
        full = PROJECT_ROOT / rel_path
        try:
            text = full.read_text(encoding="utf-8")
        except (UnicodeDecodeError, FileNotFoundError):
            continue
        for lineno, line in enumerate(text.splitlines(), start=1):
            if pattern.search(line):
                hits.append(f"{rel_path}:{lineno}: {line.strip()}")
    return hits


def test_no_stray_money_literals():
    hits = find_stray_literals()
    assert not hits, (
        "Found money literals outside data/pricing.json-driven output. "
        "Either source the number from wordpress.pricing / "
        "mission_control.services.pricing, or add a documented entry to "
        "ALLOWLIST in this file:\n" + "\n".join(hits)
    )


# ── 2. Equivalence: old duplicated formula vs. new pricing.json-driven one ──

def _old_race_plan_price_cents(weeks: int) -> int:
    """The formula every generator/template/JS file used to hardcode before
    D18: $15/week, 4-week minimum, $249 cap. This is intentionally NOT
    imported from anywhere — it is the literal old behavior, frozen here so
    the new function can be checked against it."""
    OLD_PRICE_PER_WEEK_CENTS = 1500
    OLD_PRICE_CAP_CENTS = 24900
    OLD_MIN_WEEKS = 4
    weeks = max(OLD_MIN_WEEKS, weeks)
    return min(weeks * OLD_PRICE_PER_WEEK_CENTS, OLD_PRICE_CAP_CENTS)


@pytest.mark.parametrize("weeks", range(1, 61))
def test_price_equivalence_1_to_60_weeks(weeks):
    old_cents = _old_race_plan_price_cents(weeks)
    new_cents = wp_pricing.compute_race_plan_price_cents(weeks)
    assert old_cents == new_cents, (
        f"{weeks} weeks: old formula={old_cents}c, new pricing.json-driven={new_cents}c"
    )


def test_price_equivalence_covers_below_minimum_and_above_cap():
    # 1..60 already covers this, but pin the two edges explicitly so a future
    # refactor can't silently narrow the parametrize range and lose them.
    assert wp_pricing.compute_race_plan_price_cents(1) == wp_pricing.compute_race_plan_price_cents(wp_pricing.MIN_WEEKS)
    assert wp_pricing.compute_race_plan_price_cents(60) == wp_pricing.PRICE_CAP_CENTS


# ── 3. wordpress.pricing / mission_control.services.pricing agree with pricing.json ──

def test_pricing_json_is_the_source():
    raw = json.loads(PRICING_JSON_PATH.read_text())
    assert raw["products"]["race_plan"]["weekly_rate_cents"] == wp_pricing.PRICE_PER_WEEK_CENTS
    assert raw["products"]["race_plan"]["cap_cents"] == wp_pricing.PRICE_CAP_CENTS
    assert raw["products"]["race_plan"]["minimum_weeks"] == wp_pricing.MIN_WEEKS


def test_mission_control_pricing_matches_wordpress_pricing():
    """Both loaders read the same data/pricing.json — they must agree."""
    import importlib
    import types
    import os
    from unittest.mock import MagicMock

    os.environ.setdefault("SUPABASE_URL", "https://fake.supabase.co")
    os.environ.setdefault("SUPABASE_SERVICE_KEY", "fake-key")
    if "supabase" not in sys.modules or not hasattr(sys.modules["supabase"], "Client"):
        fake = types.ModuleType("supabase")
        fake.Client = MagicMock
        fake.create_client = MagicMock()
        sys.modules["supabase"] = fake

    mc_pricing = importlib.import_module("mission_control.services.pricing")

    assert mc_pricing.PRICE_PER_WEEK_CENTS == wp_pricing.PRICE_PER_WEEK_CENTS
    assert mc_pricing.PRICE_CAP_CENTS == wp_pricing.PRICE_CAP_CENTS
    assert mc_pricing.MIN_WEEKS == wp_pricing.MIN_WEEKS
    assert mc_pricing.SEASON_PLAN_PRICE_CENTS == wp_pricing.SEASON_PLAN_PRICE_CENTS
    for weeks in range(1, 61):
        assert (mc_pricing.compute_race_plan_price_cents(weeks)
                == wp_pricing.compute_race_plan_price_cents(weeks))


# ── 4. The generated JS constant (web/training-plans-form.js) ───────────

def test_training_plans_form_js_pricing_block_is_current():
    sys.path.insert(0, str(PROJECT_ROOT / "scripts"))
    import generate_pricing_js

    current = generate_pricing_js.FORM_JS_PATH.read_text()
    assert current == generate_pricing_js.render(current), (
        "web/training-plans-form.js pricing block is stale — run: "
        "python scripts/generate_pricing_js.py"
    )


# ── 5. Season Plan (D2, D15, D16) ────────────────────────────────────────

def test_season_plan_price_is_499():
    assert wp_pricing.SEASON_PLAN_PRICE_CENTS == 49900
    assert wp_pricing.SEASON_PLAN["price_display"] == "$499"


def test_season_plan_shape():
    sp = wp_pricing.SEASON_PLAN
    assert sp["max_weeks"] == 52
    assert sp["scheduled_rebuilds"] == 4
    assert sp["refund_window_days"] == 7
    assert sp["reconciliation_label"] == "season_plan"


def test_season_plan_labour_budget_documented():
    budget = wp_pricing.SEASON_PLAN["labour_budget"]
    assert budget["first_build_minutes"] == 45
    assert budget["rebuild_minutes_each"] == 15
    assert budget["rebuild_count"] == 4
    assert budget["total_minutes_per_athlete_per_year"] == (
        budget["first_build_minutes"] + budget["rebuild_minutes_each"] * budget["rebuild_count"]
    )
    assert budget["total_minutes_per_athlete_per_year"] == 105


def test_season_plan_sits_between_race_plan_and_coaching():
    # D2's reasoning: $499 sits between a $249 race plan and ~$2,600/yr
    # coaching ($199 / 4 weeks * 13 cycles). Pin the ordering, not the exact
    # coaching number (coaching pricing is out of scope for this change).
    assert wp_pricing.PRICE_CAP_CENTS < wp_pricing.SEASON_PLAN_PRICE_CENTS
    coaching_min_yearly_cents = 199 * 100 * 13  # $199 / 4wk cycle, 13 cycles/yr
    assert wp_pricing.SEASON_PLAN_PRICE_CENTS < coaching_min_yearly_cents


def test_season_plan_reconciliation_label_registered():
    """docs/specs/goals-2027-funnel-spec.md D15: a Season Plan sale must be
    classifiable in revenue reporting or it shows up as unattributed."""
    import importlib
    import types
    import os
    from unittest.mock import MagicMock

    os.environ.setdefault("SUPABASE_URL", "https://fake.supabase.co")
    os.environ.setdefault("SUPABASE_SERVICE_KEY", "fake-key")
    if "supabase" not in sys.modules or not hasattr(sys.modules["supabase"], "Client"):
        fake = types.ModuleType("supabase")
        fake.Client = MagicMock
        fake.create_client = MagicMock()
        sys.modules["supabase"] = fake

    mc_pricing = importlib.import_module("mission_control.services.pricing")
    assert "season_plan" in mc_pricing.RECONCILIATION_LABELS
    assert mc_pricing.RECONCILIATION_LABELS["season_plan"] == "Season Plan"
    # The race plan's existing label must still resolve — adding Season Plan
    # must not have displaced it.
    assert mc_pricing.RECONCILIATION_LABELS["training_plan"] == "Custom Training Plan"


def test_season_plan_rebuild_dates_are_four_and_spread_across_the_year():
    """docs/specs/goals-2027-funnel-spec.md D2/D16: four scheduled rebuilds,
    spread across the year, recorded on the order so fulfilment can see
    them. This is the data the checkout server needs — it does not itself
    schedule or automate anything."""
    from datetime import date, timedelta

    purchase = date(2027, 1, 5)
    rebuild_dates = wp_pricing.compute_season_plan_rebuild_dates(purchase)

    assert len(rebuild_dates) == wp_pricing.SEASON_PLAN_REBUILDS == 4
    # Strictly increasing, and every one inside the up-to-52-week season.
    assert rebuild_dates == sorted(rebuild_dates)
    assert rebuild_dates[0] > purchase
    assert rebuild_dates[-1] <= purchase + timedelta(weeks=wp_pricing.SEASON_PLAN_MAX_WEEKS)
    # Spread, not clustered: no two rebuilds inside the same 4-week block.
    for earlier, later in zip(rebuild_dates, rebuild_dates[1:]):
        assert (later - earlier) >= timedelta(weeks=4)
