"""Imported WordPress post: https://gravelgodcycling.com/and-just-like-that-its-over/

Generated by scripts/wp_post_import.py 2916; the body and metadata
(and-just-like-that-its-over.body.html / .json) are regenerated by the
converter, this file is not. ALT is written from what each image shows;
IN_SHORT follows the "In short" rule in wp_post (neutral, third person).

"In short" links point at paragraph anchors that render() adds (ANCHORS); text
is unchanged. A 685-word post: at most two claims.

DESCRIPTION replaces the live meta description ("what a full year of gravel
racing teaches you about effort, aging, and starting over"): the post says
nothing about aging; it is about what the offseason is for.
No infographic.

Regenerate: python3 wordpress/post_sources/and_just_like_that_its_over.py
"""
from __future__ import annotations

import dataclasses
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
if str(HERE.parent) not in sys.path:
    sys.path.insert(0, str(HERE.parent))

from editorial_shell import Claim  # noqa: E402
import wp_post  # noqa: E402

SLUG = "and-just-like-that-its-over"
SOURCE = wp_post.load(SLUG)
OUTPUT_PATH = wp_post.output_path(SLUG)

DESCRIPTION = ("An end-of-season essay: after the last race of the year, the author argues that the offseason "
               "is a time to stop making sense and follow impulses before the work resumes.")

ALT = {
    "season": "Google Maps driving routes from Wisconsin to Fort Collins, Colorado, about 16 hours and 1,019 to 1,086 miles; the Colorado half of the map is grey and labelled \"Off-season\", the Wisconsin half green and labelled \"Season\".",
    "season-1": "Cartoon Gravel God in a cowboy hat, wearing a parachute harness, leaps off the top of a wind turbine above flat brown farm fields.",
    "untitled-design-1": "Cartoon Gravel God in a cowboy hat sits on a wooden bench with his back to the camera, facing a grey, foggy sky between bare shrubs.",
}

ANCHORS = {
    "Left to your default, your neurosis": "p-default",
    "Stop trying to make sense all the time.": "p-stop",
}

# The "In short" rule (wp_post docstring); section = 0-based h2 index.
IN_SHORT = (
    Claim("The post describes three ways to spend the offseason: clinging to fitness, collapsing, or taking a deliberate, brief break.",
          "#p-default", "See the passage · §01", 0),
    Claim("The author argues the offseason is for not making sense, following impulses for a while before the work resumes.",
          "#p-stop", "See the passage · §01", 0),
)


def _anchored(body: str) -> str:
    for start, pid in ANCHORS.items():
        needle = f"<p>{start}"
        if body.count(needle) != 1:
            raise ValueError(f"anchor {pid}: {needle!r} found {body.count(needle)} times")
        body = body.replace(needle, f'<p id="{pid}">{start}', 1)
    return body


def render() -> str:
    src = dataclasses.replace(SOURCE, body=_anchored(SOURCE.body))
    return wp_post.render_post(src, alt=ALT, in_short=IN_SHORT, description=DESCRIPTION)


def main() -> None:
    wp_post.write(OUTPUT_PATH, render())


if __name__ == "__main__":
    main()
