"""Imported WordPress post: https://gravelgodcycling.com/but-are-you-eating-almonds-out-of-your-purse/

Generated by scripts/wp_post_import.py 3811; the body and metadata
(but-are-you-eating-almonds-out-of-your-purse.body.html / .json) are
regenerated by the converter, this file is not. ALT is written from what each
image shows; IN_SHORT follows the "In short" rule in wp_post (neutral, third
person).

The live meta description is kept (it matches the post).

Infographic (2026-10-09): fig-killer-math, the post's two scenarios as one
table, every value as the post states it (nothing computed).
Corrected 2026-10-09 (Matt approved): CORRECTIONS below changes +179 to +178 and the
difference 321 to 322; each
entry names its evidence. The page notes the correction at the end.
KILLER_MATH shows +178 to match.

Regenerate: python3 wordpress/post_sources/but_are_you_eating_almonds_out_of_your_purse.py
"""
from __future__ import annotations

import dataclasses
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
if str(HERE.parent) not in sys.path:
    sys.path.insert(0, str(HERE.parent))

from editorial_shell import Claim, DataTable, TableCell, TableColumn, TableRow  # noqa: E402
import wp_post  # noqa: E402

SLUG = "but-are-you-eating-almonds-out-of-your-purse"
SOURCE = wp_post.load(SLUG)
OUTPUT_PATH = wp_post.output_path(SLUG)

ALT = {
    "killah-2": "Black-and-white photo of the author's mother smiling on a rocky lakeshore, edited as a \"killer\" meme: pixel sunglasses, a gold dollar-sign chain, a cigar beside her, an assault rifle leaning on the rock and a pile of green cash in the corner.",
}

ANCHORS = {
    "How does my mom do that?": "p-purse",
}

# The "In short" rule (wp_post docstring); section = 0-based h2 index.
IN_SHORT = (
    Claim("The post presents the author&rsquo;s mother, who carries healthy food in her purse and does not drink, as a &ldquo;killer&rdquo;: someone who acts on goals.",
          "#p-purse", "See the passage · Intro", 0),
    Claim("It argues that results lag daily choices, so putting a good choice off until tomorrow is why goals fail.",
          "#but-there-it-is-that-s-the-difference-that-s-why-you-failed", "See the passage · Intro", 0),
    Claim("In the post&rsquo;s worked example, three good days with 10% compounding reach +3.31, against +1 after a Friday fish fry.",
          "#fig-killer-math", "See the table · §03", 2),
)

# ── fig-killer-math: the two scenarios side by side ──────────
# Values exactly as the post prints them.
COLUMNS = (
    TableColumn("When", card="title", sortable=False),
    TableColumn("Killer (compounding)", kind="num", card="fact", sortable=False),
    TableColumn("Not killer (linear)", kind="num", card="fact", sortable=False),
)


def _row(when: str, killer: str, linear: str) -> TableRow:
    return TableRow(cells=(TableCell(when), TableCell(killer), TableCell(linear)))


KILLER_MATH = DataTable(
    id="fig-killer-math",
    kicker="The two scenarios above, side by side",
    title="Running totals: compounding good choices vs. a Friday fish fry",
    intro_html="Totals as the post states them.",
    footnote_html=("Days 1&ndash;3: every good choice is +1, with a 10% compounding bonus on the previous "
                   "day&rsquo;s total for the killer; the non-killer starts with a fish fry and beer (&minus;1). "
                   "Six months: the post&rsquo;s figures with the bonus lowered to 1%."),
    columns=COLUMNS,
    rows=(
        _row("Day 1", "+1", "&minus;1"),
        _row("Day 2", "+2.10", "0"),
        _row("Day 3", "+3.31", "+1"),
        _row("Six months (1%)", "+500", "+178"),
    ),
    after="– 322.",
)


def _anchored(body: str) -> str:
    for start, pid in ANCHORS.items():
        needle = f"<p>{start}"
        if body.count(needle) != 1:
            raise ValueError(f"anchor {pid}: {needle!r} found {body.count(needle)} times")
        body = body.replace(needle, f'<p id="{pid}">{start}', 1)
    return body


# Figures corrected to match the post's own evidence (Matt, 2026-10-09:
# "Yeah go ahead and fix"). wp_post applies each to the body (old text must
# occur exactly once) and the word-for-word tests apply them to the snapshot.
CORRECTIONS = (
    wp_post.Correction(
        "+179",
        "+178",
        "the post's linear scenario (-1, then +1 a day) reaches +178 at 180 days; the +500 compounding figure is 180 days at 1%"),
    wp_post.Correction(
        "– 321.",
        "– 322.",
        "500 - 178 = 322"),
)


def render() -> str:
    src = dataclasses.replace(SOURCE, body=_anchored(SOURCE.body))
    return wp_post.render_post(src, corrections=CORRECTIONS, alt=ALT, in_short=IN_SHORT, figures=(KILLER_MATH,))


def main() -> None:
    wp_post.write(OUTPUT_PATH, render())


if __name__ == "__main__":
    main()
