"""Imported WordPress post: https://gravelgodcycling.com/controversial-opinion-you-dont-need-a-power-meter-to-be-fast/

Generated by scripts/wp_post_import.py 1078; the body (controversial-opinion-you-dont-need-a-power-meter-to-be-fast.body.html) and
metadata (controversial-opinion-you-dont-need-a-power-meter-to-be-fast.json) are regenerated by the converter, this file is not.
ALT is written from what each image shows; IN_SHORT follows the "In short" rule in wp_post (neutral, third person).

The post has no headings, so "In short" links point at paragraph anchors that
render() adds (ANCHORS: the paragraph's opening words -> id). Text is unchanged.

Infographic (2026-10-09): fig-fortunato-year, the two "ballpark" paragraphs as a
table. Every figure is the post's own wording ("approximately 3 hours a day",
"almost 20,000 miles", "nearly 50,000"); cells the post doesn't state are left
empty. Nothing is computed.

DESCRIPTION replaces the live meta description, which promised "when data
helps, when it hurts"; the post leaves when power meters help for another day
and is about a rider who trains by volume without one.

Regenerate: python3 wordpress/post_sources/controversial_opinion_you_dont_need_a_power_meter_to_be_fast.py
"""
from __future__ import annotations

import dataclasses
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
if str(HERE.parent) not in sys.path:
    sys.path.insert(0, str(HERE.parent))

from editorial_shell import Claim, DataTable, TableCell, TableColumn, TableRow  # noqa: E402
import wp_post  # noqa: E402

SLUG = "controversial-opinion-you-dont-need-a-power-meter-to-be-fast"
SOURCE = wp_post.load(SLUG)
OUTPUT_PATH = wp_post.output_path(SLUG)

DESCRIPTION = ("Fortunato Ferrara, a national-level New Mexico rider, trains about 20 hours a week without "
               "a power meter; the post argues that riding lots matters more than power data.")

ALT = {
    "fortunato-doesnt-use-a-power-meter": "A nuclear mushroom cloud glowing orange against a dark sky, under the words \"Fortunato doesn't use a power meter.\"",
    "you-dont-need-a-power-meter-to-be-fast": "Chalk lightbulbs hang on a blackboard; the one above cartoon Gravel God's head is lit in rainbow colours, and his speech bubble reads: \"You don't need a power meter to be fast.\"",
    "wow": "Cartoon Gravel God rides his bike through a starfield in front of a spiral galaxy, saying: \"Wow.\"",
    "copy-of-just-say-no-1": "A red no-entry street sign on a weathered wall, with a Shimano 105 crank arm laid across it as the slash.",
}

ANCHORS = {
    "He KOMed the segment 4 hours in": "p-kom",
    "That’s laughed at now": "p-simple-measures",
}

# The "In short" rule (wp_post docstring); one section (no headings).
IN_SHORT = (
    Claim("Fortunato Ferrara, described as national-level fast, trains without a power meter and sets KOMs hours into long rides.",
          "#p-kom", "See the passage", 0),
    Claim("He rides roughly 20 hours a week all year: about 1,000 hours, almost 20,000 miles and nearly 50,000 TSS a year by the post&rsquo;s estimate.",
          "#fig-fortunato-year", "See the numbers", 0),
    Claim("The post argues that simple measures, such as riding 100 miles, ask something of a rider that a power meter does not.",
          "#p-simple-measures", "See the passage", 0),
)

# ── fig-fortunato-year: the ballpark paragraphs as a table ───
# (period, hours, miles, TSS): the post's words; "" = not stated.
YEAR = (
    ("Per day", "approximately 3", "", "140"),
    ("Per week", "20", "about 400", ""),
    ("Per month", "80", "1,600", "almost 4,000"),
    ("Per year", "1,000", "almost 20,000", "nearly 50,000"),
)

YEAR_TABLE = DataTable(
    id="fig-fortunato-year",
    kicker="The two paragraphs above, as a table",
    title="Twenty hours a week, every week",
    intro_html="The post&rsquo;s ballpark for Fortunato&rsquo;s training, in its own words.",
    footnote_html=("Miles assume &ldquo;a rough average of 20 miles an hour&rdquo;; TSS assumes &ldquo;an average intensity "
                   "factor of 0.7&rdquo;. &mdash; = not stated in the post. The post adds: CTL &ldquo;about 140&rdquo;, "
                   "&ldquo;like Fortunato averages going almost an hour and a half at threshold every day&rdquo;."),
    columns=(
        TableColumn("Period", card="title", sortable=False),
        TableColumn("Hours", card="fact", sortable=False),
        TableColumn("Miles", card="fact", sortable=False),
        TableColumn("TSS", card="row", sortable=False),
    ),
    rows=tuple(TableRow(cells=tuple(TableCell(v) for v in row)) for row in YEAR),
    after="for the entire year, for the past eight years.</p>",
)


# Nothing in this table sorts, so the shell's "Click a column to sort" hint is hidden.
CSS = "#fig-fortunato-year .gg-sort-hint{display:none}"


def _anchored(body: str) -> str:
    for start, pid in ANCHORS.items():
        needle = f"<p>{start}"
        if body.count(needle) != 1:
            raise ValueError(f"anchor {pid}: {needle!r} found {body.count(needle)} times")
        body = body.replace(needle, f'<p id="{pid}">{start}', 1)
    return body


def render() -> str:
    src = dataclasses.replace(SOURCE, body=_anchored(SOURCE.body))
    return wp_post.render_post(src, alt=ALT, in_short=IN_SHORT, figures=(YEAR_TABLE,), extra_css=CSS,
                               description=DESCRIPTION)


def main() -> None:
    wp_post.write(OUTPUT_PATH, render())


if __name__ == "__main__":
    main()
