"""Imported WordPress post: https://gravelgodcycling.com/david-beckham-has-something-to-say-to-cyclists/

Generated by scripts/wp_post_import.py 3581; the body and metadata
(david-beckham-has-something-to-say-to-cyclists.body.html / .json) are
regenerated by the converter, this file is not. ALT is written from what each
image shows (all five are AI-generated pictures of a Beckham lookalike; the
file names carry the prompts); IN_SHORT follows the "In short" rule in wp_post.

The featured image is also inline, so the page has no hero. No infographic:
the post's one "formula" is already plain text. The live meta description
stands (it is narrow but not wrong).

Regenerate: python3 wordpress/post_sources/david_beckham_has_something_to_say_to_cyclists.py
"""
from __future__ import annotations

import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
if str(HERE.parent) not in sys.path:
    sys.path.insert(0, str(HERE.parent))

from editorial_shell import Claim  # noqa: E402
import wp_post  # noqa: E402

SLUG = "david-beckham-has-something-to-say-to-cyclists"
SOURCE = wp_post.load(SLUG)
OUTPUT_PATH = wp_post.output_path(SLUG)

ALT = {
    "wattgod-david-beckham-riding-a-gravel-bike-ar-169-v-5-2-fd206068-68ed-4d07-b872-62cdb4a69aec": "AI-generated image of a David Beckham lookalike in orange sunglasses and a tan T-shirt riding a bike through blowing dust between desert dunes, a figure walking in the haze behind him.",
    "wattgod-david-beckham-winning-the-champions-league-v-5-2-4c787519-8203-4e7a-84f3-d0a302b855a8": "AI-generated image of a Beckham lookalike in a white kit and a winner's medal, grinning as he cradles a large silver trophy under falling confetti, teammates celebrating beside him.",
    "wattgod-david-beckham-practicing-soccer-as-a-kid-ar-169-v-5-5df1e189-6dc7-482d-802a-901587ecdfc6": "AI-generated image of a tattooed Beckham lookalike in a maroon shirt walking across a pitch with a football at his feet, a blond boy in a green kit following behind him.",
    "wattgod-david-beckham-meditating-on-the-soccer-pitch-crowd-yell-ec77f21d-fb52-46eb-9727-41705bf700b3": "AI-generated image of a Beckham lookalike in a red shirt, head thrown back, eyes shut and mouth wide open in a roar, in a floodlit stadium packed with fans.",
    "wattgod-david-beckham-versions-of-him-from-child-to-old-man-a-da6f722f-c6cf-473d-ae18-962d3639f797": "Two AI-generated portraits of a Beckham lookalike side by side on black: older and grey-haired in a cardigan on the left, younger with a swept-up quiff and a collared shirt on the right.",
}

# The "In short" rule (wp_post docstring); section = 0-based h2 index.
IN_SHORT = (
    Claim("The post uses the Beckham documentary to argue that likability, not only legs, can decide whether a young rider lands on a good team.",
          "#likability", "See Likability · §01", 0),
    Claim("It sets out exceptional results as talent plus extreme work ethic plus an extreme lifestyle, not talent alone.",
          "#success", "See Success · §02", 1),
    Claim("Citing Beckham&rsquo;s recovery after his 1998 World Cup red card, the post argues that getting through setbacks depends on the people in a rider&rsquo;s life.",
          "#compartmentalization", "See Compartmentalization · §04", 3),
    Claim("Because physical potential declines with age, the post argues that cycling goals should be aggressive while there is still time to chase them.",
          "#realities-of-aging", "See Realities of Aging · §05", 4),
)


def render() -> str:
    return wp_post.render_post(SOURCE, alt=ALT, in_short=IN_SHORT)


def main() -> None:
    wp_post.write(OUTPUT_PATH, render())


if __name__ == "__main__":
    main()
