"""Imported WordPress post: https://gravelgodcycling.com/does-beer-make-you-slow/

Generated by scripts/wp_post_import.py 1269; the body (does-beer-make-you-slow.body.html) and
metadata (does-beer-make-you-slow.json) are regenerated by the converter, this file is not.
ALT is written from what each image shows. IN_SHORT is a DRAFT for Matt's
read: plain, third-person statements of what the post argues, each one
supported by the post text.

Infographic (2026-10-09): fig-beer-steps, the post's second chalkboard chart
("Fitness progression" sober vs with beer) redrawn as SVG with draw-in. The
chart has no units or numbers; the step positions are digitized from the
original (~/specs/gg-wp-posts-2026-10-09/pilot/tools/digitize_beer_steps.py,
px in the 1200x600 original) and drawn unitless, exactly as the chalk shows
them. The original image stays one click away under the chart; the first
(sober-only) chart is kept as the post has it.

Regenerate: python3 wordpress/post_sources/does_beer_make_you_slow.py
"""
from __future__ import annotations

import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
if str(HERE.parent) not in sys.path:
    sys.path.insert(0, str(HERE.parent))

from editorial_shell import Claim  # noqa: E402,F401
import wp_post  # noqa: E402
from wp_post import HtmlFigure  # noqa: E402

SLUG = "does-beer-make-you-slow"
SOURCE = wp_post.load(SLUG)
OUTPUT_PATH = wp_post.output_path(SLUG)

ALT = {
    "does-beer-make-you-slow": "Close-up of golden beer and foam filling the frame, with cartoon Gravel God in a cowboy hat standing arms crossed in front of it.",
    "thats-unexpected": "Cartoon Gravel God's head in a cowboy hat beside a speech bubble: \"Wait, so drinking poison makes me feel great? That's Unexpected.\"",
    "dont-drink": "Chalkboard headed \"Don't freaking drink\" in red neon letters: four glasses of beer, each crossed out with a red no sign, around cartoon Gravel God.",
    "fitness-progression-sober": "Chalkboard chart titled \"Fitness progression - sober\": fitness against time as eight chalk steps climbing evenly from bottom left to upper right, with a big hatched arrow pointing up.",
    "fitness-progression-sober-1": "The same chalkboard chart titled \"Fitness progression\" with a beer mug: the eight white sober steps, and below them seven yellow steps that start at the second step and climb about half as steeply. Cartoon Gravel God in the corner says \"Oh.\"",
    "blinking-arrow": "Animated: a big white arrow pointing right, nudging forward on a dark background.",
    "dont-drink-1": "A huge wave and fiery meteors bear down on a coastal town; a tiny cartoon Gravel God on a bike in the foreground says: \"It's a disaster.\"",
    "why-cyclists-drink": "Chalkboard titled \"Why cyclists drink\" beside cartoon Gravel God: \"1. It's fun. 2. Athletes think training allows them certain liberties, like happy hour. 3. Humans suck at grasping the effect of small choices over time.\"",
    "it-depends": "Cartoon Gravel God in a cowboy hat, arms crossed, wearing an adult diaper, with an arrow labelled \"It...\" pointing at it; small text in the corner reads \"(That's a Depends diaper)\".",
}

# Figures this module adds (excluded from the word-for-word text diff).
ADDED_IDS = {"fig-beer-steps"}

# DRAFT for Matt: matter-of-fact statements of what the post argues;
# section = 0-based h2 index.
IN_SHORT = (
    Claim("The post states that regular drinking leaves the body only partially adapted to training, because it clears alcohol before catching up on training strain.",
          "#huh", "See §03", 2),
    Claim("Repeated over months, it says, that partial adaptation compounds into a large fitness gap, as its two step charts show.",
          "#fig-beer-steps", "See the chart · §03", 2),
    Claim("It argues for periodized enthusiasm: happy hour is fine months out, but within two months of racing season, drinking should stop or be severely limited.",
          "#periodized-enthusiasm", "See §04", 3),
)

# ── fig-beer-steps: the chalkboard chart, redrawn ────────────
# (x_start, x_end, y_centre) in px of the 1200x600 original; the x axis is at
# y = 540 and the y axis at x = 110. Unitless: the chalk chart has no numbers.
SOBER = ((137, 251, 456), (252, 367, 421), (378, 493, 386.5), (516, 630, 348.5),
         (641, 754, 318.5), (766, 878, 289.5), (890, 999, 262), (1010, 1118, 233.5))
DRINKING = ((256, 376, 438.5), (391, 506, 421), (517, 630, 404.5), (639, 755, 386),
            (764, 879, 368), (881, 996, 348.5), (997, 1116, 331))
_INK, _INK2, _TEAL, _GOLD = "#2a211b", "#59473c", "#178079", "#7d6508"


def _X(x: float) -> float:
    return 56 + (x - 110) * 0.58


def _Y(y: float) -> float:
    return 262 - (540 - y) * 0.68


def _steps(segs, colour: str, i: int, dash: str = "") -> str:
    d = " ".join(f"M{_X(a):.1f},{_Y(y):.1f}H{_X(b):.1f}" for a, b, y in segs)
    da = f' stroke-dasharray="{dash}"' if dash else ""
    return (f'<path d="{d}" fill="none" stroke="{colour}" stroke-width="5" stroke-linecap="round"{da} '
            f'data-draw="wipe" style="--draw-dur:1.2s;--draw-i:{i * 6}"/>')


def _svg() -> str:
    top, bottom = 22, 262
    last_s, last_d = SOBER[-1], DRINKING[-1]
    return (
        '<svg viewBox="0 0 680 300" role="img" aria-labelledby="beer-steps-t beer-steps-d" '
        'xmlns="http://www.w3.org/2000/svg">'
        '<title id="beer-steps-t">Fitness progression, sober and with beer</title>'
        '<desc id="beer-steps-d">Fitness against time, no units. Sober: eight equal steps climbing steadily. '
        'With beer: from the second step on, seven steps that climb about half as much each time, '
        'so the gap to the sober line widens with every step.</desc>'
        f'<path d="M56,{top}V{bottom}H660" fill="none" stroke="{_INK}" stroke-width="1.6"/>'
        f'<text x="358" y="{bottom + 26}" text-anchor="middle" font-size="14" fill="{_INK2}">Time</text>'
        f'<text transform="translate(34 {(top + bottom) / 2}) rotate(-90)" text-anchor="middle" font-size="14" '
        f'fill="{_INK2}">Fitness</text>'
        + _steps(SOBER, _TEAL, 0)
        + _steps(DRINKING, _GOLD, 1)
        + f'<text x="{_X(last_s[1]) - 2:.1f}" y="{_Y(last_s[2]) - 14:.1f}" text-anchor="end" font-size="15" '
          f'font-weight="700" fill="{_TEAL}" data-draw="fade" style="--draw-at:1200ms">Sober</text>'
        + f'<text x="{_X(last_d[1]) - 2:.1f}" y="{_Y(last_d[2]) + 26:.1f}" text-anchor="end" font-size="15" '
          f'font-weight="700" fill="{_GOLD}" data-draw="fade" style="--draw-at:1900ms">With beer</text>'
        "</svg>"
    )


STEPS_FIGURE = HtmlFigure(
    id="fig-beer-steps",
    kicker="The chart above, redrawn",
    title="Fitness progression: sober and with beer",
    html=_svg(),
    caption_html=("The post&rsquo;s chalkboard chart, traced step for step. It has no units: "
                  "it shows the shape of the argument, not a measurement."),
)

CSS = """
#fig-beer-steps svg{max-width:640px;margin:0 auto}
"""



def render() -> str:
    return wp_post.render_post(SOURCE, alt=ALT, in_short=IN_SHORT,
                               replace={"fitness-progression-sober-1": STEPS_FIGURE},
                               replace_label="Show the original chart (with Gravel God)", extra_css=CSS)


def main() -> None:
    wp_post.write(OUTPUT_PATH, render())


if __name__ == "__main__":
    main()
