"""Imported WordPress post: https://gravelgodcycling.com/eight-years-of-nate-wilson/

Generated by scripts/wp_post_import.py 3594; the body and metadata
(eight-years-of-nate-wilson.body.html / .json) are regenerated by the converter,
this file is not. ALT is written from what each image shows (the three workout
screenshots transcribed); IN_SHORT follows the "In short" rule in wp_post
(neutral, third person). The live meta description is kept; TITLE replaces the
live title ("Eight Years of Coaching Nate"), which inverts the post: Nate
Wilson coached the author (2015 to 2021). The new title keeps the headline's words.

The post's only heading is a long quote, so "In short" links point at paragraph
anchors that render() adds (ANCHORS: the paragraph's opening words -> id). Text
is unchanged. The one approved comment renders as a read-only archive.

Infographic (2026-10-09): fig-road-to-cat-1, the years the post names from
2013 to 2019 as a table. Every quote is the post's; nothing is computed.

Matt to read: the post's workout description ("4x10min that are 40 sec @
420-480, 20 sec easy, 9min steady @ 320-340" and "1x4min vo2 @ 400-440") does
not match the screenshots it follows ("3x10min that are 2min @ 400-420, 8min @
320-340" and "1x4min vo2 @ 400-430").

Regenerate: python3 wordpress/post_sources/eight_years_of_nate_wilson.py
"""
from __future__ import annotations

import dataclasses
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
if str(HERE.parent) not in sys.path:
    sys.path.insert(0, str(HERE.parent))

from editorial_shell import Claim, DataTable, TableCell, TableColumn, TableRow  # noqa: E402
import wp_post  # noqa: E402

SLUG = "eight-years-of-nate-wilson"
SOURCE = wp_post.load(SLUG)
OUTPUT_PATH = wp_post.output_path(SLUG)

TITLE = "Eight Years of Nate Wilson, My Cycling Coach | Gravel God"

ALT = {
    "november-2015-bar": "Illustration: cartoon Gravel God's grinning head on a muscular man in a white T-shirt and denim shorts, holding a beer outside a bar on a Boulder, Colorado street, while a curly-haired man in glasses drinks at a stool nearby.",
    "flagstaff-tears": "Illustration: cartoon Gravel God in a cowboy hat, tears streaming down his face, sits hugging his knees beside a road through golden foothills, his bike leaning on the bank.",
    "screenshot-2023-11-15-at-14-07-13": "TrainingPeaks workout description: \"45-60min Z1/Z2 warm up, then this gold standard Boulder climbing workout\": NCAR from Broadway at tempo (300-330w) with 1min 300-330w / 30 sec out of the saddle @ 420-460w alternations, Super Flag to the amphitheater @ 320-340w, a climb up to Gross at 300-330w after a hard first pitch, and a Z4 effort up backside Flag.",
    "screenshot-2023-11-15-at-14-05-27": "TrainingPeaks workout description: \"30-45min z2 warmup, then on a climb: 3x10min that are 2min @ 400-420, 8min @ 320-340. 6min recovery between efforts. Finish with 5x30 sec hard w/ 30 sec recovery between\", shooting for 500+.",
    "screenshot-2023-11-15-at-14-03-19": "TrainingPeaks workout description: \"Warmup for 30+. 6x10 sec HARD sprints, w/ 50 sec easy between. z2. 10min tempo climb @ 300-330, ramp to 380-400 the last 2min. spin out for 5-10min. 1x4min vo2 @ 400-430. cooldown\".",
    "spirit-of-nate": "Illustration: cartoon Gravel God in a cowboy hat rides a gravel road through sagebrush toward mountains, as the faint face of a smiling man in glasses floats in the sky like a spirit.",
    "icarus-matti": "Illustration: cartoon Gravel God, grinning, walks his bike up a ridge toward a blazing sun over rolling desert hills.",
    "watching-nate-go": "Illustration: a man in a cowboy hat and denim shorts, seen from behind, stands at an airport window watching a plane take off.",
    "nate-zoom": "A laptop on a wooden table showing a video call with a smiling, curly-haired man in glasses, a coffee cup beside it.",
    "life": "Illustration: cartoon Gravel God, seen from behind at his handlebars, looks down a long desert road, the word \"LIFE\" faint in the sky.",
    "dalle-2023-11-15-14-18-34-create-a-full-body-portrait-of-a-character-for-company-branding-in-a-16-9-aspect-ratio-with-the-characters-back-shown-riding-toward-the-mountains-a": "Illustration: a rider in a cowboy hat, white T-shirt and denim shorts, seen from behind, rides down a road toward the Flatirons at sunrise, snow on the slopes.",
}

ANCHORS = {
    "“I’ll coach you,” Nate said.": "p-ill-coach-you",
    "That year, in 2018, at the Green Mountain Stage Race": "p-cat-1",
    "Nate taught me that in the end, it was on me.": "p-on-me",
    "But, that’s not enough. That’s not why you should hire a coach.": "p-hire",
}

# The "In short" rule (wp_post docstring); section = 0-based h2 index.
IN_SHORT = (
    Claim("The post recounts how Nate Wilson, a former World Tour rider, offered in a Boulder bar in 2015 to coach the author.",
          "#p-ill-coach-you", "See the passage", 0),
    Claim("After cutting his weight from 187 to 168 pounds in three months, the author upgraded to Cat 1 at the 2018 Green Mountain Stage Race.",
          "#p-cat-1", "See the passage", 0),
    Claim("The post argues that coaches rarely name an athlete&rsquo;s rate-limiting factors, such as weight or drinking, so responsibility for them rests with the athlete.",
          "#p-on-me", "See the passage", 0),
    Claim("The post gives two reasons to hire a coach: an athlete&rsquo;s own blind spot, and needing someone else to care.",
          "#p-hire", "See the passage", 0),
)

# ── fig-road-to-cat-1: the years the post names, 2013-2019 ───
# (year, quote): word for word from the post.
YEARS = (
    ("2013", "In my first P12 race at the Dead Dog Classic in Wyoming", "I finished fifth."),
    ("2014", "2014 was a humiliation.", ""),
    ("2015", "“I’ll coach you,” Nate said.", ""),
    ("2017", "The day after Thanksgiving 2017, I stepped on a scale.", "I saw 187 lbs. I still wasn’t CAT 1."),
    ("2018", "Three months later, I was 168 lbs.", "sealing enough points to upgrade to Cat 1 after five long years in roadie limbo."),
    ("2019", "at 32, competed in my first NRC race.", "I finished 35th overall."),
)


def _quote(*parts: str) -> TableCell:
    return TableCell(" &hellip; ".join(f"&ldquo;{p}&rdquo;" for p in parts if p))


ROAD_TO_CAT_1 = DataTable(
    id="fig-road-to-cat-1",
    kicker="The years above, in order",
    title="2013 to 2019, in the post’s words",
    intro_html="The years the post names on the way to Cat 1 and the NRC.",
    footnote_html="Every quote is from the post. &hellip; = words left out.",
    columns=(
        TableColumn("Year", card="title", sortable=False),
        TableColumn("In the post", card="row", sortable=False),
    ),
    rows=tuple(TableRow(cells=(TableCell(y), _quote(a, b))) for y, a, b in YEARS),
    after="I finished 35th overall.</p>",
)

# Nothing in this table sorts, so the shell's "Click a column to sort" hint is hidden.
CSS = "#fig-road-to-cat-1 .gg-sort-hint{display:none}"


def _anchored(body: str) -> str:
    for start, pid in ANCHORS.items():
        needle = f"<p>{start}"
        if body.count(needle) != 1:
            raise ValueError(f"anchor {pid}: {needle!r} found {body.count(needle)} times")
        body = body.replace(needle, f'<p id="{pid}">{start}', 1)
    return body


def render() -> str:
    src = dataclasses.replace(SOURCE, body=_anchored(SOURCE.body))
    return wp_post.render_post(src, alt=ALT, in_short=IN_SHORT, figures=(ROAD_TO_CAT_1,), extra_css=CSS, title=TITLE)


def main() -> None:
    wp_post.write(OUTPUT_PATH, render())


if __name__ == "__main__":
    main()
