"""Imported WordPress post: https://gravelgodcycling.com/gratitude-and-toilet-bowls/

Generated by scripts/wp_post_import.py 2345; the body (gratitude-and-toilet-bowls.body.html) and
metadata (gratitude-and-toilet-bowls.json) are regenerated by the converter, this file is not.
ALT is written from what each image shows. IN_SHORT is a DRAFT for Matt's
read: plain, third-person statements of what the post argues, each one
supported by the post text. The post has no headings (one section), so the
links point at the image that opens each part. No infographic: the post
states no figures worth charting.

Regenerate: python3 wordpress/post_sources/gratitude_and_toilet_bowls.py
"""
from __future__ import annotations

import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
if str(HERE.parent) not in sys.path:
    sys.path.insert(0, str(HERE.parent))

from editorial_shell import Claim  # noqa: E402,F401
import wp_post  # noqa: E402

SLUG = "gratitude-and-toilet-bowls"
SOURCE = wp_post.load(SLUG)
OUTPUT_PATH = wp_post.output_path(SLUG)

ALT = {
    "toilet-bowls": "Cartoon Gravel God in a cowboy hat lies flat on a bathroom floor in front of a toilet, blue tiles behind him, staring up at the ceiling.",
    "toilet-bowls-2": "Cartoon Gravel God lies in a hospital bed, hat still on, saying: \"I'm fine. I'm totally fine. I can train tomorrow for sure.\"",
    "who-likes-to-party": "Photo of a family dining table on a snowy day: two small children at the table, a woman holding a baby, a plate of pastries; cartoon Gravel God floats above it holding a bottle of champagne and a cinnamon roll.",
    "must-not-slip": "A TrainingPeaks calendar for the week of the 22nd to the 28th, with endurance rides, strength sessions and a summary panel (Fitness 78, Fatigue 41, Form 32); cartoon Gravel God rides a bike in front of it: \"Must. Not. Slip.\"",
    "must-not-slip-1": "A young man glares sideways under a speech bubble: \"I don't care if anyone likes me. I want to win the local race series at all costs!\"",
    "must-not-slip-2": "Photo of a smiling man in a cowboy hat and a laughing baby peeking over the back of a brown leather couch in a living room.",
}

# DRAFT for Matt: matter-of-fact statements of what the post argues;
# section = 0-based h2 index (the post has one section).
IN_SHORT = (
    Claim("The post recounts food poisoning in 2019 that led the author to skip his usual four-hour Thanksgiving ride and spend the day with family.",
          "#fig-toilet-bowls-2", "See the story", 0),
    Claim("It argues that no single day of training decides a race in April, and that rigid adherence without exceptions is itself harmful.",
          "#fig-must-not-slip", "See the argument", 0),
    Claim("It calls the balance an art: pushing hard, letting go, and being present for the occasions that matter to other people.",
          "#fig-must-not-slip-1", "See the balance", 0),
)


def render() -> str:
    return wp_post.render_post(SOURCE, alt=ALT, in_short=IN_SHORT)


def main() -> None:
    wp_post.write(OUTPUT_PATH, render())


if __name__ == "__main__":
    main()
