"""Imported WordPress post: https://gravelgodcycling.com/hacking-unbound-200-with-best-bike-split/

Generated by scripts/wp_post_import.py 3203; the body and metadata
(hacking-unbound-200-with-best-bike-split.body.html / .json) are regenerated by
the converter, this file is not. ALT is written from what each image shows;
IN_SHORT follows the "In short" rule in wp_post (neutral, third person).

DESCRIPTION replaces the live meta description ("how to build a data-driven
pacing strategy"): the post is not about pacing; it estimates how much time
equipment, weight and fitness changes save at Unbound 200.

The closing price tables are the converter's price-table mapping. The coaching
table's "Apply Now" button has an empty link on the live page, so it stays
plain text.

Infographic (2026-10-09): fig-bbs-savings, the three Best Bike Split time
savings the post states in its text, as a table. Nothing derived.

Matt to read:
- The post's FTP tables (~9:30 and ~12:30 finishers), the "Combined" buy-vs-earn
  breakdown, the dollars-per-watt aero list and the tire Crr chart are not on
  the live page (their Elementor columns are empty), so the text refers to
  tables that aren't there. Not recreated: the numbers aren't in the post.
- Numbers: a 7 W chain saving = 15:29 and "the equivalent of raising your FTP
  by 4%", but 7 W is 1.9% of the 370 W FTP, and the post's own +5% power run
  saves only 17:33. The Best Bike Split screenshot (12:26:02, NP 161.64 W,
  IF 0.65, 1.92 W/kg) implies an FTP near 249 W and about 82 kg, not the
  post's rider (FTP 370, 166 lb).

Regenerate: python3 wordpress/post_sources/hacking_unbound_200_with_best_bike_split.py
"""
from __future__ import annotations

import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
if str(HERE.parent) not in sys.path:
    sys.path.insert(0, str(HERE.parent))

from editorial_shell import Claim, DataTable, TableCell, TableColumn, TableRow  # noqa: E402
import wp_post  # noqa: E402

SLUG = "hacking-unbound-200-with-best-bike-split"
SOURCE = wp_post.load(SLUG)
OUTPUT_PATH = wp_post.output_path(SLUG)

ALT = {
    "47-watts-1": "Cartoon Gravel God in a cowboy hat rides a gravel road through green farmland past an old wooden barn, with watt savings floating around him: \"-47 watts\", \"-17 watts\", \"-10 watts\" and \"-5 watts\".",
    "unbound-best-bike-split-scaled": "Best Bike Split screenshot of the race plan \"Unbound 200 (Gravel God)\" on the 2022 Unbound 200 course with the Default Gravel Bike: power, speed and elevation over 200 miles, a route map around Emporia, Kansas, and a race overview of 199.98 mi, 12:26:02, 16.08 mph, 156.72 W average and 161.64 W normalized power, IF 0.65, TSS 523, 1.92 W/kg.",
    "47-watts-2": "Cartoon Gravel God in a cowboy hat stands on a grassy verge beside a wide, freshly graded white gravel road, puffing a cigar.",
}

DESCRIPTION = ("Best Bike Split estimates of how much time chain waxing, aero, tires, weight loss and fitness "
               "save at Unbound 200, and what the simulator leaves out.")

# The "In short" rule (wp_post docstring); section = 0-based h2 index.
IN_SHORT = (
    Claim("The post argues that the slower a rider goes, the more time small gains save, because they act over more hours.",
          "#baseline", "See Baseline · §02", 1),
    Claim("By its Best Bike Split runs, a waxed chain saving up to 7 watts is worth 15:29 over Unbound 200.",
          "#fig-bbs-savings", "See the numbers · §02", 1),
    Claim("On Unbound&rsquo;s rolling course, the post finds a 5% weight loss saves about half the time of a 5% power gain.",
          "#weight-loss", "See Weight Loss · §02", 1),
    Claim("Its bottom line: equipment can buy about a third of a rider&rsquo;s potential speed; fitness, skills and execution make up the rest.",
          "#combined", "See Combined · §02", 1),
)

# ── fig-bbs-savings: the post's stated Best Bike Split results ───
SAVINGS = DataTable(
    id="fig-bbs-savings",
    kicker="The numbers above, side by side",
    title="Time saved at Unbound 200, by Best Bike Split",
    intro_html="The three simulation results the post states in its text.",
    footnote_html=("From the post&rsquo;s Best Bike Split runs for Unbound 200 (rider: age 26, 166 lbs, FTP 370; "
                   "default gravel bike). Chain: &ldquo;as much as 7 watts (in extreme cases)&rdquo; of drivetrain loss."),
    columns=(
        TableColumn("Change", card="title", sortable=False),
        TableColumn("Time saved", card="fact", sortable=False),
    ),
    rows=(
        TableRow(cells=(TableCell("Clean, waxed chain (up to 7 W)"), TableCell("15:29"))),
        TableRow(cells=(TableCell("Power +5%"), TableCell("17:33"))),
        TableRow(cells=(TableCell("Body weight &minus;5%"), TableCell("8:18"))),
    ),
    after="decreasing your weight by 5% saves you 8:18.</p>",
)

# Nothing in this table sorts, so the shell's "Click a column to sort" hint is hidden.
CSS = "#fig-bbs-savings .gg-sort-hint{display:none}"


def render() -> str:
    return wp_post.render_post(SOURCE, alt=ALT, in_short=IN_SHORT, figures=(SAVINGS,), extra_css=CSS,
                               description=DESCRIPTION)


def main() -> None:
    wp_post.write(OUTPUT_PATH, render())


if __name__ == "__main__":
    main()
