"""Imported WordPress post: https://gravelgodcycling.com/how-to-hydrate-so-you-dont-die-in-your-gravel-race/

Generated by scripts/wp_post_import.py 2014; the body (how-to-hydrate-so-you-dont-die-in-your-gravel-race.body.html) and
metadata (how-to-hydrate-so-you-dont-die-in-your-gravel-race.json) are regenerated by the converter, this file is not.
ALT is written from what each image shows. IN_SHORT is a DRAFT for Matt's
read: plain, third-person statements of what the post says, each one
supported by the post text.

Infographic (2026-10-09): fig-hydrate-sodium, the post's bib-salt rule of
thumb as bars: 500 mg, 750-1000 mg and 1500 mg of sodium per bottle, one
bottle an hour in hot conditions. Every number is the post's; the rule stays
in the text, word for word, above the figure.

Regenerate: python3 wordpress/post_sources/how_to_hydrate_so_you_dont_die_in_your_gravel_race.py
"""
from __future__ import annotations

import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
if str(HERE.parent) not in sys.path:
    sys.path.insert(0, str(HERE.parent))

from editorial_shell import Claim  # noqa: E402,F401
import wp_post  # noqa: E402
from wp_post import HtmlFigure  # noqa: E402

SLUG = "how-to-hydrate-so-you-dont-die-in-your-gravel-race"
SOURCE = wp_post.load(SLUG)
OUTPUT_PATH = wp_post.output_path(SLUG)

ALT = {
    "desert": "Cartoon Gravel God in a cowboy hat rides a bike across a cracked, dried-out desert lake bed toward low mountains, under a blazing sun.",
    "leg-twitch-1": "Animated: close-up video of a sunburnt, dust-flecked calf twitching with cramp above a purple patterned sock, as a rider sits on a curb; the camera then pans to his gravel bike lying on the pavement, a Garmin on the stem and a course-profile sticker on the top tube.",
    "seethisplaceinjanuary": "Cartoon Gravel God in a cowboy hat stands on a frozen, snow-covered fjord shore, sipping from a mug: \"Cold? It's June. You should see this place in January.\"",
    "sweat": "Cartoon Gravel God in a cowboy hat grins, drops of sweat on his face and legs, standing in a puddle of his own sweat.",
    "glood-plasma": "Diagram of a blood sample in a test tube: red blood cells settled at the bottom, a thin band of white blood cells and platelets, and yellow plasma on top, its contents listed as water, gases, ions, proteins, nutrients and wastes.",
    "inbloodbro": "Photo of a man in a dark sweater and white collar, looking at the camera, with a speech bubble: \"It's all in your blood, bro.\"",
    "startdehydrated": "Cartoon Gravel God in a cowboy hat grins: \"You're going to start your workout dehydrated? Awesome. It's going to go great!\"",
    "sodium": "Cartoon Gravel God in a cowboy hat eyes two wooden spoons heaped with fine salt and coarse salt crystals on dark slate.",
    "just-drink": "Cartoon Gravel God in a cowboy hat, sipping a drink at a bar counter: \"So what I'm getting from your 2,000 words is to just drink beer and you won't cramp.\"",
}

# Figures this module adds (excluded from the word-for-word text diff).
ADDED_IDS = {"fig-hydrate-sodium"}

# DRAFT for Matt: matter-of-fact statements of what the post says;
# section = 0-based h2 index (the intro counts with the first section).
IN_SHORT = (
    Claim("The post explains that the cardiovascular system both fuels muscles and sheds heat, prioritizing heat, and that sweating depends on blood plasma volume.",
          "#here-s-the-deal-humans-are-physically-useless-out-in-the-wil", "See §01", 0),
    Claim("It advises starting every ride fully hydrated, citing estimates that roughly 30% of athletes begin workouts dehydrated.",
          "#so-how-do-you-maintain-your-blood-plasma-volume-during-train", "See §03", 2),
    Claim("Water alone risks low blood sodium; the post suggests 500 to 1500 mg of sodium per hourly bottle, depending on how salty the bibs get.",
          "#fig-hydrate-sodium", "See the sodium chart · §06", 5),
    Claim("For quick recovery it recommends drinking at least one and a half times the fluid lost, with sodium, and warns hydration cannot offset poor pacing.",
          "#4-rehydration", "See §08", 7),
)

# ── fig-hydrate-sodium: the bib rule as bars ─────────────────
# (bibs, text as in the post, low mg, high mg); scale 0-1500 mg.
SODIUM = (
    ("Clean bibs", "500 mg", 500, 500),
    ("Kinda salty", "750-1000 mg", 750, 1000),
    ("Really salty", "1500 mg", 1500, 1500),
)


def _bars() -> str:
    rows = []
    for i, (label, text, low, high) in enumerate(SODIUM):
        rng = ""
        if high > low:
            rng = (f'<span class="hs-range" data-draw="grow-x" style="left:{low / 15:.2f}%;width:{(high - low) / 15:.2f}%;'
                   f'--draw-i:{i};--draw-at:400ms"></span>')
        rows.append(f'<li><span class="hs-label">{label}</span><span class="hs-track">'
                    f'<span class="hs-bar" data-draw="grow-x" style="width:{low / 15:.2f}%;--draw-i:{i}"></span>{rng}</span>'
                    f'<span class="hs-val">{text}</span></li>')
    axis = "".join(f'<span style="left:{v / 15:.2f}%">{v}</span>' for v in (0, 500, 1000, 1500))
    return (f'<ol class="hs-bars">{"".join(rows)}</ol>'
            f'<div class="hs-axis" aria-hidden="true"><span class="hs-axis-in">{axis}</span></div>')


SODIUM_FIGURE = HtmlFigure(
    id="fig-hydrate-sodium",
    kicker="The rule above, as bars",
    title="Sodium per bottle, by how salty your bibs look",
    html=_bars(),
    caption_html=("Milligrams of sodium per water bottle, one bottle every hour of riding in hot conditions, "
                  "as the post gives them. &ldquo;Kinda salty&rdquo; is a range: the outline runs from 750 to 1000 mg."),
    after="every hour you’re riding in hot conditions.</p>",
)

CSS = """
.hs-bars{list-style:none;margin:0;padding:0}
.hs-bars li{display:grid;grid-template-columns:130px minmax(0,1fr) 120px;align-items:center;gap:12px;padding:6px 0;margin:0}
.hs-label{font:700 15px var(--mono);color:var(--ink)}
.hs-val{font:400 14px var(--mono);color:var(--ink2)}
.hs-track{position:relative;height:18px}
.hs-bar{position:absolute;left:0;top:0;bottom:0;background:var(--teal)}
.hs-range{position:absolute;top:0;bottom:0;box-shadow:inset 0 0 0 2px var(--teal)}
.hs-axis{display:grid;grid-template-columns:130px minmax(0,1fr) 120px;gap:12px;margin-top:6px}
.hs-axis-in{grid-column:2;position:relative;height:18px;font:400 12px var(--mono);color:var(--ink3)}
.hs-axis-in span{position:absolute;top:0;transform:translateX(-50%)}
.hs-axis-in span:first-child{transform:none}
.hs-axis-in span:last-child{transform:translateX(-100%)}
@media (max-width:640px){
  .hs-bars li{grid-template-columns:minmax(0,1fr) auto;grid-template-areas:"label val" "track track";row-gap:4px}
  .hs-label{grid-area:label}.hs-val{grid-area:val}.hs-track{grid-area:track}
  .hs-axis{grid-template-columns:minmax(0,1fr)}.hs-axis-in{grid-column:1}
}
"""



def render() -> str:
    return wp_post.render_post(SOURCE, alt=ALT, in_short=IN_SHORT, figures=(SODIUM_FIGURE,), extra_css=CSS)


def main() -> None:
    wp_post.write(OUTPUT_PATH, render())


if __name__ == "__main__":
    main()
