"""Imported WordPress post: https://gravelgodcycling.com/how-to-do-workouts-the-right-way/

Generated by scripts/wp_post_import.py 2469; the body (how-to-do-workouts-the-right-way.body.html) and
metadata (how-to-do-workouts-the-right-way.json) are regenerated by the converter, this file is not.
ALT is written from what each image shows; IN_SHORT follows the "In short" rule in wp_post (neutral, third person).

Infographic (2026-10-09): fig-zones, the intensity line of every zone block in
"Executing the workout" as one table, copied word for word from the post
(including its ranges as written, e.g. Sweet Spot 92%-98% and Threshold
98%-105%). The dose column holds the only two per-workout doses the post
states (Zone 5: 15 to 25 minutes; Zone 6: 8 to 12 minutes). Nothing is derived.

Regenerate: python3 wordpress/post_sources/how_to_do_workouts_the_right_way.py
"""
from __future__ import annotations

import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
if str(HERE.parent) not in sys.path:
    sys.path.insert(0, str(HERE.parent))

from editorial_shell import Claim, DataTable, TableCell, TableColumn, TableRow  # noqa: E402
import wp_post  # noqa: E402

SLUG = "how-to-do-workouts-the-right-way"
SOURCE = wp_post.load(SLUG)
OUTPUT_PATH = wp_post.output_path(SLUG)

_TP = "TrainingPeaks workout window"
ALT = {
    "faster-dammit": "Black-and-white photo of a dirt road along a vast crop field under a cloudy sky: a rider in black leads, and cartoon Gravel God in a cowboy hat pedals a few lengths behind.",
    "recovery-makes-you-fast": "Chalkboard sketch of fitness over time: from the starting-fitness line, the curve dips during \"Train\", bottoms out and climbs during \"Rest\", and ends above the dashed starting line at \"Ending fitness\".",
    "lagging-outcome": "A 2022 year calendar in dark mode with handwritten notes: \"Training a lot here\" points to February 6, \"When you think you'll get much faster\" to March 1, and \"When you do\" to June 6.",
    "progress-is-not-linear": "Chalkboard sketch: a jagged line labelled \"Actual progress\" zigzags up and down around a straight dashed arrow labelled \"Expected progress\", both rising to the right.",
    "search-for-answers": "A calendar fortnight, June 20 to July 2, with every day except Sundays filled with the same entry: the Strava logo and \"KOM Attempt\".",
    "overtraining": "A young man at a bar, arm out, says: \"So I trained 1400 hours last year, lost my job, wife, and couldn't get out of bed for three months!\" Cartoon Gravel God, cigar in his mouth, listens at the right.",
    "recovery-makes-you-fast-fitness-is-a-lagging-outcome-dont-search-for-answers-overtraining-doesnt-make-you-special-1": "A pale bedroom seen from behind cartoon Gravel God's cowboy hat, surrounded by floating items: a yellow road bike, a calendar with crossed-off days, a TrainingPeaks workout window, a stack of pancakes with syrup, a water bottle and a \"Choco Bar\".",
    "what-is-a-watt": "Cartoon Gravel God, seen from behind, rides a dirt track through tall grass and hillside farmland and asks: \"Watts? What the hell is a watt?\"",
    "screen-shot-2022-02-08-at-10-25-42-am": f"{_TP}, Saturday, February 19, 2022: \"Day Off\", no time, distance or TSS. Description: \"Don't touch your bike. Sleep more. Get a nap if you can. Get off your screens. Relax harder.\"",
    "screen-shot-2022-02-08-at-10-29-24-am": f"{_TP}, Saturday, February 19, 2022: \"Cafe Ride\", 1:00:00, 30 TSS, IF 0.55. Description: \"Z1 - EASY spin, light on the pedals.\" Pre-activity comment: 30 TSS is a recovery ride; the biggest mistake athletes make is making recovery days too hard, and the ride should feel stupidly easy.",
    "screen-shot-2022-02-08-at-10-31-59-am": f"{_TP}, Saturday, February 19, 2022: \"Base - 240 min\", 4:00:00, 174 TSS, IF 0.66. Description: warm up from Z1 to Z2 keeping cadence over 85 rpm, then steady Z2 for about 240 minutes using the entire zone, not just the top of it, cadence 85-95, then cool down.",
    "screen-shot-2022-02-09-at-3-14-45-pm": f"{_TP}, Friday, February 18, 2022: \"The Artist 1\", 1:30:00, 89 TSS, IF 0.77. Description: Z1-Z2 warm-up in the little ring at 100+ rpm, then 4x12' Z3 with varied technique (100+ rpm; alternating 50-60 and 80-100 rpm; 1.5' seated / 30\" standing), full recovery between.",
    "screen-shot-2022-02-09-at-3-13-47-pm": f"{_TP}, Thursday, February 17, 2022: \"Not Threshold - Stein\", 1:12:00, 88 TSS, IF 0.86. Description: a stepped warm-up from Z1 to Z4, 5 minutes easy at high cadence, 1x30min SS (95%) FTP, 10m Z2, 5x20sec all out with 40 sec Z1, cool down.",
    "screen-shot-2022-02-09-at-3-12-58-pm": f"{_TP}, Wednesday, February 16, 2022: \"Old SKOOL 1\", 1:30:00, 116 TSS, IF 0.88. Description: 10-15min warm-up Z1/Z2, 3x15min Z4 with 5 min Z1 between, finish with Z2. Pre-activity comment: \"Make sure you're eating a higher % of carbs beforehand.\"",
    "screen-shot-2022-02-09-at-3-12-06-pm": f"{_TP}, Tuesday, February 15, 2022: \"The Dæhlie - 2 (3mx4)\", 1:30:00, 111 TSS, IF 0.86. Description: 10m Z1-2, a 4-step ramp, 2 sets of 4x3m VO2max with 3 min between reps and 5 min between sets. Pre-activity comment: goal is the best average overall, no fireworks early.",
    "screen-shot-2022-02-09-at-3-37-17-pm": f"{_TP}, Saturday, February 19, 2022: \"30/30's\", 1:14:00, 75 TSS, IF 0.78. Description: 15m progressive warm-up, 3 sets of 5x30sec ON (all out) / 30 sec easy with 5m between sets, finishing with 5x 10s standing sprints. Pre-activity comment begins: keep the cadence high on the 30 sec ON.",
    "screen-shot-2022-02-09-at-3-42-41-pm": f"{_TP}, Monday, February 14, 2022: \"Schneider 0\", 1:22:00, 113 TSS, IF 0.91. Description: 15-20m warm-up Z1-Z2, a ramp of 1 min steps from Z2 to Z4 and 30 sec at Z5, 1x10min high-cadence Z3 at 100-120 rpm, then small-geared sprints from 10 mph or less.",
    "screen-shot-2022-02-09-at-3-46-46-pm": f"{_TP}, Thursday, February 10, 2022: \"Kjøkkenvask - Svake Knær\", 4:00:00, 252 TSS, IF 0.80. Description: 60m L1/L2 warm-up, 3x5min Z3 at cadence over 100, 30min Z2, 1x8min Z4, 30min Z2, 8x3min Z5 with 2min Z1, 30min Z2, 1x8 min Z4, cool down.",
    "iv": "Cartoon Gravel God in a cowboy hat, in profile, gazes up at an IV drip bag hanging in a blurred hospital room.",
    "time-to-party-1": "A packed nightclub under a disco ball: confetti falls, sparkler fountains burn beside the stage, and cartoon Gravel God grins in the crowd with a cigar.",
}

# The "In short" rule (wp_post docstring); section = 0-based h2 index.
IN_SHORT = (
    Claim("The post says training creates the potential for adaptation and that recovery, above all sleep, is when the body rebuilds slightly fitter.",
          "#recovery-makes-you-fast", "See Recovery makes you fast · §01", 0),
    Claim("The post treats a missed workout as the athlete&rsquo;s responsibility and recommends planning each week ahead against what could derail training.",
          "#if-you-miss-it-it-s-your-fault", "See If you miss it · §02", 1),
    Claim("For every zone, from rest day to sprint, it gives an intensity range and the usual ways athletes get the workout wrong.",
          "#fig-zones", "See the zones · §03", 2),
    Claim("For long, hard rides it recommends at least 50 (probably 70) grams of carbohydrate an hour, a water bottle an hour and 500 mg sodium.",
          "#long-hard-workouts-in-other-words-kitchen-sink-workouts", "See Kitchen Sink workouts · §03", 2),
)

# ── fig-zones: the zone intensities, word for word ───────────
# (zone, % FTP text, FTP sort key, % FTHR text, dose text). Text exactly as the post.
ZONES = (
    ("Zone 0 &ndash; Rest day", "Literally none.", 0, "", ""),
    ("Zone 1 &ndash; Recovery", "Less than 55%", 1, "&lt;68%", ""),
    ("Zone 2 &ndash; Endurance", "56-75%", 56, "69-83%", ""),
    ("Zone 3 &ndash; Tempo", "76-90%", 76, "84-94%", ""),
    ("Zone 3/4 &ndash; Sweet Spot", "92%-98%", 92, "95-100%", ""),
    ("Zone 4 &ndash; Threshold", "98%-105%", 98, "98-105%", ""),
    ("Zone 5 &ndash; VO2 max", "106%-120%", 106, "&gt; 106%", "15 to 25 minutes"),
    ("Zone 6 &ndash; Anaerobic capacity/FRC/W&rsquo;", "121%-151%", 121, "&gt;106%", "8 to 12 minutes"),
    ("Zone 7 &ndash; Sprint/pMax", "Just send it.", 200, "", ""),
)

HR_NOTES = {"Zone 6 &ndash; Anaerobic capacity/FRC/W&rsquo;": "just go hard because of heart rate lag"}

ZONES_TABLE = DataTable(
    id="fig-zones",
    kicker="The zones below, in one place",
    title="Training zones: intensity and dose",
    intro_html="Each zone&rsquo;s intensity line from this section, as the post writes it.",
    footnote_html=("FTP = functional threshold power; FTHR = functional threshold heart rate. "
                   "Dose = the time in the zone the post gives per workout (&ldquo;the effective dose of VO2 max work&rdquo;; "
                   "&ldquo;in Zone 6, 8 to 12 minutes is PLENTY&rdquo;); &mdash; = not stated. "
                   "Long/Hard &lsquo;Kitchen Sink&rsquo; workouts: usually all zones."),
    columns=(
        TableColumn("Zone", card="title", sortable=False),
        TableColumn("% of FTP", kind="num", card="fact"),
        TableColumn("% of FTHR", card="fact", sortable=False),
        TableColumn("Dose per workout", card="row", sortable=False),
    ),
    rows=tuple(
        TableRow(cells=(TableCell(z), TableCell(ftp, sort=key), TableCell(hr, note_html=HR_NOTES.get(z, "")), TableCell(dose)))
        for z, ftp, key, hr, dose in ZONES
    ),
    after="share a list of the most common ways athletes screw up workout execution by zone type:</p>",
)


def render() -> str:
    return wp_post.render_post(SOURCE, alt=ALT, in_short=IN_SHORT, figures=(ZONES_TABLE,))


def main() -> None:
    wp_post.write(OUTPUT_PATH, render())


if __name__ == "__main__":
    main()
