"""Imported WordPress post: https://gravelgodcycling.com/how-to-not-fk-up-your-holiday-training/

Generated by scripts/wp_post_import.py 2942; the body and metadata
(how-to-not-fk-up-your-holiday-training.body.html / .json) are regenerated by
the converter, this file is not. ALT is written from what each image shows;
IN_SHORT follows the "In short" rule in wp_post (neutral, third person).

The live meta description is kept (it matches the post). No infographic: the
post's few numbers (700+ pro hours, 2-6 lb a year) don't form a comparison a
chart would clarify.

Regenerate: python3 wordpress/post_sources/how_to_not_fk_up_your_holiday_training.py
"""
from __future__ import annotations

import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
if str(HERE.parent) not in sys.path:
    sys.path.insert(0, str(HERE.parent))

from editorial_shell import Claim  # noqa: E402
import wp_post  # noqa: E402

SLUG = "how-to-not-fk-up-your-holiday-training"
SOURCE = wp_post.load(SLUG)
OUTPUT_PATH = wp_post.output_path(SLUG)

ALT = {
    "untitled-design-5": "Cartoon Gravel God in a cowboy hat and a Santa suit lounges on a leather sofa in a living room lit with Christmas lights, a decorated tree and wrapped presents beside him.",
    "untitled-design-6": "Cartoon Gravel God in a cowboy hat peers over a holiday table at a bottle labelled \"Egg Nog\", a glass of eggnog with whipped cream and a striped straw, and a green-frosted cupcake.",
    "oysters-happiness": "Two arrows painted on asphalt split left and right around the crown of a cowboy hat: the left labelled \"Oysters, happiness.\", the right \"No Oysters, self-respect.\"",
    "oysters-happiness-1": "Cartoon Gravel God in a cowboy hat rides a bike along a snowy path through a park at dusk, street lamps and Christmas lights glowing behind him.",
    "oysters-happiness-2": "An older, white-bearded man in a red sweater talks into the ear of cartoon Gravel God in a cowboy hat, who says: \"Fishing stories AND Jeffery Epstein conspiracy theories? It really IS Christmas!\"",
    "oysters-happiness-3": "A desert highway: cartoon Gravel God stands in the middle under \"Best way\", flanked by two red devil versions of himself labelled \"Lazy\" (\"No, I am!!\") and \"Nut\" (\"I'm more fun.\").",
}

# The "In short" rule (wp_post docstring); section = 0-based h2 index.
IN_SHORT = (
    Claim("The post argues that both extremes over the holidays, not training at all and training obsessively, are mistakes.",
          "#so-how-do-you-emerge-on-january-first-not-reeking-of-baileys", "See §01", 0),
    Claim("It says amateurs cannot take months off like professionals, who train 700+ hours a year and have far more time to regain fitness.",
          "#but-i-know-a-pro-that-takes-two-months-off-every-year", "See §02", 1),
    Claim("It recommends two short, specific bike workouts a week, with other aerobic activity filling the gaps.",
          "#but-a-little-specificity-goes-a-long-way", "See §06", 5),
    Claim("On food, it suggests eating like a grandparent: try everything, rarely finish the plate, skip seconds and snacks.",
          "#you-are-not-a-food-dumpster", "See §07", 6),
)


def render() -> str:
    return wp_post.render_post(SOURCE, alt=ALT, in_short=IN_SHORT)


def main() -> None:
    wp_post.write(OUTPUT_PATH, render())


if __name__ == "__main__":
    main()
