"""Imported WordPress post: https://gravelgodcycling.com/how-to-develop-your-athletic-sht-detector/

Generated by scripts/wp_post_import.py 2904; the body and metadata
(how-to-develop-your-athletic-sht-detector.body.html / .json) are regenerated by
the converter, this file is not. ALT is written from what each image shows
(the globe GIF's frames checked; the tweets transcribed); IN_SHORT follows the
"In short" rule in wp_post (neutral, third person).

DESCRIPTION replaces the live meta description ("develop an evidence-based
detector for the training myths, supplement scams, and bad coaching"): the post
says its compass does not judge a claim's validity, and calls the coach it
examines "probably right"; it judges applicability by context.

Infographic (2026-10-09): fig-compass, the post's three worked examples run
through its two anchors (Impact, Life), as a table. Every cell quotes the post
word for word; nothing is summarised in new words beyond the row names.

Regenerate: python3 wordpress/post_sources/how_to_develop_your_athletic_sht_detector.py
"""
from __future__ import annotations

import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
if str(HERE.parent) not in sys.path:
    sys.path.insert(0, str(HERE.parent))

from editorial_shell import Claim, DataTable, TableCell, TableColumn, TableRow  # noqa: E402
import wp_post  # noqa: E402

SLUG = "how-to-develop-your-athletic-sht-detector"
SOURCE = wp_post.load(SLUG)
OUTPUT_PATH = wp_post.output_path(SLUG)

_P = "my-thoughts-if-you-can-afford-a-bike-you-can-afford-a-portable-lactate-teste"
ALT = {
    f"{_P}-3": "Cartoon Gravel God in a cowboy hat, seen from behind, sits at a desk watching a video in which a cartoon cyclist says, \"I only train in Zone 7 now, fueled entirely by meatloaf.\"",
    _P: "Animated: a globe spins on its stand against a starfield, its axis labelled \"Biopsychosocial\" and \"Impact\", with cartoon Gravel God in a cowboy hat peering up from beside it.",
    f"{_P}-2": "Tweet from Alan Couzens (@Alan_Couzens): \"My thoughts... If you can afford a bike, you can afford a portable lactate tester.\"",
    f"{_P}-1": "Tweet thread from Alan Couzens (@Alan_Couzens): \"7 unpopular truths for the serious endurance athlete\", including showing up every day for years, living differently from your peers, conflict at work and in relationships, \"7-10 hours a week is *exercise* ... not competitive training\", and triathlon as a lifestyle sport.",
    f"{_P}-2-2": "A person holds up a phone showing a glucose monitor app reading 108 mg/dL, with a daily trace and a 90-day overview, next to a round white sensor patch on the back of their upper arm.",
    "untitled-design": "Cartoon Gravel God in a cowboy hat, hand on chin, stands in thought in front of a white brick wall covered in faint charts, formulas and diagrams.",
}

DESCRIPTION = ("How to judge a training method or product by context: how much it can improve performance, "
               "and whether it fits the rest of an athlete's life.")

# The "In short" rule (wp_post docstring); section = 0-based h2 index.
IN_SHORT = (
    Claim("The post argues that the usefulness of any training method or product is always contextual, whatever its intrinsic efficacy.",
          "#the-utility-of-any-training-methodology-or-product-to-improv", "See the argument · §01", 0),
    Claim("It judges each claim against two anchors: impact, meaning how much it can improve performance, and the athlete&rsquo;s biological, psychological and social life.",
          "#impact", "See the anchors · §01", 0),
    Claim("On lactate testing, the post suggests a threshold test plus training a little easier than the calculated zone 2 may reach roughly the same outcome.",
          "#example-endurance-influencers", "See the example · §02", 1),
    Claim("On glucose monitors, it notes that about 90g of carbohydrate per hour, roughly three gels, is the upper limit most people absorb.",
          "#example-glucose-monitor", "See the example · §03", 2),
)

# ── fig-compass: the three examples through the two anchors ──
# (example, Impact quote, Life quote, verdict quote): all word for word from the post.
COMPASS = (
    ("Frequent lactate testing",
     "It could be important",
     "If you do it in a lab, that’s expensive in time and money.",
     "Wouldn’t that be roughly the same outcome without spending hundreds of dollars and lots of time to do the same thing?"),
    ("Reordering your Life to train optimally",
     "Alan’s claim is inarguably Impactful.",
     "Are you willing to deprioritize everything in your Life so you’re faster?",
     "For most people, the answer is no."),
    ("A continuous blood glucose monitor",
     "that would probably dramatically improve your performance, no question.",
     "Do you even have the time or desire to do all this?",
     "It looks like the glucose monitor just got removed from your shopping cart."),
)


def _q(text: str) -> TableCell:
    return TableCell(f"&ldquo;{text}&rdquo;")


COMPASS_TABLE = DataTable(
    id="fig-compass",
    kicker="The three examples above, side by side",
    title="Two anchors, three claims",
    intro_html="Each example the post works through, checked against its two anchor points.",
    footnote_html="Every quote is from the post. Impact: how much it can improve performance. Life: the biopsychosocial anchor.",
    columns=(
        TableColumn("Claim", card="title", sortable=False),
        TableColumn("Impact", card="row", sortable=False),
        TableColumn("Life", card="row", sortable=False),
        TableColumn("The post’s answer", card="row", sortable=False),
    ),
    rows=tuple(TableRow(cells=(TableCell(name), _q(a), _q(b), _q(c))) for name, a, b, c in COMPASS),
    after="It looks like the glucose monitor just got removed from your shopping cart.</p>",
)

# Nothing in this table sorts, so the shell's "Click a column to sort" hint is hidden.
CSS = "#fig-compass .gg-sort-hint{display:none}"


def render() -> str:
    return wp_post.render_post(SOURCE, alt=ALT, in_short=IN_SHORT, figures=(COMPASS_TABLE,),
                               extra_css=CSS, description=DESCRIPTION)


def main() -> None:
    wp_post.write(OUTPUT_PATH, render())


if __name__ == "__main__":
    main()
