"""Imported WordPress post: https://gravelgodcycling.com/how-to-achieve-your-goals-and-stop-ruining-your-dreams/

Generated by scripts/wp_post_import.py 2298; the body (how-to-achieve-your-goals-and-stop-ruining-your-dreams.body.html) and
metadata (how-to-achieve-your-goals-and-stop-ruining-your-dreams.json) are regenerated by the converter, this file is not.
Hand-edit ALT (one entry per image, written from what the image shows),
IN_SHORT (drafts restate the post's own words) and any infographics.

IN_SHORT (2026-10-09): matter-of-fact restatements for Matt's read. The post has
no headings, so each claim links to the figure that follows its proof.

Infographic (2026-10-09): fig-weight-chart, the weigh-in chart in the GIF
"All I had for breakfast was a big gust of wind" redrawn as an SVG line that
draws in. Points digitized from the GIF's last frame
(~/specs/gg-wp-posts-2026-10-09/pilot/tools/digitize_weight.py, output
weight_points.json there): 147 visible markers, plus the 169.1 lb end point the
chart's own tooltip labels (its marker sits under the tooltip). A few markers
hidden by the cartoon, the speech bubble and the tooltips are left out. The GIF
stays in place above the redraw.
Corrected 2026-10-09 (Matt approved): CORRECTIONS below changes "early March"
to "late March" (the chart labels 169.1 lb on Mon, 3/26/2018); the entry names
its evidence. The page notes the correction at the end. Left unchanged after
review: "18 pounds" (twice).

Regenerate: python3 wordpress/post_sources/how_to_achieve_your_goals_and_stop_ruining_your_dreams.py
"""
from __future__ import annotations

import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
if str(HERE.parent) not in sys.path:
    sys.path.insert(0, str(HERE.parent))

from editorial_shell import Claim  # noqa: E402
import wp_post  # noqa: E402
from wp_post import HtmlFigure  # noqa: E402

SLUG = "how-to-achieve-your-goals-and-stop-ruining-your-dreams"
SOURCE = wp_post.load(SLUG)
OUTPUT_PATH = wp_post.output_path(SLUG)

ALT = {
    "dream-big": "Cartoon Gravel God in his cowboy hat stands astride a road bike on an empty two-lane road under a cloudy sky; \"DREAM BIG\" is painted in large white letters on the asphalt in front of him.",
    "so-i-guess-my-goals-are-to-be-fast-and-win-everything": "A smiling woman on a desktop computer screen says: \"So I guess my goals are to be fast and win everything!\" Cartoon Gravel God, only his cowboy hat visible in the foreground, answers: \"Great. That's really helpful.\"",
    "process": "Cartoon Gravel God in a cowboy hat shouts through a megaphone above large bold text: \"It's the process people. PROCESS PROCESS PROCESS!\"",
    "pileomillers": "Friends sit around a campfire at night on a hillside above city lights; cartoon Gravel God stands at the left with a can raised to his mouth, beside a pile of Miller Lite cans and wedges of cheese.",
    "no-idea": "Cartoon Gravel God shrugs, palms up, while three tomatoes fly at him, saying: \"I have no idea.\"",
    "beyond-help": "A doctor in a white coat sits facing cartoon Gravel God, seen from behind in his cowboy hat, and says: \"I think you're beyond the help of not just me, but the entire field.\"",
    "all-i-had-for-breakfast-was-a-big-gust-of-wind": "Animated: a line chart titled \"Weight, 11/25/2017 - 3/26/2018\", near-daily weigh-ins falling from a labelled 186.5 lbs on Mon, 11/27/2017 to a labelled 169.1 lbs on Mon, 3/26/2018. In the lower left, cartoon Gravel God tosses a bagel into a garbage can: \"I shared my breakfast with a garbage can.\"",
    "so-i-guess-my-goals-are-to-be-fast-and-win-everything-1": "A chalkboard beside a grinning cartoon Gravel God in a cowboy hat reads: \"Goals: upgrade to Cat 1. Factors: training, sleep, body comp, race tactics, mental game, etc. Process goal: improve body comp. Habit: weigh myself every morning.\"",
}

# Matter-of-fact restatements; section = 0-based h2 index (no headings: 0).
IN_SHORT = (
    Claim("A written goal only sets a direction. The post argues the decisive step is knowing one&rsquo;s strengths and weaknesses against the race&rsquo;s demands.",
          "#fig-process", "See the argument", 0),
    Claim("Extending James Clear&rsquo;s <em>Atomic Habits</em>, the post holds that identity includes what a person wants, and some wants undermine the habits a goal requires.",
          "#fig-pileomillers", "See the example", 0),
    Claim("The author&rsquo;s worked example: weighing in every morning, which took him from 186.5 to 169.1 pounds and contributed to his upgrade to Cat 1.",
          "#fig-weight-chart", "See the weigh-ins", 0),
)

# ── fig-weight-chart: the GIF's weigh-in chart, redrawn ──────
# "day:lbs", day = days after 11/25/2017 (the chart's first date), read off the
# GIF's last frame; the final 121.4:169.1 is the chart's own tooltip value.
WEIGHINS = (
    "2.2:186.5 5.4:184.2 5.6:182.4 6.5:184.6 7.9:181.3 8.8:182.9 9.5:183.3 10.5:184.1 11.4:184 12.4:182.7 "
    "13.4:181.1 14.6:178.5 14.9:181.1 15.5:181.2 15.9:182 16.5:182.3 17.5:183.2 18.5:181.2 19.5:182.5 "
    "20.5:180.3 21.6:179.5 21.9:179.9 22.6:179.8 22.8:178.5 23.4:181.3 24.5:180.4 25.5:178.6 25.8:178 "
    "26.5:179.1 27.5:179.7 27.7:180 28.3:178.2 30.6:178.2 31.6:177.4 31.8:176.9 32.4:176.5 32.8:177.9 "
    "33.5:177.3 33.8:177.6 34.4:178.8 34.9:176.5 35.4:177.9 37.6:180.4 37.8:177 38.5:178.3 39.5:177.9 "
    "39.8:177.1 40.4:176.8 40.9:176.7 41.4:177.1 42.5:178.5 42.8:175.9 43.5:178 43.8:175.7 44.5:177.7 "
    "45.4:176.9 45.8:177.3 46.4:176.6 47.4:176.2 47.8:175.6 48.5:175.9 49.5:176.5 49.9:174.2 50.5:174.4 "
    "50.8:173 51.5:174.4 52.1:175.9 53.5:175.5 54.5:176.6 55.5:174.5 56.5:173.8 57.5:175.6 57.8:175 "
    "58.4:174.2 59.4:173.8 60.4:172.8 61.1:174.8 61.4:172.6 62.4:174.6 63.7:173.5 64.4:173.2 65.4:172.6 "
    "65.8:173.6 66.1:173.9 67.5:173.7 68.4:172.2 69.4:171.3 70.4:172.1 70.7:168.9 71.5:171.5 72.4:172.4 "
    "73.4:172.6 73.8:171.7 74.4:172.3 75.4:171.7 75.8:170.6 76.4:171.1 77.4:170.9 77.6:171.8 78.3:171.6 "
    "79.4:173.1 80.4:171.9 81.4:173 82.4:171.2 83.4:170.9 84.4:171.8 84.8:169.7 85.4:173.3 85.8:171.8 "
    "86.4:173.3 87.3:173.3 88.4:172.7 89.4:172.2 89.7:168.7 90.4:172.5 91.4:172.3 91.8:173 92.4:172.6 "
    "92.8:172.6 93.4:174.1 94.4:173.7 95.4:172.5 96.4:171.5 97.3:171.8 98.4:172.8 98.8:170.9 99.4:171.8 "
    "99.8:171.5 100.4:172.1 101.4:174.3 102.4:172.8 103.4:172.2 104.3:171 106.3:170.8 106.7:171.6 "
    "107.3:171.6 108.3:173 109.3:171.9 110.3:170.9 112.3:171.9 113.4:174 114.3:173.7 115.3:172 "
    "116.3:171.8 117.3:171.8 118.3:171.2 119.6:167.3 121:168.4 121.4:169.1"
)
_INK, _INK2, _TEAL, _RULE, _PAPER = "#2a211b", "#59473c", "#178079", "#c9bcae", "#fbf7f1"
# (day, label) month ticks: Dec 1, Jan 1, Feb 1, Mar 1.
MONTHS = ((6, "Dec 1"), (37, "Jan 1"), (68, "Feb 1"), (96, "Mar 1"))


def _weight_svg(variant: str) -> str:
    """One chart, two layouts: 'wide' (column, 13 px type) and 'phone'
    (narrow viewBox so the type stays ~11 px at 328 px)."""
    pts = [tuple(float(v) for v in p.split(":")) for p in WEIGHINS.split()]
    if variant == "wide":
        VW, VH, L, R, T, B, fs = 680, 300, 52, 664, 18, 262, 13
    else:
        VW, VH, L, R, T, B, fs = 360, 260, 42, 348, 16, 222, 13
    lo, hi = 166, 188
    def X(d): return L + (R - L) * d / 122
    def Y(v): return B - (B - T) * (v - lo) / (hi - lo)
    tid = f"weight-{variant}"
    m = [f'<svg class="wc-{variant}" viewBox="0 0 {VW} {VH}" role="img" aria-labelledby="{tid}-t {tid}-d" '
         f'xmlns="http://www.w3.org/2000/svg">',
         f'<title id="{tid}-t">Morning weigh-ins, November 2017 to March 2018</title>',
         f'<desc id="{tid}-d">Near-daily weigh-ins: 186.5 lb on November 27, 2017, drifting down with '
         f'day-to-day swings of 1 to 3 lb, to 169.1 lb on March 26, 2018.</desc>']
    for v in (170, 175, 180, 185):
        m.append(f'<line x1="{L}" x2="{R}" y1="{Y(v):.1f}" y2="{Y(v):.1f}" stroke="{_RULE}" stroke-width="1"/>'
                 f'<text x="{L - 7}" y="{Y(v) + 4.5:.1f}" text-anchor="end" font-size="{fs}" fill="{_INK2}">{v}</text>')
    for d, label in MONTHS:
        m.append(f'<line x1="{X(d):.1f}" x2="{X(d):.1f}" y1="{B}" y2="{B + 5}" stroke="{_INK}" stroke-width="1.2"/>'
                 f'<text x="{X(d):.1f}" y="{B + 19}" text-anchor="middle" font-size="{fs}" fill="{_INK2}">{label}</text>')
    m.append(f'<path d="M{L},{T}V{B}H{R}" fill="none" stroke="{_INK}" stroke-width="1.4"/>')
    line = " ".join(f"{X(d):.1f},{Y(v):.1f}" for d, v in pts)
    m.append(f'<polyline points="{line}" fill="none" stroke="{_TEAL}" stroke-width="{2 if variant == "wide" else 1.6}" '
             f'stroke-linejoin="round" data-draw="wipe" style="--draw-dur:1.6s"/>')
    (d0, v0), (d1, v1) = pts[0], pts[-1]
    for d, v, label, anchor, dx, dy in ((d0, v0, "186.5 lb · Nov 27", "start", 9, 4),
                                        (d1, v1, "169.1 lb · Mar 26", "end", -9, 20)):
        m.append(f'<circle cx="{X(d):.1f}" cy="{Y(v):.1f}" r="4" fill="{_PAPER}" stroke="{_INK}" stroke-width="2" '
                 f'data-draw="fade" style="--draw-at:{0 if d == d0 else 1500}ms"/>'
                 f'<text x="{X(d) + dx:.1f}" y="{Y(v) + dy:.1f}" text-anchor="{anchor}" font-size="{fs + 1}" '
                 f'font-weight="700" fill="{_INK}" paint-order="stroke" stroke="{_PAPER}" stroke-width="4" '
                 f'data-draw="fade" style="--draw-at:{0 if d == d0 else 1500}ms">{label}</text>')
    m.append(f'<text transform="translate(12 {(T + B) / 2}) rotate(-90)" text-anchor="middle" '
             f'font-size="{fs}" fill="{_INK2}">lb</text>')
    m.append("</svg>")
    return "".join(m)


WEIGHT_FIGURE = HtmlFigure(
    id="fig-weight-chart",
    kicker="The chart above, redrawn",
    title="Every morning on the scale",
    html=_weight_svg("wide") + _weight_svg("phone"),
    caption_html=("Weigh-ins read off the chart in the GIF above (its range: 11/25/2017 &ndash; 3/26/2018); "
                  "first and last values as the chart labels them. A few points hidden behind the cartoon "
                  "and the chart&rsquo;s labels are left out."),
    marker="weight-chart",
)

CSS = """
.gg-htmlfig .wc-wide,.gg-htmlfig .wc-phone{display:block;width:100%;height:auto}
.gg-htmlfig .wc-phone{display:none}
@media (max-width:640px){.gg-htmlfig .wc-wide{display:none}.gg-htmlfig .wc-phone{display:block}}
"""


# Figures corrected to match the post's own evidence (Matt, 2026-10-09:
# "Yeah go ahead and fix"). wp_post applies each to the body (old text must
# occur exactly once) and the word-for-word tests apply them to the snapshot.
CORRECTIONS = (
    wp_post.Correction(
        "169.1 pounds by early March",
        "169.1 pounds by late March",
        "the chart labels 169.1 lb on Mon, 3/26/2018"),
)


def render() -> str:
    return wp_post.render_post(SOURCE, corrections=CORRECTIONS, alt=ALT, in_short=IN_SHORT, figures=(WEIGHT_FIGURE,),
                               after_image={"weight-chart": "all-i-had-for-breakfast-was-a-big-gust-of-wind"},
                               extra_css=CSS)


def main() -> None:
    wp_post.write(OUTPUT_PATH, render())


if __name__ == "__main__":
    main()
