"""Imported WordPress post: https://gravelgodcycling.com/how-to-manage-dopamine-to-be-a-better-cyclist/

Generated by scripts/wp_post_import.py 2161; the body and metadata
(how-to-manage-dopamine-to-be-a-better-cyclist.body.html / .json) are regenerated
by the converter, this file is not. ALT is written from what each image shows;
IN_SHORT is a DRAFT for Matt's read (each claim restates the post's own words).

Infographics (2026-10-09, data unchanged, cited to the post):
- fig-phasic: the post's tonic/phasic chart (Phasic.png) redrawn as two SVG panels.
  Traces digitized column by column from the original at 0.05 s steps
  (~/specs/gg-wp-posts-2026-10-09/pilot/tools/digitize_phasic.py). Panel B after
  5 s is panel A's trace: where both are visible they match (mean difference
  0.12 units), and the original's flag and cowboy hide parts of B. The original
  image stays one click away under the chart.
- fig-dopamine-multiples: the post's list of dopamine multiples as bars; the list
  itself stays in the text, word for word.

Regenerate: python3 wordpress/post_sources/how_to_manage_dopamine_to_be_a_better_cyclist.py
"""
from __future__ import annotations

import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
if str(HERE.parent) not in sys.path:
    sys.path.insert(0, str(HERE.parent))

from editorial_shell import Claim  # noqa: E402
import wp_post  # noqa: E402
from wp_post import HtmlFigure  # noqa: E402

SLUG = "how-to-manage-dopamine-to-be-a-better-cyclist"
SOURCE = wp_post.load(SLUG)
OUTPUT_PATH = wp_post.output_path(SLUG)

ALT = {
    "phasic": "The original chart: two panels of the change in dopamine, Δ[DA], over 20 seconds. A, Tonic: a noisy trace hovering around a dashed baseline, a wedge of cheese drawn beneath it. B, Phasic: a spike to about 6 just after one second, then the same tonic noise, with a pile of white powder, a Norwegian flag and a cartoon Gravel God, hand at his nose, drawn over it.",
    "never-coming-out-1": "Cartoon Gravel God in a cowboy hat stands at the mouth of a dark rock tunnel beside a beer and a wedge of cheese, saying: \"I'm never coming out.\"",
    "say-no-to-drugs": "Pills arranged in a heart on a wooden table beside a \"Say NO to Drugs\" note, a syringe and a bag of white powder; cartoon Gravel God strokes his beard: \"It all makes so much sense now!\"",
    "feels-great": "Cartoon Gravel God, seen from behind, rides a dirt road through sagebrush desert under a blue sky, saying: \"This feels great, I want to be here, I love this. (lolz)\"",
    "dopamine-layering": "Cartoon Gravel God shrugs in a dark gym above a row of coffee, a croissant, a phone, a speaker and a beer: \"How can I train without coffee, snacks, my phone, music, and a beer at the end?\"",
    "hangover-future-me": "A crowd dances under falling confetti, drinks raised; cartoon Gravel God grins among them: \"Hangover? Sounds like a problem for future me.\"",
    "cold-shower": "Cartoon Gravel God, grimacing, stands under an outdoor shower: \"I hate that this works.\"",
    "dope": "A chalkboard reading \"Dopamine\" with its formula, C8H11NO2, and its structural diagram; a grinning cartoon Gravel God in a cowboy hat stands at the right.",
}

# DRAFT for Matt: each claim restates the post; section = 0-based h2 index.
IN_SHORT = (
    Claim("Whenever something raises dopamine above your tonic level, there is a corresponding drop below the baseline. What comes up must come down.",
          "#fig-phasic", "See the chart · Intro", 0),
    Claim("Tell yourself you like the effort while it&rsquo;s hard and you rewire yourself to release dopamine during exertion, so the effort feels easier.",
          "#1-reward-the-friction-of-effort", "See §01", 0),
    Claim("Dopamine layering (pre-workout coffee, music, your phone, a tasty reward) shifts the pleasure from the activity to the things layered on it.",
          "#2-avoid-dopamine-layering", "See §02", 1),
    Claim("Abstain from dopamine-spiking behaviors and substances for a month every year, and your baseline creeps back up.",
          "#3-avoid-dopamine-spikes", "See §03", 2),
)

# ── fig-phasic: tonic vs phasic, redrawn ─────────────────────
# Δ[DA] every 0.05 s from t = 0 to 20 s (401 values per panel).
TONIC = (
    "0.83 0.76 0.56 0.43 0.32 0.46 0.56 0.7 0.69 0.67 0.68 0.67 0.63 0.76 0.92 1.12 1.32 1.32 1.21 1.24 "
    "1.33 1.52 1.58 1.62 1.56 1.55 1.61 1.63 1.64 1.62 1.66 1.74 1.72 1.74 1.8 1.68 1.63 1.54 1.54 1.56 "
    "1.56 1.56 1.68 1.68 1.63 1.65 1.69 1.55 1.41 1.3 1.27 1.24 1.2 1.2 1.14 0.96 0.88 0.78 0.82 1.07 "
    "1.19 1.24 1.15 0.94 0.77 0.64 0.65 0.69 0.75 0.83 0.86 0.78 0.51 0.35 0.19 0.27 0.41 0.4 0.4 0.3 "
    "0.24 0.17 0.08 0.09 0.14 0.21 0.24 0.24 0.12 0.13 0.17 0.22 0.32 0.45 0.66 0.84 0.95 1.01 0.88 0.78 "
    "0.74 0.77 0.79 0.74 0.6 0.49 0.34 0.29 0.24 0.18 0.31 0.37 0.4 0.5 0.61 0.78 0.97 1.35 1.63 1.77 2.1 "
    "2.14 2.23 2.22 2.14 1.96 1.87 1.92 2.01 1.91 1.87 1.79 1.75 1.65 1.62 1.56 1.5 1.53 1.53 1.76 1.87 2 "
    "2.01 1.96 1.87 1.82 1.81 1.86 1.87 1.93 2.01 2.15 2.32 2.5 2.4 2.27 2.22 2.04 1.94 2.02 2.22 2.37 "
    "2.42 2.32 2.24 2.12 2.12 2.06 1.87 1.76 1.7 1.64 1.56 1.52 1.57 1.61 1.56 1.5 1.57 1.6 1.71 1.8 1.88 "
    "1.94 2.04 2.2 2.4 2.49 2.6 2.53 2.48 2.54 2.57 2.47 2.24 2.09 2.03 1.99 1.9 1.78 1.76 1.81 1.75 1.67 "
    "1.55 1.4 1.31 1.29 1.34 1.37 1.45 1.62 1.72 1.73 1.6 1.56 1.47 1.44 1.4 1.35 1.42 1.42 1.38 1.32 1.3 "
    "1.19 0.91 0.77 0.55 0.4 0.23 0.14 0.17 0.19 0.18 0.22 0.58 0.8 1.03 1.08 1.27 1.62 1.82 1.81 1.71 "
    "1.53 1.49 1.37 1.34 1.23 1.27 1.36 1.61 1.54 1.49 1.21 0.96 0.82 0.74 0.54 0.54 0.65 0.88 1 1.04 "
    "0.86 0.87 0.89 1.19 1.24 1.33 1.28 1.13 1.05 1.08 1.08 1.19 1.35 1.61 1.84 1.97 1.97 1.94 1.94 1.82 "
    "1.76 1.67 1.64 1.71 1.55 1.48 1.32 1.34 1.55 1.75 1.99 2 1.98 1.98 1.86 1.64 1.48 1.37 1.38 1.37 "
    "1.21 1.2 1.03 0.97 0.95 0.95 1.07 1.18 1.1 0.94 1.06 1.17 1.12 0.95 0.9 0.88 0.79 0.65 0.5 0.59 0.76 "
    "0.87 0.97 0.97 0.95 0.83 0.75 0.57 0.51 0.61 0.76 0.88 1.01 1.11 1.11 1.12 1.26 1.29 1.4 1.32 1.12 "
    "1.08 0.99 0.9 0.81 0.88 0.99 1.09 1.17 1.14 0.95 0.85 0.59 0.53 0.47 0.6 0.68 0.68 0.6 0.41 0.23 "
    "0.16 0.1 0.08 0.23 0.4 0.53 0.77 0.82 0.85 0.81 0.72 0.73 0.83 1.03 1.18 1.21 1.2 1.23 1.27 1.22 "
    "1.12 0.94 0.76 0.56 0.6 0.62 0.6 0.6 0.59 0.69 0.7 0.81 1.06 1.09 1.16 "
)
PHASIC = (
    "0.96 0.9 0.84 0.8 0.79 0.78 0.77 0.75 0.74 0.71 0.72 0.73 0.69 0.74 0.9 1.04 1.33 1.35 1.25 1.32 "
    "1.78 2.25 3.01 3.62 4.17 4.63 4.87 5.17 5.53 5.63 5.85 5.99 6.04 6.05 6.15 6.07 6 5.76 5.75 5.71 "
    "5.61 5.54 5.54 5.47 5.3 5.22 5.13 4.94 4.66 4.42 4.26 4.16 4.01 3.88 3.74 3.46 3.25 3.09 2.93 3.02 "
    "3.13 3.12 2.98 2.79 2.43 2.24 2.07 2.06 2.06 2.07 2.08 1.99 1.65 1.45 1.17 1.16 1.23 1.23 1.2 1.07 "
    "1.01 0.87 0.74 0.69 0.67 0.71 0.76 0.72 0.62 0.56 0.54 0.6 0.64 0.7 0.86 1.07 1.21 1.3 1.29 1.14 "
    "0.74 0.77 0.79 0.74 0.6 0.49 0.34 0.29 0.24 0.18 0.31 0.37 0.4 0.5 0.61 0.78 0.97 1.35 1.63 1.77 2.1 "
    "2.14 2.23 2.22 2.14 1.96 1.87 1.92 2.01 1.91 1.87 1.79 1.75 1.65 1.62 1.56 1.5 1.53 1.53 1.76 1.87 2 "
    "2.01 1.96 1.87 1.82 1.81 1.86 1.87 1.93 2.01 2.15 2.32 2.5 2.4 2.27 2.22 2.04 1.94 2.02 2.22 2.37 "
    "2.42 2.32 2.24 2.12 2.12 2.06 1.87 1.76 1.7 1.64 1.56 1.52 1.57 1.61 1.56 1.5 1.57 1.6 1.71 1.8 1.88 "
    "1.94 2.04 2.2 2.4 2.49 2.6 2.53 2.48 2.54 2.57 2.47 2.24 2.09 2.03 1.99 1.9 1.78 1.76 1.81 1.75 1.67 "
    "1.55 1.4 1.31 1.29 1.34 1.37 1.45 1.62 1.72 1.73 1.6 1.56 1.47 1.44 1.4 1.35 1.42 1.42 1.38 1.32 1.3 "
    "1.19 0.91 0.77 0.55 0.4 0.23 0.14 0.17 0.19 0.18 0.22 0.58 0.8 1.03 1.08 1.27 1.62 1.82 1.81 1.71 "
    "1.53 1.49 1.37 1.34 1.23 1.27 1.36 1.61 1.54 1.49 1.21 0.96 0.82 0.74 0.54 0.54 0.65 0.88 1 1.04 "
    "0.86 0.87 0.89 1.19 1.24 1.33 1.28 1.13 1.05 1.08 1.08 1.19 1.35 1.61 1.84 1.97 1.97 1.94 1.94 1.82 "
    "1.76 1.67 1.64 1.71 1.55 1.48 1.32 1.34 1.55 1.75 1.99 2 1.98 1.98 1.86 1.64 1.48 1.37 1.38 1.37 "
    "1.21 1.2 1.03 0.97 0.95 0.95 1.07 1.18 1.1 0.94 1.06 1.17 1.12 0.95 0.9 0.88 0.79 0.65 0.5 0.59 0.76 "
    "0.87 0.97 0.97 0.95 0.83 0.75 0.57 0.51 0.61 0.76 0.88 1.01 1.11 1.11 1.12 1.26 1.29 1.4 1.32 1.12 "
    "1.08 0.99 0.9 0.81 0.88 0.99 1.09 1.17 1.14 0.95 0.85 0.59 0.53 0.47 0.6 0.68 0.68 0.6 0.41 0.23 "
    "0.16 0.1 0.08 0.23 0.4 0.53 0.77 0.82 0.85 0.81 0.72 0.73 0.83 1.03 1.18 1.21 1.2 1.23 1.27 1.22 "
    "1.12 0.94 0.76 0.56 0.6 0.62 0.6 0.6 0.59 0.69 0.7 0.81 1.06 1.09 1.16 "
)
_INK, _INK2, _TEAL, _RULE = "#2a211b", "#59473c", "#178079", "#6b5a4e"


def _panel(letter: str, label: str, values: str, label_at: tuple[float, float], *, onset: float | None = None) -> str:
    ys = [float(v) for v in values.split()]
    L, R, T, B = 40, 330, 14, 196  # plot box in a 340 x 236 viewBox
    def X(t): return L + (R - L) * t / 20
    def Y(v): return B - (B - T) * v / 8
    pts = " ".join(f"{X(i * 0.05):.1f},{Y(v):.1f}" for i, v in enumerate(ys))
    tid = f"phasic-{letter.lower()}"
    m = [f'<svg viewBox="0 0 340 236" role="img" aria-labelledby="{tid}-t {tid}-d" xmlns="http://www.w3.org/2000/svg">',
         f'<title id="{tid}-t">{letter}. {label}</title>']
    if letter == "A":
        m.append(f'<desc id="{tid}-d">Change in dopamine over 20 seconds: a noisy trace between about 0 and 2.6 '
                 'that keeps returning to the dashed baseline at 1.</desc>')
    else:
        m.append(f'<desc id="{tid}-d">The same tonic trace with a burst at about 1 second: it spikes to about 6.2 '
                 'at 1.7 seconds, falls back below the baseline by about 4 seconds, then follows the tonic trace.</desc>')
    for v in (0, 4, 8):
        m.append(f'<line x1="{L - 5}" x2="{L}" y1="{Y(v)}" y2="{Y(v)}" stroke="{_INK}" stroke-width="1.2"/>'
                 f'<text x="{L - 9}" y="{Y(v) + 4.5}" text-anchor="end" font-size="13" fill="{_INK2}">{v}</text>')
    for t in (0, 5, 10, 15, 20):
        m.append(f'<line x1="{X(t)}" x2="{X(t)}" y1="{B}" y2="{B + 5}" stroke="{_INK}" stroke-width="1.2"/>'
                 f'<text x="{X(t)}" y="{B + 19}" text-anchor="middle" font-size="13" fill="{_INK2}">{t}</text>')
    m.append(f'<path d="M{L},{T}V{B}H{R}" fill="none" stroke="{_INK}" stroke-width="1.4"/>')
    m.append(f'<line x1="{L}" x2="{R}" y1="{Y(1)}" y2="{Y(1)}" stroke="{_RULE}" stroke-width="1.2" stroke-dasharray="6 5"/>')
    if onset is not None:
        m.append(f'<line x1="{X(onset)}" x2="{X(onset)}" y1="{T}" y2="{B}" stroke="{_RULE}" stroke-width="1.2" stroke-dasharray="2 3"/>')
    m.append(f'<polyline points="{pts}" fill="none" stroke="{_TEAL}" stroke-width="2" stroke-linejoin="round" data-draw="wipe" style="--draw-dur:1.4s"/>')
    m.append(f'<text x="{X(label_at[0])}" y="{Y(label_at[1])}" font-size="15" font-weight="700" fill="{_INK}" '
             f'paint-order="stroke" stroke="#fbf7f1" stroke-width="4">{label}</text>')
    m.append(f'<text x="{(L + R) / 2}" y="{B + 37}" text-anchor="middle" font-size="13" fill="{_INK2}">t (s)</text>')
    m.append(f'<text transform="translate(11 {(T + B) / 2}) rotate(-90)" text-anchor="middle" font-size="13" fill="{_INK2}">Δ[DA]</text>')
    m.append("</svg>")
    return f'<div class="dm-panel"><p class="dm-panel-h">{letter}</p>{"".join(m)}</div>'


PHASIC_FIGURE = HtmlFigure(
    id="fig-phasic",
    kicker="The chart above, redrawn",
    title="Tonic and phasic dopamine release",
    html=('<div class="dm-panels">'
          + _panel("A", "Tonic", TONIC, (8.2, 0.3))
          + _panel("B", "Phasic", PHASIC, (2.6, 5.4), onset=1.0)
          + "</div>"),
    caption_html=("Change in dopamine, &Delta;[DA], over 20 seconds; dashed line = the tonic baseline. "
                  "Traces digitized from the post&rsquo;s original chart. Panel B after 5 s repeats panel A, "
                  "which it matches wherever both are visible in the original."),
)

# ── fig-dopamine-multiples: the post's list as bars ──────────
# (label, value text exactly as in the post, low, high); scale 0-10x.
MULTIPLES = (
    ("Caffeine", "Not at all**", 1, 1),
    ("Chocolate", "1.5x", 1, 1.5),
    ("Sex", "2x", 1, 2),
    ("Alcohol", "2x", 1, 2),
    ("Nicotine", "2.5x", 1, 2.5),
    ("Cocaine", "2.5x", 1, 2.5),
    ("Amphetamine", "10x", 1, 10),
    ("Exercise", "not at all or 2x", 1, 2),
)


def _bars() -> str:
    rows = []
    for i, (label, text, low, high) in enumerate(MULTIPLES):
        maybe = label == "Exercise"
        up = ""
        if high > low:
            cls = "dm-up is-maybe" if maybe else "dm-up"
            up = (f'<span class="{cls}" data-draw="grow-x" style="left:{low * 10:g}%;width:{(high - low) * 10:g}%;'
                  f'--draw-i:{i}"></span>')
        rows.append(f'<li><span class="dm-label">{label}</span><span class="dm-track">'
                    f'<span class="dm-base" style="width:10%"></span>{up}</span>'
                    f'<span class="dm-val">{text}</span></li>')
    axis = "".join(f'<span class="dm-tick-{v}" style="left:{v * 10:g}%">{v}x</span>' for v in (1, 2, 5, 10))
    return (f'<ol class="dm-bars">{"".join(rows)}</ol>'
            f'<div class="dm-axis" aria-hidden="true"><span class="dm-axis-in">{axis}</span></div>')


MULTIPLES_FIGURE = HtmlFigure(
    id="fig-dopamine-multiples",
    kicker="The list above, as bars",
    title="Dopamine release as a multiple of your baseline",
    html=_bars(),
    caption_html=("Values exactly as the post lists them (2x = twice your baseline dopamine level). "
                  "Shaded = the baseline itself; the bar past it is the increase. Exercise is an outline: "
                  "&ldquo;not at all or 2x&rdquo;."),
    after="it enhances dopamine function.</p>",
)

CSS = """
.dm-panels{display:grid;grid-template-columns:1fr 1fr;gap:18px}
.dm-panel-h{font:700 14px var(--mono);color:var(--ink3);margin:0 0 2px}
@media (max-width:640px){.dm-panels{grid-template-columns:1fr}}
.dm-bars{list-style:none;margin:0;padding:0}
.dm-bars li{display:grid;grid-template-columns:120px minmax(0,1fr) 150px;align-items:center;gap:12px;padding:5px 0;margin:0}
.dm-label{font:700 15px var(--mono);color:var(--ink)}
.dm-val{font:400 14px var(--mono);color:var(--ink2)}
.dm-track{position:relative;height:16px}
.dm-base{position:absolute;left:0;top:0;bottom:0;background:var(--sand2)}
.dm-up{position:absolute;top:0;bottom:0;background:var(--teal)}
.dm-up.is-maybe{background:transparent;box-shadow:inset 0 0 0 2px var(--teal)}
.dm-axis{display:grid;grid-template-columns:120px minmax(0,1fr) 150px;gap:12px;margin-top:6px}
.dm-axis-in{grid-column:2;position:relative;height:18px;font:400 12px var(--mono);color:var(--ink3)}
.dm-axis-in span{position:absolute;top:0;transform:translateX(-50%)}
@media (max-width:640px){
  .dm-bars li{grid-template-columns:minmax(0,1fr) auto;grid-template-areas:"label val" "track track";row-gap:4px;padding:6px 0}
  .dm-label{grid-area:label}.dm-val{grid-area:val}.dm-track{grid-area:track}
  .dm-axis{grid-template-columns:minmax(0,1fr)}.dm-axis-in{grid-column:1}.dm-axis-in .dm-tick-2{display:none}
}
"""


def render() -> str:
    return wp_post.render_post(
        SOURCE, alt=ALT, in_short=IN_SHORT,
        replace={"phasic": PHASIC_FIGURE}, replace_label="Show the original chart (with Gravel God)",
        figures=(MULTIPLES_FIGURE,), extra_css=CSS)


def main() -> None:
    wp_post.write(OUTPUT_PATH, render())


if __name__ == "__main__":
    main()
