"""Imported WordPress post: https://gravelgodcycling.com/i-didnt-screw-up-red-granite-grinder-and-neither-do-you/

Generated by scripts/wp_post_import.py 2209; the body and metadata
(i-didnt-screw-up-red-granite-grinder-and-neither-do-you.body.html / .json) are
regenerated by the converter, this file is not. ALT is written from what each
image shows; IN_SHORT follows the "In short" rule in wp_post (neutral, third person).

Post 3537 has the identical title; this is post 2209 at its own slug.

The race report (everything before "How to Red Granite Grinder 144") has no
headings, so its "In short" links point at paragraph anchors that render() adds
(ANCHORS: the paragraph's opening words -> id). Text is unchanged.

DESCRIPTION replaces the live meta description ("how to execute a clean gravel
race when everything finally goes according to plan"): in the post the race is
won despite a failed headset bearing, a dropped chain, a loose skewer and a
broken spoke.

Infographic (2026-10-09): fig-rgg-race, the race at the mile points the post
states, as bars. Nothing is derived except bar lengths (mile / 144).
Matt to read: the post says "I'd been solo for 129 of 144 miles", but it also
says the chasers caught him at mile 35 and he went solo again at mile 50
("Soloing for 94 miles"); the figure shows the stated mile points only.

Regenerate: python3 wordpress/post_sources/i_didnt_screw_up_red_granite_grinder_and_neither_do_you.py
"""
from __future__ import annotations

import dataclasses
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
if str(HERE.parent) not in sys.path:
    sys.path.insert(0, str(HERE.parent))

from editorial_shell import Claim  # noqa: E402
import wp_post  # noqa: E402
from wp_post import HtmlFigure  # noqa: E402

SLUG = "i-didnt-screw-up-red-granite-grinder-and-neither-do-you"
SOURCE = wp_post.load(SLUG)
OUTPUT_PATH = wp_post.output_path(SLUG)

DESCRIPTION = ("A race report from the 2021 Red Granite Grinder 144 in Wausau, won solo despite mechanicals, "
               "with advice on fitness, skills, equipment, fueling and tactics.")  # <=160 chars

ALT = {
    "cruxassembly-1": "Animated, filmed from floor level in a garage: a Specialized gravel bike with an orange, yellow and blue fade is assembled in stages in front of a cardboard The Pro's Closet shipping box.",
    "img-9425": "Three metal headset bearing races lying on rough asphalt in low sun; one still holds a ring of ball bearings, the other two are empty and bent.",
    "fml": "Cartoon Gravel God in a cowboy hat, seen from below, frowning down past a flat front tire in his parents' living room, with a speech bubble saying \"FML.\"",
    "who-wants-to-party": "A woman in a black zip-up jacket points and grins across a kitchen island with playing cards on it, with a speech bubble saying \"Who wants to party??!!!\"; cartoon Gravel God in a cowboy hat watches from behind.",
    "what-gave-me-away": "The Ironbull start arch on the grass in downtown Wausau at dawn: a rider in pink says \"'sup Matti!\" and cartoon Gravel God in a cowboy hat, standing with his bike, replies \"What gave me away?\" Photo credit: Ironbull, Red Granite Grinder 2021, Coates Photography.",
    "rgg-course": "Route map of the Red Granite Grinder around Wausau, Wisconsin, with labels for \"Childhood home\" near Wausau and \"Grandpa's old farm\" to the southwest, an elevation profile from 0 to 140 miles beneath it, and cartoon Gravel God in a cowboy hat at the right.",
    "let-him-go-es-a-nobody": "A two-lane paved road climbing through autumn trees beside a rock cut, with a tiny cartoon Gravel God in a cowboy hat riding away up the bike lane and the photographer's shadow in the foreground.",
    "waaaaaahhhhhhhhhhuhhh": "Race photo of a rider in a black jacket, bib tights and white helmet carrying his bike over rocks on a wooded hike-a-bike, under the caption \"Waaaaaahhhhhhhhhhuhhh!\" and a Led Zeppelin \"Immigrant Song\" single sleeve. Credit: Ironbull, Red Granite Grinder 2021, Coates Photography.",
    "casserole-here": "A straight gravel path between green fields; four people stand far down it, one saying \"Hot casserole here!\", seen past the brim of cartoon Gravel God's cowboy hat in the foreground.",
    "millar": "Cartoon Gravel God in a cowboy hat riding a gravel road through green woods, with a thought bubble holding a can of Miller Lite and a wedge of cheese.",
    "cold-casserole": "A gravel road curving through bright autumn leaves; four people stand at the left edge, one saying \"Cold casserole here!\", and cartoon Gravel God's cowboy hat is in the right foreground.",
    "seriously-tho": "A paved road through autumn trees: a grinning rider in a helmet flexes at the right, saying \"What UP MATTIIIIIIII!!!\", and cartoon Gravel God in a cowboy hat, seen from behind, answers \"Seriously, what's giving me away? Is it the hat?\"",
    "red-granite-bar": "A highway intersection beside the Red Granite Bar, a small roadside tavern with a gravel lot; at the left a woman holds out a bottle, saying \"Whoop whoop get ya watuhhh!!!\", as a tiny cartoon Gravel God rides in.",
    "dingdingding": "A long, straight dirt road rolling over wooded autumn hills, with cartoon Gravel God in a cowboy hat riding toward the camera, \"Ding Ding Ding\" beside him and a speech bubble saying \"Don't explode. Don't explode. Don't explode.\"",
    "img-9541-1": "Animated close-up of the rear tire turning slowly between the frame's stays in a garage, a scuffed brown band along its tread where it rubs.",
    "img-9540-1": "Animated close-up of the damaged rear wheel turning in the frame in a garage: hub, disc rotor and spokes, with children's bikes in the background.",
    "img-1793-scaled": "Seven people stand on the grass at the finish beside the Ironbull arch on a sunny afternoon: the author in his helmet and race kit in the middle, with family members in jackets on either side.",
    "tmp": "Animated: a bald, bearded warrior in dark leather in a field, with a wolf on a rock behind him, turns and screams at the sky with his arms flung wide.",
    "rib-falls-flash": "Black-and-white street view of a country road passing a steepled church in the woods, with cartoon Gravel God in a cowboy hat riding along it and a colour thought bubble showing an old photo of a grandfather holding a toddler.",
    "screen-shot-2021-10-21-at-10-53-13-am": "TrainingPeaks entry, Friday October 15, 2021, \"Opener/Bike Check\": 0:18:29 of a planned 1:30:00, 5.71 mi, 17 TSS, normalized power 262 W; the author's comment: \"My head set bearings double encases ball bearings in the front fork exploded. Lolz. Good thing I did a pre-ride.\"",
    "img-9516": "Race photo of a rider with a moustache in a black jacket and white helmet riding a Specialized gravel bike over leaf-covered forest singletrack, another rider behind. Credit: Ironbull, Red Granite Grinder 2021, Coates Photography.",
    "img-0368": "The Specialized gravel bike lying on grass after the race: tan-wall tires, deep carbon wheels, a frame bag and a water bottle, with riders' legs around it.",
    "img-9509": "A 24-can case of New Glarus Brewing Spotted Cow standing on a table, the box marked \"Only in Wisconsin\".",
    "img-9404": "A diner breakfast plate: a cheese omelette, fried potatoes, buttered multigrain toast and two cups of ketchup.",
    "havent-showered-in-a-week": "A rider in Rio Grande kit and white helmet rides a gravel bike past dry grass and bare trees, with a speech bubble saying \"Why aren't I drafting? I haven't showered in a week.\"",
    "billy-goat-fam": "The author in race kit and helmet stands with six family members, composited against a teal sky above a wide view of hazy purple forest.",
}

ANCHORS = {
    "Then I got out of the saddle and almost veered": "p-bearing",
    "So I picked up my bike. I ran up the last Billy Goat": "p-spoke",
}

# The "In short" rule (wp_post docstring); section = 0-based h2 index.
IN_SHORT = (
    Claim("On the pre-ride the day before the race, the author&rsquo;s headset bearing failed; a Wausau bike shop replaced it the same day.",
          "#p-bearing", "See the passage · Intro", 0),
    Claim("The author attacked on Rib Mountain, was caught at mile 35, and rode alone from the aid station at mile 50.",
          "#fig-rgg-race", "See the race by mile · Intro", 0),
    Claim("A broken spoke on the Billy Goat Hills left the rear wheel rubbing the frame for the last miles; the author still won.",
          "#p-spoke", "See the passage · Intro", 0),
    Claim("The advice section recommends arriving well rested, carrying plenty of food one enjoys, and riding in a group that shares pulls.",
          "#how-to-red-granite-grinder-144", "See the advice · §01", 0),
)

# ── fig-rgg-race: the race at the mile points the post states ──
# (label, event as the post tells it, from mile, to mile, outline?)
RACE = (
    ("Mile 8", "Top of Rib Mountain after the attack; about a minute&rsquo;s gap", 0, 8, False),
    ("Mile 35", "Seven chasers catch him", 0, 35, False),
    ("Mile 50", "Leaves the aid station by Highway 29 alone", 0, 50, False),
    ("Mile 100", "Family at the northernmost point; 44 to go", 0, 100, False),
    ("14 to go", "Red Granite Bar, the last aid station", 0, 130, False),
    ("Under 10 to go", "Pothole on the Billy Goat Hills: a broken spoke", 134, 144, True),
    ("Mile 144", "Wins in 8 hours and 20 minutes", 0, 144, False),
)
TOTAL = 144


def _rows() -> str:
    out = []
    for i, (label, event, start, end, outline) in enumerate(RACE):
        cls = "rg-bar is-span" if outline else "rg-bar"
        bar = (f'<span class="{cls}" data-draw="grow-x" style="left:{start / TOTAL * 100:.2f}%;'
               f'width:{(end - start) / TOTAL * 100:.2f}%;--draw-i:{i}"></span>')
        out.append(f'<li><span class="rg-label">{label}</span><span class="rg-track">{bar}</span>'
                   f'<span class="rg-event">{event}</span></li>')
    axis = "".join(f'<span style="left:{m / TOTAL * 100:.2f}%">{m}</span>' for m in (0, 50, 100, 144))
    # The axis is the list's last row, so it shares the rows' grid and indent.
    out.append(f'<li class="rg-axis" aria-hidden="true"><span></span><span class="rg-axis-in">{axis}</span></li>')
    return f'<ol class="rg-rows">{"".join(out)}</ol>'


RACE_FIGURE = HtmlFigure(
    id="fig-rgg-race",
    kicker="The race above, by mile",
    title="Red Granite Grinder 144: where things happened",
    html=_rows(),
    caption_html=("Mile points as the post states them, on the 144-mile course; each bar runs from the start. "
                  "The post places the Red Granite Bar 14 miles from the finish and the broken spoke "
                  "&ldquo;less than 10 miles out&rdquo;, so that bar is an outline over the last 10 miles."),
    after="8 hours and 20 minutes of effort",
)

CSS = """
.rg-rows{list-style:none;margin:0;padding:0}
.rg-rows li{display:grid;grid-template-columns:118px minmax(0,1fr) minmax(0,1.1fr);align-items:center;gap:12px;padding:5px 0;margin:0}
.rg-label{font:700 14px var(--mono);color:var(--ink)}
.rg-event{font:400 14px/1.35 var(--mono);color:var(--ink2)}
.rg-track{position:relative;height:14px;background:var(--sand2)}
.rg-bar{position:absolute;top:0;bottom:0;background:var(--teal)}
.rg-bar.is-span{background:transparent;box-shadow:inset 0 0 0 2px var(--teal)}
.rg-rows li.rg-axis{padding:2px 0 0}
.rg-axis-in{display:block;position:relative;height:18px;font:400 12px var(--mono);color:var(--ink3)}
.rg-axis-in span{position:absolute;top:0;transform:translateX(-50%)}
.rg-axis-in span:last-child{transform:translateX(-100%)}
.rg-axis-in span:first-child{transform:none}
@media (max-width:640px){
  .rg-rows li{grid-template-columns:minmax(0,1fr);grid-template-areas:"label" "event" "track";row-gap:3px;padding:7px 0}
  .rg-label{grid-area:label}.rg-event{grid-area:event}.rg-track{grid-area:track}
  .rg-rows li.rg-axis{display:block;padding:2px 0 0}.rg-rows li.rg-axis>span:first-child{display:none}
}
"""


def _anchored(body: str) -> str:
    for start, pid in ANCHORS.items():
        needle = f"<p>{start}"
        if body.count(needle) != 1:
            raise ValueError(f"anchor {pid}: {needle!r} found {body.count(needle)} times")
        body = body.replace(needle, f'<p id="{pid}">{start}', 1)
    return body


def render() -> str:
    src = dataclasses.replace(SOURCE, body=_anchored(SOURCE.body))
    return wp_post.render_post(src, alt=ALT, in_short=IN_SHORT, figures=(RACE_FIGURE,),
                               extra_css=CSS, description=DESCRIPTION)


def main() -> None:
    wp_post.write(OUTPUT_PATH, render())


if __name__ == "__main__":
    main()
