"""Imported WordPress post: https://gravelgodcycling.com/i-didnt-screw-up-red-granite-grinder-and-neither-do-you-2/

Generated by scripts/wp_post_import.py 3537; the body and metadata
(i-didnt-screw-up-red-granite-grinder-and-neither-do-you-2.body.html / .json) are
regenerated by the converter, this file is not. ALT is written from what each
image shows; IN_SHORT follows the "In short" rule in wp_post (neutral, third person).

This post (2023) shares its title with post 2209 (another batch); it is
converted at its own slug, which ends in "-2". Slugs never change.

DESCRIPTION replaces the live meta description ("another clean ride. Some races
just fit your strengths"): the post is about losing the 2023 race by one second
in a sprint; it never argues that the race fits the author's strengths.

The only heading is "Quotes of the Week", so the "In short" links point at
paragraph anchors (ANCHORS). No infographic: the Strava/TrainingPeaks
screenshots carry their own numbers and the text states none to chart.

Corrected 2026-10-09 (Matt approved): CORRECTIONS below changes "broke 150" to
"reached 150" (the panel's max is 150 bpm); each
entry names its evidence. The page notes the correction at the end.

Regenerate: python3 wordpress/post_sources/i_didnt_screw_up_red_granite_grinder_and_neither_do_you_2.py
"""
from __future__ import annotations

import dataclasses
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
if str(HERE.parent) not in sys.path:
    sys.path.insert(0, str(HERE.parent))

from editorial_shell import Claim  # noqa: E402
import wp_post  # noqa: E402

SLUG = "i-didnt-screw-up-red-granite-grinder-and-neither-do-you-2"
SOURCE = wp_post.load(SLUG)
OUTPUT_PATH = wp_post.output_path(SLUG)

_TP = "TrainingPeaks file of the October 14, 2023 ride (7:43:13, 145 mi, 530 TSS) with the route map and power, heart-rate and cadence traces"

ALT = {
    "rgggggg": "Strava activity \"Red Granite Grinder - Andre Plass!\", Saturday, October 14, 2023, Wausau, Wisconsin: 145.04 mi, 7:43:15 moving time, 7,631 ft, 282 W weighted average power, 18.8 mi/h average, and KOMs on four segments including the Billy Goat Hills; cartoon Gravel God in a cowboy hat grins on the right.",
    "rgg-gif-podium": "Animated: three riders on tree-stump podium blocks in a grassy square before a tall brick hotel. The winner, centre, in a light-blue hoodie, hoists a wooden cutting board overhead; the rider in a cowboy hat on the right holds his board. A grey-haired woman walks past in front with a speech bubble: \"It's honestly hard to be proud of you today.\"",
    "img-4766": "Strava comments on Hayden Pucker's 61.18-mile \"Morning Ride\" near Fond du Lac: Adam Bird asks \"You racing red granite?\", Hayden replies \"I am!\" and then \"I'm gonna beat Matti Rowe this year\".",
    "rgg-rib-year-comparison": "Animated Strava segment comparison of the \"Wisport TT Climb Section\" on Rib Mountain (2.1 mi, 5% grade, 600 ft): the 2023 ride, 2021 and 2022 race up the map and elevation profile together; at the top the 2023 effort reads 9:47, with 2021 24 seconds and 2022 35 seconds behind.",
    "bekken": "A rider in a blue team kit and helmet carries his muddy gravel bike up out of a small forest stream on a leafy singletrack, while a cartoon Gravel God in a cowboy hat rides past on the bank above.",
    "theyre-away": "A dusty, autumn-forest gravel road: a rider in a mustard-and-navy kit with a number plate on his bars leads, and cartoon Gravel God in a cowboy hat sits on his wheel through the dust.",
    "pit-climb": "TrainingPeaks file of the October 14, 2023 ride (7:43:13, 145 mi, 530 TSS) with a 0.22-mile climb selected: 415 W normalized, average 392 W and max 542 W, heart rate 123 to 150 bpm, 5.07 W/kg.",
    "gruff": _TP + ", a 48-second, 0.13-mile climb selected: 545 W normalized, 505 W average, 648 W max, heart rate up to 157 bpm, 12.7% grade, 6.53 W/kg.",
    "final-billy-goat": _TP + ", a 1:25.90, 0.28-mile climb selected: 500 W normalized, 450 W average, 607 W max, heart rate up to 164 bpm, 8.5% grade, 5.82 W/kg.",
    "brokaw": _TP + ", a 3:02.53, 0.57-mile climb selected: 441 W normalized, 423 W average, 543 W max, heart rate up to 165 bpm, 6.9% grade, 5.47 W/kg.",
    "rgg-finish": "A rider in a blue kit crosses the line on a brick plaza between red \"Finish\" and \"Start\" banners strung with pennants and traffic cones, with a cartoon Gravel God in a cowboy hat watching from the path behind.",
    "unc-and-ce": "A group of gravel riders in helmets and dark jackets rides a red dirt track between tall golden cornstalks, a rider wearing race number 201 at the front and a smiling rider in a blue jacket alongside.",
    "matti-doing-shit-scaled": "A grinning man in a cowboy hat and a red, white and blue jacket holds a giant \"Lotzza Motzza\" sausage and mushroom pizza in a supermarket freezer aisle.",
    "img-5129": "Strava activity \"Solo Haul\" by Labi Shabani from the Village of Weston, Wisconsin: a route from Wausau to La Crosse, 146.02 mi, 5,161 ft of climbing, 6:48:11 moving time, 221 W average power, 21.5 mi/h.",
    "forest-hietpas": "Close-up selfie of a rider with a big ginger mustache, his face and white \"The Corson Building\" jersey spattered with mud.",
    "kumgo": "Two white-and-black trucker hats with the red Kum & Go logo side by side on a granite countertop.",
    "rice-cake-creation": "Animated: a man in a green vest over a yellow hoodie stands at a kitchen counter and pounds packs of Oreos with a frying pan, again and again.",
    "krueger-heia": "Animated: two gravel riders roll along a cracked, patched country road between birch woods under a grey sky, filmed by a rider holding a phone out from just behind them.",
    "sunny-d": "A four-pack box of SunnyD Vodka Seltzer, 4.5% alcohol, on a supermarket shelf.",
}

# Paragraph anchors for the "In short" links (the post has one heading).
ANCHORS = {
    '<a href="https://www.instagram.com/polejniczak/': "p-one-second",
    "At the second aid station": "p-aid-station",
    "Hayden had a mechanical": "p-hayden",
    "The real drama of the day": "p-real-drama",
}

# The "In short" rule (wp_post docstring); section = 0-based h2 index.
IN_SHORT = (
    Claim("The author, winner in 2021 and 2022, lost the 2023 Red Granite Grinder to Peter Olejniczak by one second in a sprint.",
          "#p-one-second", "See the passage", 0),
    Claim("The two broke clear on Rib Mountain and cooperated for about 135 miles; the author waited for Olejniczak at the second aid station.",
          "#p-aid-station", "See the passage", 0),
    Claim("Hayden Pucker, who had called the author out on Strava, broke a wheel on a stick, and the author&rsquo;s parents drove him back.",
          "#p-hayden", "See the passage", 0),
    Claim("The post names the day&rsquo;s real drama as the author&rsquo;s brother and brother-in-law riding their first gravel race, the 56-mile event.",
          "#p-real-drama", "See the passage", 0),
)


def _anchored(body: str) -> str:
    for start, pid in ANCHORS.items():
        needle = f"<p>{start}"
        if body.count(needle) != 1:
            raise ValueError(f"anchor {pid}: {needle!r} found {body.count(needle)} times")
        body = body.replace(needle, f'<p id="{pid}">{start}', 1)
    return body


DESCRIPTION = ("The 2023 Red Granite Grinder: a long two-man breakaway with Peter Olejniczak, "
               "lost by one second in the sprint, and a rival's broken wheel.")


# Figures corrected to match the post's own evidence (Matt, 2026-10-09:
# "Yeah go ahead and fix"). wp_post applies each to the body (old text must
# occur exactly once) and the word-for-word tests apply them to the snapshot.
CORRECTIONS = (
    wp_post.Correction(
        "my heart rate broke 150",
        "my heart rate reached 150",
        "the TrainingPeaks panel for the climb (pit-climb) shows a max of 150 bpm"),
)

# Dead YouTube embeds (YouTube returns 404 for them, checked 2026-10-09): left
# out of the page. The converter still writes them into the body; delete an
# entry here to restore the click-to-load figure where it sat.
DEAD_YOUTUBE = {
    "JEvc9KtautY": "after Forest's bell-pepper quote, before the Era restaurant breakfast order",
}


def render() -> str:
    src = dataclasses.replace(SOURCE, body=_anchored(SOURCE.body))
    return wp_post.render_post(src, corrections=CORRECTIONS, dead_youtube=DEAD_YOUTUBE, alt=ALT, in_short=IN_SHORT, description=DESCRIPTION)


def main() -> None:
    wp_post.write(OUTPUT_PATH, render())


if __name__ == "__main__":
    main()
