"""Imported WordPress post: https://gravelgodcycling.com/i-didnt-screw-up-red-granite-grinder-again-and-neither-do-you/

Generated by scripts/wp_post_import.py 2844; the body and metadata
(i-didnt-screw-up-red-granite-grinder-again-and-neither-do-you.body.html /
.json) are regenerated by the converter, this file is not. ALT is written from
what each image shows; IN_SHORT follows the "In short" rule in wp_post
(neutral, third person).

The race story sits under one h2, so most "In short" links point at paragraph
anchors that render() adds (an id on the <p>; the text is unchanged).

The post has six approved comments; they render as the read-only archive.

DESCRIPTION replaces the live meta description ("another clean execution and
more proof that consistency beats heroics"): the post is a dead derailleur the
night before, brakes lost at mile 90 and a win anyway.

Infographic: fig-night-before, the night before the race by the clock, every
time as the post states it; nothing computed.

Corrected 2026-10-09 (Matt approved): CORRECTIONS below changes "2 miles an hour
faster" to 1; each
entry names its evidence. The page notes the correction at the end.
Left unchanged: "he just resumed pulling at about 55 mph" is surely a typo
(the Strava screenshot's max for the whole ride is 42.2 mph), but no
screenshot shows that speed, so there is no figure to put in its place.

Regenerate: python3 wordpress/post_sources/i_didnt_screw_up_red_granite_grinder_again_and_neither_do_you.py
"""
from __future__ import annotations

import dataclasses
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
if str(HERE.parent) not in sys.path:
    sys.path.insert(0, str(HERE.parent))

from editorial_shell import Claim, DataTable, TableCell, TableColumn, TableRow  # noqa: E402
import wp_post  # noqa: E402

SLUG = "i-didnt-screw-up-red-granite-grinder-again-and-neither-do-you"
SOURCE = wp_post.load(SLUG)
OUTPUT_PATH = wp_post.output_path(SLUG)

ALT = {
    "strava-rgg": "Strava screenshot of Matti Rowe's ride \"Red Granite Grinder - Første plass!\", 6:20 AM on Saturday, October 15, 2022, Town of Stettin, Wisconsin: 148.43 mi, 8:54:42 moving time, 6,017 ft of climbing, 267 W weighted average power, 7,548 kJ, 9:24:38 elapsed, with the course map around Wausau and the elevation profile; KOMs listed below.",
    "rgg-course-split": "Race photo on a gravel road lined with bare trees: rider 35, with cartoon Gravel God's face in a cowboy hat pasted on, rides beside rider 730 in a neck gaiter.",
    "sram-grx-axs": "Looking down at a garage floor: a boxed SRAM derailleur with a price sticker, next to a red Feedback Sports work stand, a bike wheel and a soda can.",
    "fred-flinstone": "A forest trail covered in fallen yellow leaves with a dusting of snow; a rider with cartoon Gravel God's face in a cowboy hat pasted on puts a foot down to slow his bike.",
    "forest-tacoma": "A red Toyota Tacoma pulls alongside a rider on a gravel forest road, a man in a beanie leaning out of the window to talk to him.",
    "two-specs": "A long, wet gravel road through the forest: two tiny riders appear far up the road behind a rider with cartoon Gravel God's face in a cowboy hat pasted on.",
    "last-billy-goat-1": "Three riders crest a hill on a gravel road through bright autumn forest, the straight road dropping and rising behind them; rider 35, on the right, has cartoon Gravel God's face in a cowboy hat pasted on.",
    "rgg-win": "A mud-spattered rider with a cartoon cowboy hat, seen from behind, rolls into a downtown finish plaza past spectators and a man sitting on a bench.",
    "img-3900": "Two men in jackets inspect a brown hunting blind for sale outside a farm store, snow falling, a \"Now Hiring\" sign in the window above.",
    "0c2e846d-50ec-4e5d-a8e1-8a85e5043d03": "An older couple in shorts, one in sunglasses and a grey shirt, the other in a plaid shirt, smiling on a park path beside flowering hydrangeas.",
    "img-3816": "An old photo of two teenagers on a front porch, a girl in a blue T-shirt and a boy in a white Umbro T-shirt.",
    "shane": "A rider in a yellow jersey and helmet works a loaded bikepacking bike over red rocks on a desert trail, another rider behind him.",
    "img-2670": "Matti and his wife run down a freshly mown hillside meadow with their two young children, a fjord and mountains behind.",
    "rgg-finish": "Faded black-and-white photo of Matti lying spread-eagled on the pavement beside his muddy bike after the finish, the ride's elevation profile across the bottom.",
}

DESCRIPTION = ("Red Granite Grinder 2022 race report: a derailleur that died the night before, brakes lost at "
               "mile 90, and a second straight win in the 144-mile race.")

# Paragraph anchors (first words of the paragraph -> id).
ANCHORS = {
    "Twelve hours before the Red Granite Grinder started": "p-derailleur",
    "As I approached a gate toward the end of the snowmobile trails": "p-brakes",
    "I don’t know: I attacked at the bottom of Rib": "p-recap",
}

# The "In short" rule (wp_post docstring); section = 0-based h2 index.
IN_SHORT = (
    Claim("The author&rsquo;s electronic derailleur failed twelve hours before the start, and a local shop that had closed sold him a replacement.",
          "#p-derailleur", "See the night before", 0),
    Claim("Around mile 90 his brakes stopped working; he lost nine minutes on repairs and slowed with his foot from then on.",
          "#p-brakes", "See the passage", 0),
    Claim("The post says he survived five attacks in the last 10 miles without brakes, hiding the problem from the two riders who caught him.",
          "#p-recap", "See the recap", 0),
    Claim("He won the 144-mile race for the second year in a row after the rider leading him missed a turn near the finish.",
          "#pull-quote-1", "See the finish", 0),
)

# ── fig-night-before: the clock, as the post states it ───────
NIGHT = (
    ("7 pm", "The derailleur is fried; most shops closed an hour earlier. Rib Mountain Cycles picks up and has “one left.”"),
    ("10 pm", "New derailleur on; pairing it in the SRAM app starts again."),
    ("Seventy minutes later", "“It still wasn’t paired.”"),
    ("11:45 pm", "Quits the app and searches YouTube for a hack."),
    ("Five minutes later", "Finds one; pairs everything “in under a minute.”"),
    ("12:30 am", "Final food prep."),
    ("1 am", "In bed, heart rate “pinned at 80 bpm.”"),
    ("3 am", "Finally asleep."),
    ("5 am", "Alarm."),
)

NIGHT_TABLE = DataTable(
    id="fig-night-before",
    kicker="The section above, by the clock",
    title="The night before the race",
    intro_html="Every time is the post&rsquo;s own.",
    footnote_html="Times and quotes from the post; nothing added.",
    columns=(
        TableColumn("When", card="title", sortable=False),
        TableColumn("What happened", card="row", sortable=False),
    ),
    rows=tuple(TableRow(cells=(TableCell(t), TableCell(w))) for t, w in NIGHT),
    after="It was 3 am by the time I finally passed out. The alarm clock was set for 5 am. Game on.</p>",
)

# Nothing in this table sorts, so the shell's "Click a column to sort" hint is hidden.
CSS = "#fig-night-before .gg-sort-hint{display:none}"


def _anchored(body: str) -> str:
    for start, pid in ANCHORS.items():
        needle = f"<p>{start}"
        if body.count(needle) != 1:
            raise ValueError(f"anchor {pid}: {needle!r} found {body.count(needle)} times")
        body = body.replace(needle, f'<p id="{pid}">{start}', 1)
    return body


# Figures corrected to match the post's own evidence (Matt, 2026-10-09:
# "Yeah go ahead and fix"). wp_post applies each to the body (old text must
# occur exactly once) and the word-for-word tests apply them to the snapshot.
CORRECTIONS = (
    wp_post.Correction(
        "going 2 miles an hour faster than me",
        "going 1 mile an hour faster than me",
        "closing a 2-mile gap in the 2 hours left takes 1 mph more"),
)

# Dead YouTube embeds (YouTube returns 404 for them, checked 2026-10-09): left
# out of the page. The converter still writes them into the body; delete an
# entry here to restore the click-to-load figure where it sat.
DEAD_YOUTUBE = {
    "U3lNsHOqiYc": "after \"It was faint, but I could almost hear the Beatles in my ear already.\"",
    "UY8zep_tLMA": "after the thank-yous intro, before \"My Brother (Uncle Andy)\"",
}


def render() -> str:
    src = dataclasses.replace(SOURCE, body=_anchored(SOURCE.body))
    return wp_post.render_post(src, corrections=CORRECTIONS, dead_youtube=DEAD_YOUTUBE, alt=ALT, in_short=IN_SHORT, figures=(NIGHT_TABLE,), extra_css=CSS,
                               description=DESCRIPTION)


def main() -> None:
    wp_post.write(OUTPUT_PATH, render())


if __name__ == "__main__":
    main()
