"""Imported WordPress post: https://gravelgodcycling.com/i-didnt-screw-up-unbound-200-and-you-dont-have-to-either/

Generated by scripts/wp_post_import.py 3433; the body and metadata
(i-didnt-screw-up-unbound-200-and-you-dont-have-to-either.body.html / .json) are
regenerated by the converter, this file is not. ALT is written from what each
image shows; IN_SHORT follows the "In short" rule in wp_post (neutral, third person).

The post's only headings are the "Hot take" pair, so most claims link to
paragraph anchors (ANCHORS). The featured image is the first inline image, so
the page has no hero. No infographic: the post states no data worth charting.

Regenerate: python3 wordpress/post_sources/i_didnt_screw_up_unbound_200_and_you_dont_have_to_either.py
"""
from __future__ import annotations

import dataclasses
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
if str(HERE.parent) not in sys.path:
    sys.path.insert(0, str(HERE.parent))

from editorial_shell import Claim  # noqa: E402
import wp_post  # noqa: E402

SLUG = "i-didnt-screw-up-unbound-200-and-you-dont-have-to-either"
SOURCE = wp_post.load(SLUG)
OUTPUT_PATH = wp_post.output_path(SLUG)

ALT = {
    "wakeeney-pit-stop": "A black Subaru with Colorado \"GRVLGOD\" plates parked on a highway shoulder, hood up and a dark pool of oil under the front; a man in a grey T-shirt stands beside it, and cartoon Gravel God in a cowboy hat takes a drag on a cigar on the right.",
    "wakeeney-pit-stop-1": "Helmet-camera view from the back of a gravel pack at dawn: dozens of riders funnel onto a churned, muddy farm track between green fields, with the brim of cartoon Gravel God's cowboy hat poking up at the bottom of the frame.",
    "forest-hietpas-2": "Selfie at a green-walled bar hung with old black-and-white photos: a grey-haired man in a blue shirt raises a copper mug, and a red-bearded man in a SkyGOAT T-shirt grins and lifts a glass behind him.",
    "pale-uncle": "Two men talk on a grassy roadside above an interstate under a big Kansas sky: a grey-haired man in sunglasses and a blue shirt, and a red-bearded man in a grey T-shirt.",
    "forest-hietpas": "Close-up selfie of a rider with a big ginger mustache, his face and white \"The Corson Building\" jersey spattered with mud.",
    "pale-uncle-3": "Cartoon Gravel God in a cowboy hat, seen from behind, stands on a red gravel road through green prairie, watching a few riders pedal away ahead of him.",
    "forest-hietpas-1": "At night on a downtown street near a \"Restrooms\" sign, a mud-caked rider in a helmet and hydration-vest straps holds a slice of pizza and a can of Miller Lite beside his filthy gravel bike, aero bars on the front.",
    "pale-uncle-1": "Aerial view of a thin line of riders strung out along a dirt road across rolling green Flint Hills grassland, with a tiny cartoon Gravel God in his cowboy hat among them.",
    "forest-hietpas-3": "Riders push their bikes on foot through tall grass along a fence line beside a muddy prairie road, with a long queue of walkers stretching to the horizon; cartoon Gravel God's hat fills the bottom of the frame.",
    "pale-uncle-2": "A phone lock-screen WHOOP widget at 06:26: 1% recovery, HRV 19, strain 0.3, 431 calories, with a faded cartoon Gravel God in a cowboy hat grinning behind it.",
}

# Paragraph anchors for the "In short" links (the post has almost no headings).
ANCHORS = {
    "That assumption was interrupted": "p-oil-plug",
    "Data is neat, but": "p-sensations",
    "I looked back – 12:26": "p-result",
}

# The "In short" rule (wp_post docstring); section = 0-based h2 index.
IN_SHORT = (
    Claim("The post recounts the author&rsquo;s car breaking down in WaKeeney, Kansas, two days before Unbound, after an oil change left the oil pan plug loose.",
          "#p-oil-plug", "See the passage", 1),
    Claim("Its hot take is that if a rider is sure of finishing Unbound, it is not Unbound: the race guarantees nothing.",
          "#hot-take", "See the hot take", 0),
    Claim("The post argues that bodily sensations, not device metrics, should meter effort, and describes the author letting wheels go while others chased.",
          "#p-sensations", "See the passage", 1),
    Claim("After rolling his right foot in the opening mud, the author finished in 12:26, 48th in the pro field.",
          "#p-result", "See the finish", 1),
)


def _anchored(body: str) -> str:
    for start, pid in ANCHORS.items():
        needle = f"<p>{start}"
        if body.count(needle) != 1:
            raise ValueError(f"anchor {pid}: {needle!r} found {body.count(needle)} times")
        body = body.replace(needle, f'<p id="{pid}">{start}', 1)
    return body


def render() -> str:
    src = dataclasses.replace(SOURCE, body=_anchored(SOURCE.body))
    return wp_post.render_post(src, alt=ALT, in_short=IN_SHORT)


def main() -> None:
    wp_post.write(OUTPUT_PATH, render())


if __name__ == "__main__":
    main()
