"""Imported WordPress post: https://gravelgodcycling.com/i-didnt-screw-up-ned-gravel-and-neither-do-you/

Generated by scripts/wp_post_import.py 3483; the body and metadata
(i-didnt-screw-up-ned-gravel-and-neither-do-you.body.html / .json) are
regenerated by the converter, this file is not. ALT is written from what each
image shows; IN_SHORT follows the "In short" rule in wp_post (neutral, third
person).

The post has no headings, so "In short" links point at paragraph anchors that
render() adds (ANCHORS: the paragraph's opening words -> id). Text is unchanged.

The featured image (The-Sherrif.png) is also inline, so the page has no hero.
The live meta description is kept. No infographic: the post's numbers (90 g of
carbohydrate an hour, 9,000 ft in 70 miles, 8th) are few and already plain;
they agree with the Strava screenshot (69.96 mi, 9,108 ft, "Åttende Plass").

Regenerate: python3 wordpress/post_sources/i_didnt_screw_up_ned_gravel_and_neither_do_you.py
"""
from __future__ import annotations

import dataclasses
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
if str(HERE.parent) not in sys.path:
    sys.path.insert(0, str(HERE.parent))

from editorial_shell import Claim  # noqa: E402
import wp_post  # noqa: E402

SLUG = "i-didnt-screw-up-ned-gravel-and-neither-do-you"
SOURCE = wp_post.load(SLUG)
OUTPUT_PATH = wp_post.output_path(SLUG)

ALT = {
    "ned-gravel": "Strava screenshot of Matti Rowe's ride \"Ned Gravel: Åttende Plass!\", July 8, 2023, Nederland, Colorado: 69.96 mi, 4:21:01 moving time, 9,108 ft of climbing, 287 W weighted average power, with the looping route map west of Boulder and the elevation profile; a cartoon Gravel God in a cowboy hat stands in front of it in profile.",
    "food-stall": "A kitchen island set with a charcuterie plate and a vegetable tray; cartoon Gravel God's head in a cowboy hat sits on a man in a floral shirt leaning on the counter, while a girl in pigtails eats a carrot and gives the camera a sideways look.",
    "the-sherrif": "Two pro riders sprint side by side down a long, dusty dirt road, with a tiny cartoon Gravel God in a cowboy hat far behind them in the distance.",
    "back-pain": "Cartoon Gravel God in a cowboy hat, seen from behind, rides up a dirt road through pine trees toward snowy peaks, with red lightning bolts flashing from his lower back.",
    "img-0449-scaled": "The author, in a black cowboy hat and vest, smiles cheek to cheek with his grinning daughter at a restaurant table, a basket of chicken tenders and fries on newspaper and a beer in front of them.",
}

ANCHORS = {
    "So the first lesson you can take from Ned Gravel": "p-heavy",
    "You don’t. I’m willing to be 90%": "p-challenge",
    "Part of me wanted to celebrate": "p-burleigh",
    "But not gravel.": "p-gravel",
}

# The "In short" rule (wp_post docstring); no headings, so section 0.
IN_SHORT = (
    Claim("Following a Colby Pearce podcast, the author arrived at Ned Gravel heavy with stored carbohydrate and took a 90-gram gel every hour.",
          "#p-heavy", "See the passage", 0),
    Claim("The post challenges racers to eat at least 90 grams of carbohydrate an hour at a low-stakes race and see what happens.",
          "#p-challenge", "See the passage", 0),
    Claim("The author passed Michael Burleigh, once the fastest road racer on the Front Range, and attributes it to Burleigh training less since having children.",
          "#p-burleigh", "See the passage", 0),
    Claim("The post contrasts a dying Front Range road racing scene with gravel, where riders can choose their own pace and distance.",
          "#p-gravel", "See the passage", 0),
)


def _anchored(body: str) -> str:
    for start, pid in ANCHORS.items():
        needle = f"<p>{start}"
        if body.count(needle) != 1:
            raise ValueError(f"anchor {pid}: {needle!r} found {body.count(needle)} times")
        body = body.replace(needle, f'<p id="{pid}">{start}', 1)
    return body


def render() -> str:
    src = dataclasses.replace(SOURCE, body=_anchored(SOURCE.body))
    return wp_post.render_post(src, alt=ALT, in_short=IN_SHORT)


def main() -> None:
    wp_post.write(OUTPUT_PATH, render())


if __name__ == "__main__":
    main()
