"""Imported WordPress post: https://gravelgodcycling.com/i-didnt-screw-up-sbt-grvl-and-neither-do-you/

Generated by scripts/wp_post_import.py 3520; the body and metadata
(i-didnt-screw-up-sbt-grvl-and-neither-do-you.body.html / .json) are regenerated
by the converter, this file is not. ALT is written from what each image shows;
IN_SHORT follows the "In short" rule in wp_post (neutral, third person).

The opening (before "What Surging?") has no heading, so its "In short" link
points at a paragraph anchor that render() adds (ANCHORS). Text is unchanged apart from CORRECTIONS.

DESCRIPTION replaces the live meta description ("What redemption looks like
after years of mistakes"): the post is about the Panic Pack, Surge Addicts and
when to surge, a 45th place, and the post-race community.

No infographic: the post's argument is a list of reasons, already a list.
Corrected 2026-10-09 (Matt approved): CORRECTIONS below changes "the height of June" to
August (the race was August 20, 2023); each
entry names its evidence. The page notes the correction at the end.

Regenerate: python3 wordpress/post_sources/i_didnt_screw_up_sbt_grvl_and_neither_do_you.py
"""
from __future__ import annotations

import dataclasses
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
if str(HERE.parent) not in sys.path:
    sys.path.insert(0, str(HERE.parent))

from editorial_shell import Claim  # noqa: E402
import wp_post  # noqa: E402

SLUG = "i-didnt-screw-up-sbt-grvl-and-neither-do-you"
SOURCE = wp_post.load(SLUG)
OUTPUT_PATH = wp_post.output_path(SLUG)

DESCRIPTION = ("An SBT GRVL 2023 race report from Steamboat Springs: the Panic Pack and Surge Addicts, three "
               "good reasons to surge, 45th place, and the post-race community.")  # <=160 chars

ALT = {
    "festival-of-pain": "Strava activity \"SBT GRVL - Topp Femti!\", Sunday, August 20, 2023, Steamboat Springs, Colorado: 145.42 mi, 7:15:32 moving time, 9,419 ft of climbing, 268 W weighted average power, 5,995 kJ, with four segment PRs; faded behind it, cartoon Gravel God's face with bloodshot eyes.",
    "panic-pack": "Black-and-white photo of a long line of gravel riders strung out up a dirt road between grassy hills, seen past the back of cartoon Gravel God's cowboy hat in the foreground.",
    "sbt-grvl-climb": "A group of gravel racers riding toward the camera on a dirt road with mountains behind; one rider at the right, drinking from a bottle, has cartoon Gravel God's face pasted over his own.",
    "surge-addicts": "TrainingPeaks file for Sunday, August 20, 2023: 7:15:37, 145 mi, 455 TSS, normalized power 277 W, IF 0.79, with the route map and a jagged power graph; cartoon Gravel God on a bike pops a wheelie, saying \"Cheese and crackers! I feel freaking greeeeeat!!!!\"",
    "1": "Panel 1, black and white: cartoon Gravel God in a cowboy hat sprints up a gravel road, a cloud of dust behind him, with the words \"What chain?\"",
    "2": "Panel 2: cartoon Gravel God stands straddling his bike on the same gravel road, with the words \"Not pedaling feels nice.\"",
    "3": "Panel 3: cartoon Gravel God has collapsed on the gravel road, legs in the air, with the words \"Why da f do I do this?\"",
    "matti-jet": "Blurred gravel racers on a dirt road with mountains behind, and a small plane flying low over them with cartoon Gravel God in a cowboy hat standing on top of it, hand at his mouth.",
    "sbt-grvl-23": "Blurred gravel racers on a dirt road below a green mountain, and a small plane flying low over them with cartoon Gravel God in a cowboy hat standing on top of it.",
}

ANCHORS = {
    "The cardinal sin of the Panic Pack": "p-panic-pack",
    "When we reached the bottom of the big climb at mile 95": "p-finish",
    "But, on August 20th, 2023": "p-vibes",
}

# The "In short" rule (wp_post docstring); section = 0-based h2 index.
IN_SHORT = (
    Claim("The post describes the Panic Pack: riders caught far back at the start who ride much too hard chasing the leaders, and mostly blow up.",
          "#p-panic-pack", "See the Panic Pack · Intro", 0),
    Claim("It gives three reasons to surge: a tempo faster than the group&rsquo;s, a bridgeable group ahead, or a long, sustained climb.",
          "#what-surging", "See §01", 0),
    Claim("The author rode within himself until the big climb at mile 95, then gained 30 places to finish 45th overall.",
          "#p-finish", "See the finish · §01", 0),
    Claim("The post says the friendly post-race festival surprised the author, who had expected bike racers not to talk to each other.",
          "#p-vibes", "See the passage · §01", 0),
)


def _anchored(body: str) -> str:
    for start, pid in ANCHORS.items():
        needle = f"<p>{start}"
        if body.count(needle) != 1:
            raise ValueError(f"anchor {pid}: {needle!r} found {body.count(needle)} times")
        body = body.replace(needle, f'<p id="{pid}">{start}', 1)
    return body


# Figures corrected to match the post's own evidence (Matt, 2026-10-09:
# "Yeah go ahead and fix"). wp_post applies each to the body (old text must
# occur exactly once) and the word-for-word tests apply them to the snapshot.
CORRECTIONS = (
    wp_post.Correction(
        "in the height of June",
        "in the height of August",
        "the post and its Strava/TrainingPeaks screenshots date the race Sunday, August 20, 2023"),
)


def render() -> str:
    src = dataclasses.replace(SOURCE, body=_anchored(SOURCE.body))
    return wp_post.render_post(src, corrections=CORRECTIONS, alt=ALT, in_short=IN_SHORT, description=DESCRIPTION)


def main() -> None:
    wp_post.write(OUTPUT_PATH, render())


if __name__ == "__main__":
    main()
