"""Imported WordPress post: https://gravelgodcycling.com/i-got-into-yoga-so-you-dont-have-to/

Generated by scripts/wp_post_import.py 3617; the body and metadata
(i-got-into-yoga-so-you-dont-have-to.body.html / .json) are regenerated by the
converter, this file is not. ALT is written from what each image shows;
IN_SHORT follows the "In short" rule in wp_post (neutral, third person).

The post has no headings, so "In short" links point at paragraph anchors that
render() adds (ANCHORS: the paragraph's opening words -> id). Text is unchanged.

DESCRIPTION replaces the live meta description, which is in the first person
and says the author "resisted it for years"; the post says he started after the
2023 season, at his wife's urging, and does not review "what doesn't" help.

The featured image is also the first inline image, so the page has no hero.
No infographic: the post states no figures a chart would clarify.

Regenerate: python3 wordpress/post_sources/i_got_into_yoga_so_you_dont_have_to.py
"""
from __future__ import annotations

import dataclasses
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
if str(HERE.parent) not in sys.path:
    sys.path.insert(0, str(HERE.parent))

from editorial_shell import Claim  # noqa: E402
import wp_post  # noqa: E402

SLUG = "i-got-into-yoga-so-you-dont-have-to"
SOURCE = wp_post.load(SLUG)
OUTPUT_PATH = wp_post.output_path(SLUG)

ALT = {
    "yoga-bros-1": "Two shirtless men in swimwear and running shoes stand arm in arm on a yoga mat in a grey studio: one in red Norway-flag trunks, his face a long-haired cartoon Gravel God in a cowboy hat, the other in blue briefs and a USA headband.",
    "mmmmmm": "A black-and-white image of an empty, misty yoga studio, mats and bolsters on the floor and tall windows at the far end; cartoon Gravel God in a cowboy hat, seen from behind, stands looking in.",
    "feels": "Rows of yoga mats in a bright, empty studio facing a wall of mirrors, in which a cartoon Gravel God in a cowboy hat is reflected, hand on his chin.",
    "toye-seg-litt": "A black-and-white overhead view of a full yoga class, everyone in a lunge with one arm raised; cartoon Gravel God in a cowboy hat watches from the corner, hand at his mouth.",
}

DESCRIPTION = ("A cyclist takes up hot yoga after the 2023 season: the stillness it brings, the "
               "mobility it restores, and why the post calls it the minimum riders should do.")

ANCHORS = {
    "After safely putting the 2023 cycling season behind me": "p-started",
    "Positions that were formerly": "p-mobility",
    "Funnily enough, the course points out": "p-pyramid",
    "Stop. Breathe.": "p-stillness",
}

# The "In short" rule (wp_post docstring); one section (no headings).
IN_SHORT = (
    Claim("The author took up hot yoga after the 2023 season, at his wife&rsquo;s urging, and says he found stillness on the mat.",
          "#p-started", "See the passage", 0),
    Claim("After about 30 hours of classes, the post reports looser hamstrings, hips and shoulders, and less pain in the author&rsquo;s left QL on the bike.",
          "#p-mobility", "See the passage", 0),
    Claim("Citing a strength course, the post argues mobility and stability form the base of strength training, making yoga the bare minimum for riding pain-free.",
          "#p-pyramid", "See the passage", 0),
    Claim("The post closes by urging cyclists to find stillness, even twice a week, rather than constantly obsessing over training and comparing themselves to others.",
          "#p-stillness", "See the passage", 0),
)


def _anchored(body: str) -> str:
    for start, pid in ANCHORS.items():
        needle = f"<p>{start}"
        if body.count(needle) != 1:
            raise ValueError(f"anchor {pid}: {needle!r} found {body.count(needle)} times")
        body = body.replace(needle, f'<p id="{pid}">{start}', 1)
    return body


def render() -> str:
    src = dataclasses.replace(SOURCE, body=_anchored(SOURCE.body))
    return wp_post.render_post(src, alt=ALT, in_short=IN_SHORT, description=DESCRIPTION)


def main() -> None:
    wp_post.write(OUTPUT_PATH, render())


if __name__ == "__main__":
    main()
