"""Imported WordPress post: https://gravelgodcycling.com/i-opened-a-fascat-ai-coaching-email-so-you-dont-have-to/

Generated by scripts/wp_post_import.py 4060; the body and metadata
(i-opened-a-fascat-ai-coaching-email-so-you-dont-have-to.body.html / .json)
are regenerated by the converter, this file is not. ALT is written from what
each image shows (the email screenshots transcribed, typos as sent); IN_SHORT
follows the "In short" rule in wp_post (neutral, third person).

The live meta description is kept: it broadly matches the post.

The post has one approved comment (Jack, 2025-02-20); it renders as the
read-only archive. No infographic.

Corrected 2026-10-09 (Matt approved): CORRECTIONS below changes $7,757 to $7,787
(twice): 13 four-week bills of $599; each
entry names its evidence. The page notes the correction at the end.

Regenerate: python3 wordpress/post_sources/i_opened_a_fascat_ai_coaching_email_so_you_dont_have_to.py
"""
from __future__ import annotations

import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
if str(HERE.parent) not in sys.path:
    sys.path.insert(0, str(HERE.parent))

from editorial_shell import Claim  # noqa: E402
import wp_post  # noqa: E402

SLUG = "i-opened-a-fascat-ai-coaching-email-so-you-dont-have-to"
SOURCE = wp_post.load(SLUG)
OUTPUT_PATH = wp_post.output_path(SLUG)

_COACHCAT = ("the AI comment \"Nice work on your Morning Ride, Gavin! Pushing into the anaerobic capacity zone for "
             "over 10 minutes is solid, especially as you peak towards 312W on your best 1-minutes power\"")

ALT = {
    "screenshot-2025-02-15-at-09-13-46": "CoachCat ad graphic \"Personalized Coaching with Instant Feedback\": a rider on a road bike behind a power chart reading 212 watts average and 310 watts max, with " + _COACHCAT + ".",
    "screenshot-2025-02-15-at-09-14-21": "Top of the FasCat email: the same CoachCat graphic (212 W average, 310 W max, " + _COACHCAT + "), then the line \"Do you ever feel buried under mountains of data from your wearable device and bike computer? Like it's sucking the fun out of your cycling -- and juggling multiple apps to analyze it is more hassle than it's worth?\"",
    "screenshot-2025-02-15-at-09-19-47": "Crop of the email: " + _COACHCAT + ", beside the highlighted bullet \"Instant Data Analysis: CoachCat digests your numbers in a snap, so you can celebrate your gains or spot areas for improvement.\"",
    "screenshot-2025-02-15-at-09-17-19": "Post by Andrew Feeney (@andrewfeeney@phpc.social): \"@kevlin @cwebber described ChatGPT as Mansplaining As A Service, and honestly I can't think of a better description. A service that instantly generates vaguely plausible sounding yet totally fabricated and baseless lectures in an instant with unflagging confidence in its own correctness on any topic, without concern, regard or even awareness of the level of expertise of its audience.\"",
    "screenshot-2025-02-15-at-09-18-10": "The email's bullet list with \"Fun, Interactive Coaching\" highlighted: \"Chat with anAI that helps you reshape your training plan when life gets busy. No ore guesswork, and it's actually fu to use!\" (typos as sent).",
    "screenshot-2025-02-15-at-09-19-20": "The same bullet list with \"Real Results\" highlighted: \"Meet Chad, a 53 year old cyclist who boosted his FTP by 32 watts in just 6 months -- training only 8-10 hours per week.\"",
    "screenshot-2025-02-15-at-09-21-36": "The email's closing paragraph, highlighted: \"If you're tired of juggling multiple apps, hiring expensive personal coaches and feeling overwhelmed by ride data, CoachCat will blow your mind. Build a custom training plan free for one month (no credit card required) and start seeing results like Chad.\" Below it: \"Click here to improve with CoachCat now!\"",
    "screenshot-2025-02-15-at-09-25-45": "The Michael Jackson popcorn meme from Thriller, captioned \"Me watching FasCat roast their own coaching business to sell AI\".",
    "screenshot-2025-02-15-at-09-45-14": "Distracted-boyfriend meme: \"Frank\" turns to look at \"Coach Cat\" walking past while \"Frank's coaches\" glares at him.",
}

# The "In short" rule (wp_post docstring); section = 0-based h2 index.
IN_SHORT = (
    Claim("The post argues that the email sells a fix for data overload that companies like FasCat helped create.",
          "#analysis-paralysis", "See the argument · §01", 0),
    Claim("It calls CoachCat&rsquo;s sample ride comment empty praise and jargon, and writes a longer coach-style comment as a contrast.",
          "#instant-data-analysis", "See the comment · §02", 1),
    Claim("The post says the email&rsquo;s example, a 32-watt FTP gain in six months, is typical of a new rider.",
          "#real-results", "See the passage · §04", 3),
    Claim("It points out that the email pitches CoachCat to people tired of hiring coaches, while FasCat also sells 1:1 coaching.",
          "#omfg-omgfg-omfg-wut-have-you-done", "See the passage · §05", 4),
)


# Figures corrected to match the post's own evidence (Matt, 2026-10-09:
# "Yeah go ahead and fix"). wp_post applies each to the body (old text must
# occur exactly once) and the word-for-word tests apply them to the snapshot.
CORRECTIONS = (
    wp_post.Correction(
        "$7,757*** more",
        "$7,787*** more",
        "billed every four weeks: 13 x $599 = $7,787"),
    wp_post.Correction(
        "$7,757/yr",
        "$7,787/yr",
        "13 x $599 = $7,787"),
)


def render() -> str:
    return wp_post.render_post(SOURCE, corrections=CORRECTIONS, alt=ALT, in_short=IN_SHORT)


def main() -> None:
    wp_post.write(OUTPUT_PATH, render())


if __name__ == "__main__":
    main()
