"""Imported WordPress post: https://gravelgodcycling.com/i-screwed-up-sbt-grvl-so-you-dont-have-to/

Generated by scripts/wp_post_import.py 2324; the body and metadata
(i-screwed-up-sbt-grvl-so-you-dont-have-to.body.html / .json) are regenerated
by the converter, this file is not. ALT is written from what each image shows;
IN_SHORT follows the "In short" rule in wp_post (neutral, third person).

The race story has no headings (only the "How to SBT GRVL" guide does), so
its "In short" links point at paragraph anchors that render() adds (an id on
the <p>; the text is unchanged). The guide's call-to-action widget (the SBT
GRVL training plan) renders as the converter's callout, text and link verbatim.

DESCRIPTION replaces the live meta description ("altitude missteps in
Steamboat Springs and the pacing lessons I keep learning the hard way"): it is
first person and names neither the crash, the descending fear nor the sodium
plan the post is about.

Infographic: fig-sodium, the post's race-day sodium steps as a table, in the
post's own words; nothing added or computed.

For Matt (arithmetic, text unchanged): "lose 20 seconds per mile ... roughly
80 miles ... approximately 30 minutes": 20 s x 80 = 1,600 s, about 27 minutes.

Regenerate: python3 wordpress/post_sources/i_screwed_up_sbt_grvl_so_you_dont_have_to.py
"""
from __future__ import annotations

import dataclasses
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
if str(HERE.parent) not in sys.path:
    sys.path.insert(0, str(HERE.parent))

from editorial_shell import Claim, DataTable, TableCell, TableColumn, TableRow  # noqa: E402
import wp_post  # noqa: E402

SLUG = "i-screwed-up-sbt-grvl-so-you-dont-have-to"
SOURCE = wp_post.load(SLUG)
OUTPUT_PATH = wp_post.output_path(SLUG)

ALT = {
    "crash-nurse": "Two photos side by side: a selfie of Matti in a red Rio Grande jersey after his crash, nose and lip bloodied and grazed, earbuds in; and a young girl in a nurse costume taping a dressing onto his scraped thigh at home.",
    "sbt-grvl-start": "Painterly-filtered photo of the SBT GRVL start: a crowd of helmeted riders under string lights facing the SBT GRVL arch, with the top of cartoon Gravel God's cowboy hat among them.",
    "hey-yeah-you-snap-out-of-it-youre-a-stallion": "Selfie of a weathered, grey-haired rider in a cycling cap and light-blue jersey, with a speech bubble: \"Hey. Yeah, you. Snap out of it. You're a STALLION!\"",
    "sbt-aften": "Collage after the race: Matti grinning in red Rio Grande kit beside his bike in the finish area, and Matti in glasses at a restaurant with a small boy in an SBT GRVL cap and a girl in a floral dress.",
    "screen-shot-2021-11-24-at-10-56-27-am": "TrainingPeaks summary of \"SBT Gravel\", August 15, 2021: 7:22:30, 145 mi, 396 hrTSS, Fitness 107, Fatigue 146, Form -4; planned vs completed 140 vs 145 mi, 17.5 vs 19.6 mph, 9,000 vs 7,808 ft, normalized power 302 W; Matti's comment begins \"Best gravel race I've put together so far\" and says he preloaded 1500 mg of sodium the night before and 1500 mg 90 minutes before.",
    "check-those-rims-scaled": "Close-up of a black carbon rim with a gouge in its edge, below a tan-wall tyre printed \"MAX. INFLATION\".",
    "derailleur-danger-scaled": "Close-up of a SRAM rear derailleur on a Specialized frame, its pulley cage wrapped in dry grass and twigs.",
    "salty-rims-scaled": "Looking down at black bib shorts streaked with dried white salt across both thighs.",
    "snack-security-scaled": "A woman and two small children in a restaurant booth after the race, with empty plates, beer glasses and a bowl of spaghetti on the table.",
    "solo-dolo": "Matti riding alone up a paved road in red Rio Grande kit, a dry grassy hillside behind him.",
    "screen-shot-2021-11-24-at-11-23-12-am": "Strava screenshot of Matti Rowe's SBT GRVL ride \"Glad Som En Laks\", 5:52 AM on Sunday, August 15, 2021, Steamboat Springs, Colorado: 144.63 mi, 7:22:47 moving time, 6,716 ft of climbing, 291 W weighted average power, 6,737 kJ, 19.6 mi/h average.",
}

DESCRIPTION = ("SBT GRVL race report: a crash three days out, fear on dry washboard descents, a high-sodium "
               "plan that ended the cramping, 68th place, and a course guide.")  # <=160 chars

# Paragraph anchors (first words of the paragraph -> id).
ANCHORS = {
    "That’s what’s such a bitch about getting technically better": "p-fear-cost",
    "He was wrong. I wasn’t racing for 5,000th place.": "p-68th",
}

# The "In short" rule (wp_post docstring); section = 0-based h2 index (the
# race story comes before the first h2).
IN_SHORT = (
    Claim("The post estimates that losing 20 seconds a mile over roughly 80 miles of descents and technical trail costs about 30 minutes.",
          "#p-fear-cost", "See the estimate", 0),
    Claim("After switching from drinking to thirst to heavy sodium loading, the author reports no cramping or nausea in the race.",
          "#fig-sodium", "See the sodium steps", 0),
    Claim("The author finished 68th, passing fading riders late in the race, and calls it his first gravel finish without shame.",
          "#p-68th", "See the finish", 0),
    Claim("Its course guide advises arriving fresh rather than fitter but fatigued, and choosing wider, grippier tires unless the rider handles a bike well.",
          "#how-to-sbt-grvl", "See the guide · §01", 0),
)

# ── fig-sodium: the race-day sodium steps, in the post's words ──
SODIUM = (
    ("The night before", "“I downed a Pedialyte”"),
    ("An hour and a half before the race", "“I drank another”"),
    ("Before the third hour", "“another 3,000 mg of sodium”"),
    ("After that", "“a sleeve of electrolyte tablets”"),
)

SODIUM_TABLE = DataTable(
    id="fig-sodium",
    kicker="The two paragraphs above, as a timeline",
    title="Race-day sodium, step by step",
    intro_html="What the author took, quoted from the post.",
    footnote_html=("The post&rsquo;s result: &ldquo;I never cramped. I never felt nauseous.&rdquo; Its guide below adds: "
                   "pre-load sodium, take lots in the first hours and more than you think in the final hours."),
    columns=(
        TableColumn("When", card="title", sortable=False),
        TableColumn("What", card="row", sortable=False),
    ),
    rows=tuple(TableRow(cells=(TableCell(w), TableCell(x))) for w, x in SODIUM),
    after="I felt like a goddamn Gravel God.</p>",
)

# Nothing in this table sorts, so the shell's "Click a column to sort" hint is hidden.
CSS = "#fig-sodium .gg-sort-hint{display:none}"


def _anchored(body: str) -> str:
    for start, pid in ANCHORS.items():
        needle = f"<p>{start}"
        if body.count(needle) != 1:
            raise ValueError(f"anchor {pid}: {needle!r} found {body.count(needle)} times")
        body = body.replace(needle, f'<p id="{pid}">{start}', 1)
    return body


# Dead YouTube embeds (YouTube returns 404 for them, checked 2026-10-09): left
# out of the page. The converter still writes them into the body; delete an
# entry here to restore the click-to-load figure where it sat.
DEAD_YOUTUBE = {
    "LYJ0QGV0Sco": "after the washboard-gravel paragraph (\"But now? Jesus Christ...\")",
}


def render() -> str:
    src = dataclasses.replace(SOURCE, body=_anchored(SOURCE.body))
    return wp_post.render_post(src, dead_youtube=DEAD_YOUTUBE, alt=ALT, in_short=IN_SHORT, figures=(SODIUM_TABLE,), extra_css=CSS,
                               description=DESCRIPTION)


def main() -> None:
    wp_post.write(OUTPUT_PATH, render())


if __name__ == "__main__":
    main()
