"""Imported WordPress post: https://gravelgodcycling.com/i-screwed-up-unbound-gravel-200-so-you-dont-have-to/

Generated by scripts/wp_post_import.py 1964; the body and metadata
(i-screwed-up-unbound-gravel-200-so-you-dont-have-to.body.html / .json) are
regenerated by the converter, this file is not. ALT is written from what each
image shows; IN_SHORT follows the "In short" rule in wp_post (neutral, third
person). One approved comment renders as the read-only archive.

The live meta description is kept.

Infographic (2026-10-09): fig-if, the "Tactics" intensity-factor numbers on
one scale: 0.55 recovery pace, the 0.69 ceiling the post sets for the race,
1.0 an all-out hour at threshold (all from the text), plus the author's own
planned 0.65 and completed 0.74, read off the TrainingPeaks screenshot
(dk-card). Nothing is derived.

Corrected 2026-10-09 (Matt approved; CORRECTIONS below): the starters were
"960 or so", then "900 of us rode off", then "the other 975" after the top 15
(990); they now all follow the post's "960 or so" (no official 200-mile start
count was quickly verifiable). The tire advice said "less than a 35 mm tire",
then "do NOT run anything less than a 38mm tire"; both say 38 now.
Left unchanged: "206 miles" is the official 2021 course length (206.8 mi); the
screenshots' 208 mi include riding to and from the start.

Regenerate: python3 wordpress/post_sources/i_screwed_up_unbound_gravel_200_so_you_dont_have_to.py
"""
from __future__ import annotations

import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
if str(HERE.parent) not in sys.path:
    sys.path.insert(0, str(HERE.parent))

from editorial_shell import Claim  # noqa: E402
import wp_post  # noqa: E402
from wp_post import HtmlFigure  # noqa: E402

SLUG = "i-screwed-up-unbound-gravel-200-so-you-dont-have-to"
SOURCE = wp_post.load(SLUG)
OUTPUT_PATH = wp_post.output_path(SLUG)

ALT = {
    "ahhhh": "Animated: a straight gravel road between green and golden fields at dusk; a tiny cartoon Gravel God rides toward the camera as the words \"AAAAHHH!!!\" appear over the road.",
    "img-8079": "The Wagon Wheel Bar and Grill: a long, low, red-sided building with a hand-painted Burgers & Beer sign, cars parked along its gravel lot under a blue sky.",
    "wagon-wheel-bar-and-grille": "A dim, crowded film-set cantina full of rough-looking characters at the bar; cartoon Gravel God in a cowboy hat, seen from behind, looks on.",
    "64455047215-34830351-3f02-463a-9f42-9538492492a6-fullsizerender-1": "A man in a black T-shirt and a wide-brimmed hat stands on an empty street holding open a foam takeout box of food.",
    "kanza-start": "Riders in helmets packed shoulder to shoulder at the start in front of a red-brick church; cartoon Gravel God in a cowboy hat peeks in from the bottom right.",
    "yawn": "Cartoon Gravel God in a cowboy hat, white T-shirt and short shorts stands with his hands behind his back against a black background.",
    "kanza-start-1": "A newspaper front page, \"DAILY NEWS\", with the headline \"Gravel Enthusiast bombs biggest race of the year but remains handsome.\" above a grinning cartoon Gravel God in a cowboy hat.",
    "64455045854-f51090d3-62e4-4b04-b6d3-935a301fbf31-fullsizerender": "A ruddy, bearded man in a blue T-shirt grins wide-eyed into the camera, mouth open mid-shout.",
    "you-suck-at-cooking-you-can-barely-readd": "Cartoon Gravel God in a cowboy hat rides a dirt track through bright green fields, his speech bubble reading: \"...you suck at cooking, you can barely read, you can't even touch your toes, you have like 2.5 friends, you should just go die\"",
    "water-tower-of-emporia": "A grey aerial view of Emporia with its water tower, lettered EMPORIA, at the centre, and a giant translucent face of cartoon Gravel God in a cowboy hat over the town.",
    "img-8104": "A smiling man in a grey T-shirt in the finish-area expo, among vendor tents, bikes and spectators.",
    "pale-thunder-rv-1": "Animated: a man in sunglasses drives the RV down a residential street, a phone mounted on the dashboard.",
    "dk-card": "TrainingPeaks file \"DK\", Saturday June 5, 2021: 12:48:21, 208 mi, 705 TSS. Planned against completed: duration 16:48:00 against 12:48:21, TSS 700 against 705, IF 0.65 against 0.74; 16.3 mph average, normalized power 267 W, 9,396 ft of climbing, 10,069 kJ, and a 405 W best 10-minute power.",
    "try-new-things-1": "A rider climbs a sandy desert singletrack through scrub; cartoon Gravel God on a bike behind him says: \"Uggggh I don't have to steer on Zwift.\"",
    "img-8075": "Race number 2859, \"Matti Rowe\", Unbound Gravel 200, zip-tied to the handlebars of a gravel bike with a Garmin, parked beside an RV.",
    "img-8088-scaled": "A man in a cowboy hat drinks from a can in front of an RV fridge stacked with cans of Miller Lite.",
    "watch-out-im-behind-you-5": "Paper plates of seasoned fries, a burger and a foil-wrapped hot dog with ketchup on a sidewalk; cartoon Gravel God in a cowboy hat eyes them in profile.",
    "power-meter-clown-2-1": "Riders kick up dust on a gravel road into a low sun; cartoon Gravel God rides behind them, saying: \"Perfect! Everyone is in front of me! Now I will show them how many watts I can put out!\"",
    "img-8084": "A man in a blue T-shirt and shorts poses inside the RV with one fist raised, a 30-pack of Miller Lite at his feet.",
    "screen-shot-2021-08-12-at-2-48-00-pm": "Strava screenshot of Matti Rowe's ride \"Aldri igjen før neste år\", June 5, 2021, Emporia, Kansas: 208.15 mi, 12:48:17 moving time, 14:07:29 elapsed, 9,396 ft of climbing, 255 W weighted average power, 10,077 kJ, 16.3 mi/h average.",
}

# ── fig-if: the intensity-factor numbers on one scale ────────
LO, HI = 0.5, 1.05
MARKS = (  # (IF, label, source, class)
    (0.55, "Recovery pace", "post", "is-ref"),
    (0.65, "Author&rsquo;s planned IF", "file", "is-file"),
    (0.69, "The post&rsquo;s ceiling for the race", "post", "is-cap"),
    (0.74, "Author&rsquo;s completed IF", "file", "is-file"),
    (1.0, "All-out hour at threshold", "post", "is-ref"),
)


def _pct(v: float) -> str:
    return f"{(v - LO) / (HI - LO) * 100:.1f}%"


def _if_scale() -> str:
    rows = "".join(
        f'<li class="if-row {cls}"><span class="if-l">{label}</span>'
        f'<span class="if-track"><span class="if-zone" style="width:{_pct(0.69)}"></span>'
        f'<span class="if-dot" data-draw="fade" style="left:{_pct(v)};--draw-i:{i}"></span></span>'
        f'<span class="if-v">{v:.2f}</span></li>'
        for i, (v, label, _, cls) in enumerate(MARKS))
    return f'<ol class="if-rows">{rows}</ol>'


IF_FIGURE = HtmlFigure(
    id="fig-if",
    kicker="Intensity factor, from the Tactics section",
    title="Where 0.69 sits",
    html=_if_scale(),
    caption_html=("IF = normalized power &divide; threshold power. 0.55, 0.69 and 1.0 are the post&rsquo;s numbers; "
                  "the author&rsquo;s planned 0.65 and completed 0.74 are read off the TrainingPeaks file above. "
                  "Shaded: at or under the post&rsquo;s ceiling; open dots are the author&rsquo;s file."),
    after="should not exceed .69.</p>",
)

CSS = """
.if-rows{list-style:none;margin:0;padding:0}
.if-row{display:grid;grid-template-columns:230px minmax(0,1fr) 52px;align-items:center;gap:12px;padding:6px 0;margin:0}
.if-l{font:400 14px/1.3 var(--mono);color:var(--ink2)}
.if-v{font:700 15px var(--mono);color:var(--ink);text-align:right}
.if-track{position:relative;height:14px;background:var(--sand)}
.if-zone{position:absolute;left:0;top:0;bottom:0;background:var(--sand2)}
.if-dot{position:absolute;top:50%;width:14px;height:14px;margin:-7px 0 0 -7px;border-radius:50%;background:var(--ink3)}
.if-row.is-cap .if-dot{background:var(--teal);border-radius:0;width:4px;height:24px;margin:-12px 0 0 -2px}
.if-row.is-cap .if-l,.if-row.is-cap .if-v{color:var(--teal-ink);font-weight:700}
.if-row.is-file .if-dot{background:var(--paper);box-shadow:inset 0 0 0 3px var(--ink)}
@media (max-width:640px){
  .if-row{grid-template-columns:minmax(0,1fr) auto;grid-template-areas:"label val" "track track";row-gap:4px}
  .if-l{grid-area:label}.if-v{grid-area:val}.if-track{grid-area:track}
}
"""

# The "In short" rule (wp_post docstring); section = 0-based h2 index.
IN_SHORT = (
    Claim("Four miles in, the author&rsquo;s spare tube jammed his rear wheel; he spent heavily chasing the front group and cracked at mile 96.",
          "#when-i-passed-96-miles-i-cracked", "See the race · §02", 1),
    Claim("At the last aid station, at mile 155, his friend Joe Howdyshell made him drink, eat and get back on the bike.",
          "#pull-quote-2", "See the aid station · §02", 1),
    Claim("The post recommends wide tires, aero bars, a hydration plan of roughly 1,000 mg of sodium an hour, and real food alongside gels.",
          "#hydation", "See the advice · §03", 2),
    Claim("The post sets a target intensity factor of no more than 0.69 for the race and advises against chasing the leaders.",
          "#fig-if", "See the scale · §03", 2),
)


# Figures corrected to match the post's own evidence (Matt, 2026-10-09:
# "Yeah go ahead and fix"). wp_post applies each to the body (old text must
# occur exactly once) and the word-for-word tests apply them to the snapshot.
CORRECTIONS = (
    wp_post.Correction(
        "900 of us rode off",
        "960 or so of us rode off",
        "the post's own \"960 or so starters\"; it also gave 900 and 990 (15 + 975); no official 200-mile start count was quickly verifiable"),
    wp_post.Correction(
        "For the other 975 people",
        "For the other 945 people",
        "960 or so starters minus the top 15"),
    wp_post.Correction(
        "less than a 35 mm tire",
        "less than a 38 mm tire",
        "the next line's rule: \"do NOT run anything less than a 38mm tire\""),
)

# Dead YouTube embeds (YouTube returns 404 for them, checked 2026-10-09): left
# out of the page. The converter still writes them into the body; delete an
# entry here to restore the click-to-load figure where it sat.
DEAD_YOUTUBE = {
    "laCYM4ZpcBQ": "end of the race-report section, after \"...filled with something I'd call life.\"",
}


def render() -> str:
    return wp_post.render_post(SOURCE, corrections=CORRECTIONS, dead_youtube=DEAD_YOUTUBE, alt=ALT, in_short=IN_SHORT, figures=(IF_FIGURE,), extra_css=CSS)


def main() -> None:
    wp_post.write(OUTPUT_PATH, render())


if __name__ == "__main__":
    main()
