"""Imported WordPress post: https://gravelgodcycling.com/i-screwed-up-gunni-grinder-so-you-dont-have-to/

Generated by scripts/wp_post_import.py 2065; the body and metadata
(i-screwed-up-gunni-grinder-so-you-dont-have-to.body.html / .json) are
regenerated by the converter, this file is not. ALT is written from what each
image shows; IN_SHORT follows the "In short" rule in wp_post (neutral, third
person).

Almost all of the post sits before its only heading, so "In short" links point
at paragraph anchors that render() adds (ANCHORS: the paragraph's opening
words -> id). Text is unchanged.

DESCRIPTION replaces the live meta description ("pacing mistakes, altitude
miscalculations"): the post mentions neither. It is about a weekend with the
author's oldest friend, a wrong turn, and technical terrain.

No infographic: the post states no figures a chart would clarify.

Matt to read: the text says his friend weighed "139.8 pounds"; the scale in
the image (139-5.jpg) reads 139.5. The text is unchanged.

Regenerate: python3 wordpress/post_sources/i_screwed_up_gunni_grinder_so_you_dont_have_to.py
"""
from __future__ import annotations

import dataclasses
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
if str(HERE.parent) not in sys.path:
    sys.path.insert(0, str(HERE.parent))

from editorial_shell import Claim  # noqa: E402
import wp_post  # noqa: E402

SLUG = "i-screwed-up-gunni-grinder-so-you-dont-have-to"
SOURCE = wp_post.load(SLUG)
OUTPUT_PATH = wp_post.output_path(SLUG)

ALT = {
    "sherpacafe": "A café patio strung with Tibetan prayer flags under a blue sky; a man in sunglasses sits at a table at the back, and cartoon Gravel God in a cowboy hat, seen from behind, stands in the foreground looking at him.",
    "139-5": "Bare feet on a bathroom scale reading 139.5, set over a black-and-white photo of a dug-up backyard with cardboard foundation tubes for a deck.",
    "img-9209": "A rider in a helmet, hoodie and shorts bends over a gravel bike with a frame bag in a motel parking lot, a Registration banner and pine trees behind him.",
    "easystreet": "A green highway sign, \"Easy Street NEXT EXIT\", against a blue sky; cartoon Gravel God in a cowboy hat says: \"Whew! I knew I'd find you! I'd hate to have to push myself.\"",
    "onewetbar": "A white speedboat carves a wake along a rocky coastline; cartoon Gravel God in a cowboy hat stands on its bow, saying: \"Don't judge, I've got problems. This boat only has 1 wet bar!\"",
    "img-9214": "Bare legs on a hotel-room carpet, caked in dust and grime down to sharp sock lines, the feet clean below them.",
    "cantbeit-3": "Two men in matching striped Nordic-style sweaters pose shoulder to shoulder, one with an arm around the other, against a faded desert landscape.",
}

DESCRIPTION = ("Gunni Grinder race report: a weekend in Gunnison with the author's oldest friend, "
               "a wrong turn, punishing technical terrain, and why the hardship is the point.")

ANCHORS = {
    "I took a wrong turn": "p-technique",
    "Driving to Gunnison": "p-friend",
    "Finish anything truly physically insane": "p-ultra",
    "Forty minutes later": "p-airik",
}

# The "In short" rule (wp_post docstring); section = 0-based h2 index.
IN_SHORT = (
    Claim("The author says his weak technical skills, not his fitness, keep him from doing well in gravel races.",
          "#p-technique", "See the passage", 0),
    Claim("The post presents the trip as a reunion with the author&rsquo;s oldest friend, Airik, more than a race.",
          "#p-friend", "See the passage", 0),
    Claim("The post argues that finishing an ultra event depends less on fitness, planning or nutrition than people think; when planning unravels, the rider remains.",
          "#p-ultra", "See the passage", 0),
    Claim("Airik, who had not ridden for two weeks beforehand, finished only fifty-some minutes behind the author.",
          "#p-airik", "See the passage", 0),
)


def _anchored(body: str) -> str:
    for start, pid in ANCHORS.items():
        needle = f"<p>{start}"
        if body.count(needle) != 1:
            raise ValueError(f"anchor {pid}: {needle!r} found {body.count(needle)} times")
        body = body.replace(needle, f'<p id="{pid}">{start}', 1)
    return body


def render() -> str:
    src = dataclasses.replace(SOURCE, body=_anchored(SOURCE.body))
    return wp_post.render_post(src, alt=ALT, in_short=IN_SHORT, description=DESCRIPTION)


def main() -> None:
    wp_post.write(OUTPUT_PATH, render())


if __name__ == "__main__":
    main()
