"""Imported WordPress post: https://gravelgodcycling.com/i-screwed-up-foco-fondo-so-you-dont-have-to/

Generated by `scripts/wp_post_import.py 3504 --aside Sidebar`; the body and
metadata (i-screwed-up-foco-fondo-so-you-dont-have-to.body.html / .json) are
regenerated by the converter, this file is not. ALT is written from what each
image shows; IN_SHORT is a DRAFT for Matt's read (each claim restates the post).

"Sidebar" (an h3 heading widget + its text widget) is rendered as an aside, so
the race story isn't filed under a "Sidebar" contents entry. The post's
Click-to-Tweet is a pull quote (converter).

Infographic (2026-10-09): fig-turbo, the post's own turbo-button metaphor as a
gauge strip. Every quote is the post's; the gauge lengths only show the colour
stage the post names (full, yellow, red, empty), not a measurement.
Not drawn: a to-scale distance chart. The post says "Seventy miles down, 50 to
go" and also "For 50 miles in 100", so the course length needs Matt first.

Regenerate: python3 wordpress/post_sources/i_screwed_up_foco_fondo_so_you_dont_have_to.py
"""
from __future__ import annotations

import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
if str(HERE.parent) not in sys.path:
    sys.path.insert(0, str(HERE.parent))

from editorial_shell import Claim  # noqa: E402
import wp_post  # noqa: E402
from wp_post import HtmlFigure  # noqa: E402

SLUG = "i-screwed-up-foco-fondo-so-you-dont-have-to"
SOURCE = wp_post.load(SLUG)
OUTPUT_PATH = wp_post.output_path(SLUG)

ALT = {
    "focofondo-2": "Black-and-white photo of a gravel road curving through open rolling hills toward dark forested ridges; two riders lead around the bend while a cartoon Gravel God in a cowboy hat pedals far behind at the left.",
    "focofondo-rolling-hills": "A dusty dirt road across green-brown prairie under a deep blue sky: a tight bunch of riders up the road, and a cartoon Gravel God in a cowboy hat chasing alone behind them in a huge cloud of dust.",
    "whitney-and-zach": "Photo of race promoters Whitney and Zach Allison in matching cream FoCo Fondo shirts, studying a phone and a clipboard together by an event tent.",
    "focofondo-rocket": "Animated: cartoon Gravel God in a cowboy hat rockets down a straight dirt road across the prairie with a fireball streaming beside him, riders silhouetted up the road ahead.",
    "focofondo-3": "A wide gravel road climbing across a grassy plain: a rider in a blue kit and a cartoon Gravel God in a cowboy hat ride side by side toward the camera.",
    "focofondo-5": "Aerial photo of a lone rider on a red-dirt road through scrubby hillside, under a thought bubble from Gravel God's face: \"FML just kill me. Even your dog doesn't like you. You're ugly and that can't be fixed. Quit and never come back. You're as bright as a tunnel.\"",
    "focofondo-4": "Aerial photo of a lone rider on a straight red-dirt road cutting through green, scrubby hillside.",
}

# DRAFT for Matt: each claim restates the post; section = 0-based h2 index.
IN_SHORT = (
    Claim("After the single track there were two tactics: ride smart in a group and wait for the climb, or mash the turbo button and bridge.",
          "#fig-focofondo-rocket", "See the turbo button · Intro", 0),
    Claim("About three hours of turbo left the gauge yellow as the road turned up for an hour; on the steep ramps it went red.",
          "#fig-turbo", "See the gauge · Intro", 0),
    Claim("In the Piper, the third act, success depends less on your engine and handling than on eating, drinking and using your energy.",
          "#the-piper-3hrs", "See the Piper · §01", 0),
    Claim("Racing on adrenaline and ego made the last fifty miles a parade of pain, legs at the very bottom of Zone 1.",
          "#the-piper-3hrs", "See the last fifty miles · §01", 0),
)

# ── fig-turbo: the turbo button, stage by stage ──────────────
# (when, quote from the post, gauge stage). Stage lengths are not data.
TURBO = (
    ("After the single track", "I mashed the button.", "full"),
    ("About three hours in", "Mine wasn’t red yet, but there’s no question it was yellow", "yellow"),
    ("The steep, unrelenting ramps", "red wasn’t just on my cycling computer screen but also the indicator on my turbo. I was done", "red"),
    ("Seventy miles down, 50 to go", "I pulled the leash on my parachute.", "empty"),
    ("The last 15 miles", "The Gods even stepped in and offered a tailwind", "empty"),
)
_STAGE = {"full": ("Full", 100), "yellow": ("Yellow", 55), "red": ("Red", 18), "empty": ("Empty", 0)}


def _turbo() -> str:
    rows = []
    for i, (when, quote, stage) in enumerate(TURBO):
        name, width = _STAGE[stage]
        fill = (f'<span class="tb-fill is-{stage}" data-draw="grow-x" style="width:{width}%;--draw-i:{i}"></span>'
                if width else "")
        rows.append(f'<li><p class="tb-when">{when}</p><p class="tb-gauge"><span class="tb-bar" role="img" '
                    f'aria-label="Turbo: {name.lower()}">{fill}</span><span class="tb-stage">{name}</span></p>'
                    f'<p class="tb-quote">&ldquo;{quote}&rdquo;</p></li>')
    return f'<ol class="tb-steps">{"".join(rows)}</ol>'


TURBO_FIGURE = HtmlFigure(
    id="fig-turbo",
    kicker="The race, by turbo gauge",
    title="Mash the button and the bar runs down",
    html=_turbo(),
    caption_html=("Every quote is from the post. Not to scale: the post names the gauge&rsquo;s colours, "
                  "not numbers, so bar lengths show the stage only."),
    after="The nightmare had begun.</p>",
)

CSS = """
.tb-steps{list-style:none;margin:0;padding:0}
.tb-steps li{display:grid;grid-template-columns:190px 130px minmax(0,1fr);gap:14px;align-items:baseline;
  padding:10px 0;margin:0;border-top:1px solid var(--sand2)}
.tb-steps li:first-child{border-top:0}
.tb-steps p{margin:0}
.tb-when{font:700 14px/1.35 var(--mono);color:var(--ink)}
.tb-gauge{display:flex;align-items:center;gap:8px}
.tb-bar{position:relative;display:block;width:76px;height:12px;box-shadow:inset 0 0 0 1.5px var(--ink3)}
.tb-fill{position:absolute;left:0;top:0;bottom:0}
.tb-fill.is-full{background:var(--teal)}
.tb-fill.is-yellow{background:#d4a514}
.tb-fill.is-red{background:var(--stop)}
.tb-stage{font:400 13px var(--mono);color:var(--ink3)}
.tb-quote{font:italic 400 18px/1.45 var(--serif);color:var(--ink2)}
@media (max-width:640px){
  .tb-steps li{grid-template-columns:minmax(0,1fr) auto;grid-template-areas:"when gauge" "quote quote";row-gap:6px}
  .tb-when{grid-area:when}.tb-gauge{grid-area:gauge}.tb-quote{grid-area:quote;font-size:17px}
}
"""


def render() -> str:
    return wp_post.render_post(SOURCE, alt=ALT, in_short=IN_SHORT, figures=(TURBO_FIGURE,), extra_css=CSS)


def main() -> None:
    wp_post.write(OUTPUT_PATH, render())


if __name__ == "__main__":
    main()
