"""Imported WordPress post: https://gravelgodcycling.com/i-screwed-up-co2ut-so-you-dont-have-to/

Generated by scripts/wp_post_import.py 3353; the body and metadata
(i-screwed-up-co2ut-so-you-dont-have-to.body.html / .json) are regenerated by
the converter, this file is not. ALT is written from what each image shows;
IN_SHORT follows the "In short" rule in wp_post (neutral, third person).

The post has no headings, so "In short" links point at paragraph anchors that
render() adds (an id on the <p>; the text is unchanged).

DESCRIPTION replaces the live meta description ("cracking in the Colorado heat
and the hydration mistakes that turned a good day into a survival march"): the
post mentions neither heat nor hydration; it is a misbooked hotel, a failed
bike rack, cattle-track gravel and a 9th-place finish.

The featured image (co2ut-podium-1) is the first inline image, so the page has
no hero. The GIF (img-2460) is a muted play-once video. No infographic.

Regenerate: python3 wordpress/post_sources/i_screwed_up_co2ut_so_you_dont_have_to.py
"""
from __future__ import annotations

import dataclasses
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
if str(HERE.parent) not in sys.path:
    sys.path.insert(0, str(HERE.parent))

from editorial_shell import Claim  # noqa: E402
import wp_post  # noqa: E402

SLUG = "i-screwed-up-co2ut-so-you-dont-have-to"
SOURCE = wp_post.load(SLUG)
OUTPUT_PATH = wp_post.output_path(SLUG)

ALT = {
    "co2ut-podium-1": "A race podium under a finish-line banner: the winner in a black T-shirt and denim shorts on the top step, a rider in a blue Go4Graham skinsuit on third, and cartoon Gravel God in a cowboy hat photoshopped onto the second step with a cigar in his mouth.",
    "untitled-design-16": "The CO2UT start: a packed field of gravel riders at the line, with cartoon Gravel God's face in a cowboy hat pasted on a rider in red Rio Grande kit.",
    "swedish-engineering": "A black Cervélo gravel bike hangs sideways off a hitch bike rack on a white car at the roadside, its wheel arm sprung open, while cartoon Gravel God in a cowboy hat ponders it, hand on chin.",
    "diesel-daddy-1": "Race photo of a rider in red Rio Grande kit, number 2036, on a dirt road with mountains behind, cartoon Gravel God's face in a cowboy hat pasted over his; another rider follows.",
    "untitled-design-15": "Two teammates lounge on a motel bed, one shirtless with his hands behind his head, the other smiling at his phone, under a framed black-and-white rafting photo; the top of cartoon Gravel God's cowboy hat pokes up in the corner.",
    "img-2460": "Animated: a curly-haired teammate with a moustache, in a black Rio Grande quarter-zip, brushes his teeth in a motel room, then twirls the ends of his moustache.",
    "co2ut-finish": "Rider 2036 in red Rio Grande kit rolls under an inflatable orange-and-blue Grand Junction Sports Commission finish arch, cartoon Gravel God's face in a cowboy hat pasted over his.",
    "missed-podium": "Team Rio Grande 2023 group chat: Zack writes \"@Matti Rowe you missed your podium !!\", Matti answers \"Wut\", Zack: \"Yea 50+ you were second\", then \"Sorry that was a joke I don't know how old you are but yea he called you\", and Tyrel: \"Grvl God\".",
}

DESCRIPTION = ("CO2UT race report: a misbooked hotel, a bike rack that sprang open on I-70, rough cattle-track "
               "gravel, and a 9th place the author learned of driving home.")  # <=160 chars

# Paragraph anchors (first words of the paragraph -> id).
ANCHORS = {
    "What they billed as racing with the dinosaurs": "p-dino-tracks",
    "I threw on the hazards": "p-rack",
    "Sure enough, as soon as we made a left turn": "p-descents",
    "Erin was right.": "p-ninth",
}

# The "In short" rule (wp_post docstring); one section (no headings).
IN_SHORT = (
    Claim("The post says the course&rsquo;s &ldquo;dinosaur tracks&rdquo; were hardened cattle tracks covering about a third of the route.",
          "#p-dino-tracks", "See the passage", 0),
    Claim("On the drive to the race, the author&rsquo;s bike rack sprang open on the highway; the bike stayed on by a partly broken ratchet.",
          "#p-rack", "See the passage", 0),
    Claim("The author, a road racer, describes losing the lead group on the gravel by braking hard into every descent and corner.",
          "#p-descents", "See the passage", 0),
    Claim("He finished 9th overall and placed in his age group, but had already left before the podium ceremony.",
          "#p-ninth", "See the result", 0),
)


def _anchored(body: str) -> str:
    for start, pid in ANCHORS.items():
        needle = f"<p>{start}"
        if body.count(needle) != 1:
            raise ValueError(f"anchor {pid}: {needle!r} found {body.count(needle)} times")
        body = body.replace(needle, f'<p id="{pid}">{start}', 1)
    return body


def render() -> str:
    src = dataclasses.replace(SOURCE, body=_anchored(SOURCE.body))
    return wp_post.render_post(src, alt=ALT, in_short=IN_SHORT, description=DESCRIPTION)


def main() -> None:
    wp_post.write(OUTPUT_PATH, render())


if __name__ == "__main__":
    main()
