"""Imported WordPress post: https://gravelgodcycling.com/i-screwed-up-belgian-waffle-ride-so-you-dont-have-to/

Generated by scripts/wp_post_import.py 1923; the body and metadata
(i-screwed-up-belgian-waffle-ride-so-you-dont-have-to.body.html / .json) are
regenerated by the converter, this file is not. ALT is written from what each
image shows; IN_SHORT follows the "In short" rule in wp_post (neutral, third
person).

The live meta description is kept.
No infographic: the post's numbers (the Double Peak climb, training hours,
sodium) are few and already plain in the text, and the climb's two
descriptions disagree (below), so a chart of it would pick one.

Corrected 2026-10-09 (Matt approved): CORRECTIONS below changes 11,000 ft to "nearly
10,000" (Strava: 9,787 ft) and the final climb's "4 miles" to 4.5; each
entry names its evidence. The page notes the correction at the end.

Regenerate: python3 wordpress/post_sources/i_screwed_up_belgian_waffle_ride_so_you_dont_have_to.py
"""
from __future__ import annotations

import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
if str(HERE.parent) not in sys.path:
    sys.path.insert(0, str(HERE.parent))

from editorial_shell import Claim  # noqa: E402
import wp_post  # noqa: E402

SLUG = "i-screwed-up-belgian-waffle-ride-so-you-dont-have-to"
SOURCE = wp_post.load(SLUG)
OUTPUT_PATH = wp_post.output_path(SLUG)

ALT = {
    "watch-out-im-behind-you-14": "The cut-out, mud-spattered face of a woman rider in a blue-and-yellow helmet, with a speech bubble: \"Watch out! I'm behind you!\"",
    "watch-out-im-behind-you-1-1": "The same mud-spattered woman rider's face, with a speech bubble: \"Hey, could you pull me up to them?\"",
    "hangonb": "A greyscale cartoon Gravel God in a cowboy hat, jaw set, beside the words \"Ready? Hang on.\"",
    "watch-out-im-behind-you-3": "TrainingPeaks file of the race, 7:44:55, 131 mi, 420 TSS, with the route map around Escondido and Ramona; the cursor at 3:43:08 reads 182 bpm, 7.64 mph and 95 °F. Cartoon Gravel God in a cowboy hat says: \"Ow.\"",
    "watch-out-im-behind-you-4": "Cartoon Gravel God in a cowboy hat and short shorts, hand at his mouth, beside a speech bubble: \"Yeah I guess. Got nothing better to do.\"",
    "babes": "Race photo of a small group climbing a road through dry grass, led by two women riders in the drops, one in a teal-and-white kit and braid, one in orange and black.",
    "watch-out-im-behind-you-5": "Paper plates of seasoned fries, a burger and a foil-wrapped hot dog with ketchup on a sidewalk; cartoon Gravel God in a cowboy hat eyes them in profile.",
    "unnamed-1-scaled": "A white race number with a styrofoam helmet tag, #47, still attached, printed with \"Do not wrap number around your head tube\".",
    "watch-out-im-behind-you-6": "A chalkboard headed \"GRAVEL RACING TACTICS\": \"1. Blow every match to stay with the front group. 2. Wisely pace yourself.\" Cartoon Gravel God in a cowboy hat grins beside it.",
    "bwrstaart-scaled": "Riders crowd the start line under the Belgian Waffle Ride arch on a city street at dawn, American flags and tall buildings around them.",
    "watch-out-im-behind-you-7": "Cartoon Gravel God in a cowboy hat sprints out of the saddle beside the words \"F EVERYTHING!!!\"",
    "watch-out-im-behind-you-8": "Cartoon Gravel God in a cowboy hat, speech bubble \"You should see somebody.\", faces a faceless figure in a dark hoodie labelled \"BWR Director\".",
    "leg-twitch-1": "Animated: four close-ups of a rider's calves and legs, tanned to the sock line, twitching and cramping after the race, next to the bike's top tube.",
    "watch-out-im-behind-you-9": "TrainingPeaks file \"BWR\", Sunday July 18, 2021: 7:44:55, 131 mi, 420 TSS; planned 7:00:00, IF planned 0.77 against 0.74 completed, 4161 kJ, a 396 W best 10-minute power, and Fitness 111, Fatigue 138, Form 13 enlarged across it.",
    "img-8865": "A rider in red Rio Grande kit carries his gravel bike up a rocky dirt trail between boulders, other riders following.",
    "whip": "A rider in red Rio Grande kit sits on a curb beside a landscaped strip, his Specialized gravel bike lying on the pavement in front of him.",
    "watch-out-im-behind-you-11": "Cartoon Gravel God in a cowboy hat, hand at his mouth, stands on a desert ridge of bare hills and a lone tree, saying: \"This will help.\"",
    "watch-out-im-behind-you-12": "A spread of raw meats, chicken breasts, sausage coils, ground beef, pork belly and steaks, with cartoon Gravel God in a cowboy hat saying: \"Love the meat sweats.\"",
    "watch-out-im-behind-you-13": "A close-up of a red keyboard key labelled \"send\".",
    "screen-shot-2021-08-11-at-10-13-02-pm": "Strava screenshot of Matti Rowe's ride \"Spiste ikke engang en vaffel\", July 18, 2021, San Marcos, California: 130.68 mi, 7:45:28 moving time, 8:19:37 elapsed, 9,787 ft of climbing, 255 W weighted average power, 4,172 kJ, 16.8 mi/h average.",
}

# The "In short" rule (wp_post docstring); section = 0-based h2 index.
IN_SHORT = (
    Claim("Halfway through, the author pulled Katarina Nash up to the leading women at great cost; after the race she told him she had won.",
          "#after-the-race-i-m-sitting-alone", "See the finish · §02", 1),
    Claim("Before the start, the author misplaced the race&rsquo;s helmet tag, so he expected no official time however well he rode.",
          "#and-then-she-left-me-to-eat-seasoned-meats-on-the-curb-alone", "See the mistake · §02", 1),
    Claim("The author chose to chase the front group rather than pace himself, then spent repeated hard efforts after dropping his chain.",
          "#so-i-chose-route-1-even-after-my-kanza-experience-even-knowi", "See the race · §07", 6),
    Claim("The post advises training at least 10 hours a week for 12 weeks, taking mountain-bike lessons, choosing wider tires when unsure, and a sodium plan.",
          "#how-to-bwr-san-diego", "See the advice · §10", 9),
)


# Figures corrected to match the post's own evidence (Matt, 2026-10-09:
# "Yeah go ahead and fix"). wp_post applies each to the body (old text must
# occur exactly once) and the word-for-word tests apply them to the snapshot.
CORRECTIONS = (
    wp_post.Correction(
        "130 miles with 11,000 feet of climbing",
        "130 miles with nearly 10,000 feet of climbing",
        "the Strava screenshot: 130.68 mi, 9,787 ft"),
    wp_post.Correction(
        "1800 feet in 4 miles",
        "1800 feet in 4.5 miles",
        "the post gives the final climb as 4.5 miles twice"),
)


def render() -> str:
    return wp_post.render_post(SOURCE, corrections=CORRECTIONS, alt=ALT, in_short=IN_SHORT)


def main() -> None:
    wp_post.write(OUTPUT_PATH, render())


if __name__ == "__main__":
    main()
