"""Imported WordPress post: https://gravelgodcycling.com/i-screwed-up-unbound-2024-so-you-dont-have-to/

Generated by scripts/wp_post_import.py 3749; the body and metadata
(i-screwed-up-unbound-2024-so-you-dont-have-to.body.html / .json) are
regenerated by the converter, this file is not. ALT is written from what each
image shows; IN_SHORT follows the "In short" rule in wp_post (neutral, third person).

DESCRIPTION replaces the live meta description ("the mistakes that stack up ...
when heat and hubris collide"): the post describes an early flat, a stolen
bike and an argument for riding for its own sake, not stacked mistakes or heat.

The only heading is "Quotes", so the "In short" links point at paragraph
anchors (ANCHORS). No infographic: the Expectations/Reality cartoon is already
clear, and the post states no data.

Regenerate: python3 wordpress/post_sources/i_screwed_up_unbound_2024_so_you_dont_have_to.py
"""
from __future__ import annotations

import dataclasses
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
if str(HERE.parent) not in sys.path:
    sys.path.insert(0, str(HERE.parent))

from editorial_shell import Claim  # noqa: E402
import wp_post  # noqa: E402

SLUG = "i-screwed-up-unbound-2024-so-you-dont-have-to"
SOURCE = wp_post.load(SLUG)
OUTPUT_PATH = wp_post.output_path(SLUG)

ALT = {
    "trash-1": "Cartoon Gravel God in a cowboy hat lies sprawled on his back in a sunlit, litter-strewn alley beside a row of rusty green dumpsters.",
    "image000005": "Security-camera still photographed off a monitor, timestamped 06-07-2024: a man with a bulging backpack wheels a bike away along a store front lined with stacked cases of bottled water.",
    "image000004": "A second security-camera still off the same monitor: the man, in dark clothes with a backpack, walks along the store front beside the stacked water, bikes leaning against it.",
    "image000003": "A third security-camera still: the man walks toward the camera along the store front; below the monitor, a handwritten note reads \"June 5th 4:53pm - 5:00 pm\".",
    "waxed": "Cartoon Gravel God in a cowboy hat stands with his bike at the foot of a rutted dirt road that climbs straight up a green hillside between wire fences.",
    "hwy-h": "Cartoon Gravel God in a cowboy hat, T-shirt and shorts runs along the shoulder of a two-lane country highway past soybean fields, a farmhouse and a creek, the sun low behind him.",
    "expectations": "Two-panel cartoon. \"Expectations\": cartoon Gravel God rides up a straight, steady slope to a can of Miller Lite. \"Reality\": he tumbles head-first along a wildly looping, up-and-down line to the same can.",
}

DESCRIPTION = ("Unbound 2024: an early flat, 99th place in 10:53, a bike stolen five days later, "
               "and why riding has to be worth more than its results.")

# Paragraph anchors for the "In short" links (the post has one heading).
ANCHORS = {
    "Except I didn’t have it.": "p-flat",
    "I looked up. My bike was gone.": "p-stolen",
    "The thing is, Life is never": "p-j-curve",
    "Because everything external": "p-internal-value",
}

# The "In short" rule (wp_post docstring); section = 0-based h2 index.
IN_SHORT = (
    Claim("The author flatted at mile 29 of Unbound 2024, rode the remaining 175 miles hard, and finished 99th in 10:53.",
          "#p-flat", "See the passage", 0),
    Claim("Five days after the race, the author&rsquo;s bike was stolen from outside a gas station in Boulder.",
          "#p-stolen", "See the passage", 0),
    Claim("The post argues that progress is rarely a steady upward curve, and that bad stretches lasting months are part of the process.",
          "#p-j-curve", "See the passage", 0),
    Claim("It concludes that riding needs internal value, because results alone will not always repay the hours put into it.",
          "#p-internal-value", "See the passage", 0),
)


def _anchored(body: str) -> str:
    for start, pid in ANCHORS.items():
        needle = f"<p>{start}"
        if body.count(needle) != 1:
            raise ValueError(f"anchor {pid}: {needle!r} found {body.count(needle)} times")
        body = body.replace(needle, f'<p id="{pid}">{start}', 1)
    return body


def render() -> str:
    src = dataclasses.replace(SOURCE, body=_anchored(SOURCE.body))
    return wp_post.render_post(src, alt=ALT, in_short=IN_SHORT, description=DESCRIPTION)


def main() -> None:
    wp_post.write(OUTPUT_PATH, render())


if __name__ == "__main__":
    main()
