"""Imported WordPress post: https://gravelgodcycling.com/listening-to-robert-in-silver-city/

Generated by scripts/wp_post_import.py 3694; the body and metadata
(listening-to-robert-in-silver-city.body.html / .json) are regenerated by the
converter, this file is not. ALT is written from what each image shows;
IN_SHORT follows the "In short" rule in wp_post (neutral, third person).

The post has no headings (bold lines only), so "In short" links point at the
bold lines' ids and at paragraph anchors that render() adds (ANCHORS). Text is
unchanged.

The live meta description is kept: it is vague but does not misstate the post.
No infographic: the w/kg figures in the post mix durations and riders, and a
chart of them would claim more precision than the text gives.

Regenerate: python3 wordpress/post_sources/listening_to_robert_in_silver_city.py
"""
from __future__ import annotations

import dataclasses
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
if str(HERE.parent) not in sys.path:
    sys.path.insert(0, str(HERE.parent))

from editorial_shell import Claim  # noqa: E402
import wp_post  # noqa: E402

SLUG = "listening-to-robert-in-silver-city"
SOURCE = wp_post.load(SLUG)
OUTPUT_PATH = wp_post.output_path(SLUG)

ALT = {
    "are-you-all-alive-1": "Black-and-white group photo at a Tour of the Gila finish: riders in Rio Grande kit, one with cartoon Gravel God's face in a cowboy hat, stand with an older couple and a man in jeans beside a bike numbered 105, pine hills behind.",
    "cancelled": "The faded Silver City's Tour of the Gila, powered by SRAM, logo of a cyclist on a time-trial bike, with \"CANCELED\" across it in glowing red neon letters.",
    "losers": "A downtown street race lined with spectators and brick storefronts: a field of riders in red approaches, and cartoon Gravel God in a cowboy hat rides ahead of them, saying \"LOSERS!\"",
    "keanu-reeves-1680-x-1137-px": "Keanu Reeves sits alone on a park bench beside a paper bag, looking down; cartoon Gravel God in a cowboy hat stands at the right, watching him.",
    "robert-roberting": "An older man in a yellow shirt and khakis leans into the open back doors of a white Rio Grande team van parked on gravel while a rider in an orange T-shirt waits; cartoon Gravel God in a cowboy hat stands at the right.",
}

ANCHORS = {
    "Nope – the reason was that many had bad": "p-locals",
    "But for thirty minutes – guaranteed": "p-robert",
}

# The "In short" rule (wp_post docstring); one section (no headings).
IN_SHORT = (
    Claim("The post says rumors after 2022 held that Silver City might drop the Tour of the Gila because locals found the riders rude.",
          "#p-locals", "See the passage", 0),
    Claim("It argues that riders in the UCI 2.2 Gila field are slow next to World Tour riders, so their self-importance has no basis.",
          "#you-re-not-that-fast", "See the argument", 0),
    Claim("It holds that racing culture cannot be fixed, but individual riders can be polite and approachable with locals.",
          "#can-this-be-fixed", "See the argument", 0),
    Claim("The post closes with the team&rsquo;s 76-year-old host, Robert, and argues that listening to his stories mattered more than any result.",
          "#p-robert", "See the passage", 0),
)


def _anchored(body: str) -> str:
    for start, pid in ANCHORS.items():
        needle = f"<p>{start}"
        if body.count(needle) != 1:
            raise ValueError(f"anchor {pid}: {needle!r} found {body.count(needle)} times")
        body = body.replace(needle, f'<p id="{pid}">{start}', 1)
    return body


def render() -> str:
    src = dataclasses.replace(SOURCE, body=_anchored(SOURCE.body))
    return wp_post.render_post(src, alt=ALT, in_short=IN_SHORT)


def main() -> None:
    wp_post.write(OUTPUT_PATH, render())


if __name__ == "__main__":
    main()
