"""Imported WordPress post: https://gravelgodcycling.com/maybe-stop-sandbagging-your-goals/

Generated by scripts/wp_post_import.py 2927; the body and metadata
(maybe-stop-sandbagging-your-goals.body.html / .json) are regenerated by the
converter, this file is not. ALT is written from what each image shows;
IN_SHORT follows the "In short" rule in wp_post (neutral, third person).

The live meta description is accurate and kept.

Infographic (2026-10-09): fig-steps, the post's two-path step chart
(Lars-did-you-know-were-all-going-to-die-3.png) redrawn as two SVG panels with
draw-in. Levels are the original chart's: both paths start at level 1; one
goes 2, 1, 2 (forward, backward, forward), the other 2, 3, 4. The original
image stays one click away under the chart.

Corrected 2026-10-09 (Matt approved): CORRECTIONS below changes "the same place" to where
the first year got you (the chart ends one level up); each
entry names its evidence. The page notes the correction at the end.

Regenerate: python3 wordpress/post_sources/maybe_stop_sandbagging_your_goals.py
"""
from __future__ import annotations

import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
if str(HERE.parent) not in sys.path:
    sys.path.insert(0, str(HERE.parent))

from editorial_shell import Claim  # noqa: E402
import wp_post  # noqa: E402
from wp_post import HtmlFigure  # noqa: E402

SLUG = "maybe-stop-sandbagging-your-goals"
SOURCE = wp_post.load(SLUG)
OUTPUT_PATH = wp_post.output_path(SLUG)

ALT = {
    "lars-did-you-know-were-all-going-to-die": "A girl in a Halloween costume and a small boy in an orange coat walk a dirt road through a new housing development at sunset; cartoon Gravel God in a cowboy hat and black suit stands beside them, and the girl's speech bubble reads: \"Lars, did you know we're all going to die?\"",
    "2023": "A shirtless man in jeans and work gloves, his face a cartoon Gravel God in a cowboy hat, splits logs beside a huge woodpile, with \"2023\" in glowing red neon numerals on the stump in front of him.",
    "lars-did-you-know-were-all-going-to-die-1": "A handwritten list on lined notebook paper titled \"Goals 2023\": \"Maybe finish a few races\", \"Live, laugh, love\", \"Push through 'ouchie' feelings\", \"Only miss two workouts a week\".",
    "redacted": "A greyed-out TrainingPeaks Performance Management Chart, \"Last Year, Last 365 days\", from late 2021 to October 2022: TSS per day and form (TSB) traces, with fitness building to about 65 TSS/d in spring and early summer and sliding to about 30 at several breaks.",
    "lars-did-you-know-were-all-going-to-die-2": "Cartoon Gravel God in a cowboy hat, hand on chin, in front of a chalkboard, with a thought bubble: \"DNF? DFL? How do I get slower?\"",
    "lars-did-you-know-were-all-going-to-die-3": "Two step charts of level against year, with cartoon Gravel God standing on the last step of each. Left: from level 1 the steps go up to 2, down to 1, and up to 2 over three years. Right: they climb 2, 3, 4.",
    "untitled-design-2": "A grey, surreal image of a human figure built entirely of clock faces, with clocks breaking off and floating away from its shoulder, beside a faded profile of cartoon Gravel God in a cowboy hat.",
}

# ── fig-steps: the post's step chart, redrawn ────────────────
# Levels as the original chart shows them; year 0 = the start.
PATHS = (
    ("Forward, backward, forward", (1, 2, 1, 2), "is-zig"),
    ("Forward, forward, forward", (1, 2, 3, 4), "is-up"),
)
TOP = 4


def _panel(title: str, levels: tuple[int, ...], cls: str) -> str:
    w, h, left, base, step = 300, 210, 34, 180, 38
    bw = (w - left - 8) / len(levels)
    grid = "".join(
        f'<line x1="{left}" x2="{w}" y1="{base - lv * step}" y2="{base - lv * step}" class="st-grid"/>'
        f'<text x="{left - 10}" y="{base - lv * step + 5}" text-anchor="end" class="st-tick">{lv}</text>'
        for lv in range(1, TOP + 1))
    bars = "".join(
        f'<rect x="{left + i * bw + 3:.1f}" y="{base - lv * step}" width="{bw - 6:.1f}" height="{lv * step}" '
        f'class="st-bar{" is-start" if i == 0 else ""}" data-draw="grow" style="--draw-i:{i}"/>'
        for i, lv in enumerate(levels))
    xs = "".join(
        f'<text x="{left + i * bw + bw / 2:.1f}" y="{base + 22}" text-anchor="middle" class="st-tick">'
        f'{"Start" if i == 0 else f"Year {i}"}</text>' for i in range(len(levels)))
    end = (f'<text x="{left + (len(levels) - 0.5) * bw:.1f}" y="{base - levels[-1] * step - 8}" '
           f'text-anchor="middle" class="st-end" data-draw="fade" style="--draw-i:{len(levels)}">'
           f'Level {levels[-1]}</text>')
    label = f"{title}: levels {', '.join(map(str, levels))}"
    return (f'<div class="st-panel {cls}"><p class="st-h">{title}</p>'
            f'<svg viewBox="0 -14 {w} {h + 26}" role="img" aria-label="{label}">'
            f'{grid}<line x1="{left}" x2="{w}" y1="{base}" y2="{base}" class="st-axis"/>{bars}{xs}{end}</svg></div>')


STEPS_FIGURE = HtmlFigure(
    id="fig-steps",
    kicker="The post’s chart, redrawn",
    title="Three years, two paths",
    html=f'<div class="st-panels">{"".join(_panel(*p) for p in PATHS)}</div>',
    caption_html=("Levels as in the post&rsquo;s chart: both paths start at level 1. "
                  "After three years the second path is two levels higher (4 against 2)."),
)

CSS = """
.st-panels{display:grid;grid-template-columns:1fr 1fr;gap:22px}
@media (max-width:640px){.st-panels{grid-template-columns:1fr;gap:14px}}
.st-panel{display:flex;flex-direction:column}
.st-panel svg{margin-top:auto}
.st-h{font:700 14px var(--mono);color:var(--ink);margin:0 0 4px}
.st-grid{stroke:var(--sand2);stroke-width:1;stroke-dasharray:4 4}
.st-axis{stroke:var(--ink3);stroke-width:1.5}
.st-bar{fill:var(--ink3)}
.st-bar.is-start{fill:var(--sand2)}
.st-panel.is-up .st-bar:not(.is-start){fill:var(--teal)}
.st-tick{font-size:12px;fill:var(--ink3)}
.st-end{font-size:13px;font-weight:700;fill:var(--ink)}
"""

# The "In short" rule (wp_post docstring); section = 0-based h2 index.
IN_SHORT = (
    Claim("The post challenges riders to replace finish-only goals with a result goal that scares them, such as a top 100 at Unbound 200.",
          "#here-s-my-challenge-whatever-you-want-out-of-racing-bikes-in", "See the challenge · §02", 1),
    Claim("The post argues that fitness potential falls with each decade of age, so the window to chase it is small.",
          "#here-s-my-challenge-whatever-you-want-out-of-racing-bikes-in", "See §02", 1),
    Claim("Using one athlete&rsquo;s training chart, the post argues that illness, family and work can derail even a consistent rider&rsquo;s year.",
          "#wrong", "See the example · §03", 2),
    Claim("The post says three years of forward, backward, forward leave a rider two levels behind three straight years of progress.",
          "#fig-steps", "See the chart · §03", 2),
)


# Figures corrected to match the post's own evidence (Matt, 2026-10-09:
# "Yeah go ahead and fix"). wp_post applies each to the body (old text must
# occur exactly once) and the word-for-word tests apply them to the snapshot.
CORRECTIONS = (
    wp_post.Correction(
        "only to end up at the same place.",
        "only to end up where your first year got you.",
        "the post's chart (and the steps) go 1, 2, 1, 2: three years end one level up, where year one ended"),
)


def render() -> str:
    return wp_post.render_post(SOURCE, corrections=CORRECTIONS, alt=ALT, in_short=IN_SHORT,
                               replace={"lars-did-you-know-were-all-going-to-die-3": STEPS_FIGURE},
                               replace_label="Show the original chart (with Gravel God)", extra_css=CSS)


def main() -> None:
    wp_post.write(OUTPUT_PATH, render())


if __name__ == "__main__":
    main()
