"""Imported WordPress post: https://gravelgodcycling.com/maybe-a-hate-poster-is-what-youve-been-missing/

Generated by scripts/wp_post_import.py 3945; the body and metadata
(maybe-a-hate-poster-is-what-youve-been-missing.body.html / .json) are
regenerated by the converter, this file is not. ALT is written from what each
image shows; IN_SHORT follows the "In short" rule in wp_post (neutral, third
person).

The live meta description is kept (it matches the post). The repeated
"Stalk and Arrange" paragraphs are in the WordPress post itself and stay.
No infographic.
Matt to read: the text describes "a collage with five squares" with one larger
square in the middle, but the poster image shows nine round avatars in a 3x3
grid.

Regenerate: python3 wordpress/post_sources/maybe_a_hate_poster_is_what_youve_been_missing.py
"""
from __future__ import annotations

import dataclasses
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
if str(HERE.parent) not in sys.path:
    sys.path.insert(0, str(HERE.parent))

from editorial_shell import Claim  # noqa: E402
import wp_post  # noqa: E402

SLUG = "maybe-a-hate-poster-is-what-youve-been-missing"
SOURCE = wp_post.load(SLUG)
OUTPUT_PATH = wp_post.output_path(SLUG)

ALT = {
    "hater-poster-scaled": "A mock hater poster: nine round grey placeholder avatars in a three-by-three grid, men and women drawn as faceless silhouettes, two of them with drawn faces.",
    "youll-never-amount-to-anything-and-your-exes-are-right": "A roadside marquee sign on a sunny day reading \"You'll never amount to anything and your exes are right.\"",
}

ANCHORS = {
    "If you think there’s a ‘just kidding’": "p-serious",
}

# The "In short" rule (wp_post docstring); section = 0-based h2 index.
IN_SHORT = (
    Claim("The post proposes a ten-minute &ldquo;grievance archeology&rdquo; session listing at least ten people who wronged, doubted or dismissed the reader.",
          "#1-grievance-archeology", "See §01", 0),
    Claim("It then describes a five-photo collage with the most resented face placed largest in the middle.",
          "#2-stalk-and-arrange", "See §02", 1),
    Claim("The author calls the advice serious though probably irresponsible, and says pettiness motivates many athletes more than lofty ideals.",
          "#p-serious", "See the passage · §03", 2),
)


def _anchored(body: str) -> str:
    for start, pid in ANCHORS.items():
        needle = f"<p>{start}"
        if body.count(needle) != 1:
            raise ValueError(f"anchor {pid}: {needle!r} found {body.count(needle)} times")
        body = body.replace(needle, f'<p id="{pid}">{start}', 1)
    return body


def render() -> str:
    src = dataclasses.replace(SOURCE, body=_anchored(SOURCE.body))
    return wp_post.render_post(src, alt=ALT, in_short=IN_SHORT)


def main() -> None:
    wp_post.write(OUTPUT_PATH, render())


if __name__ == "__main__":
    main()
