"""Imported WordPress post: https://gravelgodcycling.com/no-one-cares-if-youre-bored/

Generated by scripts/wp_post_import.py 2394; the body (no-one-cares-if-youre-bored.body.html) and
metadata (no-one-cares-if-youre-bored.json) are regenerated by the converter, this file is not.
ALT is written from what each image shows. IN_SHORT is a DRAFT for Matt's
read: plain, third-person statements of what the post argues, each one
supported by the post text. No infographic: the post states no figures.

The post has no headings (one section), so the "In short" links point at the
image that opens each part of the argument (racing, training, the payoff).

Regenerate: python3 wordpress/post_sources/no_one_cares_if_youre_bored.py
"""
from __future__ import annotations

import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
if str(HERE.parent) not in sys.path:
    sys.path.insert(0, str(HERE.parent))

from editorial_shell import Claim  # noqa: E402,F401
import wp_post  # noqa: E402

SLUG = "no-one-cares-if-youre-bored"
SOURCE = wp_post.load(SLUG)
OUTPUT_PATH = wp_post.output_path(SLUG)

ALT = {
    "um-no": "A speaker at a lectern addresses a seated audience: \"Thou shalt NEVER be bored!\" In the crowd, a cartoon Gravel God in a cowboy hat answers: \"Um...No\".",
    "really": "Photo of riders in red Rio Grande kits in a road race. One rider says \"F**K it. I'm going to send it.\" while the bearded rider beside him replies \"Really???\"",
    "volcano": "A laptop shows a planned workout: 1:05:00 planned, 0:20:00 done, TSS 41, IF 0.62, a steady Z2 description, and the post-activity comment \"I'm bored\". Beside it, a cartoon Gravel God stares with a volcano erupting behind his head.",
    "boredom": "A boy in a superhero mask and cape reaches up; cartoon Gravel God asks him \"What is your superpower?\" and the boy answers \"Boredom.\"",
    "1": "Cartoon Gravel God in a cowboy hat rides alone down an empty, straight desert highway toward distant buttes, a thought bubble above him holding a TV, a beer can, cheese, books and a cheering crowd.",
}

# DRAFT for Matt: matter-of-fact statements of what the post argues;
# section = 0-based h2 index (the post has one section).
IN_SHORT = (
    Claim("The post argues that patience in a race, sitting on wheels and waiting for the decisive moment, depends on tolerating boredom.",
          "#fig-um-no", "See the racing argument", 0),
    Claim("It holds that endurance training is repetitive by nature, so boredom is no reason to skip or cut short a workout.",
          "#fig-volcano", "See the training argument", 0),
    Claim("It says fearing boredom is worse than boredom itself, and that accepting it makes long rides, and daily life, easier.",
          "#fig-boredom", "See the payoff", 0),
)


def render() -> str:
    return wp_post.render_post(SOURCE, alt=ALT, in_short=IN_SHORT)


def main() -> None:
    wp_post.write(OUTPUT_PATH, render())


if __name__ == "__main__":
    main()
