"""Imported WordPress post: https://gravelgodcycling.com/5-ways-to-become-a-power-meter-clown/

Generated by scripts/wp_post_import.py 1626; the body (5-ways-to-become-a-power-meter-clown.body.html) and
metadata (5-ways-to-become-a-power-meter-clown.json) are regenerated by the converter, this file is not.
Hand-edit ALT (one entry per image, written from what the image shows),
IN_SHORT (drafts restate the post's own words) and any infographics.

IN_SHORT (2026-10-09): matter-of-fact restatements for Matt's read.

Infographic (2026-10-09): fig-power-meters, the post's own example readings
(one rider, every meter fitted at once: 20-minute and 30-second efforts) as a
table, so the flip in order between the two efforts is visible. Values exactly
as the text gives them; the Garmin Vectors get no number in the post, so they
are left out. Placed after the paragraph with the 30-second readings.

DESCRIPTION replaces the live meta description, which listed "chasing FTP"
among the mistakes; the post's five are comparing watts between riders,
trusting a split-second reading, staring at the stem on Z2 rides, reading a
Strava PR as a win, and racing by power (plus a bonus: watts as a pickup line).

The post has 20 sections; the shell's phone Contents bar handles 10+ sections
itself, so this page carries no CSS of its own.

Regenerate: python3 wordpress/post_sources/post_5_ways_to_become_a_power_meter_clown.py
"""
from __future__ import annotations

import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
if str(HERE.parent) not in sys.path:
    sys.path.insert(0, str(HERE.parent))

from editorial_shell import Claim, DataTable, TableCell, TableColumn, TableRow  # noqa: E402
import wp_post  # noqa: E402

SLUG = "5-ways-to-become-a-power-meter-clown"
SOURCE = wp_post.load(SLUG)
OUTPUT_PATH = wp_post.output_path(SLUG)

ALT = {
    "power-meter-clown": "A clown in a red and yellow costume stands on a gravel road under a blue sky, a speech bubble full of power-meter crank arms and exclamation marks; cartoon Gravel God in his cowboy hat stands across from him.",
    "droppedbutpowernumbers": "A race results list (Men SM 1-2) with one row near the bottom highlighted, under a training-app summary of \"Boulder Roubaix\": 2:32:08, 48.7 mi, 151 TSS, peak 393 W 5-min power. Cartoon Gravel God grins: \"Sure, I was 39/85 racers, but look at my power numbers!\"",
    "power-meter-clown-1": "A face in clown make-up with a red nose and rainbow wig peers through torn cardboard, holding an SRM power-meter crank and an SRM head unit, and says: \"Heyyy.... Anyone want to hear how many watts I can put out?!?!\"",
    "power-meter-clown-2": "A recipe notebook among baking things, titled \"Watt Clown Cake\": \"1. Look at someone's file on Strava, usually a Pro. 2. See how many watts they held. 3. Realize you've once held the same or nearly the same watts. 4. Since you can do, or almost do what they did, that makes you pro. 5. Actually, maybe it makes you better than them.\" Cartoon Gravel God strokes his beard at the right.",
    "wat": "Animated: a wide-eyed fluffy cat against a swirling green background, captioned \"WAT\".",
    "power-meter-clown-3": "Three archery targets labelled SRM, STAGES and Garmin, each with a dart at a different distance from the bullseye, above the line: \"Accuracy - how close is your power value to the true power value.\"",
    "power-meter-clown-4": "A Jeopardy! stage: a contestant in a suit at a podium showing $14,400, the podium screens asking for \"the circumstance in which the variability of a variable is unequal across the range of values of a second variable that predicts it\"; cartoon Gravel God answers: \"What is heteroskedasticity, just the way your mother likes it Trebeck!\"",
    "power-meter-clown-5": "Three targets: \"Precise, not accurate\" (darts clustered together off the bullseye), \"Not Precise, nor accurate\" (darts scattered) and \"Precise and accurate\" (darts clustered on the bullseye), above: \"Precision - the numbers have similar accuracy test after test.\"",
    "so-the-numbers-are-just-made-up-and-im-better-off-selling-the-power-meter-and-making-up-numbers": "A toddler in a blue puffer jacket grins beside a car's rear bike rack and asks: \"So the numbers are just made up, and I'm better off selling the power meter and making up numbers?\"",
    "500-watts": "Animated: a rider's view over the handlebars on a rough road, a Garmin head unit reading 500 between two flashing yellow lightning bolts.",
    "power-meter-clown-6": "Cartoon Gravel God, in an argyle sweater, turns to a man in a pink shirt and says: \"I think they're all on steroids.\"",
    "what-cha-looking-at": "Cartoon Gravel God rides a gravel road past tall chalk rock formations while a pro rider in a white team kit rides beside him, head down toward his stem; Gravel God asks: \"What cha looking at?\"",
    "chris-froome-pinnochio": "Animated: a cut-out photo of Chris Froome's smiling face whose nose grows long like Pinocchio's.",
    "power-meter-clown-7": "Cartoon Gravel God points at the text: \"Because most training isn't you, three mountain passes in, with perfect knowledge of the power you need to put out to destroy your rivals. It's a Zone 2 ride.\"",
    "nothing-to-see-here": "A small cartoon Gravel God rides a coastal road along a cliff above a wide, hazy ocean bay and says: \"Nothing to see here.\"",
    "process-of-delusion": "A chalkboard beside cartoon Gravel God, a cigar in his mouth: \"1. Get in fantastic shape. 2. Confirm it by putting out lots of watts on your favorite Strava segment. 3. Secretly delude yourself into believing that your PR means you will automatically win the next race in domineering style.\"",
    "power-meter-clown-8": "A dark alley with a bright door. A cartoon boy asks: \"Hey, what's a sandbagger?\" Cartoon Gravel God answers: \"Someone who races below their ability level so they have a greater chance of winning. Now get out of here.\"",
    "power-meter-clown-1-1": "Cartoon Gravel God pops a wheelie over an open manhole on a city road, saying: \"Not today Sucka!\"",
    "power-meter-clown-2-1": "Cartoon Gravel God, seen from behind, rides at the back of a group of gravel racers in a dusty, sunlit desert and says: \"Perfect! Everyone is in front of me! Now I will show them how many watts I can put out!\"",
    "im-pretty-much-a-pro-cyclist-i-can-push-400-watts-for-like-20-minutes": "A smiling woman at a bar listens as cartoon Gravel God, seen from behind in his cowboy hat, says: \"I'm pretty much a pro cyclist. I can push 400 watts for like 20 minutes.\"",
    "im-pretty-much-a-pro-cyclist-i-can-push-400-watts-for-like-20-minutes-1": "A doctor in a white coat tells cartoon Gravel God: \"Best we can tell, your date died of a stroke because you talked about your watts too much.\"",
    "im-pretty-much-a-pro-cyclist-i-can-push-400-watts-for-like-20-minutes-2": "A whiteboard list: \"1. No one outside cycling and light-bulb users even knows what a watt is. 2. If they do, and how it applies to cycling, you're still only useful in a sport that 99% of people don't care about. 3. At best, referencing watts will segue into the 'why do you shave your legs' conversation, and no one wins that one.\"",
    "2021-03-11-17-40-13-1": "Animated: Joey from the TV show Friends, in a plaid shirt, grins and says: \"How you doin'?\"",
}

# Matter-of-fact restatements; section = 0-based h2 index.
IN_SHORT = (
    Claim("Power meters disagree with each other, and by different amounts at different powers, so one rider&rsquo;s watts cannot be compared directly with another&rsquo;s.",
          "#fig-power-meters", "See the readings · §04", 3),
    Claim("A meter need not be perfectly accurate; what matters for measuring progression is precision, reading nearly the same for the same effort day to day.",
          "#wrong", "See §07", 6),
    Claim("A one-second number glimpsed while getting dropped is not the effort&rsquo;s power: in the post&rsquo;s example, the rider saw 500 watts and averaged 287.",
          "#500-500-500-200-300-500-250-300-270-2-minutes-later-250-200-", "See §09", 8),
    Claim("In races, the post recommends hiding the power field and building race feel: reading the bunch, finding the draft and anticipating attacks.",
          "#5-racing-by-power", "See §15", 14),
)

# ── fig-power-meters: the post's example readings as a table ─
# Every value is a number the post's text states. Nothing is derived.
POWER_METERS = DataTable(
    id="fig-power-meters",
    kicker="The readings above, side by side",
    title="Same efforts, three power meters",
    intro_html="The post&rsquo;s example: one rider with every power meter fitted at once.",
    footnote_html=("Watts as the post gives them. The SRM reads in the middle on the 20-minute effort "
                   "and highest on the 30-second one. The Garmin Vectors get no number in the post."),
    columns=(
        TableColumn("Power meter", card="title", sortable=False),
        TableColumn("20-minute effort", kind="num", card="fact"),
        TableColumn("30-second effort", kind="num", card="fact"),
    ),
    rows=(
        TableRow(cells=(TableCell("SRM"), TableCell("280 W", sort=280), TableCell("500 W", sort=500))),
        TableRow(cells=(TableCell("Stages"), TableCell("310 W", sort=310), TableCell("460 W", sort=460))),
        TableRow(cells=(TableCell("PowerTap"), TableCell("270 W", sort=270), TableCell("480 W", sort=480))),
    ),
    after="splits the difference at 480.</p>",
)


DESCRIPTION = ("Five power-meter mistakes: comparing watts between riders, trusting one-second readings, "
               "watching watts on easy rides, banking on a Strava PR, racing by power.")


def render() -> str:
    return wp_post.render_post(SOURCE, alt=ALT, in_short=IN_SHORT, figures=(POWER_METERS,),
                              description=DESCRIPTION)


def main() -> None:
    wp_post.write(OUTPUT_PATH, render())


if __name__ == "__main__":
    main()
