"""Imported WordPress post: https://gravelgodcycling.com/random-midweek-thought-stay-present/

Generated by scripts/wp_post_import.py 3791; the body and metadata
(random-midweek-thought-stay-present.body.html / .json) are regenerated by the
converter, this file is not. ALT is written from what the image shows; IN_SHORT
follows the "In short" rule in wp_post (neutral, third person). A 460-word post:
two claims.

The post has no headings, so "In short" links point at paragraph anchors that
render() adds (ANCHORS: the paragraph's opening words -> id). Text is unchanged.

DESCRIPTION replaces the live meta description ("why chasing future fitness
ruins the ride you're on"): the post never mentions future fitness; it applies
a yoga teacher's cue to a hot interval session and to attention in general.

No infographic.

Regenerate: python3 wordpress/post_sources/random_midweek_thought_stay_present.py
"""
from __future__ import annotations

import dataclasses
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
if str(HERE.parent) not in sys.path:
    sys.path.insert(0, str(HERE.parent))

from editorial_shell import Claim  # noqa: E402
import wp_post  # noqa: E402

SLUG = "random-midweek-thought-stay-present"
SOURCE = wp_post.load(SLUG)
OUTPUT_PATH = wp_post.output_path(SLUG)

ALT = {
    "stay-present": "A sunlit yoga studio with mats laid across a wooden floor, plants on the windowsills, and a cartoon Gravel God in a cowboy hat and denim shorts standing in the middle holding his road bike.",
}

ANCHORS = {
    "But then Kevin’s words drifted back to me": "p-kevin",
    "The tendency to join with every thought": "p-tendency",
}

DESCRIPTION = ("A yoga teacher's cue to stay present, applied to a hot interval session "
               "and to attention off the bike.")

# The "In short" rule (wp_post docstring); no headings, so section 0.
IN_SHORT = (
    Claim("A yoga teacher&rsquo;s cue to stay present returns to the author during a third set of intervals in 96F heat, when he considers stopping.",
          "#p-kevin", "See the passage", 0),
    Claim("The post argues that joining every passing thought, made worse by smartphones, leaves people numb to what they are doing and feeling now.",
          "#p-tendency", "See the passage", 0),
)


def _anchored(body: str) -> str:
    for start, pid in ANCHORS.items():
        needle = f"<p>{start}"
        if body.count(needle) != 1:
            raise ValueError(f"anchor {pid}: {needle!r} found {body.count(needle)} times")
        body = body.replace(needle, f'<p id="{pid}">{start}', 1)
    return body


def render() -> str:
    src = dataclasses.replace(SOURCE, body=_anchored(SOURCE.body))
    return wp_post.render_post(src, alt=ALT, in_short=IN_SHORT, description=DESCRIPTION)


def main() -> None:
    wp_post.write(OUTPUT_PATH, render())


if __name__ == "__main__":
    main()
