"""Imported WordPress post: https://gravelgodcycling.com/right-now-i-cant/

Generated by scripts/wp_post_import.py 3825; the body and metadata
(right-now-i-cant.body.html / .json) are regenerated by the converter, this
file is not. ALT is written from what each image shows; IN_SHORT follows the
"In short" rule in wp_post (neutral, third person).

The post has no headings, so "In short" links point at paragraph anchors that
render() adds (an id on the <p>; the text is unchanged).

DESCRIPTION replaces the live meta description ("Cycling injury recovery:
dealing with setbacks, burnout, or life disruptions... It's temporary"): the
post is about a lung illness after COVID, not an injury, and it doesn't argue
that it's temporary.

The featured image (never-see-it-coming) is the first inline image, so the page
has no hero. No infographic.

Regenerate: python3 wordpress/post_sources/right_now_i_cant.py
"""
from __future__ import annotations

import dataclasses
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
if str(HERE.parent) not in sys.path:
    sys.path.insert(0, str(HERE.parent))

from editorial_shell import Claim  # noqa: E402
import wp_post  # noqa: E402

SLUG = "right-now-i-cant"
SOURCE = wp_post.load(SLUG)
OUTPUT_PATH = wp_post.output_path(SLUG)

ALT = {
    "never-see-it-coming": "A yellow-and-blue train blurs through a Dutch level crossing, barriers down and \"WACHT\" signs lit, while a tiny cartoon Gravel God in a cowboy hat stands beside the tracks.",
    "rontagen": "A cartoon chest X-ray: pale blue ribs on a dark blue background, with six Miller Lite cans where the lungs should be.",
    "already-got-my-cardio-for-the-day-1": "Cartoon Gravel God in a cowboy hat stands at the foot of a white staircase in a bright hallway, saying: \"Already got my cardio for the day.\"",
    "already-got-my-cardio-for-the-day-1-2": "Four puppies peer over a concrete ledge at cartoon Gravel God in a cowboy hat, seen from behind, who tells them: \"I'm telling you – life is a sham. Love doesn't exist and I wouldn't get your hopes up that anyone is going to adopt you.\"",
}

DESCRIPTION = ("An essay on weeks off the bike with inflamed lungs after COVID: an X-ray, steroids, "
               "a CTL down 50 points, and what the author misses about training.")

# Paragraph anchors (first words of the paragraph -> id).
ANCHORS = {
    "Standing in the doctor’s office": "p-xray",
    "I have training data in TrainingPeaks": "p-twelve-years",
    "And there’s the upshot there": "p-upshot",
}

# The "In short" rule (wp_post docstring); one section (no headings).
IN_SHORT = (
    Claim("The author describes weeks without training after an X-ray showed inflamed lungs, an illness that arrived weeks after COVID.",
          "#p-xray", "See the passage", 0),
    Claim("The post says that in 12 years of TrainingPeaks data the author had never gone two weeks without training.",
          "#p-twelve-years", "See the passage", 0),
    Claim("Unable to train, the author says his family has filled the space, though he still misses the hardship of training.",
          "#p-upshot", "See the passage", 0),
)


def _anchored(body: str) -> str:
    for start, pid in ANCHORS.items():
        needle = f"<p>{start}"
        if body.count(needle) != 1:
            raise ValueError(f"anchor {pid}: {needle!r} found {body.count(needle)} times")
        body = body.replace(needle, f'<p id="{pid}">{start}', 1)
    return body


def render() -> str:
    src = dataclasses.replace(SOURCE, body=_anchored(SOURCE.body))
    return wp_post.render_post(src, alt=ALT, in_short=IN_SHORT, description=DESCRIPTION)


def main() -> None:
    wp_post.write(OUTPUT_PATH, render())


if __name__ == "__main__":
    main()
