"""Imported WordPress post: https://gravelgodcycling.com/since-no-one-asked-why-did-dumoulin-retire-he-just-wants-to-eat-some-cheese-2/

Generated by scripts/wp_post_import.py 1230; the body and metadata
(since-no-one-asked-why-did-dumoulin-retire-he-just-wants-to-eat-some-cheese-2.body.html / .json)
are regenerated by the converter, this file is not. ALT is written from what each
image shows; IN_SHORT is a DRAFT for Matt's read (plain statements of what the
post says, each linking to its section).

Post 1186 (the same title without "-2") did not convert: its snapshot has an
Elementor slides widget the converter has no mapping for.

Infographic (2026-10-09): fig-phenotypes, the post's chalkboard "Phenotypes" chart
(phenotypes.png) redrawn as four small SVG panels with a draw-in. The original
is schematic (no scale on either axis), so the redraw is too: each curve's corners
were read off the original by eye, in 0-1 plot units. The line under each panel
is the post's own description of that rider type. The original image (with
Gravel God's "Guilty as charged!") stays one click away under the chart.

Regenerate: python3 wordpress/post_sources/since_no_one_asked_why_did_dumoulin_retire_he_just_wants_to_eat_some_cheese_2.py
"""
from __future__ import annotations

import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
if str(HERE.parent) not in sys.path:
    sys.path.insert(0, str(HERE.parent))

from editorial_shell import Claim  # noqa: E402
import wp_post  # noqa: E402
from wp_post import HtmlFigure  # noqa: E402

SLUG = "since-no-one-asked-why-did-dumoulin-retire-he-just-wants-to-eat-some-cheese-2"
SOURCE = wp_post.load(SLUG)
OUTPUT_PATH = wp_post.output_path(SLUG)

ALT = {
    "ftp-invitational-5": "The letters FTP, wearing a gold crown, stand on top of the tallest column of a podium built from wooden blocks.",
    "phenotypes": "Chalkboard chart titled \"Phenotypes\": four sketches of power against duration. Sprinter: very high power that drops off almost at once. Pursuiter: high power held a little longer, then a steep drop. Allrounder: moderate power that steps down gradually. Time trialist: lower peak power that levels off into a long, high plateau; cartoon Gravel God on a bike says \"Guilty as charged!\"",
    "holy-ftp": "A black book titled \"the Holy FTP\", with cartoon Gravel God in a cowboy hat beside it saying: \"Bend the knee.\"",
    "ftp-invitational-3": "A crowded beer hall. A faceless rider in a black-and-green kit says: \"My FTP is 450*, what's yours? Also, what is your genital size?\" Cartoon Gravel God answers: \"Sick! That's super high. Yeah, last time I checked, mine was 570. Also, what? It's so loud in here!\"",
    "ftp-invitational-4": "A pub bar with beer taps. The faceless rider says: \"What's your FTP? Mine is 450 - I saw it on my Garmin once.\" Cartoon Gravel God answers: \"Sick! What's your FRC tho? Mine is 55 kjs. FTP isn't everything, bro!\"",
    "ftp-invitational-2": "A red, orange and yellow comic explosion with stars and the words: \"FTP still matters a HELL of a lot!\"",
    "ftp-invitational-1": "\"FTP Invitational\": a staircase of poker tables rising from \"CAT 5\" through \"CAT 4>3\", \"CAT 3>2\", \"CAT 2>1\", \"Bad Pro\" and \"Good Pro\" to \"Bad WT\" and \"Good WT\". Cartoon Gravel God says: \"Your FTP determines what poker table you're playing at. Your FRC determines how you play at the table.\"",
}

# DRAFT for Matt: plain statements of what the post says; section = 0-based h2 index.
IN_SHORT = (
    Claim("Tools such as WKO and Golden Cheetah read a rider&rsquo;s phenotype (sprinter, pursuiter, all-rounder or time trialist) from their power duration curve.",
          "#fig-phenotypes", "See the phenotypes · Intro", 0),
    Claim("Anaerobic metrics, FRC in WKO and W&rsquo; in Golden Cheetah, shifted attention away from FTP after 15 years of focus on it.",
          "#fig-ftp-invitational-4", "See the shift · Intro", 0),
    Claim("The post argues FTP still decides which level a rider can compete at, while FRC decides how they race at that level.",
          "#but", "See BUT... · §01", 0),
)

# ── fig-phenotypes: the chalkboard chart, redrawn ────────────
# Corners of each curve in plot units (x = duration, y = power), read off the original.
PHENOTYPES = (
    ("Sprinter", ((0, .90), (.11, .90), (.38, .07), (1, .07)),
     "Great power from 1&ndash;20 seconds, comparatively lower aerobic power."),
    ("Pursuiter", ((0, .82), (.22, .82), (.47, .06), (1, .06)),
     "Excels from 20 seconds to 2 minutes, also lacks aerobic power."),
    ("All-rounder", ((0, .72), (.20, .72), (.38, .40), (.62, .28), (.79, .08), (1, .07)),
     "Good but not spectacular power across all durations."),
    ("Time trialist", ((0, .52), (.28, .31), (1, .31)),
     "High power for long durations, but can&rsquo;t sprint."),
)


def _panel(i: int, name: str, pts: tuple, note: str) -> str:
    L, R, T, B = 22, 196, 10, 118  # plot box in a 206 x 140 viewBox
    poly = " ".join(f"{L + (R - L) * x:.1f},{B - (B - T) * y:.1f}" for x, y in pts)
    sid = f"ph-{i}"
    return (
        f'<div class="ph-panel"><p class="ph-h">{name}</p>'
        f'<svg viewBox="0 0 206 140" role="img" aria-labelledby="{sid}-t" xmlns="http://www.w3.org/2000/svg">'
        f'<title id="{sid}-t">{name}: {note}</title>'
        f'<path class="ph-axis" d="M{L},{T - 4}V{B}H{R + 6}" fill="none"/>'
        f'<polyline class="ph-line" points="{poly}" fill="none" data-draw="wipe" style="--draw-dur:1.1s;--draw-i:{i}"/>'
        f'<text class="ph-ax" x="{(L + R) / 2}" y="{B + 17}" text-anchor="middle">Duration</text>'
        f'<text class="ph-ax" transform="translate(12 {(T + B) / 2}) rotate(-90)" text-anchor="middle">Power</text>'
        f"</svg><p class=\"ph-note\">{note}</p></div>"
    )


PHENOTYPE_FIGURE = HtmlFigure(
    id="fig-phenotypes",
    kicker="The chart above, redrawn",
    title="Four rider phenotypes",
    html=('<div class="ph-grid">' + "".join(_panel(i, n, p, t) for i, (n, p, t) in enumerate(PHENOTYPES)) + "</div>"),
    caption_html=("Power against duration for each rider type, schematic as in the post&rsquo;s chalkboard chart "
                  "(no scale on either axis). Descriptions condensed from the paragraph below the chart."),
)

CSS = """
.ph-grid{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:14px}
.article .ph-h{font:700 14px var(--mono);color:var(--ink);margin:0 0 2px}
.article .ph-note{font:400 13px/1.45 var(--mono);color:var(--ink3);margin:4px 0 0}
.ph-axis{stroke:var(--ink);stroke-width:1.4}
.ph-line{stroke:var(--teal);stroke-width:3;stroke-linejoin:round;stroke-linecap:round}
.ph-ax{font:400 11px var(--mono);fill:var(--ink3)}
@media (max-width:640px){.ph-grid{grid-template-columns:repeat(2,minmax(0,1fr));row-gap:18px}}
"""


def render() -> str:
    return wp_post.render_post(SOURCE, alt=ALT, in_short=IN_SHORT,
                               replace={"phenotypes": PHENOTYPE_FIGURE},
                               replace_label="Show the original chart (with Gravel God)", extra_css=CSS)


def main() -> None:
    wp_post.write(OUTPUT_PATH, render())


if __name__ == "__main__":
    main()
