"""Imported WordPress post: https://gravelgodcycling.com/since-no-one-asked-why-did-dumoulin-retire-he-just-wants-to-eat-some-cheese/

Generated by scripts/wp_post_import.py 1186; the body
(since-no-one-asked-why-did-dumoulin-retire-he-just-wants-to-eat-some-cheese.body.html)
and metadata (...-cheese.json) are regenerated by the converter, this file is not.
ALT is written from what each image shows; IN_SHORT follows the "In short" rule
in wp_post (neutral, third person).

Not the same post as 1230 ("In Defense of FTP", slug ...-cheese-2), which
reused this slug with a -2 suffix.

The Elementor slides widget (the 8-step "recipe for a Grand Tour Contender")
converts to one text figure per slide, in order; each slide's background was
plain white (post-1186.css), so no art is lost.

The post has no headings, so "In short" links point at paragraph anchors that
render() adds (ANCHORS: the paragraph's opening words -> id). Text is unchanged.

No infographic: the post's only chart (Happiness vs Commitment) is a drawn
curve with no numbers, and it stays as drawn.

Regenerate: python3 wordpress/post_sources/since_no_one_asked_why_did_dumoulin_retire_he_just_wants_to_eat_some_cheese.py
"""
from __future__ import annotations

import dataclasses
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
if str(HERE.parent) not in sys.path:
    sys.path.insert(0, str(HERE.parent))

from editorial_shell import Claim  # noqa: E402
import wp_post  # noqa: E402

SLUG = "since-no-one-asked-why-did-dumoulin-retire-he-just-wants-to-eat-some-cheese"
SOURCE = wp_post.load(SLUG)
OUTPUT_PATH = wp_post.output_path(SLUG)

ALT = {
    "dumoulin-dilemma": "Tom Dumoulin in a yellow and black Jumbo-Visma jersey stands smiling between two thought bubbles: a bronze trophy on the left, a wedge of cheese on the right.",
    "happiness-vs-commitment": "Chalkboard sketch titled \"Happiness vs Commitment\": happiness on the vertical axis, commitment on the horizontal, and a bell curve that rises to a peak in the middle and falls back to zero at high commitment. A small photo of Tom Dumoulin smiles in the bottom right corner.",
    "dumoulin-tombstone": "A grey granite tombstone in a cemetery, engraved with one long sentence: train 4-7 hours every day for the next five years, often to the ragged edge, frequently starving yourself, denying every pleasure except coffee, living out of a suitcase, taking risks that could end your career or your life, knowing an ill-timed cough, crash or a competitor's cheating can undo all of it.",
    "fast-as-possible": "Cartoon Gravel God in a cowboy hat, white T-shirt and denim shorts stands with a road bike on a tropical beach beside a thatched umbrella and two loungers, a wedge of cheese in the sand, asking in a speech bubble: \"Why do you want to be as fast as possible?\"",
}

ANCHORS = {
    "I see their point, but on behalf of Dumoulin": "p-defend",
    "Here’s the recipe for a Grand Tour Contender:": "p-recipe",
    "Do you detect a theme?": "p-theme",
    "Don’t dream of being as fast as possible": "p-fun",
}

# The "In short" rule (wp_post docstring); one section (no headings).
IN_SHORT = (
    Claim("The post defends Tom Dumoulin&rsquo;s decision to step away from the sport, arguing that critics do not understand what being a Grand Tour contender demands.",
          "#p-defend", "See the passage", 0),
    Claim("It lists eight steps to becoming a Grand Tour contender, from being born with the right genes to guarding against anything that could cost 0.1%.",
          "#p-recipe", "See the steps", 0),
    Claim("Citing Dumoulin and Marcel Kittel, the post argues that professional cycling demands a tradeoff between quality of life and performance.",
          "#p-theme", "See the passage", 0),
    Claim("For other riders, it advises aiming to be as fast as they can be while having fun, rather than as fast as possible.",
          "#p-fun", "See the passage", 0),
)


def _anchored(body: str) -> str:
    for start, pid in ANCHORS.items():
        needle = f"<p>{start}"
        if body.count(needle) != 1:
            raise ValueError(f"anchor {pid}: {needle!r} found {body.count(needle)} times")
        body = body.replace(needle, f'<p id="{pid}">{start}', 1)
    return body


def render() -> str:
    src = dataclasses.replace(SOURCE, body=_anchored(SOURCE.body))
    return wp_post.render_post(src, alt=ALT, in_short=IN_SHORT)


def main() -> None:
    wp_post.write(OUTPUT_PATH, render())


if __name__ == "__main__":
    main()
