"""Imported WordPress post: https://gravelgodcycling.com/since-no-one-asked-my-take-on-whoop/

Generated by scripts/wp_post_import.py 901; the body (since-no-one-asked-my-take-on-whoop.body.html) and
metadata (since-no-one-asked-my-take-on-whoop.json) are regenerated by the converter, this file is not.
ALT is written from what each image shows; IN_SHORT follows the "In short" rule in wp_post (neutral, third person).

The post has no headings, so "In short" links point at paragraph anchors that
render() adds (ANCHORS: the paragraph's opening words -> id). Text is unchanged.

No infographic: the post states no data set to chart (one example figure,
"1 drink = -10 HRV or -3 BPM in RHR").

Regenerate: python3 wordpress/post_sources/since_no_one_asked_my_take_on_whoop.py
"""
from __future__ import annotations

import dataclasses
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
if str(HERE.parent) not in sys.path:
    sys.path.insert(0, str(HERE.parent))

from editorial_shell import Claim  # noqa: E402
import wp_post  # noqa: E402

SLUG = "since-no-one-asked-my-take-on-whoop"
SOURCE = wp_post.load(SLUG)
OUTPUT_PATH = wp_post.output_path(SLUG)

ALT = {
    "whoop-header": "Cartoon Gravel God in a cowboy hat, arms crossed, in front of a wall of glowing ones and zeros; his speech bubble reads: \"Pop Quiz: Do you need more data? A: No.\"",
}

ANCHORS = {
    "Since the optical sensor isn’t accurate": "p-sensor",
    "The devil in the detail": "p-baseline",
    "WHOOP generates Monthly Performance Assessments": "p-assessments",
    "My deep down take?": "p-take",
}

# The "In short" rule (wp_post docstring); one section (no headings).
IN_SHORT = (
    Claim("The post&rsquo;s main objection: WHOOP&rsquo;s optical sensor is not accurate, so the scores built on its data have little value.",
          "#p-sensor", "See the passage", 0),
    Claim("It adds that even with accurate data, WHOOP sets a personal baseline but says nothing about whether that strain is enough to reach one&rsquo;s goals.",
          "#p-baseline", "See the passage", 0),
    Claim("The monthly performance assessments are credited as useful prompts to change lifestyle habits that affect recovery, such as drinking and blue light.",
          "#p-assessments", "See the passage", 0),
    Claim("The conclusion: most people already know which habits slow them down, and more data does not supply the will to change.",
          "#p-take", "See the conclusion", 0),
)


def _anchored(body: str) -> str:
    for start, pid in ANCHORS.items():
        needle = f"<p>{start}"
        if body.count(needle) != 1:
            raise ValueError(f"anchor {pid}: {needle!r} found {body.count(needle)} times")
        body = body.replace(needle, f'<p id="{pid}">{start}', 1)
    return body


def render() -> str:
    src = dataclasses.replace(SOURCE, body=_anchored(SOURCE.body))
    return wp_post.render_post(src, alt=ALT, in_short=IN_SHORT)


def main() -> None:
    wp_post.write(OUTPUT_PATH, render())


if __name__ == "__main__":
    main()
