"""Imported WordPress post: https://gravelgodcycling.com/so-why-do-you-skip-weight-training/

Generated by scripts/wp_post_import.py 915; the body (so-why-do-you-skip-weight-training.body.html) and
metadata (so-why-do-you-skip-weight-training.json) are regenerated by the converter, this file is not.
ALT is written from what each image shows; IN_SHORT is a DRAFT for Matt's read
(plain statements of what the post says, each linking to the passage it restates).

The post has no headings, so "In short" links point at paragraph anchors that
render() adds (ANCHORS: the paragraph's opening words -> id). Text is unchanged.

No infographic: the post states no numbers to chart.

Regenerate: python3 wordpress/post_sources/so_why_do_you_skip_weight_training.py
"""
from __future__ import annotations

import dataclasses
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
if str(HERE.parent) not in sys.path:
    sys.path.insert(0, str(HERE.parent))

from editorial_shell import Claim  # noqa: E402
import wp_post  # noqa: E402

SLUG = "so-why-do-you-skip-weight-training"
SOURCE = wp_post.load(SLUG)
OUTPUT_PATH = wp_post.output_path(SLUG)

ALT = {
    "toddler-planks": "Black-and-white photo of a home gym: a man holds a push-up plank on a rubber floor beside a squat rack and bumper plates while a baby peeks over his back from behind.",
}

ANCHORS = {
    "Sadly, no. Boring things happened.": "p-results",
    "What changed is the habits around the execution.": "p-habits",
}

# DRAFT for Matt: plain statements of what the post says; one section (no headings).
IN_SHORT = (
    Claim("After a year of completing a lifting program, the author reports no lower back pain on the bike, more anaerobic capacity and no injuries.",
          "#p-results", "See the passage", 0),
    Claim("What made it stick was habit, not equipment: on days with a lift and a ride, the lift came first.",
          "#p-habits", "See the passage", 0),
)


def _anchored(body: str) -> str:
    for start, pid in ANCHORS.items():
        needle = f"<p>{start}"
        if body.count(needle) != 1:
            raise ValueError(f"anchor {pid}: {needle!r} found {body.count(needle)} times")
        body = body.replace(needle, f'<p id="{pid}">{start}', 1)
    return body


def render() -> str:
    src = dataclasses.replace(SOURCE, body=_anchored(SOURCE.body))
    return wp_post.render_post(src, alt=ALT, in_short=IN_SHORT)


def main() -> None:
    wp_post.write(OUTPUT_PATH, render())


if __name__ == "__main__":
    main()
