"""Imported WordPress post: https://gravelgodcycling.com/the-jester-precedes-the-king/

Generated by scripts/wp_post_import.py 1879; the body (the-jester-precedes-the-king.body.html) and
metadata (the-jester-precedes-the-king.json) are regenerated by the converter, this file is not.
ALT is written from what each image shows. Several images carry text that
answers the question just above them in the post ("Why didn't I do it?",
"Why is this a problem?", "Why is trying to achieve 'good' better than
'world-class'?"), so their ALT gives that text in full. IN_SHORT is a DRAFT
for Matt's read: plain, third-person statements of what the post argues.
No infographic: the post states no figures to chart.

Regenerate: python3 wordpress/post_sources/the_jester_precedes_the_king.py
"""
from __future__ import annotations

import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
if str(HERE.parent) not in sys.path:
    sys.path.insert(0, str(HERE.parent))

from editorial_shell import Claim  # noqa: E402,F401
import wp_post  # noqa: E402

SLUG = "the-jester-precedes-the-king"
SOURCE = wp_post.load(SLUG)
OUTPUT_PATH = wp_post.output_path(SLUG)

ALT = {
    "try-new-things": "Cartoon Gravel God in a cowboy hat, seen from behind, stands at a fork in a snowy dirt road through bare trees: the left sign reads \"Try new things\", the right \"Don't grow\".",
    "looking-like-a-moron": "Cartoon Gravel God in a cowboy hat grins beside the words: \"Because I was scared of looking like a moron.\"",
    "damn-kids": "A cyclocross rider races through snow past a Shimano banner and a cheering crowd; cartoon Gravel God rides alongside on his bike: \"Damn kids!.\"",
    "still-open": "Cartoon Gravel God, seen from behind, stands at night at the lit door of a late-night shop with full shelves: \"You guys still open?\"",
    "try-new-things-1": "A mountain biker rides a dusty desert singletrack through scrub; cartoon Gravel God follows on a road bike: \"Uggggh I don't have to steer on Zwift.\"",
    "still-havent-done-cyclocross": "Cartoon Gravel God in a cowboy hat: \"Why? I never did cyclocross, EVEN TO THIS DAY!\" A small figure asks \"Y tho?\" and he answers \"I didn't want to look like a clown.\"",
    "foreclosed-identity": "Cartoon Gravel God, arms crossed, on a hazy farm road beside the text: \"Because allowing your identity to foreclose around a rigid cycling identity prevents the acquisition of skills, abilities, and experiences that will make you better at bikes in general, which indirectly benefits performance in your preferred cycling discipline.\"",
    "profile-look": "Cartoon Gravel God in a cowboy hat, in profile, gazing off to the right against a plain white background.",
    "good-beats-world-class": "Cartoon Gravel God in a wheat field beside the text: \"Because in most things, good is just as good as world-class, not because being good within a discipline is close to world-class, but because being good in many disciplines makes you world-class compared to most people.\"",
    "practice-what-you-preach": "Photo of a young girl in a pink heart shirt rolling her eyes beside a kitchen counter scattered with pink flowers: \"So you don't practice what you preach? You really are a Dad.\"",
}

# DRAFT for Matt: matter-of-fact statements of what the post argues;
# section = 0-based h2 index (the intro counts with the first section).
IN_SHORT = (
    Claim("The post recounts skipping cyclocross in 2014 while two roommates raced it; by spring they cornered, braked and handled packs better.",
          "#but-i-skipped-it-why-didn-t-i-do-it", "See §01", 0),
    Claim("It attributes stalled progression to identity foreclosure: settling on one type of cycling and passing up skills other disciplines would teach.",
          "#i-never-did", "See §02", 1),
    Claim("Its moral is that the Jester precedes the King: mastery requires accepting early humiliation, and being good at many things beats chasing world-class.",
          "#if-you-want-to-master-something-you-need-to-be-willing-to-be", "See the Jester · §02", 1),
)


def render() -> str:
    return wp_post.render_post(SOURCE, alt=ALT, in_short=IN_SHORT)


def main() -> None:
    wp_post.write(OUTPUT_PATH, render())


if __name__ == "__main__":
    main()
