"""Imported WordPress post: https://gravelgodcycling.com/the-double-day-13-the-hangover/

Generated by scripts/wp_post_import.py 2716; the body and metadata
(the-double-day-13-the-hangover.body.html / .json) are regenerated by the
converter, this file is not. ALT is written from what each image shows;
IN_SHORT follows the "In short" rule in wp_post (neutral, third person).

The post's headings are h6 only; the converter maps them to h2. The three
closing images were an Elementor gallery and render as a figure grid. A
622-word post gets at most two "In short" claims. The live meta description
stands. No infographic: the post states no data.

Regenerate: python3 wordpress/post_sources/the_double_day_13_the_hangover.py
"""
from __future__ import annotations

import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
if str(HERE.parent) not in sys.path:
    sys.path.insert(0, str(HERE.parent))

from editorial_shell import Claim  # noqa: E402
import wp_post  # noqa: E402

SLUG = "the-double-day-13-the-hangover"
SOURCE = wp_post.load(SLUG)
OUTPUT_PATH = wp_post.output_path(SLUG)

ALT = {
    "the-hangover": "Google Maps route from Denver, Colorado, to Silver City, New Mexico, via Pueblo, Santa Fe and Albuquerque: 11 hr 6 min, 720 miles, with two alternatives; cartoon Gravel God in a cowboy hat smokes a cigar on the left.",
    "road-trip": "Animated: from the front seat of a packed SUV, a girl in a yellow sundress thrashes and sings in the back while a small boy in a car seat beside her laughs; the brim of cartoon Gravel God's cowboy hat fills the right edge.",
    "untitled-design-1": "Tweet from Chris Bianchi (@BianchiWeather): with no snow in the forecast, Denver looks likely to have its shortest snow season on record, 97 days, from first measurable snow on Dec. 10 to the last on Mar. 17; cartoon Gravel God shrugs in front of it.",
    "untitled-design": "A family around a long patio table with a birthday cake and wine glasses, adults and several young children, one man's face swapped for cartoon Gravel God in a cowboy hat and a boy in front grinning at the camera.",
    "las-vegas-fire": "A plume of wildfire smoke rises over pine-dotted hills beyond dry grassland and a power pole, while cartoon Gravel God in a cowboy hat, seen from behind, looks on.",
}

# The "In short" rule (wp_post docstring); section = 0-based h2 index.
IN_SHORT = (
    Claim("After the last stage, the author drove the family from Silver City over Emory Pass to Albuquerque, where his mother-in-law lives.",
          "#what-did-we-do-today-what-was-it-like", "See the passage", 0),
    Claim("The post argues that after a travel race, riders should let the high go and use their distance from routine to examine and improve it.",
          "#no-mediocre-power-reveal-but-inner-commentary", "See §01", 0),
)


def render() -> str:
    return wp_post.render_post(SOURCE, alt=ALT, in_short=IN_SHORT)


def main() -> None:
    wp_post.write(OUTPUT_PATH, render())


if __name__ == "__main__":
    main()
