"""Imported WordPress post: https://gravelgodcycling.com/the-double-day-9-gruppetto-gods/

Generated by scripts/wp_post_import.py 2663; the body and metadata
(the-double-day-9-gruppetto-gods.body.html / .json) are regenerated by the
converter, this file is not. ALT is written from what each image shows;
IN_SHORT follows the "In short" rule in wp_post (neutral, third person).

The post's headings are h6 only; the converter maps them to h2. A 675-word
post gets at most two "In short" claims.

DESCRIPTION replaces the live meta description ("embracing the gruppetto,
learning that sometimes the back of the race is where the real stories are"):
the author did not embrace the gruppetto; he was caught behind a crash and
spent the stage chasing the time cut.

Matt to read (minor): the text says "three and a half hours"; the Strava and
TrainingPeaks screenshots show 3:57:54 / 3:58:00 moving (4:58:40 elapsed).

No infographic: the screenshots carry their own numbers.

Regenerate: python3 wordpress/post_sources/the_double_day_9_gruppetto_gods.py
"""
from __future__ import annotations

import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
if str(HERE.parent) not in sys.path:
    sys.path.insert(0, str(HERE.parent))

from editorial_shell import Claim  # noqa: E402
import wp_post  # noqa: E402

SLUG = "the-double-day-9-gruppetto-gods"
SOURCE = wp_post.load(SLUG)
OUTPUT_PATH = wp_post.output_path(SLUG)

ALT = {
    "soppel": "Strava activity \"Dag 8: Søppelbøtterild\", Thursday, April 28, 2022, Silver City, New Mexico: 87.09 mi, 3:57:54 moving time, 4,705 ft, 272 W weighted average power, 22.0 mi/h average, with the loop map north-east of Silver City and the elevation profile.",
    "baesj": "TrainingPeaks file \"Gila St2\", April 28, 2022: 3:58:00, 87.1 mi, 249 TSS, normalized power 285 W, IF 0.79, 3.23 W/kg, with power and heart-rate traces; poop emojis dot the route map and cartoon Gravel God rides along it.",
    "9fda84aa-791b-4517-b663-a680c30692ce-scaled": "A small boy in a blue T-shirt stands with his hands clasped in a bare concrete-block toilet stall with a stainless-steel toilet, looking up at the camera.",
}

DESCRIPTION = ("Day 9 of The Double: the Tour of the Gila's Inner Loop road race, spent in the third "
               "gruppetto after getting caught behind a crash before the first climb.")

# The "In short" rule (wp_post docstring); section = 0-based h2 index.
IN_SHORT = (
    Claim("Caught behind a crash before the first climb&rsquo;s KOM, the author spent the stage chasing to finish inside the time cut.",
          "#what-i-hated-about-today", "See the passage", 0),
    Claim("The post&rsquo;s takeaway is that a rider who cannot handle a bike well must be very strong to survive in this field.",
          "#mediocre-power-reveal-inner-race-commentary", "See §01", 0),
)


def render() -> str:
    return wp_post.render_post(SOURCE, alt=ALT, in_short=IN_SHORT, description=DESCRIPTION)


def main() -> None:
    wp_post.write(OUTPUT_PATH, render())


if __name__ == "__main__":
    main()
