"""Imported WordPress post: https://gravelgodcycling.com/the-double-day-11-how-do-you-get-excited-for-crits/

Generated by scripts/wp_post_import.py 2684; the body and metadata
(the-double-day-11-how-do-you-get-excited-for-crits.body.html / .json) are
regenerated by the converter, this file is not. ALT is written from what each
image shows; IN_SHORT follows the "In short" rule in wp_post (neutral, third
person).

DESCRIPTION replaces the live meta description, which says stage-race fatigue
"has consumed every reserve"; the post says the author felt good and enjoyed
the crit.

The featured image is also the first inline image, so the page has no hero.
No infographic: the post states no figures a chart would clarify.
The post's divider is one unbroken run of em dashes, wider than a phone; the
shell lets it wrap (editorial_shell.mark_dash_rules), so no sideways scroll.

Corrected 2026-10-09 (Matt approved): CORRECTIONS below changes 85F to 79F (Strava:
26 °C); each
entry names its evidence. The page notes the correction at the end.

Regenerate: python3 wordpress/post_sources/the_double_day_11_how_do_you_get_excited_for_crits.py
"""
from __future__ import annotations

import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
if str(HERE.parent) not in sys.path:
    sys.path.insert(0, str(HERE.parent))

from editorial_shell import Claim  # noqa: E402
import wp_post  # noqa: E402

SLUG = "the-double-day-11-how-do-you-get-excited-for-crits"
SOURCE = wp_post.load(SLUG)
OUTPUT_PATH = wp_post.output_path(SLUG)

ALT = {
    "boolin-1": "Strava screenshot of Matti Rowe's ride \"Dag 11: Det er på tid for Boolin'\", April 30, 2022, Silver City, New Mexico: 49.43 mi, 1:58:38 moving time, 1,263 ft of climbing, 239 W weighted average power, 25.0 mi/h average, clear and 26 °C, with the downtown crit loop traced in red on the map.",
    "silver-city-boolin": "TrainingPeaks file \"Gila St4 - Crit\", April 30, 2022: 1:58:43, 49.4 mi, 105 TSS; the selected 1:34:10 race portion shows 43.8 mi, 91 TSS, normalized power 275 W, IF 0.77 and 3.07 W/kg over a dense, spiky power graph of the laps. A cartoon Gravel God in a cowboy hat and short shorts stands in front, hand at his mouth.",
}

DESCRIPTION = ("Day 11 of The Double: the Tour of the Gila Silver City criterium, a teammate's "
               "tenth place, and the author's family cheering from the course.")

# The "In short" rule (wp_post docstring); section = 0-based h2 index. A
# 627-word post gets at most two claims (wp_post.SHORT_POST_MAX_CLAIMS).
IN_SHORT = (
    Claim("The author reports losing some seconds in the Tour of the Gila Silver City criterium but says he actually enjoyed it.",
          "#how-did-i-do", "See how it went · Intro", 0),
    Claim("Among what the author loved that day: his family cheering from the fence of their Airbnb on the crit course every lap.",
          "#what-i-loved-about-today", "See what he loved · §02", 1),
)


# Figures corrected to match the post's own evidence (Matt, 2026-10-09:
# "Yeah go ahead and fix"). wp_post applies each to the body (old text must
# occur exactly once) and the word-for-word tests apply them to the snapshot.
CORRECTIONS = (
    wp_post.Correction(
        "85F Silver City heat",
        "79F Silver City heat",
        "the Strava screenshot (boolin-1): 26 °C, about 79 °F"),
)


def render() -> str:
    return wp_post.render_post(SOURCE, corrections=CORRECTIONS, alt=ALT, in_short=IN_SHORT, description=DESCRIPTION)


def main() -> None:
    wp_post.write(OUTPUT_PATH, render())


if __name__ == "__main__":
    main()
