"""Imported WordPress post: https://gravelgodcycling.com/the-double-day-3-yield-to-tonnage/

Generated by scripts/wp_post_import.py 2592; the body and metadata
(the-double-day-3-yield-to-tonnage.body.html / .json) are regenerated by the
converter, this file is not. ALT is written from what each image shows;
IN_SHORT follows the "In short" rule in wp_post (neutral, third person).

DESCRIPTION replaces the live meta description, which misread "Yield to
tonnage" as bigger riders setting the pace; in the post it is James backing
the team's trailer through a tight gap (Matt, 2026-10-09).

The featured image (Ut-på-baeretur.png) is byte-identical to the first inline
image, so the page has no hero (the converter detects this).

Infographic (2026-10-09): fig-rte66-stats, the two stat panels in the
"stats overlayed" GIF as a table, numbers exactly as the GIF shows them.
Matt to read: the GIF shows NP 328 W vs 415 W (20:56.61 vs 18:34), while the
text says "100 more watts than I for the same duration". The table states only
what the GIF shows and computes nothing.

Regenerate: python3 wordpress/post_sources/the_double_day_3_yield_to_tonnage.py
"""
from __future__ import annotations

import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
if str(HERE.parent) not in sys.path:
    sys.path.insert(0, str(HERE.parent))

from editorial_shell import Claim, DataTable, TableCell, TableColumn, TableRow  # noqa: E402
import wp_post  # noqa: E402

SLUG = "the-double-day-3-yield-to-tonnage"
SOURCE = wp_post.load(SLUG)
OUTPUT_PATH = wp_post.output_path(SLUG)

ALT = {
    "ut-pa-baeretur-1": "Strava screenshot of Matti Rowe's ride \"Dag 3: Ut på bæretur\", April 22, 2022, San Bernardino National Forest: 20.77 mi, 1:01:03 moving time, 1,070 ft of climbing, 260 W weighted average power, with the route map and elevation profile.",
    "mega-lol": "Animated: a TrainingPeaks analysis of the time trial (a 20:50.23 selection, 9.09 mi) with big bubble letters \"LOL\" flashing in changing colours over the map, and cartoon Gravel God in a cowboy hat peeking in from the bottom left.",
    "bufz-doge-fuchs": "Animated: two time-trial files stacked. Top, \"Rte 66 TT\", with cartoon Gravel God: 20:56.61, 9.10 mi, normalized power 328 W, 4.24 W/kg. Bottom, \"Entire Workout\", with a muscle-bound cartoon teammate in a cowboy hat holding a toaster: 18:34, 9.12 mi, 415 W, 5.08 W/kg. A yellow splash sweeps across.",
    "nap-god": "Photo of the team house living room: a teammate asleep on the couch in the foreground, another sorting gear on the rug, Formula 1 on the TV, an air mattress with sleeping bags, and a cartoon Gravel God in a cowboy hat gesturing at the scene.",
    "screen-shot-2022-04-22-at-5-17-43-pm": "FaceTime screenshot: a toddler leans in so close his face fills the screen, a second child peeks from behind, and Matti smiles in the small self-view corner.",
}

DESCRIPTION = ("Day 3 of The Double: the Route 66 time trial, a teammate who out-powered the author, "
               "a team house with no toaster, and a trailer backed through a tight gap.")

# The "In short" rule (wp_post docstring); section = 0-based h2 index. A
# 572-word post gets at most two claims (wp_post.SHORT_POST_MAX_CLAIMS).
IN_SHORT = (
    Claim("The post&rsquo;s complaint of the day is that the team&rsquo;s Airbnb has no toaster, though the team has spent about $1000 on food this week.",
          "#what-i-hated-about-today", "See the complaint · Intro", 0),
    Claim("The post says a teammate of similar build put out 100 more watts than the author over the same Route 66 time trial.",
          "#fig-rte66-stats", "See the numbers · §01", 0),
)

# ── fig-rte66-stats: the overlaid stat panels as a table ─────
# Every number is read off the GIF (bufz-doge-fuchs). Nothing is derived.
STATS_COLUMNS = (
    TableColumn("Rider", card="title", sortable=False),
    TableColumn("Duration", card="aside", sortable=False),
    TableColumn("Distance", kind="num", card="fact"),
    TableColumn("Normalized power", kind="num", card="fact"),
    TableColumn("W/kg", kind="num"),
    TableColumn("Work", kind="num"),
    TableColumn("IF", kind="num"),
    TableColumn("TSS", kind="num"),
)


def _row(rider: str, duration: str, mi: str, np_w: str, wkg: str, kj: str, if_: str, tss: str) -> TableRow:
    """Values as printed in the GIF (strings keep their trailing zeros)."""
    return TableRow(cells=(
        TableCell(rider),
        TableCell(duration),
        TableCell(f"{mi} mi", sort=float(mi)),
        TableCell(f"{np_w} W", sort=float(np_w)),
        TableCell(wkg, sort=float(wkg)),
        TableCell(f"{kj} kJ", sort=float(kj)),
        TableCell(if_, sort=float(if_)),
        TableCell(tss, sort=float(tss)),
    ))


RTE66_STATS = DataTable(
    id="fig-rte66-stats",
    kicker="The stats above, side by side",
    title="Route 66 time trial: the two files",
    intro_html="Read off the overlaid stat panels in the GIF above.",
    footnote_html=("Top panel &ldquo;Rte 66 TT&rdquo; (Matti); bottom panel &ldquo;Entire Workout&rdquo; "
                   "(his teammate). IF = intensity factor; TSS = training stress score."),
    columns=STATS_COLUMNS,
    rows=(
        _row("Matti", "20:56.61", "9.10", "328", "4.24", "410", "0.91", "28"),
        _row("Teammate", "18:34", "9.12", "415", "5.08", "463", "1.06", "35"),
    ),
    marker="rte66-stats",
)


def render() -> str:
    return wp_post.render_post(SOURCE, alt=ALT, in_short=IN_SHORT, figures=(RTE66_STATS,),
                               after_image={"rte66-stats": "bufz-doge-fuchs"}, description=DESCRIPTION)


def main() -> None:
    wp_post.write(OUTPUT_PATH, render())


if __name__ == "__main__":
    main()
