"""Imported WordPress post: https://gravelgodcycling.com/the-double-day-6-do-you-know-what-rolly-gang-means/

Generated by scripts/wp_post_import.py 2635; the body and metadata
(the-double-day-6-do-you-know-what-rolly-gang-means.body.html / .json) are
regenerated by the converter, this file is not. ALT is written from what each
image shows; IN_SHORT follows the "In short" rule in wp_post (neutral, third person).

DESCRIPTION replaces the live meta description ("mid-race existential clarity
and the unexpected benefits of voluntary, structured suffering"): the day is a
drive from Redlands to the Gila, and the essay argues that racing takes
commitment and nerve as much as watts.

No infographic: the post states no data.

Regenerate: python3 wordpress/post_sources/the_double_day_6_do_you_know_what_rolly_gang_means.py
"""
from __future__ import annotations

import dataclasses
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
if str(HERE.parent) not in sys.path:
    sys.path.insert(0, str(HERE.parent))

from editorial_shell import Claim  # noqa: E402
import wp_post  # noqa: E402

SLUG = "the-double-day-6-do-you-know-what-rolly-gang-means"
SOURCE = wp_post.load(SLUG)
OUTPUT_PATH = wp_post.output_path(SLUG)

ALT = {
    "dag-seks": "Google Maps route from Redlands, California, to Silver City, New Mexico, via Phoenix and Tucson: 9 hr 19 min, 624 miles, with two longer alternatives (9 hr 36 min, 646 miles; 11 hr 14 min, 680 miles); cartoon Gravel God in a cowboy hat rides a bike across the map.",
    "boolin": "Black-and-white photo of a tightly packed criterium bunch leaning through a corner on a palm-lined street, with the word \"Boolin\" in glowing red neon letters above it.",
    "67261683480-135b1b38-4acb-4334-a87b-0d311e27fa14-scaled": "Two young children grin up at the camera on a carpeted floor: a shirtless little boy on the left and a girl in a checked sundress baring her teeth on the right.",
}

DESCRIPTION = ("Day 6 of The Double: a ten-hour drive from Redlands to the Gila, and why racing well "
               "takes commitment and nerve as much as watts.")

ANCHORS = {"Because of power meters": "p-power-meters"}

# The "In short" rule (wp_post docstring); section = 0-based h2 index.
IN_SHORT = (
    Claim("The post argues that many riders produce good power in training but lack the racing skill to use it in a big field.",
          "#p-power-meters", "See the passage", 0),
    Claim("Its advice is to pre-commit to suffering, hold one&rsquo;s nerve in the pack, and expect the race to turn hard at any moment.",
          "#dread-pain-embrace-pain", "See §01", 0),
    Claim("It concludes that racing well depends as much on commitment and nerve as on watts.",
          "#in-summary", "See In Summary · §05", 4),
)


def _anchored(body: str) -> str:
    for start, pid in ANCHORS.items():
        needle = f"<p>{start}"
        if body.count(needle) != 1:
            raise ValueError(f"anchor {pid}: {needle!r} found {body.count(needle)} times")
        body = body.replace(needle, f'<p id="{pid}">{start}', 1)
    return body


def render() -> str:
    src = dataclasses.replace(SOURCE, body=_anchored(SOURCE.body))
    return wp_post.render_post(src, alt=ALT, in_short=IN_SHORT, description=DESCRIPTION)


def main() -> None:
    wp_post.write(OUTPUT_PATH, render())


if __name__ == "__main__":
    main()
