"""Imported WordPress post: https://gravelgodcycling.com/the-double-day-12-i-like-the-way-you-die-boy/

Generated by scripts/wp_post_import.py 2696; the body and metadata
(the-double-day-12-i-like-the-way-you-die-boy.body.html / .json) are
regenerated by the converter, this file is not. ALT is written from what each
image shows; IN_SHORT follows the "In short" rule in wp_post (neutral, third
person).

DESCRIPTION replaces the live meta description ("where finishing becomes the
only goal and performance is a distant memory"), which inverts the post: the
author calls the Gila Monster stage (24th) his best UCI race and one of the
days of his life.

The featured image (gila-monster-1) is the first inline image, so the page has
no hero. The three "Random Snaps" images are a gallery. No infographic.

Regenerate: python3 wordpress/post_sources/the_double_day_12_i_like_the_way_you_die_boy.py
"""
from __future__ import annotations

import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
if str(HERE.parent) not in sys.path:
    sys.path.insert(0, str(HERE.parent))

from editorial_shell import Claim  # noqa: E402
import wp_post  # noqa: E402

SLUG = "the-double-day-12-i-like-the-way-you-die-boy"
SOURCE = wp_post.load(SLUG)
OUTPUT_PATH = wp_post.output_path(SLUG)

ALT = {
    "gila-monster-1": "Strava screenshot of Matti Rowe's ride \"Dag 12: Tjuefjerde plass! Dyret endelig våknet.\", 9:19 AM on Sunday, May 1, 2022, Silver City, New Mexico: 112.05 mi, 5:20:12 moving time, 7,825 ft of climbing, 256 W weighted average power, 4,099 kJ, with the loop north of Silver City on the map and an elevation profile with three big climbs.",
    "udyret-kommer": "Animated: a TrainingPeaks file \"Gila St5\" (5:19:54, 112 mi, 289 TSS, normalized power 265 W) with cartoon Gravel God in a cowboy hat, seen from behind, riding a bike up the right side of the screen.",
    "ristra": "Cartoon Gravel God in a cowboy hat grins on an adobe porch beside a white ladder where a red cycling jersey hangs with two Tour of the Gila race numbers, 63, still pinned on; a chile ristra hangs on the wall behind.",
    "da-fugg": "Cartoon Gravel God in a cowboy hat gestures at an old bathtub shower with exposed nickel pipes, a wall-mounted showerhead and a hand shower in a white-tiled bathroom.",
    "esel": "Cartoon Gravel God in a cowboy hat, seen from behind, stands in a dusty yard while two children look at a dark donkey behind a metal pen fence.",
    "zia": "Cartoon Gravel God in a cowboy hat looks in profile at a yellow metal tray on the wall, painted with the red Zia sun symbol of New Mexico and a small red heart.",
}

DESCRIPTION = ("Day 12 of The Double: the Tour of the Gila’s Gila Monster stage, where the author finished "
               "24th, his best UCI race, then the drive to Albuquerque with family.")  # <=160 chars

# The "In short" rule (wp_post docstring); section = 0-based h2 index. A
# 607-word post gets at most two claims (wp_post.SHORT_POST_MAX_CLAIMS).
IN_SHORT = (
    Claim("The author finished 24th on the Gila Monster stage of the Tour of the Gila, which the post calls his best UCI race.",
          "#how-did-i-do", "See the result · Intro", 0),
    Claim("The post says the best part was riding with teammates Ethan and Chaz, rejoining the leading group on the descent after the first climb.",
          "#mediocre-power-reveal-inner-race-commentary", "See the race · §01", 0),
)


def render() -> str:
    return wp_post.render_post(SOURCE, alt=ALT, in_short=IN_SHORT, description=DESCRIPTION)


def main() -> None:
    wp_post.write(OUTPUT_PATH, render())


if __name__ == "__main__":
    main()
