"""Imported WordPress post: https://gravelgodcycling.com/the-tao-of-tom/

Generated by scripts/wp_post_import.py 922; the body (the-tao-of-tom.body.html) and
metadata (the-tao-of-tom.json) are regenerated by the converter, this file is not.
ALT is written from what each image shows; IN_SHORT follows the "In short" rule in wp_post (neutral, third person).

The post has no headings, so "In short" links point at paragraph anchors that
render() adds (ANCHORS: the paragraph's opening words -> id). Text is unchanged.

No infographic: a story with no numbers to chart.

DESCRIPTION replaces the live meta description, which called Tom a cycling
mentor; in the post he is a younger teammate on the author's college ski team,
and the post is about trusting the plan. TITLE replaces the live title ("The
Tao of Tom — Cycling Mentor") for the same reason.

Regenerate: python3 wordpress/post_sources/the_tao_of_tom.py
"""
from __future__ import annotations

import dataclasses
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
if str(HERE.parent) not in sys.path:
    sys.path.insert(0, str(HERE.parent))

from editorial_shell import Claim  # noqa: E402
import wp_post  # noqa: E402

SLUG = "the-tao-of-tom"
SOURCE = wp_post.load(SLUG)
OUTPUT_PATH = wp_post.output_path(SLUG)

DESCRIPTION = ("A story about Tom, a younger teammate on the author’s college ski team who trusted "
               "the plan: easy on easy days, hard on hard days, whatever his teammates did.")

TITLE = "The Tao of Tom — Trusting the Plan | Gravel God"

ALT = {
    "tao-of-tom": "Three monks in saffron robes walk away down a misty, grassy path under arching trees; cartoon Gravel God in a cowboy hat, arms crossed, stands beside them facing the camera.",
}

ANCHORS = {
    "What Tom embodied was complete confidence in the Plan.": "p-plan",
    "Tom didn’t ski easy on easy days": "p-origin",
}

# The "In short" rule (wp_post docstring); one section (no headings).
IN_SHORT = (
    Claim("The author&rsquo;s younger college ski teammate, Tom, went easy alone on easy days and finished far ahead in intervals, trusting the plan.",
          "#p-plan", "See the passage", 0),
    Claim("The post reads this not as ego control but as measuring oneself against one&rsquo;s own process instead of against teammates.",
          "#p-origin", "See the passage", 0),
)


def _anchored(body: str) -> str:
    for start, pid in ANCHORS.items():
        needle = f"<p>{start}"
        if body.count(needle) != 1:
            raise ValueError(f"anchor {pid}: {needle!r} found {body.count(needle)} times")
        body = body.replace(needle, f'<p id="{pid}">{start}', 1)
    return body


def render() -> str:
    src = dataclasses.replace(SOURCE, body=_anchored(SOURCE.body))
    return wp_post.render_post(src, alt=ALT, in_short=IN_SHORT, description=DESCRIPTION, title=TITLE)


def main() -> None:
    wp_post.write(OUTPUT_PATH, render())


if __name__ == "__main__":
    main()
