"""Imported WordPress post: https://gravelgodcycling.com/the-double-day-10-im-not-sure-what-an-18-hrv-means/

Generated by scripts/wp_post_import.py 2673; the body and metadata
(the-double-day-10-im-not-sure-what-an-18-hrv-means.body.html / .json) are
regenerated by the converter, this file is not. ALT is written from what each
image shows; IN_SHORT follows the "In short" rule in wp_post (neutral, third person).

The post's headings are h6 only; the converter maps them to h2, and its
bold-paragraph labels ("How did I do?") keep their own anchors.

DESCRIPTION replaces the live meta description ("when your HRV drops to 18 and
the body sends signals your brain refuses to acknowledge"): the HRV of 18 is a
teammate's quote, and the post is about the Tyrone time trial, the UCI jig and
a PSA on courtesy to host towns.

No infographic: the Strava and TrainingPeaks screenshots carry their numbers.

Regenerate: python3 wordpress/post_sources/the_double_day_10_im_not_sure_what_an_18_hrv_means.py
"""
from __future__ import annotations

import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
if str(HERE.parent) not in sys.path:
    sys.path.insert(0, str(HERE.parent))

from editorial_shell import Claim  # noqa: E402
import wp_post  # noqa: E402

SLUG = "the-double-day-10-im-not-sure-what-an-18-hrv-means"
SOURCE = wp_post.load(SLUG)
OUTPUT_PATH = wp_post.output_path(SLUG)

ALT = {
    "dode-hasene-1": "Strava activity \"Dag 9: Døde Hasene\", Friday, April 29, 2022, Grant County, New Mexico: 31.05 mi, 1:23:59 moving time, 1,726 ft, 270 W weighted average power, 22.2 mi/h average, with the route map south of Silver City and the elevation profile.",
    "sheeeeeesh": "TrainingPeaks file \"Gila St3 - TT\", April 29, 2022: 1:25:10, 31.1 mi, 85 TSS, normalized power 279 W, IF 0.78, 3.14 W/kg and a \"Tyrone TT\" lap of 37:55.34, with power and heart-rate traces; cartoon Gravel God on a bike says \"Sheeeeeesh!\"",
    "img-9850": "A shirtless toddler in a camouflage cap, green shorts and pink clogs stands on a front walk with his hands raised, a flowering white shrub and a chain-link fence behind him.",
    "soap-box": "Animated: cartoon Gravel God in a cowboy hat stands on a pink bar of soap ringed with bubbles, jabbing a finger as he speaks.",
}

DESCRIPTION = ("Day 10 of The Double: the Tour of the Gila's Tyrone time trial, a 36th place, "
               "a UCI bike-check jig that was set wrong, and a plea for courtesy to host towns.")

# The "In short" rule (wp_post docstring); section = 0-based h2 index.
IN_SHORT = (
    Claim("The author finished 36th in the Tyrone time trial, Stage 3 of the Tour of the Gila.",
          "#how-did-i-do", "See How did I do?", 0),
    Claim("Several riders failed the UCI bike-check jig before the start, until the jig was found not to be level or set right.",
          "#what-i-hated-loved-about-today", "See the passage", 0),
    Claim("The post describes the course as two hills to ride all out, with descents ridden as aero as possible.",
          "#mediocre-power-reveal-inner-race-commentary", "See §01", 0),
    Claim("Its closing PSA argues that road racers should be courteous to the communities that host their races.",
          "#psa", "See PSA · §03", 2),
)


def render() -> str:
    return wp_post.render_post(SOURCE, alt=ALT, in_short=IN_SHORT, description=DESCRIPTION)


def main() -> None:
    wp_post.write(OUTPUT_PATH, render())


if __name__ == "__main__":
    main()
