"""Imported WordPress post: https://gravelgodcycling.com/the-double-day-2-thiccc-is-kwik/

Generated by scripts/wp_post_import.py 2563; the body and metadata
(the-double-day-2-thiccc-is-kwik.body.html / .json) are regenerated by the
converter, this file is not. ALT is written from what each image shows;
IN_SHORT follows the "In short" rule in wp_post (neutral, third person).
A 331-word post: at most two claims. The WordPress text breaks off mid-word
("vie6") after "What I hated about today"; the snapshot is kept as is.

DESCRIPTION replaces the live meta description ("race weight is a myth and
diesel engines win gravel"): the day was a road race, and the post makes no
claim about race weight.
No infographic.
Matt to read: the post describes "six laps of a 14-mile circuit" (84 mi plus
the final climb), while the Strava and TrainingPeaks screenshots show 96.2 mi
(possibly including riding to and from the course). The post spells the race
"Yuipica"; the Strava screenshot says Yucaipa.

Regenerate: python3 wordpress/post_sources/the_double_day_2_thiccc_is_kwik.py
"""
from __future__ import annotations

import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
if str(HERE.parent) not in sys.path:
    sys.path.insert(0, str(HERE.parent))

from editorial_shell import Claim  # noqa: E402
import wp_post  # noqa: E402

SLUG = "the-double-day-2-thiccc-is-kwik"
SOURCE = wp_post.load(SLUG)
OUTPUT_PATH = wp_post.output_path(SLUG)

DESCRIPTION = ("Day 2 of The Double: a six-lap road race with a final climb, a 76th-place finish, "
               "and a teammate's line “thicc is kwik.”")

ALT = {
    "faenskap": "Strava activity \"Dag 2: Fænskap\", Thursday, April 21, 2022, Yucaipa, California: 96.17 mi, 4:13:25 moving time, 8,862 ft of climbing, 282 W weighted average power, 3,576 kJ, with the route map and elevation profile.",
    "weeeak": "TrainingPeaks file \"Redlands St2 - Oak Glen\", April 21, 2022: 4:13:49, 96.2 mi, 286 TSS, normalized power 296 W, IF 0.82; peak power 605 W for 30 s, 457 W for 1 min, 385 W for 5 min. Cartoon Gravel God in a cowboy hat stands over the panel.",
    "hallaigjen": "Two children play doctor in a bedroom: a small boy in a blue T-shirt and his sister's sparkly black shoes wears a yellow toy stethoscope, beside a girl in a white nurse costume; cartoon Gravel God in a cowboy hat stands behind them.",
}

# The "In short" rule (wp_post docstring); section = 0-based h2 index.
IN_SHORT = (
    Claim("The author finished 76th of 153 in a road race of six 14-mile laps, ending with a 5-mile climb at 7%.",
          "#how-did-i-do", "See the result · Intro", 0),
    Claim("The quote of the day, &ldquo;thicc is kwik,&rdquo; came from a heavier teammate who put out 385+ watts at the finish and beat some climbers.",
          "#quote-of-the-day", "See the quote · Intro", 0),
)


def render() -> str:
    return wp_post.render_post(SOURCE, alt=ALT, in_short=IN_SHORT, description=DESCRIPTION)


def main() -> None:
    wp_post.write(OUTPUT_PATH, render())


if __name__ == "__main__":
    main()
