"""Imported WordPress post: https://gravelgodcycling.com/the-double-day-5-rolly-gang-rolly-gang-rolly-gang/

Generated by scripts/wp_post_import.py 2623; the body and metadata
(the-double-day-5-rolly-gang-rolly-gang-rolly-gang.body.html / .json) are
regenerated by the converter, this file is not. ALT is written from what each
image shows; IN_SHORT follows the "In short" rule in wp_post (neutral, third
person).

DESCRIPTION replaces the live meta description ("the body adapts and the mind
starts playing creative games with suffering"), which the post doesn't say:
the author was time cut the day before and didn't race; the post covers the
crash in the Sunset road race and his Zone 2 ride.

The featured image (rolly-gang) is the first inline image, so the page has no
hero. No infographic: the post states no numbers worth tabulating.

Regenerate: python3 wordpress/post_sources/the_double_day_5_rolly_gang_rolly_gang_rolly_gang.py
"""
from __future__ import annotations

import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
if str(HERE.parent) not in sys.path:
    sys.path.insert(0, str(HERE.parent))

from editorial_shell import Claim  # noqa: E402
import wp_post  # noqa: E402

SLUG = "the-double-day-5-rolly-gang-rolly-gang-rolly-gang"
SOURCE = wp_post.load(SLUG)
OUTPUT_PATH = wp_post.output_path(SLUG)

ALT = {
    "rolly-gang": "Strava screenshot of Matti Rowe's ride \"Dag 5: Rolly gang rolly gang rolly gang\", 10:47 AM on Sunday, April 24, 2022, Riverside County, California: 23.88 mi, 1:16:16 moving time, 1,191 ft of climbing, 232 W weighted average power, 1,025 kJ, with the route map and elevation profile; a faded photo of a herd of donkeys shows through behind the profile.",
    "img-1389": "Two riders outside after the crash: one in a striped T-shirt dabs a wound on the shoulder of a shirtless, curly-haired rider who sits on a red cooler, his elbow and knee bandaged, pressing a blue shirt to his face.",
    "img-1393": "Instagram story selfie of Alex Marr in a hospital bed, his face dirty, wearing a neck brace and an oxygen tube, captioned \"Went in to a brick wall at 50mph but I'm breathing and recovering\".",
    "elser": "Animated: cartoon Gravel God in a cowboy hat rides a road bike along a curb, past a landscaped hillside where a wild donkey grazes among the bushes.",
    "img-9715": "A toddler in a grey T-shirt and pink shoes sits on a blue arcade motorcycle racing game, tongue out and hands on the controls, in a busy neon-lit arcade.",
}

DESCRIPTION = ("Day 5 of The Double: the Sunset road race, which the author missed after a time cut, "
               "a high-speed crash in the bunch, and a Zone 2 ride past wild donkeys.")

# The "In short" rule (wp_post docstring); section = 0-based h2 index. A
# 402-word post gets at most two claims (wp_post.SHORT_POST_MAX_CLAIMS).
IN_SHORT = (
    Claim("The author did not race the Sunset road race, having been time cut the day before.",
          "#how-did-i-do", "See the passage · Intro", 0),
    Claim("The post reports a crash at about 50 mph in which Alex Marr hit an electric box, breaking his pelvis and T4 vertebrae.",
          "#what-i-hated-about-today", "See the crash · §01", 0),
)


def render() -> str:
    return wp_post.render_post(SOURCE, alt=ALT, in_short=IN_SHORT, description=DESCRIPTION)


def main() -> None:
    wp_post.write(OUTPUT_PATH, render())


if __name__ == "__main__":
    main()
