"""Imported WordPress post: https://gravelgodcycling.com/the-double-day-1/

Generated by scripts/wp_post_import.py 2552; the body (the-double-day-1.body.html) and
metadata (the-double-day-1.json) are regenerated by the converter, this file is not.
ALT is written from what each image shows; IN_SHORT follows the "In short" rule
in wp_post (neutral, third person). A 185-word post: two claims, no Contents.

DESCRIPTION replaces the live meta description, which describes "a 13-day stage
race experiment. Two races, two weeks, one question: is this even possible?";
the post says none of that. It is the Highland Circuit Race and a 123/162 finish.

No infographic: the post states few numbers.

Corrected 2026-10-09 (Matt approved): CORRECTIONS below changes the "5-mile circuit" to 3
(20 laps; Strava 60.15 mi; the official stage was 58.1 mi); each
entry names its evidence. The page notes the correction at the end.

Regenerate: python3 wordpress/post_sources/the_double_day_1.py
"""
from __future__ import annotations

import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
if str(HERE.parent) not in sys.path:
    sys.path.insert(0, str(HERE.parent))

from editorial_shell import Claim  # noqa: E402
import wp_post  # noqa: E402

SLUG = "the-double-day-1"
SOURCE = wp_post.load(SLUG)
OUTPUT_PATH = wp_post.output_path(SLUG)

ALT = {
    "day-1": "Strava screenshot of Matti Rowe's ride \"Dag 1: Takknemlig for jobben min\", April 20, 2022, Highland, California: 60.15 mi, 2:36:28 moving time, 2,421 ft of climbing, 297 W weighted average power, with the route map and elevation profile.",
    "lolz": "TrainingPeaks file \"Redlands - Highland\", April 20, 2022: 2:36:21, 60.2 mi, 200 TSS; a 2:15:08 selection shows 326 W normalized power and 3.46 W/kg. A cartoon Gravel God in a cowboy hat stands beside the stats, hand on chin.",
    "best-part": "Two children grinning over baskets of grilled cheese and fries at a patio table, a salad and a beer in the foreground, with a small cartoon Gravel God in a cowboy hat standing by a bike behind them.",
}

DESCRIPTION = ("Day 1 of The Double: the Highland Circuit Race, 20 laps of a circuit with a big hill, "
               "where the author finished 123rd of 162.")

# The "In short" rule (wp_post docstring); section = 0-based h2 index.
IN_SHORT = (
    Claim("The post reports the Highland Circuit Race, 20 laps of a circuit with a large hill, and the author&rsquo;s finish: 123rd of 162.",
          "#how-did-i-do", "See the result · Intro", 0),
    Claim("Its lap-by-lap commentary moves from fear of crashing on lap one, through riding at the back, to fighting to hold on near the end.",
          "#mediocre-power-reveal", "See the laps · §01", 0),
)


# Figures corrected to match the post's own evidence (Matt, 2026-10-09:
# "Yeah go ahead and fix"). wp_post applies each to the body (old text must
# occur exactly once) and the word-for-word tests apply them to the snapshot.
CORRECTIONS = (
    wp_post.Correction(
        "20 laps of a 5-mile circuit",
        "20 laps of a 3-mile circuit",
        "Strava (day-1) shows 60.15 mi for the day; the race's men's stage was 20 laps, 58.1 mi (about 2.9 mi a lap)"),
)


def render() -> str:
    return wp_post.render_post(SOURCE, corrections=CORRECTIONS, alt=ALT, in_short=IN_SHORT, description=DESCRIPTION)


def main() -> None:
    wp_post.write(OUTPUT_PATH, render())


if __name__ == "__main__":
    main()
