"""Imported WordPress post: https://gravelgodcycling.com/the-double-day-4-sheeesh/

Generated by scripts/wp_post_import.py 2608; the body and metadata
(the-double-day-4-sheeesh.body.html / .json) are regenerated by the converter,
this file is not. ALT is written from what each image shows; IN_SHORT follows
the "In short" rule in wp_post (neutral, third person).

DESCRIPTION replaces the live meta description ("when accumulated fatigue
starts whispering and the legs negotiate every pedal stroke"), which the post
doesn't say: it is the Redlands criterium, where the author was pulled, and
teammates who answer everything with "Sheesh".

The featured image (sheeesh-1) is the first inline image, so the page has no
hero. No infographic. The long em-dash divider wraps on phones via the shell
(editorial_shell.mark_dash_rules).

Regenerate: python3 wordpress/post_sources/the_double_day_4_sheeesh.py
"""
from __future__ import annotations

import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
if str(HERE.parent) not in sys.path:
    sys.path.insert(0, str(HERE.parent))

from editorial_shell import Claim  # noqa: E402
import wp_post  # noqa: E402

SLUG = "the-double-day-4-sheeesh"
SOURCE = wp_post.load(SLUG)
OUTPUT_PATH = wp_post.output_path(SLUG)

ALT = {
    "sheeesh-1": "Strava screenshot of Matti Rowe's ride \"Dag 4: Sheeesh\", 3:31 PM on Saturday, April 23, 2022, Redlands, California: 19.75 mi, 47:58 moving time, 545 ft of climbing, 283 W weighted average power, 719 kJ, 24.7 mi/h average, with the twisting criterium circuit traced over and over on the map and a flat elevation profile.",
    "mote-veggen": "Animated: a TrainingPeaks file \"Redlands St4 - Crit\" (48:08, 19.8 mi, 60 TSS, normalized power 313 W) where cartoon Gravel God in a cowboy hat rides across the power graph into a brick wall drawn over it, and a cartoon explosion fills the screen.",
    "shame": "Meme: Matti's cartoon face in a cowboy hat pasted onto the Game of Thrones walk-of-shame scene, a nun in grey and a jeering crowd behind him, captioned \"SHAME SHAME SHAME SHAME\".",
    "screen-shot-2022-04-24-at-9-09-04-am": "Message thread from the family road trip: \"Haha yep\", \"It's been an interesting trip\", \"Nana got severely car sick for quite a while\", \"Lars pitched a couple massive fits related to being denied treats in gas stations\", \"Hadley announced she had listed and illustrated 11 activities to do on Mother's Day\", \"Extremely high winds\", \"Just came through big fire, very Smokey\".",
}

DESCRIPTION = ("Day 4 of The Double: the Redlands criterium, where the author was pulled about 35 minutes in, "
               "and teammates who answer everything with “Sheesh.”")

# The "In short" rule (wp_post docstring); section = 0-based h2 index. A
# 474-word post gets at most two claims (wp_post.SHORT_POST_MAX_CLAIMS).
IN_SHORT = (
    Claim("The post&rsquo;s main complaint is that the author&rsquo;s 20-something teammates repeat &ldquo;Sheesh,&rdquo; a viral TikTok meme, in every situation.",
          "#what-i-hated-about-today", "See the complaint · Intro", 0),
    Claim("The author was pulled from the Redlands criterium about 35 minutes in; his wife&rsquo;s friend and her father had driven 80 minutes to watch.",
          "#what-ioved-about-today", "See the passage · §02", 1),
)


def render() -> str:
    return wp_post.render_post(SOURCE, alt=ALT, in_short=IN_SHORT, description=DESCRIPTION)


def main() -> None:
    wp_post.write(OUTPUT_PATH, render())


if __name__ == "__main__":
    main()
