"""Imported WordPress post: https://gravelgodcycling.com/the-tyranny-of-irony-in-cycling/

Generated by scripts/wp_post_import.py 2830; the body and metadata
(the-tyranny-of-irony-in-cycling.body.html / .json) are regenerated by the
converter, this file is not. ALT is written from what each image shows;
IN_SHORT follows the "In short" rule in wp_post (neutral, third person).

The live meta description is kept: it states the post's argument.

The featured image (trollmann-1) is the first inline image, so the page has no
hero. No infographic: the post's argument is not numeric.

Regenerate: python3 wordpress/post_sources/the_tyranny_of_irony_in_cycling.py
"""
from __future__ import annotations

import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
if str(HERE.parent) not in sys.path:
    sys.path.insert(0, str(HERE.parent))

from editorial_shell import Claim  # noqa: E402
import wp_post  # noqa: E402

SLUG = "the-tyranny-of-irony-in-cycling"
SOURCE = wp_post.load(SLUG)
OUTPUT_PATH = wp_post.output_path(SLUG)

ALT = {
    "trollmann-1": "Black-and-white photo of a misty gravel road through a forest; a green cartoon troll in a loincloth lurks at the roadside while cartoon Gravel God in a cowboy hat rides toward the camera.",
    "hitchhiker": "Cartoon Gravel God in a cowboy hat, seen from behind, stands at the edge of a long dirt road through the trees, a car's headlights far in the distance.",
    "hourglass": "Cartoon Gravel God in a cowboy hat, in profile, stares at an antique brass hourglass with sand running from the top bulb.",
    "shit-on-cycling": "Cartoon Gravel God in a cowboy hat stands by a bicycle propped against a stained wall, watching a white dog squat to relieve itself on the pavement.",
    "pyramid": "The pyramids of Giza under a blue sky, a camel caravan crossing the sand in front, with a tiny cartoon Gravel God in a cowboy hat standing among the camels with his bicycle.",
}

# The "In short" rule (wp_post docstring); section = 0-based h2 index.
IN_SHORT = (
    Claim("The post argues that cyclists who train seriously but act as if they don&rsquo;t care are protecting their egos from failure.",
          "#duh-duh-duh-duh-duh-duh", "See the argument · §01", 0),
    Claim("It argues that pretending not to care handicaps a rider, because it offers a mental out when a race gets hard.",
          "#pull-quote-2", "See the argument · §01", 0),
    Claim("The post names three ways riders who aren&rsquo;t fast seek status: ironic competing, snark on social media, or opting out.",
          "#what-the-hell-am-i-talking-about-what-is-this-activity-grave", "See the list · §03", 2),
    Claim("It concludes that if gravel riding makes someone fitter, healthier, more outdoors or more social, that person is doing it right.",
          "#here-is-another-modest-proposal-if-you-re-riding-you-re-doin", "See the proposal · §06", 5),
)


def render() -> str:
    return wp_post.render_post(SOURCE, alt=ALT, in_short=IN_SHORT)


def main() -> None:
    wp_post.write(OUTPUT_PATH, render())


if __name__ == "__main__":
    main()
