"""Imported WordPress post: https://gravelgodcycling.com/the-double-day-8-check-yourself-before-you-wreck-yourself/

Generated by scripts/wp_post_import.py 2649; the body and metadata
(the-double-day-8-check-yourself-before-you-wreck-yourself.body.html / .json) are
regenerated by the converter, this file is not. ALT is written from what each
image shows; IN_SHORT follows the "In short" rule in wp_post (neutral, third
person). A 357-word post: two claims, no Contents.

DESCRIPTION replaces the live meta description ("knowing when to ease off before
the body makes that decision for you. Ego management in real time"): the title
quote is a driver telling the author off at an intersection, and the post is
his best UCI result, 24th on Gila stage 1, plus bedtime with his son.

No infographic. Checked 2026-10-09, left unchanged: the post calls the stage "90 miles";
the screenshots show 101.75 mi (Strava) / 102 mi (TrainingPeaks), but the
official stage 1 is 92 mi (148 km) and the file includes riding to the start.

Regenerate: python3 wordpress/post_sources/the_double_day_8_check_yourself_before_you_wreck_yourself.py
"""
from __future__ import annotations

import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
if str(HERE.parent) not in sys.path:
    sys.path.insert(0, str(HERE.parent))

from editorial_shell import Claim  # noqa: E402
import wp_post  # noqa: E402

SLUG = "the-double-day-8-check-yourself-before-you-wreck-yourself"
SOURCE = wp_post.load(SLUG)
OUTPUT_PATH = wp_post.output_path(SLUG)

ALT = {
    "mogollon-1": "Strava screenshot of Matti Rowe's ride \"Dag 7: Mogollonnnnnnnnn\", April 27, 2022, Silver City, New Mexico: 101.75 mi, 4:09:00 moving time, 5,052 ft of climbing, 264 W weighted average power; the route runs north-west from Silver City and the elevation profile ends on a steep climb.",
    "mogollon-2": "TrainingPeaks file \"Gila St1\", April 27, 2022: 4:09:03, 102 mi, 240 TSS, 274 W normalized power, 2.88 W/kg, average power 226 W and heart rate 140 bpm, with the power and heart-rate traces; a cartoon Gravel God in a cowboy hat stands with his bike beside the stats.",
    "23f1958f-4a86-4717-ae65-7889b6ded975-scaled": "The author in a black T-shirt laughs in front of a blue wall painted with a large lizard, his daughter holding balloons beside him and his son walking off with more balloons.",
}

DESCRIPTION = ("Day 8 of The Double: Tour of the Gila stage 1 to Mogollon, 24th place for the author, "
               "the green jersey for a teammate, and bedtime negotiations with his son.")

# The "In short" rule (wp_post docstring); section = 0-based h2 index.
IN_SHORT = (
    Claim("The author placed 24th on Tour of the Gila stage 1, his best UCI result, and teammate Henry York won the green jersey.",
          "#how-did-i-do", "See the result · Intro", 0),
    Claim("The post says the author produced decent numbers under fatigue, which it calls the point he presses on the athletes he coaches.",
          "#mediocre-power-reveal-inner-race-commentary", "See the numbers · §01", 0),
)


def render() -> str:
    return wp_post.render_post(SOURCE, alt=ALT, in_short=IN_SHORT, description=DESCRIPTION)


def main() -> None:
    wp_post.write(OUTPUT_PATH, render())


if __name__ == "__main__":
    main()
