"""Imported WordPress post: https://gravelgodcycling.com/to-make-it-count-flip-the-switch/

Generated by scripts/wp_post_import.py 2414; the body (to-make-it-count-flip-the-switch.body.html) and
metadata (to-make-it-count-flip-the-switch.json) are regenerated by the converter, this file is not.
ALT is written from what each image shows. IN_SHORT is a DRAFT for Matt's
read: plain, third-person statements of what the post argues, each one
supported by the post text. The post has no headings (one section), so the
links point at the image or figure nearest each point.

Infographic (2026-10-09): fig-switch-hours, the post's own January-to-April
arithmetic as bars. Every number is stated in the post (80 days / 11 weeks,
58, 50 days; 75 hours, 60 hours, about 80% quality); nothing is derived.

DESCRIPTION replaces the live meta description ("The racing mindset switch:
how to access real intensity when the effort actually matters. Training is
practice, racing is war."): the post is not about race-day intensity. Its
Switch is the move from offseason indulgence to everyday discipline.

Regenerate: python3 wordpress/post_sources/to_make_it_count_flip_the_switch.py
"""
from __future__ import annotations

import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
if str(HERE.parent) not in sys.path:
    sys.path.insert(0, str(HERE.parent))

from editorial_shell import Claim  # noqa: E402,F401
import wp_post  # noqa: E402
from wp_post import HtmlFigure  # noqa: E402

SLUG = "to-make-it-count-flip-the-switch"
SOURCE = wp_post.load(SLUG)
OUTPUT_PATH = wp_post.output_path(SLUG)

ALT = {
    "the-switch": "Two white wall light switches, the left one off and the right one on, with a cartoon Gravel God in a cowboy hat shrugging between them.",
    "the-switch-1": "Cartoon Gravel God in a cowboy hat grins beside an old beige punch-clock time recorder: \"Punch in.\"",
    "the-switch-2": "Friends dance with sparklers at a night party under string lights; cartoon Gravel God, at the edge, asks: \"You know you have to train tomorrow, right?\"",
    "ritual": "A candlelit wooden table with a skull, runes and a pentagram; cartoon Gravel God, seen from behind, says: \"Whoops wrong visual.\"",
    "the-switch-3": "A bearded man in pajama pants and a yellow T-shirt lounges on a grey sofa with a laptop and a mug of beer, saying \"Back in 2010 I rode 5 hours a day.\" Cartoon Gravel God watches from the left.",
    "the-switch-4": "A snowy waterfall under a night sky streaked with aurora, with the words \"The trouble is, you think you have time.\" in glowing red; a tiny cartoon Gravel God stands at the cliff edge.",
    "the-switch-5": "Cartoon Gravel God in a cowboy hat rides a bike down a quiet paved country road at sunrise, under a sweep of high cloud.",
}

# Figures this module adds (excluded from the word-for-word text diff).
ADDED_IDS = {"fig-switch-hours"}

# DRAFT for Matt: matter-of-fact statements of what the post argues;
# section = 0-based h2 index (the post has one section).
IN_SHORT = (
    Claim("The post describes &ldquo;the Switch&rdquo;: standards may slip in the offseason, but once it is flipped, distractions and vices stop.",
          "#fig-the-switch-1", "See the Switch", 0),
    Claim("Occasional Rituals such as a birthday or wedding are an exception; a Ritual repeated every night becomes a habit and loses the Switch.",
          "#fig-ritual", "See Rituals", 0),
    Claim("By the post&rsquo;s arithmetic, 80 days to an April race leave about 75 training hours, closer to 60 after skipped work.",
          "#fig-switch-hours", "See the arithmetic", 0),
)

# ── fig-switch-hours: the post's arithmetic as bars ──────────
# (label, value as stated, number, group max). Each number is the post's.
DAYS = (
    ("From now to April, roughly 11 weeks", "~80 days", 80),
    ("Rest twice a week", "58 days", 58),
    ("At least 8 days missed: sickness, family and friends, mechanicals", "50 days", 50),
)
HOURS = (
    ("50 days at one and a half hours a workout", "75 hours", 75),
    ("After skipped intervals, cut rides and skipped sessions, at about 80% quality", "~60 hours", 60),
)


def _group(title: str, rows, top: float, start: int) -> str:
    items = []
    for i, (label, value, n) in enumerate(rows):
        items.append(
            f'<li><span class="sw-label">{label}</span>'
            f'<span class="sw-track"><span class="sw-bar" data-draw="grow-x" '
            f'style="width:{100 * n / top:.1f}%;--draw-i:{start + i}"></span></span>'
            f'<span class="sw-val">{value}</span></li>')
    return f'<p class="sw-h">{title}</p><ol class="sw-bars">{"".join(items)}</ol>'


HOURS_FIGURE = HtmlFigure(
    id="fig-switch-hours",
    kicker="The arithmetic above, as bars",
    title="January to an April race: how much training is left",
    html=_group("Training days", DAYS, 80, 0) + _group("Training hours", HOURS, 75, len(DAYS)),
    caption_html=("Numbers as the post states them, for a race in April counted from January. "
                  "Bars compare within each group."),
    after="that you can’t look at.</p>",
)

CSS = """
.sw-h{font:700 14px var(--mono);letter-spacing:.08em;text-transform:uppercase;color:var(--ink3);margin:6px 0 6px}
.sw-bars{list-style:none;margin:0 0 14px;padding:0}
.sw-bars li{display:grid;grid-template-columns:minmax(0,1.2fr) minmax(0,1fr) 90px;align-items:center;gap:12px;padding:6px 0;margin:0}
.sw-label{font:400 15px/1.35 var(--mono);color:var(--ink)}
.sw-val{font:700 14px/1.35 var(--mono);color:var(--ink2)}
.sw-track{position:relative;height:16px;background:var(--sand2)}
.sw-bar{position:absolute;left:0;top:0;bottom:0;background:var(--teal)}
@media (max-width:640px){
  .sw-bars li{grid-template-columns:minmax(0,1fr) auto;grid-template-areas:"label val" "track track";row-gap:4px}
  .sw-label{grid-area:label}.sw-track{grid-area:track}.sw-val{grid-area:val}
}
"""

DESCRIPTION = ("The post argues for ending the offseason with a switch to strict discipline, "
               "keeping occasional rituals from becoming habits, and doing the work now.")


def render() -> str:
    return wp_post.render_post(SOURCE, alt=ALT, in_short=IN_SHORT, figures=(HOURS_FIGURE,), extra_css=CSS,
                              description=DESCRIPTION)


def main() -> None:
    wp_post.write(OUTPUT_PATH, render())


if __name__ == "__main__":
    main()
