"""Imported WordPress post: https://gravelgodcycling.com/tour-of-the-gila-stage-3-my-life-is-a-mistake/

Generated by scripts/wp_post_import.py 3631; the body and metadata
(tour-of-the-gila-stage-3-my-life-is-a-mistake.body.html / .json) are
regenerated by the converter, this file is not. ALT is written from what each
image shows; IN_SHORT follows the "In short" rule in wp_post (neutral, third person).

DESCRIPTION replaces the live meta description ("the Gila Monster stage, where
the climbs get personal"): Stage 3 in the post is the Tyrone time trial.

A 347-word post gets at most two "In short" claims. No infographic: the post
states no data.

Regenerate: python3 wordpress/post_sources/tour_of_the_gila_stage_3_my_life_is_a_mistake.py
"""
from __future__ import annotations

import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
if str(HERE.parent) not in sys.path:
    sys.path.insert(0, str(HERE.parent))

from editorial_shell import Claim  # noqa: E402
import wp_post  # noqa: E402

SLUG = "tour-of-the-gila-stage-3-my-life-is-a-mistake"
SOURCE = wp_post.load(SLUG)
OUTPUT_PATH = wp_post.output_path(SLUG)

ALT = {
    "tyrone-tt": "Black-and-white photo of the old \"Tyrone, New Mexico\" storefront with a \"No Over Night Parking\" sign, a Scott team tent and a pickup truck out front, and a colour cartoon Gravel God in a cowboy hat looking on from the left.",
    "gaslighting": "Text-message screenshot: \"Can't wait!! How was TT?\" The reply \"Today was the crit\", then \"No way! It happened already? Not at night?\", and a final profane reply marked Delivered; a grinning cartoon Gravel God head sits between the bubbles.",
    "trust-your-neighbor": "A printed sign taped inside the cracked rear window of a weathered soft-top 4x4 reads \"Trust your neighbor but brand your cows.\"; cartoon Gravel God's cowboy hat fills the bottom of the frame.",
    "the-tony": "A man in a purple Nature Sacks T-shirt feeds a card into the pay box of a self-serve car wash under its washing-instructions dial, a blue hose trailing away, while cartoon Gravel God in a cowboy hat watches from the left.",
}

DESCRIPTION = ("Tour of the Gila Stage 3: the Tyrone time trial, the UCI bike-check jig, a result the author "
               "calls an embarrassment, and the day's overheard quotes.")

# The "In short" rule (wp_post docstring); section = 0-based h2 index.
IN_SHORT = (
    Claim("Stage 3 was a time trial in Tyrone, New Mexico, which the post describes as another pass through the UCI bike-check jig.",
          "#what-was-it-like", "See What Was It Like? · §02", 1),
    Claim("The author calls his result a complete embarrassment and reports eating an entire carton of egg whites afterward.",
          "#shoot-me-what-i-hated-about-today", "See Shoot Me · §04", 3),
)


def render() -> str:
    return wp_post.render_post(SOURCE, alt=ALT, in_short=IN_SHORT, description=DESCRIPTION)


def main() -> None:
    wp_post.write(OUTPUT_PATH, render())


if __name__ == "__main__":
    main()
