"""Imported WordPress post: https://gravelgodcycling.com/tour-of-the-gila-inner-loop-road-race/

Generated by scripts/wp_post_import.py 3281; the body and metadata
(tour-of-the-gila-inner-loop-road-race.body.html / .json) are regenerated by
the converter, this file is not. ALT is written from what each image shows;
IN_SHORT follows the "In short" rule in wp_post (neutral, third person).

DESCRIPTION replaces the live meta description ("100 miles of New Mexico
desert racing with real tactics and punishing climbs"): the ride in the post's
Strava screenshot is 85.85 mi, and the post is about the 80-man pile-up.

The five gallery photos (Silver City, after the stage) render as one figure
grid; the featured image (diesel-daddy) is one of them, so the page has no hero.
No infographic: the post states no figures a chart would clarify.

Regenerate: python3 wordpress/post_sources/tour_of_the_gila_inner_loop_road_race.py
"""
from __future__ import annotations

import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
if str(HERE.parent) not in sys.path:
    sys.path.insert(0, str(HERE.parent))

from editorial_shell import Claim  # noqa: E402
import wp_post  # noqa: E402

SLUG = "tour-of-the-gila-inner-loop-road-race"
SOURCE = wp_post.load(SLUG)
OUTPUT_PATH = wp_post.output_path(SLUG)

ALT = {
    "the-pileup": "Strava screenshot of Matti Rowe's ride \"Day 2: The Pile Up\", April 27, 2023, Gila National Forest, New Mexico: 85.85 mi, 3:43:18 moving time, 5,630 ft of climbing, 264 W weighted average power, 23.1 mi/h average and 54.6 mi/h max, with a 9th overall on one segment and three PRs. A cartoon Gravel God in a cowboy hat rides a bike in front.",
    "silver-city": "A small pink stucco house with a white screen door, a string of red chiles by the door and prickly-pear cactuses by the steps; a cartoon Gravel God in a cowboy hat and shorts stands in the doorway.",
    "woom-brooms": "Two riders pose with a bike on a sunny street: one in red Rio Grande kit, his head a grinning cartoon Gravel God in a cowboy hat, the other in a green jersey, helmet and sunglasses.",
    "ethan-ow-ow-ow-scaled": "A shirtless rider with a mullet and sunglasses, seen from behind, his shoulder and upper back scraped raw with road rash.",
    "taj2-scaled": "A shirtless rider grins and flashes peace signs at the camera in front of a team tent and race bikes, a teammate in a red Rio Grande T-shirt standing behind him.",
    "diesel-daddy": "A rider in red Rio Grande kit leans forward with his hands on his knees, his head a cartoon Gravel God in a cowboy hat, while a teammate sits on a low wall behind him with his head down.",
}

DESCRIPTION = ("Tour of the Gila Inner Loop road race: an 80-man pile-up, a teammate's broken wrist, "
               "and the author hanging on to finish with the lead group.")

# The "In short" rule (wp_post docstring); section = 0-based h2 index. A
# 521-word post gets at most two claims (wp_post.SHORT_POST_MAX_CLAIMS).
IN_SHORT = (
    Claim("The author finished with the lead group despite struggling on the rollers in the last 10 miles back to the finish.",
          "#how-did-i-do", "See how he did · §03", 2),
    Claim("The post describes an 80-man pile-up in which teammate Ethan, the team&rsquo;s best-placed rider overall, broke his wrist.",
          "#what-i-hated-about-today", "See the crash · §05", 4),
)


def render() -> str:
    return wp_post.render_post(SOURCE, alt=ALT, in_short=IN_SHORT, description=DESCRIPTION)


def main() -> None:
    wp_post.write(OUTPUT_PATH, render())


if __name__ == "__main__":
    main()
