"""Imported WordPress post: https://gravelgodcycling.com/tour-of-the-gila-the-mogollon/

Generated by scripts/wp_post_import.py 3335; the body and metadata
(tour-of-the-gila-the-mogollon.body.html / .json) are regenerated by the
converter, this file is not. ALT is written from what each image shows;
IN_SHORT follows the "In short" rule in wp_post (neutral, third person).
A 517-word post: at most two claims. Ten photos are a gallery (the noscript
duplicates are deduped by the converter).

DESCRIPTION replaces the live meta description ("5 miles straight up at
altitude"): the post states no climb length; it calls the stage a
90-something-mile road race with a finishing climb.
No infographic. The Strava screenshot shows 74.21 mi, which the post explains
("my Garmin pooped out before the Mog").

Regenerate: python3 wordpress/post_sources/tour_of_the_gila_the_mogollon.py
"""
from __future__ import annotations

import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
if str(HERE.parent) not in sys.path:
    sys.path.insert(0, str(HERE.parent))

from editorial_shell import Claim  # noqa: E402
import wp_post  # noqa: E402

SLUG = "tour-of-the-gila-the-mogollon"
SOURCE = wp_post.load(SLUG)
OUTPUT_PATH = wp_post.output_path(SLUG)

DESCRIPTION = ("Tour of the Gila 2023, the Mogollon stage: a 90-plus-mile road race with a finishing climb, "
               "the author's result, quotes from the team, and Silver City scenes.")  # <=160 chars

ALT = {
    "got-any-meelahrs": "Strava activity \"Stage 1: 'Got any MeeLahrs in Der?'\", Wednesday, April 26, 2023, Silver City, New Mexico: 74.21 mi, 3:00:19 moving time, 2,910 ft of climbing, 226 W weighted average power; cartoon Gravel God in a cowboy hat pops a wheelie at the right.",
    "do-you-even-lift-bro": "A weathered home gym on a backyard deck under a tree: a white weight-stack machine, dumbbells and a rowing machine, with cartoon Gravel God in a cowboy hat, arms folded, in front.",
    "abq-burritoes-scaled": "A store rack stacked with bags of large flour tortillas under a Coca-Cola sign, priced $2.99: \"Albuquerque burrito style tortillas\".",
    "the-food-basket": "A smiling young man in a navy T-shirt stands in the parking lot of the Food Basket grocery store under a clear blue sky; cartoon Gravel God's cowboy hat is in the corner.",
    "porch-treadmill": "A treadmill, a stationary bike and a small table on the peeling red porch of a brick house, with cartoon Gravel God in a cowboy hat standing among them.",
    "straight-zonked": "A teal-walled bedroom with a fold-down bed, two bikes against the wall and a TV; cartoon Gravel God in a cowboy hat lies asleep on the bed.",
    "ethan-anger-haircut-scaled": "A young man with a fresh mullet, shaved on the side, sits at a kitchen table in a red T-shirt, hand on his chin, staring at a plate of food.",
    "jesus-candles": "Grocery shelves packed with religious prayer candles, saints and the Virgin of Guadalupe on the glass jars, with cartoon Gravel God's cowboy hat in the foreground.",
    "numbasssss-scaled": "Three Tour of the Gila race numbers, all 122, two body numbers and a bike plate, laid out on a grey sheet.",
    "701-cooper": "A small pink stucco house behind a chain-link fence on a bright day, with cartoon Gravel God in a cowboy hat grinning on the sidewalk in front.",
    "superman": "A rider in a red and blue jersey stands on the top step of the Tour of the Gila podium with both arms raised, the UCI America Tour sponsor board behind him; riders in the crowd watch, cartoon Gravel God among them.",
}

# The "In short" rule (wp_post docstring); section = 0-based h2 index.
IN_SHORT = (
    Claim("The author made it over the first climb just behind the front group, then fell back once the final climb began.",
          "#how-did-i-do", "See §03", 2),
    Claim("The post says the author has raced the Mogollon stage seven times without ever seeing the town of Mogollon.",
          "#what-i-hated-about-today", "See §05", 4),
)


def render() -> str:
    return wp_post.render_post(SOURCE, alt=ALT, in_short=IN_SHORT, description=DESCRIPTION)


def main() -> None:
    wp_post.write(OUTPUT_PATH, render())


if __name__ == "__main__":
    main()
