"""Imported WordPress post: https://gravelgodcycling.com/tour-of-the-gila-stage-1-full-tilt-like-a-peter-built/

Generated by scripts/wp_post_import.py 3653; the body and metadata
(tour-of-the-gila-stage-1-full-tilt-like-a-peter-built.body.html / .json) are
regenerated by the converter, this file is not. ALT is written from what each
image shows; IN_SHORT follows the "In short" rule in wp_post (neutral, third
person).

DESCRIPTION replaces the live meta description ("full gas from the start,
lessons in managing aggression"); the post describes the opposite: an easy
first half and a hard second half.

The featured image is also the first inline image, so the page has no hero.
No infographic: the post states no figures a chart would clarify.

Regenerate: python3 wordpress/post_sources/tour_of_the_gila_stage_1_full_tilt_like_a_peter_built.py
"""
from __future__ import annotations

import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
if str(HERE.parent) not in sys.path:
    sys.path.insert(0, str(HERE.parent))

from editorial_shell import Claim  # noqa: E402
import wp_post  # noqa: E402

SLUG = "tour-of-the-gila-stage-1-full-tilt-like-a-peter-built"
SOURCE = wp_post.load(SLUG)
OUTPUT_PATH = wp_post.output_path(SLUG)

ALT = {
    "lol": "The Tour of the Gila 2024 podium backdrop, a UCI America Tour board covered in sponsor logos, on a trailer in a race parking lot, with a bike on a car roof rack in the foreground. A cartoon Gravel God in a cowboy hat, white tee and short shorts stands on the stage under big white letters: \"LOL!\"",
    "lol-1": "A shirtless rider in green shorts and red-lensed sunglasses, a black eight-pointed star tattooed on his stomach and a sheep on his forearm, holds a water bottle in a gravel parking lot full of team vans and riders. A cartoon Gravel God in a cowboy hat stands at the left, hand on his chin.",
}

DESCRIPTION = ("Tour of the Gila Stage 1: an easy first half, a hard, strung-out run to the final "
               "Mogollon climb, and lines overheard in the race and at the team house.")

# The "In short" rule (wp_post docstring); section = 0-based h2 index. A
# 663-word post gets at most two claims (wp_post.SHORT_POST_MAX_CLAIMS).
IN_SHORT = (
    Claim("The post describes Stage 1 as easy for its first half and a nightmare in the second half leading to the Mogollon climb.",
          "#what-do", "See the stage · §01", 0),
    Claim("Afterward, the author says he would rather race moderately hard all day than coast for two hours and then suffer for two.",
          "#shoot-me-what-i-hated-about-today", "See what he hated · §04", 3),
)


def render() -> str:
    return wp_post.render_post(SOURCE, alt=ALT, in_short=IN_SHORT, description=DESCRIPTION)


def main() -> None:
    wp_post.write(OUTPUT_PATH, render())


if __name__ == "__main__":
    main()
