"""Imported WordPress post: https://gravelgodcycling.com/tour-of-the-gila-stage-5-the-big-sad/

Generated by scripts/wp_post_import.py 3673; the body and metadata
(tour-of-the-gila-stage-5-the-big-sad.body.html / .json) are regenerated by the
converter, this file is not. ALT is written from what each image shows;
IN_SHORT follows the "In short" rule in wp_post (neutral, third person).

DESCRIPTION replaces the live meta description, which promises "what five days
of racing teaches you"; the post has no such lessons. It is a stage report:
positioning, 50th overall, quotes from the race and dinner.

The featured image is also the first inline image, so the page has no hero.
No infographic: the post states no figures a chart would clarify.

Regenerate: python3 wordpress/post_sources/tour_of_the_gila_stage_5_the_big_sad.py
"""
from __future__ import annotations

import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
if str(HERE.parent) not in sys.path:
    sys.path.insert(0, str(HERE.parent))

from editorial_shell import Claim  # noqa: E402
import wp_post  # noqa: E402

SLUG = "tour-of-the-gila-stage-5-the-big-sad"
SOURCE = wp_post.load(SLUG)
OUTPUT_PATH = wp_post.output_path(SLUG)

ALT = {
    "are-you-all-alive": "The Rio Grande team after the stage, in a mountain town: five riders in red Rio Grande kit and a teammate in a red shirt pose with an older couple in yellow and pink shirts beside a white race bike, a cargo bike behind them. One rider's face is a cartoon Gravel God in a cowboy hat.",
    "early-pain": "Race photo of a small group on a desert highway, mountains behind: a rider in red-and-white Rio Grande kit, his head a cartoon Gravel God in a cowboy hat, rides between a Landis Cyclery rider and riders in dark blue and teal kits.",
    "one-pounder-scaled": "A mustached teammate in a mauve T-shirt grins at the camera, both hands around a towering cheese-covered burger, a plate of fries in front of him, in a small diner.",
    "fikk-den-gjort": "A rider in Rio Grande kit, his face a cartoon Gravel God in a cowboy hat, rolls up the road from the Tour of the Gila 2024 finish arch and race clock, spectators at the orange barriers and pine-covered mountains behind.",
    "that-guy": "An open black toiletry bag on a table, stuffed with a Philips electric shaver, a toothpaste tube, a body-wash bottle and other toiletries.",
}

DESCRIPTION = ("Tour of the Gila Stage 5, the final road race: poor positioning, 50th overall, "
               "and lines overheard in the race and at the post-race dinner.")

# The "In short" rule (wp_post docstring); section = 0-based h2 index. A
# 406-word post gets at most two claims (wp_post.SHORT_POST_MAX_CLAIMS).
IN_SHORT = (
    Claim("The author names poor positioning, again, as what undid his good legs on the final stage.",
          "#shoot-me-what-i-hated-about-today", "See what he hated · §04", 3),
    Claim("The author finished 50th in the overall classification, which the post calls perfectly mid.",
          "#hold-me-what-i-loved-about-today", "See what he loved · §05", 4),
)


def render() -> str:
    return wp_post.render_post(SOURCE, alt=ALT, in_short=IN_SHORT, description=DESCRIPTION)


def main() -> None:
    wp_post.write(OUTPUT_PATH, render())


if __name__ == "__main__":
    main()
