"""Imported WordPress post: https://gravelgodcycling.com/tour-of-the-gila-tyrone-time-trial/

Generated by scripts/wp_post_import.py 3278; the body and metadata
(tour-of-the-gila-tyrone-time-trial.body.html / .json) are regenerated by the
converter, this file is not. ALT is written from what each image shows;
IN_SHORT follows the "In short" rule in wp_post (neutral, third person).
A 656-word post: at most two claims. The four photos are a gallery.

DESCRIPTION replaces the live meta description ("a New Mexico mine road with
2,000 feet of climbing"): the post mentions neither a mine road nor the
climbing; it calls the course a 25 km time trial through a canyon.
No infographic.

Regenerate: python3 wordpress/post_sources/tour_of_the_gila_tyrone_time_trial.py
"""
from __future__ import annotations

import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
if str(HERE.parent) not in sys.path:
    sys.path.insert(0, str(HERE.parent))

from editorial_shell import Claim  # noqa: E402
import wp_post  # noqa: E402

SLUG = "tour-of-the-gila-tyrone-time-trial"
SOURCE = wp_post.load(SLUG)
OUTPUT_PATH = wp_post.output_path(SLUG)

DESCRIPTION = ("Tour of the Gila 2023, the Tyrone Time Trial: a 25 km time trial through a canyon, "
               "the author's best Tyrone TT with a mediocre result, and quotes from the team.")

ALT = {
    "screenshot-2023-04-29-at-14-55-07": "Strava activity \"Day 3: More Blessings\", Friday, April 28, 2023, Grant County, New Mexico: 35.03 mi, 1:43:45 moving time, 2,441 ft of climbing, 258 W weighted average power, 1,374 kJ; clear, 16 °C.",
    "untitled-design-5": "Cartoon Gravel God's head on a rider in red Rio Grande kit, sitting on a black time-trial bike with a disc wheel in a sunny parking lot full of team vans and tents.",
    "untitled-design-7": "A front-yard work session: two riders crouch on a brick path fixing a disc wheel and a bike on a red repair stand, while a third, his arm in a sling, stands by on the phone.",
    "untitled-design-6": "A rider in a red sugar-skull T-shirt, green shorts and sandals, his right forearm in a cast, looks at his phone on the sidewalk in front of a pink stucco house.",
    "untitled-design-8": "A team house kitchen: a tub of cooked spaghetti on the counter, riders chatting by the stove and the dining table, and cartoon Gravel God in a cowboy hat in the foreground, seen from behind.",
}

# The "In short" rule (wp_post docstring); section = 0-based h2 index.
IN_SHORT = (
    Claim("The post calls the Tyrone Time Trial a 25 km course and the author&rsquo;s ride his best Tyrone TT, with a mediocre result.",
          "#how-did-i-do", "See §03", 2),
    Claim("A teammate who broke his wrist in the stage 2 crash later had his thumb bent in a mosh pit.",
          "#what-i-loved-about-today", "See §07", 6),
)


def render() -> str:
    return wp_post.render_post(SOURCE, alt=ALT, in_short=IN_SHORT, description=DESCRIPTION)


def main() -> None:
    wp_post.write(OUTPUT_PATH, render())


if __name__ == "__main__":
    main()
