"""Imported WordPress post: https://gravelgodcycling.com/tour-of-the-gila-the-gila-monster/

Generated by scripts/wp_post_import.py 3306; the body and metadata
(tour-of-the-gila-the-gila-monster.body.html / .json) are regenerated by the
converter, this file is not. ALT is written from what each image shows;
IN_SHORT follows the "In short" rule in wp_post (neutral, third person).

The live meta description is kept: it is generic but not wrong.

The featured image (sheeeee) is one of the gallery photos, so the page has no
hero. No infographic.

For Matt (numbers, text unchanged): the text gives the stage as "100 miles with
10,000 feet of climbing" and an average race temperature of 88 F (high 106 F);
the Strava screenshot shows 111.03 mi, 9,255 ft and a weather panel of 20 °C.

Regenerate: python3 wordpress/post_sources/tour_of_the_gila_the_gila_monster.py
"""
from __future__ import annotations

import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
if str(HERE.parent) not in sys.path:
    sys.path.insert(0, str(HERE.parent))

from editorial_shell import Claim  # noqa: E402
import wp_post  # noqa: E402

SLUG = "tour-of-the-gila-the-gila-monster"
SOURCE = wp_post.load(SLUG)
OUTPUT_PATH = wp_post.output_path(SLUG)

ALT = {
    "nobody-home": "Strava screenshot of Matti Rowe's ride \"Stage 5: Nobody Home\", 9:01 AM on Sunday, April 30, 2023, Silver City, New Mexico: 111.03 mi, 5:19:49 moving time, 9,255 ft of climbing, 242 W weighted average power, 3,951 kJ, 6:30:32 elapsed, weather clear and 20 °C; cartoon Gravel God in a cowboy hat shrugs in front of it.",
    "gang": "Teammates in red Rio Grande kit sit in the dirt against an open car hatch after the stage, one standing behind with his arms raised; cartoon Gravel God's face in a cowboy hat is pasted on the rider sitting at left.",
    "701-cooper-st": "A pink stucco house on a sunny Silver City street, teammates in red loading a car at the curb and a tiny cartoon Gravel God riding up the road.",
    "tajjjj-scaled": "A young teammate in a white helmet, orange-lens sunglasses and the red Rio Grande jersey tips his glasses at the camera.",
    "salty-boii-scaled": "A rider bends over to show the seat of his black bib shorts caked in white salt, while teammates stand by a car on a dirt road.",
    "sheeeee": "A rider in red Rio Grande kit, with cartoon Gravel God's face in a cowboy hat pasted on, strikes a dance pose on a dusty lot, arm flung out, a team van behind him.",
    "sam-1-scaled": "Close-up from above of a sweaty, exhausted teammate in a red Rio Grande jersey sitting in the dirt, hugging his knees, bottles at his feet.",
    "defeat": "A breakfast table with a full bowl of oatmeal, a can of Red Bull, a copper French press and a Starbucks mug; the top of cartoon Gravel God's cowboy hat peeks up from below the table edge.",
    "james-scaled": "Seen from above, a shirtless rider in white sunglasses and a white helmet sits hunched in the dirt, arms wrapped around his knees.",
}

# The "In short" rule (wp_post docstring); section = 0-based h2 index. A
# 720-word post gets at most two claims (wp_post.SHORT_POST_MAX_CLAIMS).
IN_SHORT = (
    Claim("The author finished 47th on the Gila Monster stage and 37th of 115 starters overall, after what the post calls an utter collapse.",
          "#how-did-i-do", "See the result · §03", 2),
    Claim("The post reports an average race temperature of 88 F, with a high of 106 F, and links it to the cramping.",
          "#mediocre-power-reveal-inner-race-commentary", "See the passage · §06", 5),
)


def render() -> str:
    return wp_post.render_post(SOURCE, alt=ALT, in_short=IN_SHORT)


def main() -> None:
    wp_post.write(OUTPUT_PATH, render())


if __name__ == "__main__":
    main()
