"""Imported WordPress post: https://gravelgodcycling.com/tour-of-the-gila-silver-city-criterium/

Generated by scripts/wp_post_import.py 3297; the body and metadata
(tour-of-the-gila-silver-city-criterium.body.html / .json) are regenerated by
the converter, this file is not. ALT is written from what each image shows;
IN_SHORT follows the "In short" rule in wp_post (neutral, third person).

A Tour of the Gila 2023 post. Its two closing photos were an Elementor gallery
and render as a figure grid; the first of them is the featured image, so the
page has no hero. A 469-word post gets at most two "In short" claims.

DESCRIPTION replaces the live meta description ("short, fast, and chaotic.
What happens when stage racers try to sprint"): the post is about riding at the
back of a 90-minute crit and finishing in the bunch, not about sprinting.

Matt to read (minor): the text describes laps "at 29 mph for 90 minutes"; the
Strava screenshot shows 48.98 mi at 24.6 mi/h average over 1:59:25 moving
(likely including riding to and from the course).

No infographic: the post states no data worth charting.

Regenerate: python3 wordpress/post_sources/tour_of_the_gila_silver_city_criterium.py
"""
from __future__ import annotations

import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
if str(HERE.parent) not in sys.path:
    sys.path.insert(0, str(HERE.parent))

from editorial_shell import Claim  # noqa: E402
import wp_post  # noqa: E402

SLUG = "tour-of-the-gila-silver-city-criterium"
SOURCE = wp_post.load(SLUG)
OUTPUT_PATH = wp_post.output_path(SLUG)

ALT = {
    "untitled-design-10": "Strava activity \"Stage 4: Circle Rhizzing\", Saturday, April 29, 2023, Silver City, New Mexico: 48.98 mi, 1:59:25 moving time, 2,500 ft, 239 W weighted average power, 24.6 mi/h average; cartoon Gravel God in a cowboy hat puffs a cigar on the right.",
    "untitled-design-11": "Cartoon Gravel God in a cowboy hat stands on a sidewalk beside a sky-blue adobe building painted with a big black-and-white lizard curled in a circle and a white bear, under a deep blue sky.",
    "untitled-design-14": "A mustached man in a tan cap with blue mirrored sunglasses takes a selfie on a porch hung with dried red chiles, while a man with cartoon Gravel God's face and cowboy hat leans on a white post behind him, holding a coffee cup.",
}

DESCRIPTION = ("The Tour of the Gila's Silver City criterium: 90 minutes of laps on a rough, hilly circuit, "
               "a finish in the bunch, and the quotes of the day.")

# The "In short" rule (wp_post docstring); section = 0-based h2 index.
IN_SHORT = (
    Claim("The post describes the criterium as about 90 minutes of laps on a short circuit with potholes, cracks and steep little climbs.",
          "#what-was-it-like", "See What was it like? · §02", 1),
    Claim("The author finished with the pack in the bunch sprint, which the post counts as a good result for a dad.",
          "#how-did-i-do", "See How did I do? · §03", 2),
)


def render() -> str:
    return wp_post.render_post(SOURCE, alt=ALT, in_short=IN_SHORT, description=DESCRIPTION)


def main() -> None:
    wp_post.write(OUTPUT_PATH, render())


if __name__ == "__main__":
    main()
