"""Imported WordPress post: https://gravelgodcycling.com/what-is-hrv-and-why-should-i-care/

Generated by scripts/wp_post_import.py 2521; the body and metadata
(what-is-hrv-and-why-should-i-care.body.html / .json) are regenerated by the
converter, this file is not. ALT is written from what each image shows (the
charts' axes and labels read off the images); IN_SHORT follows the "In short"
rule in wp_post (neutral, third person). The live meta description is kept.

Infographic (2026-10-09): fig-load-patterns, the post's four loading/unloading
patterns side by side. Every cell is the post's own wording from its four
lists; nothing is computed. The HRV charts are not redrawn: they are
screenshots without readable values for most points.

Corrected 2026-10-09 (Matt approved): CORRECTIONS below changes the two pre-SNS claims to
"the year before SNS" (the long-range chart's 2021 stretch: HRV mostly under
90 and under the pulse line; 2020 went past 150); each
entry names its evidence. The page notes the correction at the end.

Regenerate: python3 wordpress/post_sources/what_is_hrv_and_why_should_i_care.py
"""
from __future__ import annotations

import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
if str(HERE.parent) not in sys.path:
    sys.path.insert(0, str(HERE.parent))

from editorial_shell import Claim, DataTable, TableCell, TableColumn, TableRow  # noqa: E402
import wp_post  # noqa: E402

SLUG = "what-is-hrv-and-why-should-i-care"
SOURCE = wp_post.load(SLUG)
OUTPUT_PATH = wp_post.output_path(SLUG)

ALT = {
    "y-should-i-care": "\"WHY SHOULD I CARE?\" chalked on a blackboard, a stopwatch standing in for the O, with cartoon Gravel God in a cowboy hat shrugging beside it.",
    "big-load": "A flatbed truck stacked with wrapped pallets on a mountain road, and cartoon Gravel God in a cowboy hat saying, \"Whooee-uueet!! That's a big load!\"",
    "analyse": "Cartoon Gravel God in a cowboy hat studies a wall of trading screens full of price charts.",
    "hrv-1": "Cartoon Gravel God in a cowboy hat stands between a glowing up arrow labelled \"HRV\" and a down arrow labelled \"Resting HR\".",
    "hrv-20-22": "Line chart titled \"HRV '20-'22\": daily HRV (yellow) and resting heart rate (light blue) from mid-2020 to early 2022, with a gap from late 2020 to spring 2021 where cartoon Gravel God stands.",
    "hrv-garbage": "Black-and-white photo of an overflowing dumpster in a grassy field, with \"HRV\" printed on its side.",
    "hrv-case-study": "Wooden letter tiles spelling \"CASE STUDY\" on a grid notebook beside a coffee cup, glasses and a phone, with cartoon Gravel God grinning in the corner.",
    "hrv-trend": "Close-up of the HRV chart: HRV in yellow on a left axis from 50 to 150 and pulse in light blue on a right axis from 45 to 70 BPM, two dense clusters of daily points with a gap between them.",
    "hrv-zoom": "Whoop chart, \"Last 90 days\", January 4 to March 15, 2022: HRV in yellow and resting heart rate in light blue, annotated \"Standard, Not Sober begins\" at the start and \"COVID\" at a resting-heart-rate spike around January 22; the yellow line climbs in the later weeks.",
    "hrv-invest": "Cartoon Gravel God, hand on chin, in front of blurred stacks of coins and a rising line chart.",
    "hrv": "A red heartbeat trace running across a dark monitor grid, with cartoon Gravel God in a cowboy hat smiling at the right.",
}

# The "In short" rule (wp_post docstring); section = 0-based h2 index.
IN_SHORT = (
    Claim("The post defines HRV as the irregular rhythm of heartbeats, a window into the interplay of the parasympathetic and sympathetic nervous systems.",
          "#what-the-hell-is-hrv", "See the definition · §01", 0),
    Claim("It argues that Total Load, training stress plus life stress, is usually the real culprit when an athlete bombs an important event.",
          "#loads-on-loads-on-loads", "See the argument · §03", 2),
    Claim("The post advises using HRV first as a marker of health and second as a fitness indicator, not to decide each day&rsquo;s training.",
          "#hrv-interpretation", "See the interpretation · §04", 3),
    Claim("After the author cut his drinking, his HRV rose 34 percent and his resting heart rate fell five beats per minute in ten weeks.",
          "#hrv-case-study", "See the case study · §08", 7),
)

# ── fig-load-patterns: the four patterns, in the post's words ──
# (pattern, definition, what follows, who trains like this): verbatim from the lists.
PATTERNS = (
    ("Acute fatigue",
     "performing a singular hard workout that loads training stress above baseline.",
     "it may take 24-36 hours to recover and supercompensate above baseline.",
     "Exercisers and weekend warriors."),
    ("Functional Overreaching",
     "performing consecutive days (or weeks) of loading training stress with limited recovery",
     "the athlete supercompensates or adapts to a higher baseline of fitness",
     "The best athletes."),
    ("Non-functional Overreach",
     "Loading lots of training stress in a chronic and unstructured way.",
     "an athlete is putting forth a lot of effort for little to minimal gain.",
     "Type-A, self-driven uncoached athletes."),
    ("Clinically Overtrained",
     "Chronically overloading so much training stress with minimal to no deloading",
     "an athlete harms critical tissues for performance, recovery, and health, sometimes irreversibly.",
     "Few"),
)


def _q(text: str) -> TableCell:
    return TableCell(f"&ldquo;{text}&rdquo;")


LOAD_PATTERNS = DataTable(
    id="fig-load-patterns",
    kicker="The four lists above, side by side",
    title="Four ways to load and unload training stress",
    intro_html="Each pattern as the post defines it.",
    footnote_html="Every cell quotes the post&rsquo;s lists; quotes may be shortened, never reworded.",
    columns=(
        TableColumn("Pattern", card="title", sortable=False),
        TableColumn("Definition", card="row", sortable=False),
        TableColumn("What follows", card="row", sortable=False),
        TableColumn("Who trains like this?", card="row", sortable=False),
    ),
    rows=tuple(TableRow(cells=(TableCell(p), _q(d), _q(r), _q(w))) for p, d, r, w in PATTERNS),
    after="I’m getting there – this isn’t Twitter.</p>",
)

# Nothing in this table sorts, so the shell's "Click a column to sort" hint is hidden.
CSS = "#fig-load-patterns .gg-sort-hint{display:none}"


# Figures corrected to match the post's own evidence (Matt, 2026-10-09:
# "Yeah go ahead and fix"). wp_post applies each to the body (old text must
# occur exactly once) and the word-for-word tests apply them to the snapshot.
CORRECTIONS = (
    wp_post.Correction(
        "Clearly, before SNS, the yellow",
        "Clearly, in the year before SNS, the yellow",
        "the long-range chart (hrv-trend) has 2020 HRV above 150 and above the pulse line; the 2021 stretch before SNS stays under it"),
    wp_post.Correction(
        "Pre-SNS, at best my HRV wouldn’t break 90.",
        "In the year before SNS, my HRV rarely broke 90.",
        "hrv-trend: the 2021 stretch before SNS is mostly under 90 with a few points near 110-120; 2020 went past 150"),
)


def render() -> str:
    return wp_post.render_post(SOURCE, corrections=CORRECTIONS, alt=ALT, in_short=IN_SHORT, figures=(LOAD_PATTERNS,), extra_css=CSS)


def main() -> None:
    wp_post.write(OUTPUT_PATH, render())


if __name__ == "__main__":
    main()
