"""Imported WordPress post: https://gravelgodcycling.com/you-dont-need-to-bike-to-bike-fast/

Generated by scripts/wp_post_import.py 1431; the body (you-dont-need-to-bike-to-bike-fast.body.html) and
metadata (you-dont-need-to-bike-to-bike-fast.json) are regenerated by the converter, this file is not.
ALT is written from what each image shows. IN_SHORT is a DRAFT for Matt's
read: plain, third-person statements of what the post argues, each one
supported by the post text. No infographic: the post's three-reason
chalkboards already carry the structure, and it states no figures to chart.

Regenerate: python3 wordpress/post_sources/you_dont_need_to_bike_to_bike_fast.py
"""
from __future__ import annotations

import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
if str(HERE.parent) not in sys.path:
    sys.path.insert(0, str(HERE.parent))

from editorial_shell import Claim  # noqa: E402,F401
import wp_post  # noqa: E402

SLUG = "you-dont-need-to-bike-to-bike-fast"
SOURCE = wp_post.load(SLUG)
OUTPUT_PATH = wp_post.output_path(SLUG)

ALT = {
    "you-dont-need-to-bike-to-bike-fast": "A snowy forest trail; cartoon Gravel God in a cowboy hat stands arms crossed beside a pair of cross-country skis and poles and a mug of hot chocolate.",
    "you-dont-need-to-bike-to-bike-fast-1": "Cartoon Gravel God on a theatre stage between red curtains, flanked by tomatoes on stands, declaims: \"You didn't even love her Jake! You won't get away with this...\" A woman at the edge of the stage calls: \"And...Scene.\"",
    "you-dont-need-to-bike-to-bike-fast-2": "A big white question mark against a turquoise wall, with the text: \"How the hell was Jake Boyce so fast on skis when he never trained for Skiing but just rode his bike, and what the hell does this have to do with cycling training?\"",
    "you-dont-need-to-bike-to-bike-fast-3": "Chalkboard titled \"Reasons Jake Boyce was faster\" with cartoon Gravel God: \"He stole the love of my life!\" is crossed out and replaced by \"1. Cycling training made him fitter\".",
    "you-dont-need-to-bike-to-bike-fast-4": "Cartoon Gravel God beside a red classic Mustang with its hood up: a label \"Central\" points from his chest to the engine, and \"Periphery\" from his legs to the wheels.",
    "you-dont-need-to-bike-to-bike-fast-5": "The same chalkboard, now with a second reason: \"He's a terrible human being\" crossed out and replaced by \"2. Jake was happy training. I hated it.\"",
    "you-dont-need-to-bike-to-bike-fast-6": "Cartoon drawing of a hammer labelled \"Biking\" over a wooden table, nails driven into a plank labelled \"Fitness\".",
    "you-dont-need-to-bike-to-bike-fast-7": "The chalkboard with a third reason: \"Jake should never have been born\" crossed out and replaced by \"3. Bike racing made Jake a good racer.\"",
    "you-dont-need-to-bike-to-bike-fast-8": "Photo of a mass-start cross-country ski race climbing a snowy hill: an arrow labelled \"Jake\" points to a skier near the front, and \"Me (not pictured)\" points off the bottom-left edge.",
    "you-dont-need-to-bike-to-bike-fast-9": "Cartoon Gravel God in a snowy forest beside a pair of yellow snowshoes crossed out in red: \"But NO SNOWSHOEING! ANYTHING BUT THAT.\"",
}

# DRAFT for Matt: matter-of-fact statements of what the post argues;
# section = 0-based h2 index (the intro counts with the first section).
IN_SHORT = (
    Claim("The post credits a teammate&rsquo;s ski speed to cycling: training another endurance sport still builds central fitness in the heart, lungs and blood.",
          "#fig-you-dont-need-to-bike-to-bike-fast-3", "See reason one · §01", 0),
    Claim("It adds two more reasons: he enjoyed racing bikes, and bike racing&rsquo;s pack skills and pacing carried over to mass-start ski races.",
          "#fig-you-dont-need-to-bike-to-bike-fast-5", "See reasons two and three · §01", 0),
    Claim("Applied to cyclists, it recommends skiing, running, rowing or hiking in winter, with training growing more specific as the event approaches.",
          "#so-what-does-this-have-to-do-about-not-biking-to-bike-fast", "See §02", 1),
)


def render() -> str:
    return wp_post.render_post(SOURCE, alt=ALT, in_short=IN_SHORT)


def main() -> None:
    wp_post.write(OUTPUT_PATH, render())


if __name__ == "__main__":
    main()
