"""Imported WordPress post: https://gravelgodcycling.com/you-know-people-remember-how-you-race-right/

Generated by scripts/wp_post_import.py 1673; the body (you-know-people-remember-how-you-race-right.body.html) and
metadata (you-know-people-remember-how-you-race-right.json) are regenerated by the converter, this file is not.
Hand-edit ALT (one entry per image, written from what the image shows),
IN_SHORT (drafts restate the post's own words) and any infographics.

IN_SHORT (2026-10-09): matter-of-fact restatements for Matt's read.
Infographics: none. The post is a story with no data a figure would clarify.

Regenerate: python3 wordpress/post_sources/you_know_people_remember_how_you_race_right.py
"""
from __future__ import annotations

import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
if str(HERE.parent) not in sys.path:
    sys.path.insert(0, str(HERE.parent))

from editorial_shell import Claim  # noqa: E402
import wp_post  # noqa: E402

SLUG = "you-know-people-remember-how-you-race-right"
SOURCE = wp_post.load(SLUG)
OUTPUT_PATH = wp_post.output_path(SLUG)

ALT = {
    "so-long-suckas": "Cartoon Gravel God rides clear of a big crash in a road race, riders and bikes piled on the asphalt behind him and bananas on the road, and says: \"So long Suckasss!!\"",
    "hey-fubo-tv-who-is-laughing-now": "The Tiz-Cycling video site (\"Your #1 Source for Quality Cycling Videos\") with featured race videos and a Bredene Koksijde Classic 2021 live-stream banner; cartoon Gravel God says: \"Hey Fubo TV, who is laughing now???\"",
    "gammeldags-skiloper": "Old black-and-white photo of a woman in a long dark coat and hat skiing down a snowy slope with one long pole, another skier in a long dress behind her.",
    "screen-shot-2021-03-18-at-7-09-38-am": "A frame from NRK1's live TV coverage: skiers race through a sunny stadium lined with Coop banners below forested mountains; the clock reads 14:17.1.",
    "marit-bjorgen-rollerskiing": "Marit Bjørgen roller-skis uphill in a sports top and shorts, yellow helmet on, poles planted, every muscle showing.",
    "picture-035": "A group of shirtless, muscular skiers in shorts and sunglasses roller-ski up a road through summer woods.",
    "durian-rider": "Cartoon Gravel God stands beside a pair of skis and poles at a groomed ski track in snowy woods; at the left a man in a \"Go Vegan\" cycling jersey, a cigarette in his mouth, says: \"50 kilometers? Dassit? It would only take me like an hour to do that on a bike.\"",
    "klaebo-drama": "Animated: TV footage of the 50 km finish straight, a skier in Norway's white and blue beside a skier in Russia's red, a red circle drawn around their tangled skis and poles; cartoon Gravel God at the left says: \"Dramaaaaaa!!!!\"",
    "screen-shot-2021-03-07-at-7-42-17-am": "A skier in a red Russian race suit sits in the snow against a Stora Enso advertising board, one hand over his face, his skis propped beside him.",
    "screen-shot-2021-03-07-at-7-52-35-am": "A skier in red rests his head on a wooden barrier while another skier, in a 2021 World Championships Oberstdorf bib with skis and pink poles on his shoulder, leans over him.",
    "screen-shot-2021-03-07-at-8-25-51-am": "A Norwegian live blog: \"Vi vet fortsatt ikke endelig utfall på dette. 16:11 Enorm skuffelse: Her går Klæbo etter å ha fått den tunge beskjeden om at han mistet gullet\" (We still don't know the final outcome. 16:11 Huge disappointment: here goes Klæbo after the hard news that he lost the gold), above a photo of a skier in a Norge jacket walking away with two team staff.",
    "screen-shot-2021-03-18-at-10-32-58-am": "A frame from NRK's TV coverage of a relay finish in a packed stadium: a skier in red stands just short of the line, turned toward a skier in white closing in behind him; the finish clock reads 1:40:09.7.",
    "ulykket": "A crashed dark-grey car on a snowy roadside, its front crumpled and hood up, pinned against a broken guard rail.",
    "northug-cocaine": "The view through a car windshield following a white sports car down a two-lane highway; the head-up display, circled in red, shows 93 km/h.",
    "klaebo-interview-2": "Cartoon Gravel God shrugs in front of a Norwegian fjord, an oil platform on one side and a red cabin with a tin of snus on the other: \"Did they run out of oil $?\" \"Did they lose motivation when they ran out of snus?\"",
    "klaebo-interview": "Cartoon Gravel God holds a microphone to a shirtless skier with a helmet, poles and a pack beside a snowy ski jump; the skier's speech bubble, in Norwegian: \"Jeg føler at det blir feil å fortsette denne prosessen. Jeg ønsker å tenke positivt, samt legge dette bak meg. Jeg vil ikke bli oppfattet som en sytende skiløper.\"",
    "klaebo-interview-1": "Cartoon Gravel God holds a microphone to a shirtless young man in pink swim shorts standing in the snow; his speech bubble, in Norwegian: \"Noen dager lykkes man og noen dager lykkes man ikke. Men til syvende og sist er det viktigste hva jeg sitter igjen med til slutt og hva slags fyr jeg har lyst til å være. Jeg kommer ikke til å lage sånne fiendebilder, i hvert fall ikke overfor meg selv, men dere kan vær så god skrive det, sier han...Jeg konkurrerer mest mot meg selv, og jeg kommer til å konkurrere mot meg selv til jeg går i grava.\"",
    "first-loser-lance": "Lance Armstrong lies on a sofa in a dim room beneath a row of framed yellow jerseys, with a speech bubble: \"Second place is the first loser.\"",
    "10398726-508631980675-2532-n-508631980675": "A cross-country ski race in falling snow: two skiers in black and gold suits, the nearer one wearing bib 47, skate side by side while a skier in a red-and-white patterned suit skis past in the other direction.",
    "sitater": "Three speech bubbles: \"I always liked you. You were always joking around in the peloton and not taking things so seriously.\" \"You asked me how my race went and actually listened.\" \"You didn't come off like a pretentious asshole.\"",
    "klaebo-interview-3": "A judge's hand on a gavel beside brass scales, with a speech bubble: \"Objection, your honor, but the prosecution begs to differ!\"",
    "klaebo-interview-4": "Cartoon Gravel God stands in the middle of a road-race peloton riding toward the camera and says: \"Wrong!\"",
}

# Matter-of-fact restatements; section = 0-based h2 index.
IN_SHORT = (
    Claim("At the World Championships 50 km, Klæbo crossed the line first but was disqualified after a finish-line clash with Bolshunov; another Norwegian took gold.",
          "#k-durianrider-here-are-some-skis-i-ll-come-back-in-8-hours-w", "See §05", 4),
    Claim("Klæbo then dropped Norway&rsquo;s appeal, saying what matters most is what kind of person he wants to be and that he competes mainly against himself.",
          "#oh-you-still-can-t-translate-norwegian-good-lord-you-could-h", "See §10", 9),
    Claim("The post&rsquo;s point for bike racers: how someone trains and races matters more than where their name ends up on the results sheet.",
          "#holy-sh-buckets", "See §11", 10),
    Claim("It frames racing as an iterated game, in which the real winners are the people others want to keep playing with.",
          "#life-is-a-series-of-iterated-games", "See §13", 12),
)


def render() -> str:
    return wp_post.render_post(SOURCE, alt=ALT, in_short=IN_SHORT)


def main() -> None:
    wp_post.write(OUTPUT_PATH, render())


if __name__ == "__main__":
    main()
