"""Imported WordPress post: https://gravelgodcycling.com/your-eating-habits-are-killing-your-performance/

Generated by scripts/wp_post_import.py 1499; the body (your-eating-habits-are-killing-your-performance.body.html) and
metadata (your-eating-habits-are-killing-your-performance.json) are regenerated by the converter, this file is not.
Hand-edit ALT (one entry per image, written from what the image shows),
IN_SHORT (drafts restate the post's own words) and any infographics.

IN_SHORT (2026-10-09): matter-of-fact restatements for Matt's read.

Infographic (2026-10-09): fig-waffles-tests, Mr. Waffles's three tests as a
table, every number as the post's text states it (nothing derived). Placed
right after the "In 3 weeks" image.
Corrected 2026-10-09 (Matt approved): CORRECTIONS below changes "20-watt increase" to 21
(397 - 376); each
entry names its evidence. The page notes the correction at the end.

Regenerate: python3 wordpress/post_sources/your_eating_habits_are_killing_your_performance.py
"""
from __future__ import annotations

import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
if str(HERE.parent) not in sys.path:
    sys.path.insert(0, str(HERE.parent))

from editorial_shell import Claim, DataTable, TableCell, TableColumn, TableRow  # noqa: E402
import wp_post  # noqa: E402

SLUG = "your-eating-habits-are-killing-your-performance"
SOURCE = wp_post.load(SLUG)
OUTPUT_PATH = wp_post.output_path(SLUG)

ALT = {
    "im-stuffed": "Empty white plates and bowls on a white table, a fork and spoon on a wooden board; cartoon Gravel God in a cowboy hat says: \"I'm Stuffed.\"",
    "screen-shot-2021-02-18-at-1-44-15-pm": "Cyclingnews headline: \"Wout van Aert 2kg and 5 weeks away from full fitness. Belgian looking to lose cyclo-cross muscle during Tenerife altitude camp\", beside a photo of Van Aert, arms raised, in a Jumbo-Visma jersey.",
    "screen-shot-2021-02-18-at-1-44-36-pm": "Cyclingnews headline: \"Cimolai: I threw away two or three years of my career because of eating problems. 'You turn pro and think that being light is the only thing that matters'\", beside a head-and-shoulders photo of a rider in glasses.",
    "uhh-i-only-have-one-water-bottle-left": "Cartoon Gravel God stands with his bike in a cracked desert beside a dead, dried-out tree and says: \"I'm no arborist, but you look like you could use some water.\"",
    "because": "Cartoon Gravel God rides toward the viewer beside bold text: \"Because... Cycling at the highest levels IS NOT HEALTHY. And the effect of weight on cycling performance IS REAL.\"",
    "not-a-pro": "Photo of Wout van Aert in a yellow and black Jumbo-Visma jersey with a large red X painted over it.",
    "mr-waffles": "A police-lineup height chart marked 54 to 69 behind a figure in a teal shirt whose face is a smiling cartoon waffle.",
    "in-3-weeks": "Cartoon Gravel God, arms crossed, in front of a stethoscope under the word \"DIAGNOSIS:\". A notepad reads: \"In 3 weeks: His FTP went up 10%, basically because he started eating to fuel performance instead of weighing a certain amount. If he tried to get to the same w/kg by dieting, he would have had to lose almost Nine pounds assuming he could have held the same power in his previous test.\"",
    "car-spinning-wheels-pizza-1": "Animated: a grey SUV whose wheels are whole pizzas, spinning in place.",
    "hey-there": "Glazed doughnuts lined up on a snowy car windshield under the wiper; cartoon Gravel God leans in from above: \"Heeey!!! What are you doing later?\"",
    "experiment": "Two surgeons in blue scrubs operate under a surgical lamp; cartoon Gravel God, arms crossed, says: \"Removing your stomach? There's a new one.\"",
    "if-youre-into-fitness": "Animated: cartoon Gravel God pops a wheelie on his bike beside the text \"If you're into Fitness, You should be fittin' Dis\", with flashing arrows pointing at fruit, a bowl of rice and a sweet potato, then \"In your mouth.\"",
}

# Matter-of-fact restatements; section = 0-based h2 index.
IN_SHORT = (
    Claim("The post argues that power, not low body weight, drives performance, and that training hard while under-eating leaves the body unable to thrive.",
          "#train-well-for-a-long-time", "See §03", 2),
    Claim("In the post&rsquo;s coaching example, a Category 3 rider&rsquo;s 20-minute power went from 296 to 321 watts three weeks after he began fueling for performance.",
          "#fig-waffles-tests", "See the tests · §06", 5),
    Claim("Its three rules: rides under 90 minutes need no ride food; more intensity needs more carbs; eat ride food only while riding.",
          "#3-simple-rules", "See §10", 9),
)

# ── fig-waffles-tests: the post's three tests as a table ─────
# Every value is a number the post's text states. Nothing is derived.
WAFFLES_TESTS = DataTable(
    id="fig-waffles-tests",
    kicker="The numbers above, side by side",
    title="Mr. Waffles: three tests",
    intro_html="5-minute power, 20-minute power and weight, as the post gives them.",
    footnote_html=("First test: after several months of working together. Second: two months later, "
                   "after a build period. Third: three weeks after he started fueling for performance."),
    columns=(
        TableColumn("Test", card="title", sortable=False),
        TableColumn("5-minute power", kind="num", card="fact"),
        TableColumn("20-minute power", kind="num", card="fact"),
        TableColumn("Weight", kind="num"),
    ),
    rows=(
        TableRow(cells=(TableCell("First check-in"), TableCell("369 W", sort=369),
                        TableCell("291 W", sort=291), TableCell("149 lb", sort=149))),
        TableRow(cells=(TableCell("Two months later, after a build"), TableCell("376 W", sort=376),
                        TableCell("296 W", sort=296), TableCell("148 lb", sort=148))),
        TableRow(cells=(TableCell("Three weeks of fueling later"), TableCell("397 W", sort=397),
                        TableCell("321 W", sort=321), TableCell("155 lb", sort=155))),
    ),
    marker="waffles-tests",
)


# Figures corrected to match the post's own evidence (Matt, 2026-10-09:
# "Yeah go ahead and fix"). wp_post applies each to the body (old text must
# occur exactly once) and the word-for-word tests apply them to the snapshot.
CORRECTIONS = (
    wp_post.Correction(
        "397, which was a 20-watt increase",
        "397, which was a 21-watt increase",
        "the post's own 376 W before: 397 - 376 = 21"),
)


def render() -> str:
    return wp_post.render_post(SOURCE, corrections=CORRECTIONS, alt=ALT, in_short=IN_SHORT, figures=(WAFFLES_TESTS,),
                               after_image={"waffles-tests": "in-3-weeks"})


def main() -> None:
    wp_post.write(OUTPUT_PATH, render())


if __name__ == "__main__":
    main()
