#!/usr/bin/env python3
"""Canonical week-table generator for docs/specs/ultra-method-contract.md §2.

The contract's tables are GENERATED by this script: edit parameters here,
regenerate, and paste into the contract — never hand-edit the tables (they will
drift from the asserted constraints). Constraints asserted: load-week ramp ≤10%;
recovery = 65% of the preceding load week; long day ≤ week hours; floor-to-0.25h
rounding. Any change requires contract re-review per §15.

Usage: python3 docs/specs/ultra_method_tables.py > tables.md
"""
import math


def q(x):
    return math.floor(x * 4) / 4  # floor to 0.25h


def build(duration, masters):
    rec_cad = 3 if masters else 4
    if duration == 16:
        phases = {1: 'test'} | {w: 'base' for w in range(2, 7)} | \
                 {w: 'build' for w in range(7, 12)} | {w: 'spec' for w in range(12, 14)} | \
                 {w: 'cons' for w in range(14, 17)}
        sim_week, mini_week, retests = 12, None, [9]
    else:
        phases = {1: 'test'} | {w: 'base' for w in range(2, 10)} | \
                 {w: 'build' for w in range(10, 17)} | {w: 'spec' for w in range(17, 21)} | \
                 {w: 'cons' for w in range(21, 25)}
        sim_week, mini_week, retests = 18, 14, [9, 17]
    hours = {1: 6.0}
    long_day = {1: 2.5}
    rec_weeks = set()
    c = 0
    for w in range(2, duration + 1):
        if phases[w] == 'test':
            continue
        c += 1
        if c % rec_cad == 0 and w not in (sim_week, mini_week) and phases[w] != 'cons':
            rec_weeks.add(w)
    ld = 3.0
    prev_load = 6.0
    for w in range(2, duration + 1):
        ph = phases[w]
        if ph == 'cons':
            idx = w - (14 if duration == 16 else 21)
            vals = ([8.0, 6.0, 2.0] if duration == 16 else [9.0, 7.0, 5.0, 2.0])
            hours[w] = vals[idx]
            long_day[w] = min(4.0, hours[w] - 1) if hours[w] > 3 else 1.0
            continue
        if w == sim_week:
            d1 = q(ld * 1.10)
            d2 = q(d1 * 0.80)
            days = 2 if duration == 16 else 3
            hours[w] = q(d1 + d2 * (days - 1) + 1.5)
            long_day[w] = d1
            continue
        if w == mini_week:
            d1 = q(ld * 1.0)
            d2 = q(d1 * 0.7)
            hours[w] = q(d1 + d2 + 2.0)
            long_day[w] = d1
            continue
        if w in rec_weeks:
            hours[w] = q(prev_load * 0.65)
            long_day[w] = q(min(2.5, ld * 0.6))
        else:
            cap = {'base': 10.0, 'build': 13.0, 'spec': 14.0}[ph]
            hours[w] = q(min(prev_load * 1.10, cap))
            ld = q(min(ld * 1.12, {'base': 4.5, 'build': 6.0, 'spec': 6.0}[ph]))
            long_day[w] = ld
            prev_load = hours[w]
    for w in range(3, duration + 1):
        if w in rec_weeks or w in (sim_week, mini_week) or phases[w] == 'cons' \
                or (w - 1) in rec_weeks or (w - 1) in (sim_week, mini_week):
            continue
        assert hours[w] <= hours[w - 1] * 1.101 + 1e-9, (duration, masters, w)
        assert long_day[w] <= hours[w], (duration, masters, w, 'ld>hours')
    rows = []
    for w in range(1, duration + 1):
        ph = phases[w]
        wt = 'TEST' if ph == 'test' else (
            'SIM' if w == sim_week else (
                'MINI-SIM' if w == mini_week else (
                    'RECOVERY' if w in rec_weeks else (
                        'TAPER' if ph == 'cons' else 'LOAD'))))
        b2b = 'yes' if (wt == 'LOAD' and ph in ('build', 'spec')
                        and w >= (7 if duration == 16 else 11)) else (
            'SIM' if wt in ('SIM', 'MINI-SIM') else 'no')
        inten = 0 if wt in ('TEST', 'RECOVERY', 'SIM', 'MINI-SIM') else (
            1 if ph in ('base', 'spec') else 2)
        if ph == 'cons':
            inten = 1 if w == (14 if duration == 16 else 21) else 0
        str_n = 0 if wt in ('SIM', 'MINI-SIM') else (2 if ph == 'base' else 1)
        if duration == 16 and w >= 15:
            str_n = 0
        if duration == 24 and w >= 23:
            str_n = 0
        flags = []
        if w in retests:
            flags.append('RETEST')
        if w == 1:
            flags.append('360-TEST')
        rows.append(
            f"| {w} | {ph} | {wt} | {hours[w]:.2f} | {long_day[w]:.2f} | "
            f"{b2b} | {inten} | {str_n} | {','.join(flags) or '-'} |")
    label = f"{duration}w {'Masters' if masters else 'Standard'}"
    print(f"\n### Canonical table — {label}\n")
    print("| Wk | Phase | Type | Hours | Long day | B2B allowed | Intensity | Strength | Flags |")
    print("|---|---|---|---|---|---|---|---|---|")
    print("\n".join(rows))


if __name__ == '__main__':
    for d in (16, 24):
        for m in (False, True):
            build(d, m)
